createprocess.go, hcsshim.go
Use CreateProcessWithStdHandlesInComputeSystem to provide stdin/out/err.
This allows vmcompute.dll to handle creating the named pipes with the
correct paths, security attributes, etc. and provides flexibility for
changing the pipe creation protocol in future builds of Windows.
@jhowardmsft, note that this requires docker changes as part of the re-vendor. See Microsoft/docker@b9cfb089366555749305c2aef7383feaab917ea6 for the necessary changes.
With these changes, the various named pipe bugs seem resolved, and we are set for post-TP3 when we may change how the named pipes are created. There is one last bug in the console that's causing a line of output to sometimes get hidden; I still need to fix this.
=> Improve stdin/out/err handling for container processes

createprocess.go, hcsshim.go
Change for TP4. CreateProcessInComputeSystem returns rc, and doesn't log if invalid argument is found. This enables Hyper-V Container to not log errors and give a user-actionable message if they attempt to exec more than one session into a Hyper-V container.
=> TP4: CreateProcess: Return RC

createprocess.go, hcsshim.go, shutdownterminatecomputesystem.go, waitprocess.go
This makes hcsError public so that callers can inspect the internal error and check it against certain known Win32 error codes. This is following the pattern of e.g. os.PathError. Later we can clean up the HcsError.Error() method to be a little more user-friendly.
This breaks docker as-is. You need to take the changes from Microsoft/docker@3478c85e169977ff4f04b71b7686fb3950543457 and add a re-vendor with this commit. Maybe someone can handle that during the next re-vendor?
I think this resolves #19.
=> Make Win32 errors visible to callers

createprocess.go, hcsshim.go, mksyscall_windows.go, zhcsshim.go
This makes it easier to compare return values from vmcompute routines with Win32 error codes. HRESULTs are technically more flexible since they can represent non-S_OK success codes, but this is rarely used in any reasonable interfaces. For Go it seems we're standardizing on Win32.
=> Ensure HRESULTs are converted to Win32 code early

legacy.go
Post-TP4, $wcidirs$ files are required for Hives and Files directories.
=> Fix legacy export

baselayer.go, exportlayer.go, importlayer.go
Don't merge this yet.
With this change, the caller has to ensure that he has taken the appropriate privileges before calling the import/export APIs. This is done because taking these privileges for each small operation can be quite expensive, and the cheapest thing to do is to just set the privileges on the whole process if possible.
This is a breaking change. We should update the version tag appropriately after this. Docker will be able to handle this after docker/docker#22728 is merged.
=> Rely on caller to take privileges when manipulating base layers

callback.go, container.go, hcsshim.go, interface.go, mksyscall_windows.go, process.go, utils.go, waithelper.go, zhcsshim.go
This includes the changes necessary for the new API to work on both TP5 and RS1. The associated Docker changes are located at https://github.com/Microsoft/docker/tree/hcs_rpc (currently needs cleanup)
There is some slight cleanup to be done on this change, but the core logic is ready to be reviewed.
=> Implement the new hcsshim API using the new HCS RPC API

callback.go, container.go, process.go, waithelper.go
This change allows for a client to have a thread waiting on the container exit and still perform async operations such as pausing a container. HCS currently only allows a single waiter. This change splits the notifications in hcsshim.
=> New notification design allows for multiple waiters

container.go, process.go
@swernli @jhowardmsft PTAL
This correctly propogates the ErrUnexpectedContainerExit, ErrUnexpectedProcessAbort, and ErrTimeout errors when received from HCS. They were incorrectly being wrapped in a ContainerError.
=> Correctly propogate timeouts and other errors

interface.go
This adds credentials information to the container config when creating a new container.
@jhowardmsft PTAL
=> Added credentials to ContainerConfig

callback.go, container.go, interface.go, process.go, waithelper.go
A call to unregister notifications while a current notification was being sent could cause a deadlock. This stops holding the callbackMapLock when calling HcsUnregister*Callback to prevent the deadlock.
@swernli @jhowardmsft PTAL
Fixes #50 
=> Prevent deadlock when unregistering notification handler

container.go, errors.go, hcsshim.go, interface.go, process.go
Added ErrVmcomputeAlreadyStopped to be returned when a container that is already stopped is terminated or shut down.
This also moves the error code into new errors.go.
@jhowardmsft @swernli PTAL
=> Added known error code when shutdown is already complete

container.go, errors.go, process.go, waithelper.go
Removed the idea of known errors which are not wrapped in favour of helper methods to check error types.
All errors returned should now be wrapped in either ContainerError or ProcessError, which have context about the command being run when the error was encountered. The returned error can be checked by the new functions `IsPending(err)`, `IsTimeout(err)`, `IsAlreadyStopped(err)`, and `IsNotExist(err)`.
This also adds ErrComputeSystemDoesNotExist, and ErrElementNotFound to be used to check if the error is due to an already stopped container/process, or an exited process.
Callers should no longer check if the returned error is equal to `ErrVmcomputeOperationPending`, but rather that the `IsPending(err)` returns true.
=> Removed knownErrors in favour of helper methods to check error types

container.go, interface.go
=> Add statistics query

container.go
Callbacks were being registered when opening processes regardless of support for callbacks.
=> Stop calling post TP5 API in OpenProcess

hcsshim.go, hnsfuncs.go, interface.go, zhcsshim.go
Changes required to enable service discovery for containers. DNSServerCompartment in network is required to launch listeners in the correct  compartment for overlay networks once we add support for overlay networks.
=> Added dns support

interface.go
Adds Bandwidth maximum and IOPS maximum settings to MapeedDir
@swernli @jstarks
=> Added volume QoS settings to MappedDir

interface.go
Updates ConsoleSize to be a uint. This is part of the feedback from https://github.com/opencontainers/runtime-spec/pull/563#r78852905. It will require a minor tweak to docker once re-vendored.
=> ConsoleSize --> uint

process.go
Ignoring errors returned in LastWaitResult was causing containers that failed to get the exit code to return an incorrect success error code.
/cc @jstarks @jhowardmsft 
=> Check errors in LastWaitResult

container.go, errors.go, process.go
This adds a RW lock to the process and container structures, and checks for handle validity on each call to prevent a handle closing during an active request, or calling into HCS with an already closed handle.
/cc @jstarks @jhowardmsft 
=> Add RW Lock to protect the hcs handles

errors.go
ContainerError always reported that failures occured in win32. This behaviour is now the same as ProcessError.
=> Stop saying all container errors occured in win32

baselayer.go, importlayer.go, legacy.go
With this change, non-base layers can have utility VM changes. Since
Server 2016 does not support layered utility VMs, this works by cloning
the parent layer's utility VM and applying the changes directly. Layers
are assumed to be immutable, so hard links are used to make this cloning
operation fast.
@swernli PTAL
=> Support utility VM changes in non-base layers

importlayer.go, legacy.go
This is necessary to support servicing layers distributed by Microsoft,
since these layers will contain hard links to save space.
=> Support importing layers with hard links

legacy.go
This works around a Go issue where on Windows filepath.Walk follows
reparse points.
=> Don't follow reparse points when cloning the utility VM

legacy.go
This fixes issues with loading utility VM diff images with changes to reparse points.
=> Use Lstat to avoid following reparse points

container.go, errors.go, process.go
ErrInvalidHandle is better named ErrAlreadyClosed. 
Signed-off-by: Darren Stahl darst@microsoft.com
=> Change ErrInvalidHandle to ErrAlreadyClosed

container.go, interface.go
Add GetContainers to get a list of containers running on the system. This returns all containers including template containers and is needed to fix https://github.com/docker/docker/issues/28087
=> Add GetContainers function

container.go
Containers need to register for callbacks when opened so that asynchronous operations can be performed on them. 
/cc @jhowardmsft @jstarks
=> Add a callback registration when opening a container

container.go
I missed a change to existing uses of containerProperties in https://github.com/Microsoft/hcsshim/pull/86 due to GO ignoring my gopath and compiling the wrong source. Here's the fix.
@jhowardmsft 
=> Fix compile error due to containerProperties rename

container.go, process.go
This stops the extra (harmless) closes being called after already being closed once.
Signed-off-by: Darren Stahl darst@microsoft.com
/cc @jhowardmsft @jstarks
=> Nil the finalizers on Close

container.go
Errors from GetContainers were being ignored, and instead the returned pointer was unexpectedly null, resulting an (incorrect) invalid data from hcs error.
/cc @jhowardmsft @jstarks
=> bug fix: return errors from hcsEnumerateComputeSystem

mksyscall_windows.go, zhcsshim.go
Upstream mksyscall_windows.go has had many updates since this was forked. This updates to match.
=> Update mksyscall_windows.go to match upstream updates

interface.go
DNSSearchList allows us to set DNS suffixes for containers. This is required to support --dns-search docker option.
=> Added option to allow setting DNS search list for containers

interface.go
Interface support to pass in Container Name, for sharing Network Endpoints. 
Signed-off-by: Madhan Raj Mookkandy <madhanm@microsoft.com>
=> Interface changes to support --net:container:<containerid/name> for Windows

errors.go
@darrenstahlmsft - Adds an error constant as part of fix for docker/docker #30278. Have verified it fixes docker locally - needed for revendoring.
=> Add 'Access is denied' error

legacy.go
To save space, new Windows container images will have hard links between
the utility VM image and the container base layer. This change relaxes
hcsshim's requirements to allow this behavior.
=> Allow hard links between utility VM and base layer

container.go, exportlayer.go, importlayer.go, process.go
The suggested Go conventions seem to prefer to not use finalizers unless absolutely needed. These handles will close when the program closes (if the Close is not called manually, which it should be) anyway, so no need here.
I don't think this affects correctness (I did a quick look, and it seemed that all should remain live) but to avoid potential future issues this should be fixed.
@jstarks @jhowardmsft 
=> Remove finalizers due to go1.8 liveness

interface.go
Removes the TP5 left-over. Associated with https://github.com/opencontainers/runtime-spec/pull/849
=> Remove SandboxPath

interface.go
Corrects these fields which are all `omitEmpty` in HCS itself.
@swernli @darrenstahlmsft PTAL.
=> OmitEmpty on ProcessConfig fields

container.go
This has bugged me for well over a year. While in the code, just fixing it. Integer should be %d not %s
=> Fix bad debug log

container.go, interface.go
This PR adds support for querying mapped virtual disks from a utility VM which is necessary to support the dynamic sandbox management for Linux Containers on Windows.
In addition, it extends the schema to support additional Linux kernel boot parameters.
Finally, it extends the schema to support `AttachOnly` mapped virtual disks (also needed for dynamic sandbox management).
(Would like to get this in sooner so I can complete the docker PR before I'm OOF)
@darrenstahlmsft @jstarks PTAL
=> Dynamic Sandbox Management for LCOW

activatelayer.go, container.go, createlayer.go, createsandboxlayer.go, deactivatelayer.go, destroylayer.go, expandsandboxsize.go, exportlayer.go, getlayermountpath.go, getsharedbaseimages.go, hcsshim.go, hnsfuncs.go, importlayer.go, layerexists.go, layerutils.go, nametoguid.go, preparelayer.go, process.go, unpreparelayer.go, waithelper.go
This library is causing us to have two folders in our vendor called `Sirupsen` and `sirupsen`. According to the [sirupsen/logrus's README](https://github.com/sirupsen/logrus/blob/master/README.md):
> **Seeing weird case-sensitive problems?** Unfortunately, the author failed to realize the consequences of renaming to lower-case. Due to the Go package environment, this caused issues. Regretfully, there's no turning back now. Everything using `logrus` will need to use the lower-case: `github.com/sirupsen/logrus`. Any package that isn't, should be changed.
Fixing these import statements would save us some duplication.
Related Pull Requests: Azure/go-ansiterm#21, moby/moby#33641
=> downcase github.com/sirupsen/logrus imports

legacy.go
This is needed alongside Microsoft/go-winio#64 to be able to reliably get EA information out of container layers. Without this, since the EA chunk in the backup stream comes after the data chunk, go-winio's backuptar code cannot put the EAs in the tar header. With this change, the backuptar code can seek around to read the data in the order it needs.
=> Add Seek to layer reader

interface.go
@jstarks PTAL. At request of @soccerGB to support the Linux UVM boot from VHD.
=> Add Boot from VHD settings

hnspolicylist.go
AddLoadBalancer is not setting the correct parameters for VFP.
This commit adds the SourceVIP and properly sets the VIPs array if the VIP is empty.
Signed-off-by: Pradip Dhara <pradipd@microsoft.com>
=> Adding SourceVIP and fixing VIPs in AddLoadBalancer.

interface.go
@darrenstahlmsft @jstarks @jterry75 PTAL. Required for support of plan9 bind-mounts for Linux Containers.
=> Add CreateInUtilityVM to MappedDir

hnsendpoint.go
This change is limited to the hnsendpoint.go ApplyACLPolicy function. For alignment with RS3 HNS behavior, this function should be accepting multiple ACLPolicy to be applied on the endpoint. Without this change, only a single ACLPolicy (i.e. a single rule) can ever be applied to a endpoint, which is very limiting.
We are bringing up some code at the moment which requires this change for RS3. This function is not currently used by docker/k8s/anyone that we are aware of and GitHub wide search did not find any callers.
=> ApplyACLPolicy needs to allow multiple policies to be provided

hnspolicy.go
The ACLPolicy field names LocalAddress and RemoteAddress are incorrect. HNS expects "LocalAddresses" and "RemoteAddresses" for ACLPolicy.
=> Correcting ACLPolicy field names to LocalAddresses and RemoteAddresses

legacy.go, legacy18.go, legacy19.go
Due to a bug fixed in Golang 1.9, filepath.Walk needs to stop skipping directory reparse points in Go1.9 and newer. This fixes the issues being seen in https://github.com/Microsoft/hcsshim/pull/144 when using the raw file attribute check to determine if the dir should be skipped.
@jstarks 
=> Stop skipping directory reparse points in Go1.9

errors.go, hnsendpoint.go, hnsnetwork.go
This makes it easier to determine whether we got an error because a resource does not exist or something else went wrong. For example, we currently have code like this:
```
network, err := hcsshim.GetHNSNetworkByName(networkName)
if err != nil {
if err.Error() == fmt.Sprintf("Network %s not found", networkName) {
return nil
}
return err
}
```
It is brittle and tightly coupled to your implementation. We could instead write it as:
```
network, err := hcsshim.GetHNSNetworkByName(networkName)
if err != nil {
if hcsshim.IsNotExist(err) {
return nil
}
return err
}
```
=> Return typed errors when getting endpoints and networks

legacy.go
In go1.9, fi.IsDir() returns false if the directory is also a symlink.
(see https://github.com/golang/go/commit/1989921aef60c83e6f9127a8448fb5ede10e9acc)
This breaks copyFileWithMetadata as it will not pre-create the
destination dir, causing the SetFileBasicInfo call to fail
This fixes the problem by checking syscall.FILE_ATTRIBUTE_DIRECTORY
directly.
=> patch hcsshim to work with go1.9

legacy.go
Changes the `legacyLayerReader` to skip the recycle bin. In addition, it skips files which are in the recycle bin which have Unicode characters which appear to have lost fidelity between UTF16 and UTF8 conversion. See https://github.com/moby/moby/issues/32838#issuecomment-343610048 for the dockerfile which causes this problem.
@jstarks @darrenstahlmsft PTAL
=> Skip recycle bin and part fix for moby/moby 32838

legacy.go
Signed-off-by: John Stephens <johnstep@docker.com>
=> Ignore file name case when skipping $Recycle.Bin

cmd/wclayer/create.go, cmd/wclayer/export.go, cmd/wclayer/import.go, cmd/wclayer/mount.go, cmd/wclayer/remove.go, cmd/wclayer/wclayer.go, internal/appargs/appargs.go, oci/wclayer/export.go, oci/wclayer/import.go
This adds new packages oci/wclayer and cmd/wclayer that can be used to
manipulate Windows container layers. The former is concerned only with
importing and exporting layers from and to their OCI tar formats. The
latter is a command line tool with myriad uses.
=> wclayer: New package and utility for WCOW layer ops

cmd/wclayer/export.go, cmd/wclayer/import.go, internal/ociwclayer/export.go, internal/ociwclayer/import.go
We may want to iterate on this interface a bit before we support it
outside of hcsshim.
=> Move oci/wclayer to internal for now

uvm/uvm.go
@jstarks Before merging, input requested on a few things - will add individual comments.
This is the high-level external interface for a Utility VM with no implementation behind it.
=> Adds external utility VM object and methods

cmd/runhcs/container.go, cmd/runhcs/shim.go, cmd/runhcs/utils.go, cmd/runhcs/vm.go
This change opens the shim log files onto the shim processes' standard
error so that Go panics for those processes are written to the log.
=> runhcs: Open shim logs on stderr

cmd/runhcs/container.go, cmd/runhcs/shim.go, cmd/runhcs/vm.go
When a container ID is reused, it's possible to get runhcs into a state
where it will try to connect to the wrong VM (e.g. when cleaning up
resources for a container whose host has been deleted and recreated).
Resolve this comprehensively by using a new random ID to generate the
pipe names for each container.
=> runhcs: Use random pipe names when communicating

internal/hcsoci/containerex.go, internal/hcsoci/mount.go, internal/wclayer/layerid.go, internal/wclayer/layerutils.go, uvm/types.go, uvm/vsmb.go, uvm/vsmb_test.go
This restore's jhoward's previous change to separate the layer ID from
the VSMB share name, but fixes it to still pass the layer ID correctly
for the container and combined layers calls.
=> hcsoci: Simplify VSMB

cmd/wclayer/create.go, cmd/wclayer/mount.go, functional/utilities/scratch.go, internal/hcsoci/containerex.go, internal/hcsoci/mount.go, internal/hcsoci/resources_wcow.go, internal/uvm/types.go, internal/wclayer/createscratchlayer.go, internal/wclayer/expandscratchsize.go, layer.go
Part 1.... Unfortunately we have to call it `sandbox.vhdx` for v1 WCOW as it's hard-coded in HCS. But this renames a lot of places. It does introduce two new top-level APIs CreateScratchLayer and ExpandScratchSize which are mirrors of CreateSandboxLayer and ExpandSandboxSize for use by new clients. Obviously, I can't change the names of the actual functions which are exported in VMCompute though.
=> Rename sandbox to scratch, part 1.

internal/uvm/create.go, internal/uvm/start.go, internal/uvm/types.go
This change opens a vsock port when creating a utility VM and directs
the init process inside the VM to launch gcs with stderr pointing to
that port. The host then collects the log entries from gcs and reports
them via logrus.
=> uvm: Flow opengcs logs to host logrus

internal/cmd/rootfs2vhd/rootfs2vhd.go, internal/uvm/scsi.go
@jterry75 As discussed this morning. Seems to work from testing rootfs2vhd without the sync command.
=> Fix SCSI eject

internal/uvm/vpmem.go
Fixes the resource path for VPMem to match the breaking change. Validated TestVPMEM passes on rs5_release_base_dev 17718 180716-1700 with this fix. @jterry75 PTAL
=> Fix vpmem add/remove

functional/wcow_test.go
Updated to be in line with the rest of the WCOW tests. Now passes except that read-only platform bug which is in flight to the dev branch. @jterry75 PTAL
=> TestWCOWXenonOciV1 was using wrong image

functional/wcow_test.go
I put these in for debugging a long while back. Not required.
=> Remove two noisy non-required fmt.Println in test code

functional/wcow_test.go, internal/hcsoci/hcsdoc_wcow.go, internal/schema2/memory.go, internal/schema2/memory_2.go, internal/schema2/network_adapter.go, internal/schema2/properties.go, internal/schema2/property_query.go, internal/schema2/scsi.go, internal/schema2/virtual_smb.go, internal/uvm/create.go, internal/uvm/scsi.go, internal/uvm/vpmem.go
Signed-off-by: John Howard jhoward@microsoft.com
A bunch of small fixups to HCSShim.
- Refresh swagger
- Compile fixups to match
- Removes SCSI workaround
- Fixes VPMem with new schema
@jterry75 Note there isn't an RS5_RELEASE_.... build to validate these on, so I haven't bumped the RS5 build number in this PR. Have validated against 18203 HYP 180722-0859 instead.
=> Fixups to latest vmcompute as of 7/23/18

internal/wclayer/legacy.go
This is a corresponding change to the following PR: https://github.com/Microsoft/go-winio/pull/88
=> Fix FileAttributes size to work across all platforms

legacy.go
Fix fileattributes in the v0.6-dev branch to match current go-winio @jterry75
=> Changes based on PR

internal/hcs/system.go
@jterry75 Same fix as for the v0.6 branch to allow a limit to the number of parallel container starts through an optional environment variable.
=> Limit parallel starts if HCSSHIM_MAX_PARALLEL_START is set

functional/lcow_test.go, internal/uvm/start.go
@jterry75 PTAL
- Fixes a test after the recent change to uvm create and the logging stuff
- Removes time= from the GCS logging Finally make the GCS logs somewhat sane. Example below
```
time="2018-06-15T12:02:46-07:00" level=info msg="bridge: read message '{\"ContainerId\":\"00000000-0000-0000-0000-000000000000\",\"ActivityId\":\"00000000-0000-0000-0000-000000000000\",\"ProcessId\":111,\"TimeoutInMs\":4294967295}'" vm.time="2018-06-15T12:02:43Z"
```
=> abbreviate logging; fix test

internal/interop/interop.go
This is submitted on behalf of askariv.
Based on align.go line 367:
if Widthptr == 4 && w != int64(int32(w)) {
yyerror("type %v too large”, t)
}
The idea in this case is to convert to a slice of a large array of uint16s so it can be used with practically any size of a string, since ‘func UTF16ToString(s []uint16) string’.
The original code had [1<<30] of uint16 elemets which make the width 1 << 31 or 2147483648 (0x80000000) meaning  -2147483648 in 32bit!
This is why [1<<29] works, and it is large enough for any real purpose, after all it is a string.
Please let us know if you have a better idea on how to do the type cast.
=> Fix ConvertAndFreeCoTaskMemString for 32 bit platforms

internal/schema1/schema1.go
@jterry75 This was added to the v0.6.x tree, but omitted from schema1 in master. Adding it here too.
=> Adds LinuxMetadata back (omitted in master)

internal/hcs/process.go, internal/hcs/system.go, internal/hcs/watcher.go, internal/timeout/timeout.go
@jterry75 This adds a really simple syscall watcher which logs a warning if a platform API doesn't return in a reasonable length of time. We just warn the error rather than take any pre-emptive action. This would at least give us clues from the log, even in non-debug mode, that something may be awry with the platform, as we have seen on multiple occasions when debugging issues. Plus containerd gets this for free :)
=> Add syscall watcher

hnsendpoint.go
CNI needs to use the V1 Schema until customers can get the updated HNS code in RS6. This means that the Hcsshim needs to export the Namespace object that is a part of HNSEndpoint.
=> Adding Namespace to HNS exports.

internal/hcsoci/resources_wcow.go
Avoids a panic doing `runhcs create -b . test` which malformed config.json
=> Nil check in allocateWindowsResources

version.go
=> Remove redundant no-op IsTP4()

ext4/internal/compactext4/compact.go
@jstarks PTAL. Have verified the fix.
Make sure Xattrs are always initialized to avoid a panic such as below:
```
re-exec error: exit status 2: stderr: panic: assignment to entry in nil map
goroutine 1 [running]:
github.com/docker/docker/vendor/github.com/Microsoft/hcsshim/ext4/tar2ext4.Convert(0x20167c0, 0xc0000b2000, 0x20343e0, 0xc0001342b8, 0xc00063be30, 0x2, 0x2, 0x1ffe75c, 0x0)
e:/go/src/github.com/docker/docker/vendor/github.com/Microsoft/hcsshim/ext4/tar2ext4/tar2ext4.go:74 +0xa00
github.com/docker/docker/daemon/graphdriver/lcow.tar2ext4Actual(0xc000074060, 0x5a, 0x20167c0, 0xc0000b2000, 0x0, 0x0, 0x0)
e:/go/src/github.com/docker/docker/daemon/graphdriver/lcow/lcow.go:911 +0x104 …
```
=> ext4:Init Xattrs in Stat()

ext4/internal/compactext4/compact.go, ext4/internal/compactext4/compact_test.go, ext4/tar2ext4/tar2ext4.go
The limit is necessary to reduce the group descriptor block size
overhead. It may be unnecessary in the future if metabg support is
implemented.
=> tar2ext4: Make disk size limit configurable

functional/uvm_properties_test.go, internal/schema1/schema1.go
@jterry75 
Adds the properties query for guestconnection as per internal email. I don't like that everything is in the schema1 go files, but that can be resolved later - it already has a few issues about what should be where. I'm coming to the conclusion we could use a schemacommon package too. But for another day.
@madhanrm FYI
=> Add GuestConnection query

hcn/hcnendpoint.go, hcn/hcnloadbalancer.go, hcn/hcnnamespace.go, hcn/hcnnetwork.go
To aid debugging, printing out the Json on all Create calls for HNS objects.
=> Debug prints out the json provided to HNS on CreateX calls.

hcn/hcnendpoint_test.go, hcn/hcnerrors_test.go, hcn/hcnloadbalancer.go, hcn/hcnloadbalancer_test.go, hcn/hcnnamespace_test.go, hcn/hcnnetwork_test.go, hcn/hcnsupport_test.go, hcn/hcnutils_test.go, hcn/hcnv1schema_test.go, hcn/hnsv1_test.go, hnspolicylist.go, internal/hns/hnspolicylist.go
Expose DSR Settings in Load Balancer
Fix Hcn tests to continue on failure.
=> Expose DSR Settings in Load Balancer

internal/hcsoci/layers.go, internal/uvm/scsi.go, internal/uvm/types.go
@jterry75 As talked about offline.
Verified this now works end to end with containerd, and the combined layers being constructed correctly, using your example below.
```
ctr images pull --snapshotter windows-lcow docker.io/microsoft/dotnet:2.1.403-sdk-stretch
ctr run --rm --runtime io.containerd.runhcs.v1 --snapshotter windows-lcow docker.io/microsoft/dotnet:2.1.403-sdk-stretch lc1 sh -c "echo hello"
```
eg the following from the containerd debug spew when using an updated runhcs.exe from this branch:
```level=info msg="bridge: read message '{"ContainerId":"00000000-0000-0000-0000-000000000000","ActivityId":"00000000-0000-0000-a483-c500f77f0000","Request":{"RequestType":"Add","ResourceType":"CombinedLayers","Settings":{"ContainerRootPath": …
```
=> LCOW: Use SCSI for layers over 512MB rather than PMEM

functional/uvm_mem_backingtype_test.go
@jterry75 TestMemBackingTypeWCOW was failing on my test machine, probably because I'm using a nanoserver base image direct from the build share which only has one layer, rather than pulling one which probably has both the base and the patch. Fix was simple - you'd omitted to pass the scratch to the layer folders.
=> Use Scratch in TestMemBackingTypeWCOW

appveyor.yml, cmd/runhcs/container.go, functional/lcow_test.go, functional/uvm_mem_backingtype_test.go, functional/uvm_vpmem_test.go, internal/hcsoci/layers.go, internal/schema2/virtual_p_mem_controller.go, internal/uvm/constants.go, internal/uvm/create.go, internal/uvm/types.go
@jterry75 This reworks the memory backing type into individual annotations. In addition, it adds two further options for VPMem - the device count, and the maximum size (which defaults to 4GB for consistency with v1 callers).
=> Update annotation fields

cmd/runhcs/container.go
=> Stop passing appending \vm to Windows scratch LayerFolders

pkg/go-runhcs/runhcs.go, pkg/go-runhcs/runhcs_integration_test.go, pkg/go-runhcs/runhcs_test.go
=> Store the runhcs.exe path for faster invocation

internal/uvm/create.go
=> Skip uart enumeration on production boot

cmd/runhcs/container.go, internal/uvm/create.go
@jterry75 Adds the annotation `io.microsoft.virtualmachine.lcow.preferredrootfstype`. Possible values are "initrd" or "vhd"
=> Annotation for preferred rootfs type

functional/lcow_test.go, functional/utilities/createuvm.go, functional/uvm_mem_backingtype_test.go, functional/uvm_plannine_test.go, functional/uvm_properties_test.go, functional/uvm_scsi_test.go, functional/uvm_vpmem_test.go, functional/uvm_vsmb_test.go
=> Cleanup uvm functional tests to use opts

hnspolicylist.go, internal/hns/hnspolicylist.go
Reverting the breaking API change introduced in https://github.com/Microsoft/hcsshim/pull/356. We cannot do this. @madhanrm @jterry75
=> Revert breaking change to AddLoadBalancer

internal/hcs/callback.go
Previously, if we received an HCS callback of a type that we don't support, we wouldn't have a channel prepared for it. This causes a send to a nil channel, which hangs forever.
Now, we will only send to a channel if the channel has been prepared, and will otherwise log a warning.
=> Don't attempt to write to callback channels that we don't support

cmd/runhcs/container.go, cmd/runhcs/vm.go, internal/copywithtimeout/copywithtimeout.go, internal/hcs/errors.go, internal/hcs/log.go, internal/hcs/process.go, internal/hcs/system.go, internal/hcs/watcher.go, internal/logfields/fields.go
=> Changing logging to use logrus.WithFields

internal/uvm/create.go
Not doing this causes spurious machine checks during boot in some cases.
=> uvm: Mark pmem0 root fs readonly

cmd/runhcs/container.go, cmd/runhcs/create-scratch.go, cmd/runhcs/vm.go, functional/lcow_test.go, functional/utilities/createuvm.go, functional/uvm_mem_backingtype_test.go, functional/wcow_test.go, internal/cmd/rootfs2vhd/rootfs2vhd.go, internal/uvm/create.go, internal/uvm/create_lcow.go, internal/uvm/create_test.go, internal/uvm/create_wcow.go
Splits up the internal uvm.Create into uvm.CreateWCOW and uvm.CreateLCOW which
enables us to have options for each. This makes the code significantly easier
to read and maintain.
=> Split UVM create into WCOW/LCOW

internal/hcs/process.go, internal/hcs/system.go
Defer evaluates function arguments at the time of the defer statement, rather than when the function actually exits. Due to this, all of our operation end logging was seeing nil for error, and claiming the operation was a success, even if it failed.
=> Fix operation-end logging

functional/lcow_test.go, functional/uvm_scratch_test.go, functional/uvm_scsi_test.go, internal/hcsoci/hcsdoc_wcow.go, internal/hcsoci/layers.go, internal/hcsoci/resources.go, internal/hcsoci/resources_lcow.go, internal/hcsoci/resources_wcow.go, internal/lcow/scratch.go, internal/uvm/create_wcow.go, internal/uvm/plan9.go, internal/uvm/scsi.go, internal/uvm/vsmb.go
This PR adds support for passthrough mounts to the UVM for WCOW/LCOW. This can
be accomplished by passing a mount in the OCI spec as follows:
{
"type": "passthrough-disk",
"destination": "<path-in-lcow-or-wcow>",
"source": "C:\\test.vhd",
"options": ["rbind", "rw"]
}
=> Add OCI passthrough mount support for WCOW/LCOW

hcn/hcnendpoint.go, hcn/hcnendpoint_test.go, hcn/hcnloadbalancer.go, hcn/hcnloadbalancer_test.go, hcn/hcnnamespace.go, hcn/hcnnamespace_test.go, hcn/hcnnetwork.go, hcn/hcnnetwork_test.go, hcn/hcnutils_test.go, hcn/hcnv1schema_test.go
Delete methods all have object references in the return values, which are always nil.
Changing the method signature so that only the error is returned.
=> Removing nil objects from returns of Delete functions.

internal/hcs/process.go, internal/hcs/system.go, internal/hcs/watcher.go
This PR fixes two issues:
1. If the syscallWatcher function is started in a goroutine, the goroutine remains around for the length of `timeout.SyscallWatcher` (4 minutes). So a longrunning process can accumulate goroutines if it makes many syscalls that use the syscallWatcher in a 4 minute span.
2. There is a race condition where both the syscallWatcher goroutine and the main function access the `completed` variable. This will cause any test suites that: 
- run under `go test -race`
- call into hcsshim 
- last longer than 4 minutes 
to fail due to the race detector.  An easy way to reproduce is:
```
completed := false
go syscallWatcher(context, &completed)
time.Sleep(timeout.SyscallWatcher + 5 * time.Second)
completed = true	
```
This PR fixes the issue by using a context.Context object …
=> Fix race in syscallWatcher

hcn/hcnnetwork.go
Fixing the naming of the DNS struct to align with the Container Network Interface Specification.
This change won't effect anyone using the HNS V1 schema. It is for usage going forward using V2 schema in RS5+.
=> DNS Suffix Change for Alignment with Container Network Interface Specification

hcn/hcn.go, hcn/hcnglobals.go, hcn/hcnsupport.go, hcn/hcnsupport_test.go
Adding a check for DSR (Direct Server Return) and fixed the V2 API test to run regardless of version.
=> DSR version

internal/uvm/create_lcow.go
Signed-off-by: Kevin Parsons <kevpar@ntdev.microsoft.com>
=> Fix rootfs.vhd check to not be inverted

cmd/runhcs/kill.go, cmd/runhcs/kill_test.go, cmd/runhcs/signalmap.go
The Docker SignalMap for Windows passes the UNIX scheme so TERM and KILL. We
will no longer fail on Windows if a signal query comes in we simply convert it
to the correct Windows signal.
TERM = CTRLC
KILL = CTRLSHUTDOWN
=> Fix issue with Docker SignalMap

internal/uvm/start.go, internal/uvm/types.go, internal/uvm/wait.go
Previously, if an issue in the kernel or initrd prevented the UVM from running
vsockexec, we would hang forever waiting for output processing from the UVM to
complete. With this change, there is now a separate signal for when the vsock
listener connects, and when it is done processing output (these signals are
implemented by closing channels). If the UVM dies before the connect signal
occurs, the wait completes. Otherwise, we wait until output processing has
completed before returning, as we did before.
Signed-off-by: Kevin Parsons <kevpar@ntdev.microsoft.com>
=> Refactor UVM output handling

internal/uvm/plan9.go
Case sensitivity can only be set on a Plan9 share in the guest if the
source Windows directory supports it. Until we have this detection logic
make all shares case insensitive.
=> Fix bug in Plan9 case sensitivity

cmd/runhcs/shim.go, vendor.conf, vendor/github.com/opencontainers/runtime-spec/specs-go/config.go
@jterry75 Don't merge yet - the vendor part is hacked pending https://github.com/opencontainers/runtime-spec/pull/998 being merged. Have done end-to-end verification of this working with docker with the containerd back-end for runtime.
=> WCOW: Use commandline in spec if populated

internal/hcs/waithelper.go
Still trying to figure out the underlying cause of this, but this avoid a panic if `waitForNotification` is called with a callbackNumber which isn't in the callbackMap.
```
00:50:25.309 goroutine 26874 [running]:
00:50:25.311 github.com/docker/docker/vendor/github.com/Microsoft/hcsshim/internal/hcs.waitForNotification(0x433, 0x10000, 0x0, 0x0, 0x0)
00:50:25.311 	c:/go/src/github.com/docker/docker/vendor/github.com/Microsoft/hcsshim/internal/hcs/waithelper.go:20 +0x85
00:50:25.311 github.com/docker/docker/vendor/github.com/Microsoft/hcsshim/internal/hcs.(*Process).Wait(0xc0000c1db0, 0x0, 0x0)
00:50:25.313 	c:/go/src/github.com/docker/docker/vendor/github.com/Microsoft/hcsshim/internal/hcs/process.go:172 +0xc1
00:50:25.313 …
```
=> Avoid panic in waitForNotification

cmd/containerd-shim-runhcs-v1/pod.go, cmd/containerd-shim-runhcs-v1/task_hcs.go
For RS1-RS4 hosts the utility VM was not managed directly but the OCI spec
still used the presence of the HyperV section to determine the isolation level.
This change will only craete the Utility VM if the Host OS is >= RS5.
=> Fixes a bug in Xenon activation on RS1-RS4 hosts

cmd/containerd-shim-runhcs-v1/main.go, cmd/containerd-shim-runhcs-v1/serve.go, cmd/containerd-shim-runhcs-v1/service_internal.go
Doing a blanket update of the event name for consistency across docker, containerd, containerd-shim-runhcs-v1 and docker-signal to make life a lot easier and less typing.
- We weren't previously ever setting up the dump stack event 😲 
- Adds a debugger wait event triggered during create
(https://github.com/moby/moby/pull/38741 for the related moby change.)
@jterry75 PTAL
=> Setup stackdump correctly; add debugger event

cmd/containerd-shim-runhcs-v1/service_internal.go
=> Only allow Sandbox Task to shutdown a POD shim

cmd/containerd-shim-runhcs-v1/pod.go, internal/hcsoci/create.go, internal/hcsoci/network.go, internal/hcsoci/resources.go, internal/uvm/network.go, internal/uvm/types.go
1. We should only run the cleanup logic for a standalone or sandbox container
with networking but not for individual workload containers.
2. We now provision the guest NetNS in the UVM for WCOW as a seperate step since
we don't actually provision the container in the guest.
=> Fix bugs in provisioning NetNS on UVM

cmd/containerd-shim-runhcs-v1/exec.go, cmd/containerd-shim-runhcs-v1/exec_hcs.go, cmd/containerd-shim-runhcs-v1/exec_test.go, cmd/containerd-shim-runhcs-v1/exec_wcow_podsandbox.go, cmd/containerd-shim-runhcs-v1/exec_wcow_podsandbox_test.go, cmd/containerd-shim-runhcs-v1/task_hcs.go, cmd/containerd-shim-runhcs-v1/task_wcow_podsandbox.go, internal/hcs/process.go
There are some very subtile ways in which the code could fail to event the
exit and cause an upstream listener to continue to think the shim is still
running even though the task had indeed exited.
=> Simplify the hcstask/exec exit state transitions.

cmd/containerd-shim-runhcs-v1/exec_hcs.go
On close in the case of a tty the caller does not know the close is taking
place and does not have the ability to unblock the upstream pipes. Since the
caller might not be issuing any stdin even though we close the hcs side of the
pipe there is nothing that alerts go to unblock the io.Copy.
This fix stops waiting for Stdin to finish the io.Copy on hcs process exit.
=> Fix bug in runhcs shim with tty=true on close

internal/uvm/create_lcow.go
Now the path will be the "lcow-os" sub-directory in the same location as the
current executable.
=> Change default LCOW OS boot files path

cmd/containerd-shim-runhcs-v1/main.go, cmd/containerd-shim-runhcs-v1/service.go
Ensure the task entry points and main log a panic stack to ETW. We deliberately log each line of the stack trace as a single entry to make our lives easier using TVPP.
@kevpar @jterry75
=> Panic-Recover log to ETW in shim

cmd/containerd-shim-runhcs-v1/exec_hcs.go, cmd/containerd-shim-runhcs-v1/pod.go, internal/signals/signal.go
As it turns out on RS5 a Windows Process Isolated container actually
does open the network compartment at the activation of the first
container. So we cannot skip creating the pause container when creating
the pod. This is not true for Windows Hypervisor Isolated which is held
open via the GNS.
=> Revert removal of WCOW pause container activation

internal/uvm/create_wcow.go
=> Fix bug setting WCOW UVM processor count overrides

hcn/hcnnetwork.go, hcn/hcnnetwork_test.go, hcn/hcnutils_test.go
Bad scoping - each subnet you provide must have a default gateway. If you provide no\empty subnet that is still valid in some cases.
=> Fix bug where we error on network creation if no subnet was provided

cmd/containerd-shim-runhcs-v1/exec_hcs.go, cmd/containerd-shim-runhcs-v1/exec_wcow_podsandbox.go, cmd/containerd-shim-runhcs-v1/task_hcs.go, cmd/containerd-shim-runhcs-v1/task_wcow_podsandbox.go, internal/hcs/process.go, internal/hcs/system.go
It turns out that eventing the TaskExit at the end of a process is not the
correct time on Windows. In all cases there is a container Silo seperate from
the init process and in Hypervisor isolated cases there is a parent UtilityVM.
This change makes the init process TaskExit notification only fire once the
Silo/UtilityVM are successfully torn down making sure there are no resources in
use when the TaskExit is sent.
=> Change HCS TaskExit ownership responsibility

cmd/containerd-shim-runhcs-v1/service_internal.go, internal/oci/uvm.go
@jterry PTAL. Looks like this is the cause of failures on https://github.com/containerd/containerd/pull/3132
=> Don't nil deref on no shim options

cmd/containerd-shim-runhcs-v1/exec_hcs.go, cmd/containerd-shim-runhcs-v1/service_internal.go, cmd/containerd-shim-runhcs-v1/task.go, cmd/containerd-shim-runhcs-v1/task_hcs.go, cmd/containerd-shim-runhcs-v1/task_hcs_test.go, cmd/containerd-shim-runhcs-v1/task_test.go, cmd/containerd-shim-runhcs-v1/task_wcow_podsandbox.go, internal/hcs/process.go, internal/hcs/system.go
The async event TaskExit is sent post container/UVM shutdown but the actual
caller may have been unblocked on the call to Wait. We now return form Wait
after the container/UVM shutdown and alerting async TaskExit.
=> Fix a bug in Wait when waiting on the init task

cmd/containerd-shim-runhcs-v1/exec_hcs.go, cmd/runhcs/kill.go, internal/guestrequest/types.go, internal/hcs/hcs.go, internal/hcs/process.go, internal/hcs/zsyscall_windows.go, internal/signals/signal.go, internal/signals/signal_test.go, internal/signals/signalmap.go
- There was a bug in hcs.go where hcsSignalProcess was actually the syscall for
HcsTerminateProcess due to a copy paste bug.
- Signal support on WCOW based on the HCS API is actually marshalled by string
value rather than integer value. This change makes sure that the signal struct
created for WCOW validates and uses the appropriate Ctrl* string.
=> Fix signal support for WCOW

cmd/containerd-shim-runhcs-v1/exec.go, cmd/containerd-shim-runhcs-v1/exec_hcs.go, cmd/containerd-shim-runhcs-v1/exec_wcow_podsandbox.go, cmd/containerd-shim-runhcs-v1/exec_wcow_podsandbox_test.go, cmd/containerd-shim-runhcs-v1/service.go
- We should be using errdefs.ToGRPC when sending errors as a return value from
the shim. This converts known error types to a propery serialized chain and
maintains the Causer interface associated with the proper underlying error.
- Shims MUST return errdefs.ErrNotFound in process exited state
=>  Serialize all shim errors to gRPC known types

cmd/containerd-shim-runhcs-v1/serve.go
@jterry75 Mirrors the PR to containerd (I'll do one for moby as well shortly) to dump the stack to file to make grabbing the logs in that diagnostic script work.
=> shim:dump stack to file as well

scripts/Get-ContainerLogs.ps1
A rough-and-ready script to signal containerd, shims (and docker to make this generic for public use), grab the stack dumps, and also grab the system/application event logs, as well as as many Hyper-V event logs as it can, and zips them. Far from perfect, but better than nothing and a good start.
As discussed at standup: for use at 3AM during an ICM so that we have some hope of analysing what when wrong later.
@jterry75 PTAL
@kevpar - Your SF deploy script should probably binplace this somewhere in $env:PATH.
TODO subsequently:
=> Get-ContainerLogs.ps1 for later analysis

cmd/containerd-shim-runhcs-v1/exec_hcs.go, cmd/containerd-shim-runhcs-v1/io.go, cmd/containerd-shim-runhcs-v1/io_npipe.go
1. Stops setting UpstreamIO to nil on Close or CloseStdin. This means that the
call will always return a valid non-nil connection even if that connection has
been previously closed. This will stop the shim from panic'ing and instead
return a "connection already closed" error if used.
2. Adds a check on the invariant state of in, out, serr returned from the
platform and makes sure it matches the requested state on creation.
=> Stop setting UpstreamIO to nil on Close

scripts/Get-ContainerLogs.ps1
Some minor additions to Get-ContainerLogs
- Saves the containerd state directory (with the caveat only if in default location)
- This really needs an API change in containerd so that `version` reports this and we could use ctr.exe
- Improvement to how the docker stacks are found
- Gathers WMI objects for LogicalDisk for local disks, and OperatingSystem
- Gathers output of Get-ComputerInfo
@jterry75 PTAL
=> Improvements to Get-ContainerLogs.ps1

appveyor.yml
Bumps appveyor to use golang 1.12
=> Bump appveyor to go 1.12.2

cmd/containerd-shim-runhcs-v1/main.go, cmd/containerd-shim-runhcs-v1/serve.go
This allows us to collect the Goroutine stacks with WPR, rather than needing to trigger it with a kernel event.
=> Dump stacks on ETW capture state

internal/hcsoci/layers.go
@jterry75 as discussed offline.
Verified with docker LCOW/containerd. Confirmed the SCSI remove is correctly for the scratch, and the combined layers remove preceeding it is for the rootfs, not scratch.
```
time="2019-04-15T14:04:41.797268700-07:00" level=debug msg="opengcs::bridge - read message" message="{\"ContainerId\":\"00000000-0000-0000-0000-000000000000\",\"ActivityId\":\"00000000-0000-0000-2400-000000000000\",\"Request\":{\"RequestType\":\"Remove\",\"ResourceType\":\"CombinedLayers\",\"Settings\":{\"ContainerRootPath\":\"/run/gcs/c/1/rootfs\"}},\"v2Request\":null}" message-id=10 message-type=ComputeSystemModifySettingsV1 uvm-id=84d0afb29f1d534787eea5f7b2b9a8d163b3e04ad7605294cfb1b9c9c7ceed33@vm vm.time="2019-04-15 21:04:41 +0000 …
```
=> Remove combinedlayers: rootfs not scratch

osversion/windowsbuilds.go
This adds some additional comments to the build-numbers, to help correlate versions to specific Windows Server and Windows Client releases.
=> Add more information to osversion build numbers

cmd/containerd-shim-runhcs-v1/exec_hcs.go, cmd/containerd-shim-runhcs-v1/task_hcs.go, internal/hcs/errors.go, internal/hcs/process.go
- Fix panic on hcs/process.Close() with nil error
- Force HCS process exit on ERROR_NOT_FOUND
- Force UVM exit after 30 seconds of issuing SIGKILL
=> Handle Process/Container not found errors and force exits

osversion/osversion_windows.go
=> Enhancement: add osversion.Build() utility

cmd/containerd-shim-runhcs-v1/exec_hcs.go, cmd/containerd-shim-runhcs-v1/io_npipe.go, cmd/runhcs/shim.go, internal/hcs/process.go, internal/hcs/system.go, internal/hcsoci/create.go, internal/lcow/process.go, internal/tools/uvmboot/main.go, process.go, test/functional/wcow_test.go
To better support the external bridge, associate the stdio handles with
the owning process and close them when the process object is closed.
=> internal/hcs: Improve process stdio lifetime

internal/hcs/callback.go
If the HCS service crashes, then all processes and compute systems get
notified of this. The code was previously ignoring this notification,
meaning outstanding waits would never be satisfied. Now the notification
causes all pending waits to complete with an error.
=> hcs: Fail operations when the HCS service crashes

internal/uvm/create.go, internal/uvm/create_lcow.go, internal/uvm/create_wcow.go
Hyper-V only supports 2MB aligned memory sizes (presumably to avoid
splitting large pages). Rather than fail with a cryptic error from the
platform, round the requested memory size up to the next 2MB boundary.
=> uvm: Round requested memory size to 2MB

cmd/containerd-shim-runhcs-v1/main.go, cmd/containerd-shim-runhcs-v1/serve.go, internal/copywithtimeout/copywithtimeout.go, internal/hcs/waithelper.go, internal/hcsoci/create.go, internal/hcsoci/hcsdoc_lcow.go, internal/hcsoci/hcsdoc_wcow.go, internal/hcsoci/layers.go, internal/hcsoci/network.go, internal/hcsoci/resources.go, internal/hcsoci/resources_lcow.go, internal/hcsoci/resources_wcow.go, internal/lcow/process.go, internal/lcow/scratch.go, internal/lcow/tar2vhd.go, internal/oci/uvm.go, internal/schemaversion/schemaversion.go, internal/uvm/create.go, internal/uvm/create_lcow.go, internal/uvm/create_wcow.go, internal/uvm/vpmem.go, internal/uvm/vsmb.go, internal/uvmfolder/locate.go, internal/wcow/scratch.go
This change (intends to) replace all dynamically generated logrus
messages with constant values and to include dynamic data via separate
logrus fields. It does so for all non-test packages except HCN and HNS.
This makes it easier to extract data from log messages in post
processing, especially when the logrus ETW tracelogging hook is enabled.
With few exceptions, this change does not change the number of logged
events, nor does it add additional context to existing messages. There
are still many instances where events are redundant, and there are still
many events missing the necessary context to associate the message with
a container, VM, or request. These shortcomings should be addressed in
separate changes.
=> Use constant logrus messages everywhere

cmd/containerd-shim-runhcs-v1/diag.go, internal/lcow/process.go, internal/lcow/scratch.go, internal/lcow/tar2vhd.go, internal/tools/uvmboot/main.go, internal/uvm/capabilities.go, internal/uvm/create.go, internal/uvm/create_lcow.go, internal/uvm/create_wcow.go, internal/uvm/network.go, internal/uvm/start.go, internal/uvm/system.go, internal/uvm/types.go, test/functional/lcow_test.go, test/functional/uvm_properties_test.go
This change removes the ComputeSystem() call from uvm.UtilityVM and
provides wrapper functions for the few places that needed to get the
underlying compute system. This is necessary because these functions
(such as CreateProcess) will have different implementations depending on
whether the internal or external bridge is in use.
Also pre-cache some of the properties queries, caching the result of
such queries early rather than querying at each use.
=> uvm: Reduce binding between hcs and uvm interfaces

internal/hcs/process.go
This function and its associated type are not used outside the package
and are an implementation detail.
=> hcs: Make Process.Properties private

internal/hcsoci/create.go, internal/hcsoci/hcsdoc_lcow.go, internal/hcsoci/hcsdoc_wcow.go, internal/schema2/compute_system.go, internal/uvm/create.go
This change adds a CreateContainer method to UtilityVM and updates
hcsoci to use it. This change is necessary because if the external
bridge is in use, container creation goes through that instead of
through the HCS.
=> uvm: Add UtilityVM.CreateContainer method

cmd/containerd-shim-runhcs-v1/exec_hcs.go, cmd/containerd-shim-runhcs-v1/task_hcs.go, cmd/runhcs/container.go, cmd/runhcs/shim.go, container.go, internal/cow/cow.go, internal/hcs/system.go, internal/hcsoci/create.go, internal/lcow/process.go, internal/lcow/scratch.go, internal/uvm/create.go, test/functional/lcow_test.go, test/functional/test.go, test/functional/wcow_test.go
The external bridge will provide an alternate implementation of these
interfaces.
Note that the external bridge will not be compatible with clients that
call OpenProcess or OpenComputeSystem (since the bridge will run
in-proc). So runhcs, which relies on OpenComputeSystem, does not use
these types and will use a type assertion to get back to an hcs.System.
=> cow: Add and use interfaces for containers and processes

internal/cow/cow.go, internal/hcs/system.go, internal/hcsoci/cmd.go, internal/hcsoci/cmd_test.go, internal/schema1/schema1.go, internal/tools/uvmboot/main.go, internal/uvm/create.go
Cmd is modeled after os/exec.Cmd, which makes it easy to launch
and wait for processes and relay their stdio. This version of Cmd is
designed to take in an OCI process specification, and it can launch a
process on anything that implements cow.ProcessHost.
=> hcsoci: Add Cmd type for simplifying process launches

cmd/containerd-shim-runhcs-v1/diag.go
The default user for container processes does not exist for the utility
VM. Explicitly set the user to SYSTEM.
=> shim: Run diag exec processes on Windows as SYSTEM

internal/gcs/guestconnection.go, internal/gcs/process.go, internal/gcs/protocol.go, internal/uvm/create_wcow.go
This change fixes various bugs to unblock WCOW support for UVMs that
support the RS5+ GCS protocol.
=> gcs: Add WCOW support

internal/lcow/scratch.go
This change disables lazily initialization of the sandbox VHDX's inode
tables. This prevents the kernel from subsequently zeroing them in the
background at each container start.
=> lcow: Eagerly initialize the ext4 inode tables

go.mod, go.sum, layer.go, vendor/github.com/Microsoft/go-winio/file.go, vendor/github.com/Microsoft/go-winio/pkg/guid/guid.go, vendor/modules.txt
This is part of fixing the guid-to-array functions in layer.go which
were using the wrong array indices. The best way to fix this now is to
use the functionality in the go-winio guid package.
=> Replace guid-to-array with APIs from guid package

container.go, internal/hcs/process.go, internal/hcs/system.go
CreateIoCompletionPort (used by makeOpenFiles) can only be called once
successfully for a given underlying object, regardless of how many
handles we have to the object.
The previous behavior of process stdio was to call
HcsGetProcessInfo when Stdio was called, then call makeOpenFiles and
return the resulting handles[1].
As part of a recent change, CreateProcess was changed to call
makeOpenFiles on the stdio handles at process creation time, and save
the new handles on the process struct. These saved handles are now
returned directly by Stdio. In an effort to preserve legacy compat, a
new function, StdioLegacy, was added which preserved the old Stdio
behavior, and the legacy caller was changed to use StdioLegacy instead
of Stdio.
However, because CreateIoCompletionPort can only be called …
=> Add new create process API to not save stdio pipes

test/cri-containerd/container_test.go
This test runs a container that outputs incrementing integers every 0.1
seconds. The container output goes to a log file. After 3 seconds of
execution, the log file is rotated by first renaming the existing file
(which will cause output to continue to go to the renamed file), and
then calling CRI's ReopenContainerLog. ReopenContainerLog causes
containerd to close the old log file handle, and open a new handle to
the original file path. After waiting 3 more seconds, we then stop the
container, and validate to make sure no numbers were skipped in the
combined two log files.
=> Add test for container log rotation

cmd/containerd-shim-runhcs-v1/service.go
Found investigating 21355099. @jterry75 PTAL
Command being run: `ctr --debug run --rm --tty --runtime io.containerd.runhcs.v1 --mount="type=virtual-disk,src=c:\formatted.vhd,dst=c:\test" mcr.microsoft.com/windows/nanoserver:1809 mycontainer cmd`
(Note the end-to-end works fine with Xenon).
Shim panics with following stack:
```
runtime error: invalid memory address or nil pointer dereference" stack="goroutine
7 [running]:
main.stack(0xc00019db40, 0xa13200, 0x9853b0)
e:/go/src/github.com/Microsoft/hcsshim/cmd/containerd-shim-runhcs-v1/main.go:45 +0xa4
main.panicRecover()
e:/go/src/github.com/Microsoft/hcsshim/cmd/containerd-shim-runhcs-v1/main.go:57 +0x78
panic(0xa13200, 0x9853b0)
C:/Go/src/runtime/panic.go:522 +0x1c3 …
```
=> Avoid panic: argon with VHD

osversion/windowsbuilds.go
My bad; inadvertently used the wrong version on this line (added in 73d28eadd65466bcb6dfd92096909ccdf1bd6ee8 / https://github.com/Microsoft/hcsshim/pull/568)
=> Fix Windows Server version for RS4 in comment

internal/uvm/create_lcow.go
=> lcow: Explicitly pass CPU count to UVM via kernel command line

cmd/containerd-shim-runhcs-v1/exec_hcs.go, cmd/containerd-shim-runhcs-v1/exec_wcow_podsandbox.go, cmd/containerd-shim-runhcs-v1/pod.go, cmd/containerd-shim-runhcs-v1/service.go, cmd/containerd-shim-runhcs-v1/task_hcs.go, cmd/containerd-shim-runhcs-v1/task_wcow_podsandbox.go, internal/hcs/process.go, internal/hcs/vmcompute.go, internal/hcsoci/hcsdoc_lcow.go
Some HCS* functions return errors to signify a success with additional
information. In these cases we need to skip logging the error because the use
cases is expected and this isn't an error for the client who handles it.
=> Stop logging expected error values

cmd/containerd-shim-runhcs-v1/service.go, internal/hcs/process.go, internal/hcs/vmcompute.go
After talking more about this it is incorrect to revert this at the span level
this needs to be a client side filter as the span truly should represent the
status of the function or unit of work being executed.
=> Revert OpenCensus Span Filtering

internal/hcs/vmcompute.go
We do not need to log the OperationPending error code because this is an
expected case.
=> Filter OperationPending logs SystemShutdown

cmd/containerd-shim-runhcs-v1/serve.go, cmd/containerd-shim-runhcs-v1/service_internal.go, cmd/containerd-shim-runhcs-v1/start.go
containerd has an option struct for our shim which contains both
shim-wide options (e.g. logging level) and task specific options (e.g.
sandbox image to use). Previously containerd only passed these options
in as part of the task creation call, but recently also added support
to pass them in directly to the shim via a protobuf message in stdin.
Now that containerd supports passing the options directly to the shim,
we can use that as the source for shim-wide options, instead of doing
that only when a task is created. This will also make it easier to add
more shim-wide options in the future, as their affect can be applied
immediately on shim start.
=> Receive shim options via stdin

hcn/hcnnetwork.go
Fixing an issue where the network Type is missing for NAT networks. The issue comes from how HNS defines network types in the mars schema. The network type in the HNS schema V2 is defined as an "omitempty" integer-based enum where NAT is encoded as value '0'. Since '0' is interpreted by the mars compiler as an empty value, the value is omited during schema encoding. As a result, the HCSShim needs to compensate for the lack of explicit type when NAT networks are being used.
Tests run: manually tested the behavior using a private tool.
=> Fixing an issue with NAT network type and omitempty using the V2 schema

cmd/containerd-shim-runhcs-v1/nopformatter.go, cmd/containerd-shim-runhcs-v1/serve.go
Log output modes determine where logging output is sent from the serve
shim:
- NPIPE, the default, causes log output to be sent over the log pipe
that containerd provides.
- FILE, is unsupported and causes the shim to panic.
- ETW, causes log output to be sent only to ETW via the Logrus hook.
Log output mode can be set via the DebugType enumeration on the shim
options struct.
=> Add support for different log output modes

hcn/hcnendpoint.go, hcn/hcnendpoint_test.go, hcn/hcnpolicy.go
This tests that HNS doesn't spit back errors in case we send either an Add or Create request to it for a detached endpoint.
In addition, I added some fields to the L4ProxyPolicySetting struct to support the WFP proxy. I also added the ability to specify the request type when calling HostComputeEndpoint.ApplyPolicy().
**Note**: This PR is ready for review, but shouldn't be merged yet as HNS doesn't fully support this yet.
=> Add tests for the L4 proxy policy

test/cri-containerd/runpodsandbox_test.go
The setting for VM processor limit is out of 100,000 not 10,000 so previously
only 9% CPU limit was being applied for the entire UVM.
=> Fix VM processor.limit in tests

hcn/hcnpolicy.go
WFP expects the field "CompartmentID", not "NetworkCompartmentID". Passing the wrong field causes it to be silently ignored, but the proxy would be misconfigured.
=> Use the right field name in L4ProxyPolicySetting

internal/uvm/create.go, internal/uvm/create_lcow.go, internal/uvm/create_wcow.go, internal/uvm/modify.go, internal/uvm/network.go, internal/uvm/plan9.go, internal/uvm/scsi.go, internal/uvm/start.go, internal/uvm/vpmem.go, internal/uvm/vsmb.go, internal/uvm/wait.go
Almost all logs at this level are duplicate as they translate to a message that
is sent to either the gcs or hcs package which logs all RPC messages already.
=> Cleanup excess or duplicate internal/uvm package logs

cmd/containerd-shim-runhcs-v1/main.go, cmd/containerd-shim-runhcs-v1/service.go, cmd/containerd-shim-runhcs-v1/task.go, cmd/containerd-shim-runhcs-v1/task_hcs.go, cmd/containerd-shim-runhcs-v1/task_test.go, cmd/containerd-shim-runhcs-v1/task_wcow_podsandbox.go
1. Adds context to the dump stack trace so that it can be correlated.
2. Adds support for guet DumpStacks on standalone LCOW/WCOW as well.
3. Limits the guest timeout from 5 minutes to 5 seconds for a guest stack trace.
=> Include context identifiers on DumpStacks requests

test/cri-containerd/execcontainer_test.go, test/cri-containerd/runpodsandbox_test.go
Adds a couple of test to verify that creating custom size scratch vhds is working with cri/containerd annotations
=> Add Tests for create containers with custom size scratch vhd

cmd/containerd-shim-runhcs-v1/events.go
This fixes a regression introduced when we switched to TTRPC for
publishing events to containerd. Previously we explicitly passed the
namespace for each event as a command line parameter to containerd.exe,
which was invoked to publish the event. Now that TTRPC is used, the
context passed to Publish is expected to include the namespace as a
stored value.
=> Explicitly set namespace when publishing an event

internal/uvm/create_lcow.go, internal/uvm/start.go, internal/uvm/types.go, internal/uvm/wait.go, test/cri-containerd/execcontainer_test.go
This change updates the Linux UVM boot sequence to open a vsock
connection to send entropy data to seed the kernel RNG. This is
necessary so that early uses of the kernel RNG reliably get
unpredictable data.
This depends on the corresponding change to init in the opengcs repo.
=> uvm: Send entropy to Linux UVMs during boot

test/cri-containerd/execcontainer_test.go
Previously execcontainer_test.go was marked with a failing_tests build
tag which caused it to not actually be built. At some point after we
added support for run-as-user to LCOW, the build tag was removed.
However, it appears the test actually didn't work. The CRI default is to
put all containers in the same pod PID namespace, but the test assumed
the workload container's init would be PID 1 (PID 1 was actually the
sandbox container's init).
To fix this, we now specify the container PID namespace mode for the
workload container, so that it won't share a namespace with other
containers.
=> Fix LCOW run-as-user test to use own PID namespace

internal/hcsoci/layers.go, internal/uvm/create_lcow.go, internal/uvm/types.go, internal/uvm/vpmem.go
This PR fixes the bug where cri could not run a sandbox when the max number of VPMem devices is set to one. 
=> Add check for number of vpmem devices on uvm

cmd/containerd-shim-runhcs-v1/exec_test.go, cmd/containerd-shim-runhcs-v1/task_hcs.go, cmd/containerd-shim-runhcs-v1/task_hcs_test.go, test/cri-containerd/container.go, test/cri-containerd/container_network_test.go, test/cri-containerd/container_test.go, test/cri-containerd/createcontainer_test.go, test/cri-containerd/exec.go, test/cri-containerd/execcontainer_test.go, test/cri-containerd/runpodsandbox_test.go, test/cri-containerd/sandbox.go, test/cri-containerd/stopcontainer_test.go
1. When issuing a Kill we know log any error from outstanding execs but do not
stop iterating to all other execs. We finally always send that signal to the
init exec.
2. We no longer verify that when sending a signal to the init exec that all
other execs are in the exited state. This was allowing a non-exited exec to
prevent the container from stopping.
3. When issuing a delete on the init exec we now forcibly exit all outstanding
execs.
=> Fix an issue where un-exited exec's can stop container kill

go.mod, go.sum, vendor/github.com/containerd/ttrpc/.travis.yml, vendor/github.com/containerd/ttrpc/client.go, vendor/modules.txt
I see a lot of `no status provided on response` errors right now:
```
time="2019-09-25T04:25:24.786235700Z" level=error msg="forward event" error="no status provided on response"
time="2019-09-25T04:25:25.649597000Z" level=error msg="forward event" error="no status provided on response"
time="2019-09-25T04:25:26.795661200Z" level=error msg="forward event" error="no status provided on response"
time="2019-09-25T04:25:28.651497300Z" level=error msg="forward event" error="no status provided on response"
time="2019-09-25T04:25:29.810168200Z" level=error msg="forward event" error="no status provided on response"
time="2019-09-25T04:25:32.664288500Z" level=error msg="forward event" error="no status provided on response"
time="2019-09-25T04:25:33.820457100Z" level=error msg="forward event" …
```
=> Update ttrpc to fix status check error.

internal/uvm/stats.go, internal/uvm/types.go
This change does several things to make querying UVM stats more robust:
- Regardless of the error encountered when checking a process to see if
it is the correct vmmem instance, log the error and skip to the next
process. Previously we only skipped if the error was
ERROR_ACCESS_DENIED. One case this will handle better now is if the
process has exited by the time we try to open it, we will now continue
looking at the other processes.
- The error returned by the vmmem lookup is now saved and returned every
time we retrieve the saved vmmem process. This will make it easier to
understand what the original error was even if we only have logs from
the Nth time querying for stats.
- Added additional logging during vmmem lookup:
- Every time we fail to check a process
- Every vmmem process right …
=> Reliability and logging improvements to UVM stats

internal/hcsoci/resources_wcow.go, internal/requesttype/types.go, internal/uvm/create_wcow.go, internal/uvm/types.go, internal/uvm/vsmb.go, test/cri-containerd/createcontainer_test.go
We currently support a temporary fix here to allow WCOW single-file
mounts to function. VSMB does not support directly mapping a single file
into a UVM, but rather supports an `AllowedFileList` along with options
`RestrictFileAccess` and `SingleFileMapping`, which are together used to
ensure that the share only presents a subset of the actual present
files. We map the file into the UVM using this approach, and then use
bindflt in the UVM to present the file in the share at the desired
location in the container file system.
However, naively implementing this introduces some problems. Notably,
the VSMB share map tracks shares by the host path, leading to problems
if you try to map an additional single file from the same directory, or
map a directory as both a set of single files, as well as …
=> Support WCOW single-file mounts 

internal/hcsoci/resources_lcow.go
=> Do not remove sandbox prefix for sandbox mount before passing to opengcs

cmd/containerd-shim-runhcs-v1/task_hcs.go, internal/gcs/container.go
1. When issuing a Shutdown/Terminate over external bridge shorten the timeout
window to 30 seconds to protect against a misbehaving guest.
2. When waiting for a Shutdown to complete and the container to exit shorten
the timeout to 30 seconds to protect against a misbehaving guest.
=> Shorten Shutdown and Terminate timeout to 30 seconds

hcn/hcnendpoint_test.go, hcn/hcnloadbalancer_test.go, hcn/hcnpolicy.go, hcn/hcnutils_test.go
* Modified LoadBalancer tests from creating NAT Networks to create Overlay Networks. HNS added stricter validation and ELBPolicy is only allowed on SDN Networks, causing tests to fail.
* Updated WFP Proxy policy (and tests) to reflect the most recent schema changes.
=> Updating HCN LoadBalancer and Proxy code.

internal/hcsoci/hcsdoc_lcow.go
The GCS itself sets the cgroup parent based on its internal layout. Disallow
users to set this themselves.
=> Clear Linux.CgroupsPath in LCOW activation

internal/hcsoci/hcsdoc_wcow.go, internal/hcsoci/resources.go, internal/hcsoci/resources_wcow.go, internal/uvm/pipes.go, internal/uvm/vsmb.go, test/cri-containerd/createcontainer_test.go, test/cri-containerd/runpodsandbox_test.go
Adds support for forwarding a named pipe from the host into a WCOW
hypervisor container (forwarding to a process container appears to
already have been supported). To forward a pipe into a hypervisor
container, the pipe must first be mapped into the UVM via the
MappedPipes resource type. The MappedPipes resource actually just sets
up a VSMB share for the pipes, so in the future we could choose to
manage this concept directly as a VSMB share rather than via the
MappedPipes resource.
=> Support forwarding named pipes to WCOW hypervisor container

internal/wclayer/expandscratchsize.go, internal/wclayer/wclayer.go, internal/wclayer/zsyscall_windows.go
This change works around a bug in Windows where a sandbox VHDX that has
been resized cannot be successfully mounted. This is due to a failure in
the path that resizes the NTFS volume inside the VHDX during the sandbox
mount process. To work around this, manually expand the volume in the
wclayer package just after making the call to expand the VHDX.
This change hurts the performance of the resize operation on affected
Windows hosts (19H1 and prerelease versions of Vb) and should be
reverted once the Windows bug has been fixed and is widely deployed.
This should provide a workaround for #708.
=> wclayer: Work around Windows bug when expanding sandbox size

test/cri-containerd/createcontainer_test.go
Now that we properly honor the CPU set limits the test starting failing because
it uses an invalid set of processors for a default 2 vCPU UVM.
=> Fix issue in LCOW test with CPU set limit

hcn/hcn.go, hcn/hcnglobals.go, hcn/hcnsupport.go, hcn/hcnsupport_test.go
Adding Slash32EndpointPrefixes and AclSupportForProtocol252 feature detection logic.
- Introduced support for detecting features on disjoint HNS versions
- Added support for Slash32EndpointPrefixes and AclSupportForProtocol252
- Added unit-testing of version ranges to the go tests
=> Adding Slash32EndpointPrefixes and AclSupportForProtocol252 feature detection logic

internal/hcsoci/layers.go, internal/uvm/create_lcow.go, internal/uvm/types.go, internal/uvm/vpmem.go
1. Fixes a race condition between when the check for vPMEM layer space and the
actual addition takes place for parallel creates/removals.
2. Simplifies the fallback logic for LCOW when adding layers first to vPMEM and
if there is no space or the file is too large based on max vpmem layer size
settings falls back to SCSI.
=> Fix a race condition in vPMEM layer addition fallback

internal/hcsoci/layers.go, internal/uvm/scsi.go, internal/uvm/vpmem.go, test/functional/uvm_vpmem_test.go
1. Simplifies the hcsoci.MountContainerLayers logic on failure to use defer
statements to avoid duplicate code.
2. Modified the uvm.AddSCSILayer to return the uvmpath since all callers
assumed its location.
3. Modified the uvm.AddPMEM to stop returning device number since all callers
ignored its response.
=> Simplify hcsoci.MountContainerLayers cleanup logic

hcn/hcn.go, hcn/hcnglobals.go, hcn/hcnloadbalancer.go, hcn/hcnsupport.go, hcn/hcnsupport_test.go
Adding session affinity support through loadbalancer distribution type
=> Adding session affinity support through loadbalancer distribution type

internal/guestrequest/types.go, internal/hcsoci/create.go, internal/hcsoci/layers.go, internal/hcsoci/resources.go, internal/hcsoci/resources_lcow.go, internal/uvm/scsi.go, internal/uvm/vpmem.go
* move layer files to /run/layers
* move container specific files to /run/gcs/c/id
=> move container files to be backed by writeable storage

cmd/containerd-shim-runhcs-v1/service.go
To improve the ability to understand what is when the shim is managing a pod we
now include the 'pod-id' on the entry span as well as the existing 'task id'
and 'exec id'.
=> Add 'pod-id' correlation to all shim entry RPC's

container.go, internal/hcs/process.go, internal/hcs/system.go
HcsCreateProcess returns a set of stdio handles for the newly created
process. A while ago, we used to cache these handles and return them
the first time stdio handles were requested for the process, and then
get new handles via HcsGetProcessInfo for each subsequent request. At
some point, this code was cleaned up to instead always return the
original set of handles as non-closable (for new callers) and always get
new handles via HcsGetProcessInfo (for legacy callers, who required
closable handles).
However, this change introduced a race condition for legacy callers,
where in the case of a short lived container process, the container
could have terminated between when it was started and when the
orchestrator requested stdio handles. This led to ERROR_NOT_FOUND
being returned from …
=> Fix race condition in legacy process stdio code

hcn/hcnerrors.go, hcn/hcnerrors_test.go
It looks like it had its logic backwards. Added some test coverage and tried to make the test failures more helpful as well.
Resubmission of #519
=> Fix NetworkNotFoundError and EndpointNotFoundError message strings

README.md
The previous link now redirects to the top of the Virtualization team blog.
There's also a version at https://docs.microsoft.com/en-us/virtualization/community/team-blog/2017/20170127-introducing-the-host-compute-service-hcs if that is preferred, but at least some of the formatting was lost in translation to Markdown, and needs to be fixed.
=> Updated link to Host Compute Service blog post

internal/hcsoci/resources.go
The issue was observed while experimenting with Buildkit for Windows against containerd, and getting a 'ttrpc closed' error after the layer had completed its task successfully.
The null ptr access in `vm.DeleteContainerStateSupported` was killing the thread it was on, and hence the channel back to containerd was never given an answer before the shim cleaned up the container and terminated.
=> Fix shim crash when cleaning up process-isolated containers

appveyor.yml, internal/hcs/cgo.go
With https://github.com/golang/go/commit/bb0fae603bd19e096e38c3321d95bf114f40dcff this also 
works without CGO (>=Go 1.11).
=> HCS: Remove not anymore needed CGO dependency

cmd/containerd-shim-runhcs-v1/io_npipe.go
In order for the shim to support true cancellation we need to use contextual
pipe dial's when opening in/out/err pipes for container upstream IO.
=> Use winio.DialPipeContext for upstream IO

internal/copyfile/copyfile.go, internal/lcow/scratch.go, internal/wcow/scratch.go, test/functional/uvm_vpmem_test.go
CopyFileW is an external call from the shim and thus should have a span for
tracking reliability and duration.
=> Add span around CopyFileW win32 call

cmd/containerd-shim-runhcs-v1/events.go, cmd/containerd-shim-runhcs-v1/exec_hcs.go, cmd/containerd-shim-runhcs-v1/exec_wcow_podsandbox.go, cmd/containerd-shim-runhcs-v1/io_npipe.go, cmd/containerd-shim-runhcs-v1/pod.go, cmd/containerd-shim-runhcs-v1/task_hcs.go, cmd/containerd-shim-runhcs-v1/task_wcow_podsandbox.go
We decided long ago that only entry and exit methods should have spans
associated. Since the caller of all context methods will always have a span
removing these child spans makes it significantly easier to see a full log
chain.
=> Cleanup usage of internal spans in shim

internal/hcsoci/hcsdoc_wcow.go, internal/hcsoci/layers.go, internal/hcsoci/resources_wcow.go, internal/tools/zapdir/main.go, internal/uvm/scsi.go, internal/wclayer/activatelayer.go, internal/wclayer/baselayer.go, internal/wclayer/createlayer.go, internal/wclayer/createscratchlayer.go, internal/wclayer/deactivatelayer.go, internal/wclayer/destroylayer.go, internal/wclayer/expandscratchsize.go, internal/wclayer/exportlayer.go, internal/wclayer/getlayermountpath.go, internal/wclayer/getsharedbaseimages.go, internal/wclayer/grantvmaccess.go, internal/wclayer/importlayer.go, internal/wclayer/layerexists.go, internal/wclayer/layerid.go, internal/wclayer/layerutils.go, internal/wclayer/nametoguid.go, internal/wclayer/preparelayer.go, internal/wclayer/processimage.go, internal/wclayer/unpreparelayer.go, internal/wcow/scratch.go, layer.go, test/functional/utilities/scratch.go, test/functional/uvm_scsi_test.go, test/functional/wcow_test.go
1. Add span support for all wclayer operations.
2. Remove excess storage logging since it is all logged at the wclayer
interface now.
=> Improve wclayer context logging

internal/hcsoci/layers.go, internal/hcsoci/resources_lcow.go, internal/hcsoci/resources_wcow.go, internal/lcow/scratch.go, internal/uvm/scsi.go, test/cri-containerd/main.go, test/cri-containerd/runpodsandbox_test.go, test/functional/lcow_test.go, test/functional/uvm_scratch_test.go, test/functional/uvm_scsi_test.go
This is a re-visiting of the change made by abwah previously in commit
7f17353012eda1dbd8367135642ec24ebc88bd1d. That work was reverted due to
test failures with WCOW. With this new change, we no longer attempt to
support WCOW (we can look into that later if needed).
This change also differs from the original in that we now generate the
VHD dynamically at test time, rather than checking in a static VHD file.
@abwah FYI
=> Allow a VHD to be mounted into multiple LCOW containers in the same pod

internal/uvm/scsi.go, test/functional/uvm_scsi_test.go
previously in the [work to support adding the same scsi device to multiple containers](https://github.com/microsoft/hcsshim/pull/773), ref count was only set to 1 if the device was a layer. This caused allocated non-layer scsi devices to never be removed as decrementing the ref count on removal would cause uint underflow.
=> always set newly allocated scsi device's ref count to 1

internal/hcsoci/resources_lcow.go, test/cri-containerd/container_test.go, test/cri-containerd/main.go, test/functional/uvm_scsi_test.go
* add necessary annotation to previous gpu test for linux boot files
* add additional check that after container has exited, gpu vhd is removed from uvm
=> fix scsimount path for gpu vhd addition to allow proper clean up 

internal/hcsoci/resources_lcow.go, internal/uvm/counter.go, internal/uvm/types.go
Every VHD that is mounted inside a container must be mounted in the UVM first. When different containers mount the different VHDs, a unique mount path (unique inside the UVM) should be generated for each such VHD. Existing mount code generates such unique paths but those paths are unique only across the container. Hence, two different VHDs mounted by two different containers will have unique path inside their own container world but can have the same path inside the UVM. Due to this the second mount will end up mounting over the existing mount of the first container.
This change fixes the bug to generate such unique mount paths across the UVM instead of just keeping them unique to the container.
=> Fix multiple VHD overlapping mount bug LCOW

internal/hcs/syscall.go, internal/hcs/utils.go, internal/hcs/zsyscall_windows.go, internal/hcsoci/resources_wcow.go, test/cri-containerd/runpodsandbox_test.go
In order to mount a VHD to a container, first it needs to be mounted inside the UVM.  We generate a unique mount point (inside UVM) for every such mount that is requested by a container. However, this
breaks when two containers try to mount the same VHD. Because then we generate two unique paths for the same VHD and try to mount it at two different locations inside the UVM. This change fixes that issue for WCOW containers. (corresponding LCOW change was done in #773 )
=> Allow a VHD to be mounted into multiple WCOW containers in the same pod

internal/hcsoci/layers.go, internal/hcsoci/network.go, internal/hcsoci/resources.go, internal/hcsoci/resources_lcow.go, internal/hcsoci/resources_wcow.go, internal/lcow/scratch.go, internal/uvm/create_lcow.go, internal/uvm/create_wcow.go, internal/uvm/network.go, internal/uvm/pipes.go, internal/uvm/plan9.go, internal/uvm/scsi.go, internal/uvm/types.go, internal/uvm/virtual_device.go, internal/uvm/vsmb.go, test/functional/lcow_test.go, test/functional/uvm_scratch_test.go, test/functional/uvm_scsi_test.go, test/functional/uvm_virtualdevice_test.go, test/functional/uvm_vsmb_test.go
* Changed all resources that were originally just a slice of strings(paths mostly) to be actual structs with the paths as fields. This allows the structs to implement how they are cleaned up/released now.
* Moved the logic of resource cleanup out of ReleaseResources and into the corresponding Release methods of the structs.
* New interface to eventually have all resources implement so they can all be generically closed without worrying about what the resource is.
* Move scsiInfo fields into ScsiMount so we can track the lifetime of a sci mount from one object instead of two.
* Exported vsmbShare
=> Encapsulate UVM Resources into types with Release functions 

internal/hcsoci/layers.go
Fixes an issue introduced in 298b1378aa39919c4a103c1e450c95bdace16d05.
=> Fix wrapped error missing when failing to add scratch VHD

internal/hcsoci/resources_wcow.go, test/cri-containerd/createcontainer_test.go
Previously, an errant break statement caused the presence of a read-only
VSMB mount on a container to cause the container activation to fail.
This fixes the issue by removing the break statement. This commit also
adds test cases for read-only mounts (for both LCOW and WCOW, even
though VSMB is only used for WCOW).
=> Fix read-only VSMB mounts

internal/hcsoci/layers.go, internal/hcsoci/resources_lcow.go, internal/hcsoci/resources_wcow.go, internal/lcow/scratch.go, internal/uvm/scsi.go, test/functional/lcow_test.go, test/functional/uvm_scratch_test.go, test/functional/uvm_scsi_test.go
* add counter of scsi layers to uvm struct
* move mount location of scsi layers
* add option for customizing vm granted access to scsi functions
This addresses the issue where calling GrantVmAccess on a given file (for example, the nvidia vhd) causes an `Incorrect Parameter` error after numerous calls. 
=> Refactor scsi layer addition

internal/hcsoci/layers.go, test/cri-containerd/container_test.go
This fixes a bug where a scsi layer added to two containers would fail on the second container due to trying to use an incorrect uvmPath that the second container had constructed instead of the correctly set up uvmPath created on the first container's creation. 
Adds a test to find this in the future by creating two containers that share base layers in a pod that does not allow for virtual pmem devices, therefore falling back to scsi for all layer additions. 
=> Update scsi layer's uvmPath

hcn/hcnglobals.go
When [session affinity support was added](https://github.com/microsoft/hcsshim/pull/730) to hcsshim via LoadBalancerDistribution field, an incorrect version check was established. This PR correctly lines up hcsshim with the release of the LoadBalancerDistribution platform work in HNS.
=> Updating session affinity version check

test/cri-containerd/runpodsandbox_test.go
The Test_RunPodSandbox_MultipleContainersSameVhd_WCOW test does not work
prior to 19H1. In those versions, HcsFormatWritableLayerVhd requires the
VHD to be mounted prior to calling, which we don't do currently. Because
of this, we are unable to create a VHD to use for the test.
This fixes the issue by simply skipping the test on the affected OS
versions. We could potentially resolve this in the future by adding
more code to do the VHD mount ourselves, but this is a quick fix for
moment.
We will still have test coverage of this functionality on 19H1, so this
shouldn't be a big issue.
=> Skip test on Windows before 19H1

test/cri-containerd/container_downlevel_test.go, test/cri-containerd/container_network_test.go, test/cri-containerd/container_test.go, test/cri-containerd/createcontainer_test.go, test/cri-containerd/execcontainer_test.go, test/cri-containerd/main.go, test/cri-containerd/runpodsandbox_test.go, test/cri-containerd/stats_test.go, test/cri-containerd/stopcontainer_test.go, test/functional/utilities/stringsetflag.go
This change adds support to the cri-containerd test suite to pass
feature flags on the command line to control what sets of functionality
are tested. The flags are passed as "-feature <feature>", and multiple
flags can be passed to a single invocation. This change also adds a
helper function that can be used to test if a given set of features are
enabled. If any of the required features are not enabled, the current
test is skipped. If no feature flags were passed, the helper function
treats all features as enabled.
This change is needed to support environments where we only want to run
subsets of the tests. For instance, in some cases we don't want to test
LCOW at all.
The -run test command parameter offers similar functionality through
specifying a regex to filter tests. However, it does …
=> Add feature flags to cri-containerd tests

cmd/containerd-shim-runhcs-v1/exec_hcs.go, cmd/containerd-shim-runhcs-v1/task_hcs.go, cmd/containerd-shim-runhcs-v1/task_wcow_podsandbox.go, internal/hcsoci/diag.go, internal/hcsoci/io.go, internal/hcsoci/io_npipe.go
Intermediate PR for vpci assigned devices work. 
* This PR just exports the function `execInUVM` and moves around related files. Allows us to make calls to execute commands in the UVM from outside of the cmd/containerd-shim-runhcs-v1 package. 
=> Export execInUVM to allow for access to the tool outside cmd

internal/hcsoci/layers.go, internal/hcsoci/resources_wcow.go, internal/oci/uvm.go, internal/uvm/create.go, internal/uvm/create_lcow.go, internal/uvm/create_wcow.go, internal/uvm/types.go, test/cri-containerd/runpodsandbox_test.go
* Necessary for assigned devices work to allow WCOW vsmb devices to not use virtual memory, a requirement of using vpci to assign a device to a pod. 
* Adds functions to handle annotations that imply other annotations
* Adds testing for LCOW and WCOW scenarios with the new annotation
=> Add annotation for UVMs to be fully physically backed

internal/hcsoci/resources_lcow.go, internal/uvm/create_lcow.go, internal/uvm/create_wcow.go, internal/uvm/types.go, internal/uvm/virtual_device.go, test/cri-containerd/container_test.go, test/cri-containerd/container_virtual_device_test.go, test/cri-containerd/main.go, test/functional/uvm_virtualdevice_test.go
This allows us to map given gpus or assigned devices into multiple containers. This can be used to adding sidecar containers to monitor assigned gpu devices. 
* add additional tests for GPU scenarios 
=> Add ref counting of assigned devices

internal/uvm/constants.go, internal/uvm/create.go, internal/uvm/create_lcow.go, internal/uvm/create_test.go, internal/uvm/create_wcow.go, internal/uvm/stats.go, internal/uvm/types.go, internal/uvm/vpmem.go, test/cri-containerd/stats_test.go
* Added a field (physicallyBacked) to UtilityVM struct.
* Fix behavior of querying the UVMs vmmem process to get the working set
size for physical backed UVMs. Instead we assign the total memory assigned
to the UVM by using AssignedMemory * 4096 (is returned as number of 4kb pages)
=> Fix 'WorkingSetBytes' memory metric for PA backed VMs

internal/processorinfo/processor_count.go, internal/processorinfo/syscall.go, internal/processorinfo/zsyscall_windows.go
* Change to use GetActiveProcessorCount instead of GetMaximumProcessorCount
as the latter takes into account hot addable CPUs.
=> Change to use GetActiveProcessorCount for logical processor count

internal/schema2/logical_processor.go
* In a minroot configuration, everything assigned to the VM > the hosts logical processors will return -1 for RootVpIndex so unmarshaling into an unsigned integer will fail if the virtual processor count assigned to the UVM is greater than the hosts amount, i.e if the host sees 64 LPs and 65 was assigned to the UVM the last LogicalProcessor entry would have -1 for RootVpIndex. This was an 
oversight as our schema generates uints as regular ints and when manually changing them I missed that RootVpIndex was not also a uint.
=> Fix RootVpIndex type mistake

internal/hcsoci/layers.go, internal/hcsoci/resources_wcow.go, internal/uvm/create_wcow.go, internal/uvm/vsmb.go, test/functional/uvm_vsmb_test.go
* As we use almost the same set of VSMB options throughout the codebase,
this consolidates the settings into a single function instead of having to
set them manually each time.
* Remove guestrequest object from VSMBShare struct and AddVSMB as it isnt used
anywhere.
=> Add DefaultVSMBOptions function and remove guestrequest parameter

internal/uvm/vsmb.go
This was recently added with https://github.com/microsoft/hcsshim/pull/829. 
However, in the case of the single file mount case for VSMB, this function will only return the path to the directory containing the single file in the UVM. Therefore, the caller would either need to construct the full path with the single file's name or we would need to update this function to take a hostpath, neither of which are desirable. Since we already have functionality to handle getting the full UVM path for both single files and mounted directories, `GetVSMBUvmPath`, just remove the unnecessary `GuestPath` function. 
=> Remove VSMB GuestPath func

internal/hcsoci/hcsdoc_wcow.go
Previously there was an OS bug that prevented processor weight/maximum
from working properly. This has now been fixed and backported to 1809+,
so it is safe to remove this block.
@jterry75 FYI
=> Remove block on processor weight/maximum for WCOW process-isolated

test/cri-containerd/pullimage_test.go
This test involves running a 19H1-based image, and previously used
the wcow-hypervisor runtime class which uses the host OS version. This
caused the test to fail to run on RS5. This change fixes this by
explicitly using the 19H1 runtime class.
=> Change image timestamp test to use 19H1 runtime class

hcn/hcnglobals.go
This version check update reflects recent backports to rs5 and 19H1
=> Updating DSR version check to 9.3-9.max, 10.2+

osversion/windowsbuilds.go
It's not "semi-annual" if you're 12 months apart.
Mainly useful for vendoring, no tests currently distinguish V19H2 behaviour.
=> Add Windows V19H2 (1909) to builds list

internal/wclayer/createscratchlayer.go
CreateScratchLayer doesn't take a parent id anymore, just the list of parent layer paths, since #183 in 0.7.0
=> Fix comment on CreateScratchLayer

cmd/containerd-shim-runhcs-v1/task_wcow_podsandbox.go, internal/hcsoci/hcsdoc_wcow.go, internal/hcsoci/layers.go, internal/uvm/vsmb.go, test/cri-containerd/createcontainer_test.go, test/functional/uvm_vsmb_test.go
The VSMB code attempts to create as few actual shares as possible. This
is done by ref-counting existing shares so that if the same directory is
shared again, the old share is used instead. However, the mechanism for
looking up an existing share currently only keys off of the share path.
This has the unfortunate affect that a read-only share can be repurposed
as a read-write share.
I first looked at fixing this by more broadly refactoring the VSMB code,
with the aim of not only fixing this bug, but also removing some of the
hacks that were put in place to support single-file mapping. However,
that work ended up complicating things a lot, so I think other cleanup
work will need to be done first before that broader refactoring can
be merged.
As a more immediate and tactical fix, I have now …
=> Fix VSMB to not mix up rw/ro shares

cmd/wclayer/mount.go, cmd/wclayer/volumemountutils.go
This just makes life slightly easier when debugging or inspecting wclayer behaviours.
=> Teach wclayer to mount volumes at mountpoints

hcn/hcnglobals.go
Updating the AclSupportForProtocol252Version parameter to accurately reflect compatible version numbers of > 11.0
=> Update AclSupportForProtocol252Version to support versions > 11.0

cmd/containerd-shim-runhcs-v1/exec_hcs.go, cmd/containerd-shim-runhcs-v1/task_hcs.go, cmd/containerd-shim-runhcs-v1/task_wcow_podsandbox.go, cmd/runhcs/container.go, cmd/runhcs/shim.go, internal/cmd/cmd.go, internal/cmd/cmd_test.go, internal/cmd/diag.go, internal/cmd/io.go, internal/cmd/io_npipe.go, internal/credentials/credentials.go, internal/hcsoci/create.go, internal/hcsoci/hcsdoc_wcow.go, internal/hcsoci/network.go, internal/hcsoci/resources_lcow.go, internal/hcsoci/resources_wcow.go, internal/layers/layers.go, internal/lcow/scratch.go, internal/resources/resources.go, internal/tools/uvmboot/lcow.go, internal/tools/uvmboot/wcow.go, internal/uvm/automanagedvhd.go, internal/uvm/constants.go, internal/wclayer/wclayer.go, test/functional/lcow_test.go, test/functional/test.go, test/functional/wcow_test.go
This PR refactors logical units of code that were previously in the hcsoci package into their own packages. This allows us to better scope our packages and avoid circular dependencies later on. Some of the code that was moved was that relating to ImageLayers, Resource, ResourceCloser, and others. 
=> Refactor code in hcsoci into logical packages

test/cri-containerd/container_test.go
* Move the context.WithTimeout after the setup/launch of the sandbox/uvm
to avoid hitting the timeout and failing the test.
=> Fix flaky cri-containerd LCOW events test

internal/schema2/logical_processor.go
* Fix the LpIndex JSON annotation in the LogicalProcessor v2 HCS schema
from being the wrong value.
=> Fix LpIndex JSON annotation

cmd/runhcs/main.go, cmd/runhcs/prepare-disk.go, internal/lcow/common.go, internal/lcow/disk.go
Prepare-disk command formats a given disk with ext4. This is required for a disk(as passthrough) to be made available within a container. Here is an excerpt from a configuration for such a scenario.
"mounts": [
{
"host_path": "\\\\.\\PHYSICALDRIVE2",
"container_path": "/disk"
}
The gcs/runc combo expects the pass-through disk to be formatted and tries to mount it on a local path within
the uvm. Prepare-disk ensures that this restriction is met.
Note: Full disk is formatted with ext4 without any partitioning. TODO: add options to allow partitioning and then formatting.
=> Add prepare-disk command.

internal/oci/uvm.go, internal/schema2/memory.go, internal/schema2/memory_2.go, internal/tools/uvmboot/main.go, internal/uvm/create.go
The internal schema files have these values as uint64 but we previously used int32 due to an issue with the schema generation. 
=> Fix schema memory size field type

internal/uvm/memory_update.go, test/functional/test.go, test/functional/uvm_memory_test.go
This PR is part of the work to support dynamically updating resources. The work in this PR adds a call that will update the memory size (in MBs) of a UVM. This PR serves as an intermediate PR and therefore the new call is not used outside of testing. 
=> Add calls to modify UVM memory size and tests

internal/hns/namespace.go, internal/winapi/net.go, internal/winapi/winapi.go, internal/winapi/zsyscall_windows.go
* For future work to be able to run a job container in a network namespace
that isn't the hosts, added the SetJobCompartmentId function from iphlpapi.
=> Add SetJobCompartmentId function from iphlpapi.dll

internal/winapi/net.go, internal/winapi/zsyscall_windows.go
* Binding currently has the return value checked against HRESULT semantics when
this shouldn't be the case as it doesn't return an HRESULT
=> Change SetJobCompartmentId to use win32 error code semantics

internal/oci/uvm.go, internal/uvm/create.go, internal/uvm/create_wcow.go
* A change was added recently to GNS that will be backported to Vb and possibly 19H1 and RS5 that changes how network compartments are created to fix an issue with accessing smb shares in hypervisor isolated containers. To ease the worries
of this breaking anything the change will be put behind a registry key (that is only set by us) so that the change won't impact docker and can be optionally toggled off by us through this annotation.
=> Add regkey to WCOW to deal with containment for GNS compartment changes

internal/credentials/credentials.go, internal/hcsoci/resources_wcow.go, internal/resources/resources.go, internal/schema2/hv_socket_service_config.go, internal/uvm/hvsocket.go, internal/uvm/resourcepaths.go, test/cri-containerd/container_test.go, test/vendor/github.com/Microsoft/hcsshim/internal/hcsoci/credentials.go, test/vendor/github.com/Microsoft/hcsshim/internal/hcsoci/resources.go
* Add new UVM function 'UpdateHvSockServiceTable' to be able to hot add
Hvsocket service table entries.
* Add disabled field to HvSocketServiceConfig (used to be private in the schema)
* Remove hardcoded error if supplying a cred spec and the client asked for a
hypervisor isolated container.
* Misc refactors (comments, style)
=> Add GMSA support for V2 HCS schema xenon containers

cmd/containerd-shim-runhcs-v1/task.go, cmd/containerd-shim-runhcs-v1/task_hcs.go, cmd/containerd-shim-runhcs-v1/task_wcow_podsandbox.go, internal/cmd/diag.go
This PR adds a new function that allows us to exec commands on the container host of process isolated containers. This will be used in subsequent PRs to support resource modification of process isolated containers. 
=> Add new function to exec cmds in host for process isolated containers

computestorage/attach.go, computestorage/destroy.go, computestorage/detach.go, computestorage/export.go, computestorage/format.go, computestorage/import.go, computestorage/initialize.go, computestorage/mount.go, computestorage/setup.go, computestorage/storage.go, computestorage/zsyscall_windows.go
* Add bindings for the HCS storage APIs from computestorage.dll
=> Add HCS storage APIs

internal/uvm/vsmb.go, internal/winapi/filesystem.go, osversion/windowsbuilds.go
VSMB direct map requires support for querying FileIdInfo from the
backing volume. There is a bug in certain Windows versions where instead
of falling back to non-direct map when FileIdInfo is not supported, VSMB
instead causes errors whenever files on the share are accessed.
To work around this until the issue is fixed, we will query FileIdInfo
ourselves when setting up a VSMB share, and force disable direct map if
the query fails.
=> Force disable VSMB direct map when the volume does not support it

internal/jobobject/iocp.go, internal/jobobject/jobobject.go, internal/queue/mq.go, internal/queue/queue_test.go, internal/winapi/iocp.go, internal/winapi/jobobject.go, internal/winapi/winapi.go, internal/winapi/zsyscall_windows.go
* Add high level job object wrapper.
* Add extra job object bindings for stats usage.
=> Add high level job object wrapper

computestorage/helpers.go, test/go.mod, test/go.sum
* Add helper functions to setup the disks for a base WCOW layer.
=> Add base layer/uvm helpers to computestorage package

test/cri-containerd/container_downlevel_test.go, test/cri-containerd/container_network_test.go, test/cri-containerd/container_test.go, test/cri-containerd/container_virtual_device_test.go, test/cri-containerd/createcontainer_test.go, test/cri-containerd/execcontainer_test.go, test/cri-containerd/pullimage_test.go, test/cri-containerd/removepodsandbox_test.go, test/cri-containerd/runpodsandbox_test.go, test/cri-containerd/sandbox.go, test/cri-containerd/stats_test.go, test/cri-containerd/stopcontainer_test.go
refector tests to use getRunPodSandboxRequest where possible
=> add test for running container as non-default user that is missing

internal/hcsoci/hcsdoc_lcow.go
Previously,  if no network information was set on the given spec, we would hit a panic trying to set the new spec's windows devices since we relied on `setWindowsNetworkNamespace` to create the windows field. This PR fixes that by checking if the windows field is nil and creating it if so. 
=> Fix potential panic in createLCOWSpec when no network ns is set

hcn/hcnpolicy.go, hcn/hcnutils_test.go
This PR reflects the HNS L4WfpProxyPolicy change to allow the caller to distinguish the inbound and outbound proxy ports
=> Updating L4WfpProxyPolicy struct

cmd/containerd-shim-runhcs-v1/task_hcs.go
=> Fix nil dereference in `newHcsTask` if no shim options were passed

internal/cow/cow.go, internal/gcs/guestconnection.go, internal/gcs/protocol.go, internal/gcs/resourcepaths.go, internal/schema1/schema1.go, internal/uvm/update.go
This PR is part of the ongoing dynamic resources work. This PR adds new calls to allow hcsshim to issue container update requests to the running GCS. 
=> Add support for issuing a container update to gcs

.gitignore, appveyor.yml, cmd/containerd-shim-runhcs-v1/task_hcs.go, internal/cmd/io.go, internal/cmd/io_binary.go, internal/cmd/io_binary_test.go, test/cri-containerd/container.go, test/cri-containerd/helpers/log.go, test/cri-containerd/logging_binary_test.go, test/cri-containerd/runpodsandbox_test.go
This PR adds logging binary support (like in https://github.com/containerd/containerd/pull/3085).
Just like in the above PR:
* add URI parsing logic to hcsshim
* start a process for logging driver and redirect all container IO through named pipes
The flow (assuming that https://github.com/jterry75/cri/pull/82 is also merged) as follows:
* start pod
* create container inside that pod and make sure to include the `log_path` config:
```
...
"log_path": "binary:///path/to/binary.exe?foo&bar=baz"
...
```
**NOTE** that `log_path` needs to be a valid url (i.e. `"binary:\\\\\\path\\to\\binary.exe"` won't work, since `url.Parse` will fail)
* start container
You'll notice that `ctr-x-stdout` and `ctr-x-stderr` pipes won't be created, `binary-x-stdout` and `binary-x-stderr` will replace them. 
This …
=> Add support for logging binary

computestorage/attach.go, computestorage/destroy.go, computestorage/detach.go, computestorage/export.go, computestorage/format.go, computestorage/import.go, computestorage/initialize.go, computestorage/mount.go, computestorage/setup.go
* Change from stringifying errors with fmt.Errorf to errors.Wrap everywhere
Fixes: https://github.com/microsoft/hcsshim/issues/924
=> Wrap errors from computestorage package

cmd/containerd-shim-runhcs-v1/task.go, cmd/containerd-shim-runhcs-v1/task_hcs.go, cmd/containerd-shim-runhcs-v1/task_wcow_podsandbox.go, internal/gcs/bridge.go
This PR updates the code path in hcsshim when querying for stats to handle errors in a similar way [to upstream linux containers](https://github.com/containerd/containerd/blob/master/runtime/v2/runc/v2/service.go#L694). This behavior ignores errors from stats queries if the error is `Not Found`, `Does Not Exists`, or `Invalid State`. 
=> Ignore NotFound errors when getting task stats

cmd/jobobject-util/main.go, internal/jobobject/jobobject.go, internal/jobobject/limits.go, internal/safefile/safeopen.go, internal/winapi/filesystem.go, internal/winapi/jobobject.go, internal/winapi/utils.go, internal/winapi/zsyscall_windows.go, internal/winobjdir/object_dir.go
This PR does the following: 
* Creates a tool to get/set job object resource limits called `jobobject-util`
* Add new function to open existing job objects by name
* Refactor's jobobject package's resource limit functions 
* Add two new winapi functions for dealing with job objects
This PR is part of the ongoing work for dynamic resource update. The `jobobject-util` tool will be used to get/set job object limits for process- and hypervisor- isolated containers.
=> Create tool to get/set job object resource limits

appveyor.yml, internal/safefile/safeopen.go, internal/winapi/utils.go, internal/winapi/winapi_test.go
Fixes the below issue seen in the containerd test suite.
```
fatal error: checkptr: converted pointer straddles multiple allocations
```
Also adds `-gcflags=all=-d=checkptr` to all the test runs on CI, to avoid this regressing in future. This requires testing with Go 1.14 or newer, so CI now runs on Go 1.15, as [Go 1.14 did not recommend using checkptr on Windows](https://golang.org/doc/go1.14#compiler).
And Go>1.13 [requires the Visual Studio 2019 build image](https://www.appveyor.com/docs/windows-images-software/#golang) on AppVeyor.
=> Create a correctly-sized slice to proxy *uint16

cmd/containerd-shim-runhcs-v1/clone.go, cmd/containerd-shim-runhcs-v1/exec_clone.go, cmd/containerd-shim-runhcs-v1/exec_hcs.go, cmd/containerd-shim-runhcs-v1/pod.go, cmd/containerd-shim-runhcs-v1/task_hcs.go, cmd/containerd-shim-runhcs-v1/task_wcow_podsandbox.go, internal/clone/registry.go, internal/cow/cow.go, internal/gcs/container.go, internal/hcsoci/clone.go, internal/hcsoci/create.go, internal/hcsoci/hcsdoc_wcow.go, internal/hcsoci/resources_wcow.go, internal/layers/layers.go, internal/oci/uvm.go, internal/uvm/clone.go, internal/uvm/create.go, internal/uvm/create_lcow.go, internal/uvm/create_wcow.go, internal/uvm/scsi.go, internal/uvm/types.go, internal/uvm/vsmb.go
This is one of the many small PRs that enable the support for late cloning.
This commit adds the set of functions that expose the late cloning functionality
from hcsshim and adds new annotations for clients to use the late cloning feature.
=> Add support for creating late clones via hcsshim

cmd/containerd-shim-runhcs-v1/clone.go, cmd/containerd-shim-runhcs-v1/exec_clone.go, cmd/containerd-shim-runhcs-v1/exec_hcs.go, cmd/containerd-shim-runhcs-v1/pod.go, cmd/containerd-shim-runhcs-v1/task_hcs.go, cmd/containerd-shim-runhcs-v1/task_wcow_podsandbox.go, internal/clone/registry.go, internal/cow/cow.go, internal/gcs/container.go, internal/hcsoci/clone.go, internal/hcsoci/create.go, internal/hcsoci/hcsdoc_wcow.go, internal/hcsoci/network.go, internal/hcsoci/resources_wcow.go, internal/layers/layers.go, internal/oci/uvm.go, internal/uvm/clone.go, internal/uvm/create.go, internal/uvm/create_lcow.go, internal/uvm/create_wcow.go, internal/uvm/network.go, internal/uvm/scsi.go, internal/uvm/types.go, internal/uvm/vsmb.go
This is one of the many small PRs that enable the support for late cloning.
This commit adds the set of functions required for adding network namespace and
network endpoints to cloned UVMs.
=> Add support for creating network namespaces inside cloned uvms.

internal/layers/layers.go, internal/uvm/scsi.go, test/cri-containerd/container_virtual_device_test.go
=> Create upper and work directories in new locations if sharing scratch

cmd/containerd-shim-runhcs-v1/clone.go, cmd/containerd-shim-runhcs-v1/exec_clone.go, cmd/containerd-shim-runhcs-v1/exec_hcs.go, cmd/containerd-shim-runhcs-v1/pod.go, cmd/containerd-shim-runhcs-v1/task_hcs.go, cmd/containerd-shim-runhcs-v1/task_wcow_podsandbox.go, internal/clone/registry.go, internal/cow/cow.go, internal/gcs/container.go, internal/gcs/guestconnection.go, internal/gcs/guestconnection_test.go, internal/hcsoci/clone.go, internal/hcsoci/create.go, internal/hcsoci/hcsdoc_wcow.go, internal/hcsoci/network.go, internal/hcsoci/resources_wcow.go, internal/layers/layers.go, internal/oci/uvm.go, internal/uvm/clone.go, internal/uvm/create.go, internal/uvm/create_lcow.go, internal/uvm/create_test.go, internal/uvm/create_wcow.go, internal/uvm/network.go, internal/uvm/scsi.go, internal/uvm/start.go, internal/uvm/types.go, internal/uvm/vsmb.go
This is one of the many small PRs that enable the support for late cloning.
This commit adds the template and clone creation support in the uvm module.
=> Add support for creating cloned UVMs.

internal/hcsoci/create.go, internal/hcsoci/resources_lcow.go, internal/hcsoci/resources_wcow.go, internal/layers/layers.go
* Skip unmounting the layers for the sandbox container as we know the UVM gets torn down shortly afterwards.
=> Skip unmounting layers for sandbox container.

errors.go, internal/hcs/errors.go
As part of https://github.com/kubernetes/kubernetes/issues/98509 we found that a newly started container in the "Created" state but not "Running" returns errors when it queries for stats:
```
failure in a Windows system call: The requested virtual machine or container operation is not valid in the current state. (0xc0370105) 
failure in a Windows system call: Access is denied. (0x5)
```
I've [worked around it by looking for the Error codes](https://github.com/kubernetes/kubernetes/pull/98510/files#diff-63c08ffd47f6926aa51a8bc28cc8c533d83b815c4ec47f534643303eb3af72b6R55) but would be cleaner if there were other helper functions that exposed the interal error stats
Signed-off-by: James Sturtevant <jstur@microsoft.com>
=> Expose more internal errors via hscshim api

cmd/containerd-shim-runhcs-v1/task.go
After https://github.com/microsoft/hcsshim/pull/933, In some cases we found the container would get the "access is denied" error when checking for stats: https://github.com/kubernetes/kubernetes/issues/98509
/cc  @katiewasnothere
=> Add Check for access denied when looking for stats in Containerd

internal/cmd/io_binary.go, internal/cmd/io_binary_test.go
Do a better job at cleaning the logging driver path.
Add support for non-default hard drives.
=> Add better handling of windows-style paths for io_binary

internal/hcsoci/resources_wcow.go
Recent rebase from my PR: https://github.com/microsoft/hcsshim/commit/61e1b43691874280f053a7af75bcb69fe35be117
duplicated the credential spec and devices setup in `setupMounts`.
=> Fix duplicated credential spec/devices setup in allocateWindowsResources

internal/hcsoci/hcsdoc_wcow.go
See comment in code for context.
Fixes containerd/containerd#4915
=> Resolve mount source path before passing it to HCS

ext4/internal/compactext4/compact.go
Prior to this commit, the layout of created ext4 filesystems created using tar2ext4 wasn't
deterministic. Recursive directory creation would change from run to run due to the usage
of a map as temporary storage for items from the tar stream.
This commit changes recursive directory creation to follow the same deterministic pattern
as writeDirectory.
At this point, the only possible source of non-determinism in a create file system is the
UUID in the VHD footer. If no VHD footer is included, then the results are deterministic.
=> Make directory creation deterministic

ext4/internal/compactext4/compact.go
Hard links share the same inode number leading to a lack of determinism when they are layed out.
This change sorts by inode and then if they are the same, by name thereby introducing determinism.
=> Remove non-determinism in hard link handling

internal/jobobject/jobobject.go, internal/jobobject/jobobject_test.go
If nil options were passed for `Create` or `Open` both methods would run into a
nil dereference even though for `Create` it states that it will just use default options.
For `Open` you can't open without a name so if nil options are passed just return an error.
=> Fix nil dereference in jobobject.Create and Open

cmd/containerd-shim-runhcs-v1/delete.go, cmd/containerd-shim-runhcs-v1/main.go, cmd/containerd-shim-runhcs-v1/service.go
Currently hcsshim writes the shim panic logs in a file named panic.log inside the sandbox
directory. However, those logs are never logged in containerd and they get lost when the
sandbox container is removed. This change allows the shim to log these panic logs to
containerd before deleting them.
=> Log shim panic logs in containerd.

test/cri-containerd/clone_test.go
This fixes incorrect test failures when running tests on VMs which don't have network access. If we ping
something like microsoft.com on such VMs then ping fails and because of that test fails when it really shouldn't.
=> ping localhost in tests

internal/hcsoci/hcsdoc_wcow.go, internal/jobcontainers/cpurate_test.go, internal/jobcontainers/env.go, internal/jobcontainers/jobcontainer.go, internal/jobcontainers/logon.go, internal/jobcontainers/oci.go, internal/jobcontainers/path.go, internal/jobcontainers/path_test.go, internal/jobcontainers/process.go, internal/jobcontainers/storage.go, internal/jobobject/jobobject.go, internal/jobobject/jobobject_test.go, internal/jobobject/limits.go, internal/layers/layers.go, internal/oci/uvm.go, internal/winapi/memory.go, internal/winapi/path.go, internal/winapi/process.go, internal/winapi/thread.go, internal/winapi/winapi.go, internal/winapi/zsyscall_windows.go, test/cri-containerd/jobcontainer_test.go, test/cri-containerd/main.go
* Add `JobContainer` and `JobProcess` types as the two types to represent a job container
and a process in a job container.
* Add logic to find the executable being asked to run for a job container.
* Logic to launch the container as specific user.
* Logic to mount the containers scratch space on the host to a directory.
=> Add job containers package

test/cri-containerd/pullimage_test.go
Swap the image we used to use for the Test_PullImageTimestamps test to one hosted on an
ACR registry.
=> Change image used for Test_PullImageTimestamps

ext4/tar2ext4/tar2ext4.go
The change enables getting accurate information about ext4 fs on
a given VHD, rather than doing os.Stat or temp mounting the VHD.
=> add utility method to read ext4 superblock from a VHD

ext4/internal/compactext4/compact.go, ext4/tar2ext4/tar2ext4.go
Extracting LCOW layers to vhd fails when a file shows up in the
tar list before the parent directory of that file shows up. This change fixes that by
always creating any non existing parent directories and then updating their permissions
later when actual directory entry shows up.
=> Fix tar extraction issue where parent directories don't exist.

cmd/ncproxy/ncproxy.go, computestorage/helpers.go
* Remove unused mutex for the grpc service in ncproxy
* Remove unnecessary os.Stat call that didn't even check the return value
*facepalm*
=> Fix golangci linter issues

cmd/shimdiag/exec.go, cmd/shimdiag/list.go, cmd/shimdiag/share.go
None of the ArgsUsage's for any of the commands listed flags so add this.
=> Update ArgsUsage for shimdiag commands to add flags

internal/cmd/io_binary.go
additionally clean up potential linter errors
=> use cmd.String() when logging binary_io command

internal/jobcontainers/jobcontainer.go
We don't want to inherit the job object of whatever process is running the job container code (the containerd-shim
generally but this would apply for any process). Set the CREATE_BREAKAWAY_FROM_JOB flag on job container processes
to prevent this from happening. The job object itself will also need to have the JOB_OBJECT_LIMIT_BREAKAWAY_OK limit
set for this to take affect.
=> Set CREATE_BREAKAWAY_FROM_JOB flag for job container processes

test/cri-containerd/logging_binary_test.go, test/cri-containerd/main.go, test/cri-containerd/scale_cpu_limits_to_sandbox_test.go, test/testdata/scale_cpu_limits_to_sandbox/Dockerfile, test/testdata/scale_cpu_limits_to_sandbox/main.go
Test does the following:
- calculate 1 core equivalent cpu limit based on the number of cores
the host has, i.e. 10,000/hostNumCPU
- set container CPU limit to the above value.
NOTE: There won't be any difference if the host has only 2 cores
(which is the default for a UVM), but this is unlikely to happen
- make 2 stats request with a 5 second interval and calculate
the CPU usage
- the CPU usage should be around 100% with acceptable error set to 10%
Add `requireBinary` wrapper to check if a binary with a given
name exists in the same directory as the test executable and
conditionally skips the tests if the binary doesn't exist
=> Add test for ScaleCPULimitsToSandbox runtime config

ext4/tar2ext4/tar2ext4_test.go
tar2ext layer expansion had a bug where during a tar expansion if a file showed up before its parent directory then the expansion would fail with path not found error. This was fixed in #972. This commit just a adds a test for that fix.
=> Add test for tar2ext layer expansion

internal/jobcontainers/jobcontainer.go, internal/jobcontainers/system_test.go, internal/winapi/system.go, internal/winapi/thread.go, internal/winapi/winapi.go, internal/winapi/zsyscall_windows.go
* Add PropertiesV2 and Properties calls for host process containers. The only supported queries for them are
PropertiesV2: Statistics
Properties: ProcessList
* Add NtQuerySystemInformation and SYSTEM_PROCESS_INFORMATION binds.
This work will be utilized in the containerd shim just as the PropertiesV2 and Properties calls
are today for process and hv isolated containers.
=> Add stats support for job containers

internal/cmd/io_binary.go
Prevents an egde case where a goroutine would be leaked when the following case executes 
```go
case <-time.After(binaryCmdWaitTimeout):
log.G(ctx).Errorf("timeout while waiting for binaryIO process to finish. Killing")
err := b.cmd.Process.Kill()
if err != nil {
log.G(ctx).WithError(err).Errorf("error while killing binaryIO process")
}
}
```
If the above occurs before or at the same time as the case below (and the scheduler chooses to the above case), the goroutine above the `select` block would be leaked as it is blocked by the send to the `done` channel.
```go
go func() {
done <- b.cmd.Wait()
}()
select {
case err := <-done:
if err != nil {
log.G(ctx).WithError(err).Errorf("error while waiting for binary cmd to finish")
}
```
=> prevents a goroutine from being leaked if binary cmd fails to finish

cmd/ncproxy/ncproxy.go
The GRPC service doesn't hold a mutex. This was left in from an older iteration
where the client map would get updated in the grpc service.
=> Remove incorrect comment from ncproxy grpc service struct

cmd/containerd-shim-runhcs-v1/serve.go
In a comment in the serve command for the containerd-shim it says that to signify that we're
successfully serving the ttrpc endpoint we should close stderr, but we actually seem to close stdout
to signify this. The write end of the pipe is hooked up to stdout on the "serve" command invocation
of the shim and we simply forward stderr to the read side until close. Stderr for the serve
invocation is hooked up to the panic.log file 
=> Fix stderr comment in containerd-shim serve command

cmd/containerd-shim-runhcs-v1/exec_hcs.go, cmd/containerd-shim-runhcs-v1/pod.go, cmd/containerd-shim-runhcs-v1/task_hcs.go, cmd/runhcs/container.go, cmd/runhcs/create-scratch.go, cmd/runhcs/kill.go, cmd/runhcs/prepare-disk.go, computestorage/setup.go, internal/hcsoci/hcsdoc_wcow.go, internal/schemaversion/schemaversion.go, internal/uvm/create.go, internal/uvm/create_lcow.go, internal/uvm/network.go, internal/uvm/plan9.go, internal/uvm/vsmb.go, internal/wclayer/expandscratchsize.go, osversion/osversion_windows.go, test/cri-containerd/container_virtual_device_test.go, test/cri-containerd/main.go, test/cri-containerd/runpodsandbox_test.go, test/functional/utilities/requiresbuild.go
When updating https://github.com/microsoft/hcsshim/pull/556, I noticed other uses of this, so thought I'd do a minor refactor.
In this PR I noticed there's some intermediate build numbers used that don't (yet) have a corresponding `const` in osversion;
- build: 18286 (somewhere between RS5 and V19H1) -> replace with `V19H1` ?
- build: 18967 (somewhere between V19H2 and V20H1) -> replace with `V20H1` ?
- build: 19020 (somewhere between V19H2 and V20H1) -> replace with `V20H1` ?
- build: 19645 (somewhere "after" V20H2) -> has this been released? (i.e., is there a version after `V20H2`?)
Giving that the "intermediate" versions have now made their way in releases, I _assume_ (famous last words) that those can now be replaced with `<first release that contains this change>`; happy to make …
=> Use osversion.Build() utility, and add a sync.Once

internal/guestrequest/types.go, internal/hcsoci/resources_lcow.go, internal/hcsoci/resources_wcow.go, internal/layers/layers.go, internal/lcow/disk.go, internal/lcow/scratch.go, internal/uvm/scsi.go, test/cri-containerd/runpodsandbox_test.go, test/functional/lcow_test.go, test/functional/uvm_scratch_test.go, test/functional/uvm_scsi_test.go, test/vendor/github.com/Microsoft/hcsshim/internal/guestrequest/types.go, test/vendor/github.com/Microsoft/hcsshim/internal/hcsoci/resources_lcow.go, test/vendor/github.com/Microsoft/hcsshim/internal/hcsoci/resources_wcow.go, test/vendor/github.com/Microsoft/hcsshim/internal/layers/layers.go, test/vendor/github.com/Microsoft/hcsshim/internal/lcow/disk.go, test/vendor/github.com/Microsoft/hcsshim/internal/lcow/scratch.go, test/vendor/github.com/Microsoft/hcsshim/internal/uvm/scsi.go
See https://github.com/microsoft/opengcs/pull/398 for details. 
This PR updates the fields for scsi disk attachment to match those in the PR mentioned above and adds a test for the expected behavior of `rshared` mount propagation for scsi disks. 
=> Support passing in propagation flags on scsi mounts for LCOW

internal/uvm/create.go, internal/uvm/create_lcow.go, internal/uvm/create_wcow.go
There's not a single place we used to set the uvm.Options `AdditionHCSDocumentJSON` field to anything so it was as good as not there already. Just skip the calls entirely and remove the copying of the fields for lateclone scenarios. 
I've left in the package and code for v1 (docker) in case anyone out there is actually using it 😃 
=> Get rid of mergemaps functionality for v2 codepaths

errors.go, internal/hcs/errors.go, internal/hcs/system.go
Backport of f731440f562046527c8a470acb18c3a357402655 for moby 20.10 release branch
---
- these logs create noise and are no longer useful
(cherry picked from commit f731440f562046527c8a470acb18c3a357402655)
Signed-off-by: Brian Goff <cpuguy83@gmail.com>
=> [Moby] Remove extra info from error logs

hcn/hcn.go, hcn/hcnendpoint.go
HCS today for adding a network adapter to a virtual machine sets up the switch port itself by making a VmEndpointRequest. There are cases where we will want to do this ourselves, and we need the switch ID for this which will only exist after this request.
Below is an example of using this:
```go
portID, err := guid.NewV4()
if err != nil {
return errors.Wrap(err, "failed to generate guid for port")
}
vmEndpointRequest := hcn.VmEndpointRequest{
PortId:           portID,
VirtualNicName:   fmt.Sprintf("%s--%s", "cool-NIC-ID", portID),
VirtualMachineId: guid.GUID{},
}
m, err := json.Marshal(vmEndpointRequest)
if err != nil {
return errors.Wrap(err, "failed to marshal endpoint request json")
}
if err := hcn.ModifyEndpointSettings(endpointID, &hcn.ModifyEndpointSettingRequest{
ResourceType: …
```
=> Add VmEndpointRequest in hcn for eventual usage in the shim

cmd/containerd-shim-runhcs-v1/delete.go, cmd/containerd-shim-runhcs-v1/pod.go
The change to collect shim panic logs during shim delete command does not work in cases
when the delete command itself runs into some error. To avoid losing shim panic logs in
such cases we log the shim panic logs (if found) as first thing in the delete command.
CreateTask function had `wcl` mutex lock that wasn't really being used anywhere, this
change removes that. We also don't add a `nil` entry for a new task in the `workloadTasks`
map anymore to avoid the shim panic in some cases where a `GetTask` function might
be called while we are still in the process of creating the task and haven't updated the
nil entry with the actual task struct reference.
=> Minor fixes to shim panic log & create task functions

ext4/internal/compactext4/compact.go, ext4/tar2ext4/tar2ext4_test.go
This addresses nil dereference bug we encountered when doing tar2vhd conversion and extends on the previous fix to address when parent directories don't exist.
In this case the issue arises if the root directory has not yet been initialized by the time a file not in the root directory is processed. For the bug to happen the tar has to be built in such a way that the first file processed:
1. Does not have a whiteout prefix (.wh)
2. Is not a Hard link
3. Does not have root as its parent folder (my guess is in most orderings this starts with root which is why we hadn't encountered this before). 
In the particular case of the image for which we found the issue the first file seen looked something like: /folder1/folder2/somefile which meets all the conditions above causing the failure.  As a …
=> Fix tar2vhd on specific unordered tars

internal/hcs/callback.go, internal/hcs/process.go, internal/hcs/system.go
notifcationWatcherContext -> notificationWatcherContext
=> Fix spelling mistake with `notificationWatcherContext`

hcn/hcnloadbalancer.go, hcn/hcnpolicy.go
This is to allow setting the ipv6 flag when creating outbound nat policy.
=> Add NatFlags flag to OutboundNatPolicySetting

hcn/hcnpolicy.go, hcn/hcnutils_test.go
Proxy exceptions added to hcsshim
=> Adding proxy exceptions to L4WFP Proxy Policy

hcn/hcnglobals.go
While working on https://github.com/kubernetes/kubernetes/pull/101047 I found that WS 2004 is not being shown as support.
[Docs state](https://kubernetes.io/docs/setup/production-environment/windows/intro-windows-in-kubernetes/#ipv4-ipv6-dual-stack): 2004 (kernel version 10.0.19041.610) 
```
cmd /c ver
Microsoft Windows [Version 10.0.19041.867]
```
I added custom logging to kubeproxy which showed I was on version `11` of HNS on `10.0.19041`
```
I0414 22:35:15.143135    3372 proxier.go:202] hns version%!(EXTRA hcn.Version={11 10})                    
```                                       
I am not sure how HNS versions map to WS versions.  Maybe there are minor versions of 2004 that don't support it?
=> WS 2004 supports dual stack

CODEOWNERS
The CODEOWNERS logic for the hcn package shouldn't work as the required reviewer
doesn't have write access which is required.
From https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners:
"The people you choose as code owners must have write permissions for the repository. When the code owner
is a team, that team must have write permissions, even if all the individual members of the team already have
write permissions directly, through organization membership, or through another team membership."
=> Take off hcn package CODEOWNERS line

internal/uvm/virtual_device.go, internal/vm/builder.go, internal/vm/hcs/boot.go, internal/vm/hcs/builder.go, internal/vm/hcs/hcs.go, internal/vm/hcs/memory.go, internal/vm/hcs/network.go, internal/vm/hcs/pci.go, internal/vm/hcs/plan9.go, internal/vm/hcs/processor.go, internal/vm/hcs/scsi.go, internal/vm/hcs/serial.go, internal/vm/hcs/stats.go, internal/vm/hcs/storage.go, internal/vm/hcs/supported.go, internal/vm/hcs/vmsocket.go, internal/vm/hcs/vpmem.go, internal/vm/hcs/vsmb.go, internal/vm/hcs/windows.go, internal/vm/vm.go
Add vm package and uvm interface to abstract away the operations that we call directly into
hcs for. This will be useful for having these operations be performed by a different virtstack
so long as it supports what is needed for containers.
=> Add abstractions for direct HCS interactions

hcn/hcn.go, hcn/hcnendpoint_test.go, hcn/hcnglobals.go, hcn/hcnpolicy.go, hcn/hcnsupport.go, hcn/hcnsupport_test.go, hcn/hcnutils_test.go, hcn/hnsv1_test.go
Signed-off-by: Vikas Bhardwaj <vikasb@microsoft.com>
=> Add support for tier acl policy

internal/hcs/process.go, internal/hcs/service.go, internal/hcs/system.go
e.g. hcsshim::System::Modify -> hcs::System::Modify
This should make the log messages a bit clearer.
=> internal/hcs: hcsshim -> hcs in operation name strings

internal/cmd/cmd.go, internal/cmd/cmd_test.go, internal/cow/cow.go, internal/gcs/iochannel.go, internal/gcs/process.go, internal/hcs/process.go, internal/jobcontainers/process.go
The shim is expected to close its end of the IO pipes from the gcs when
it is done using them. This is done to ensure that no data is left
buffered in the pipes on the gcs's end. Previously, this was
accomplished via the ioChannel closing its underlying connection if Read
returned EOF.
However, this is not sufficiently robust, as it will not work in cases
where the shim's IO relay breaks on the write end (e.g. if CRI has gone
away).
To resolve this, we now expose individual methods on cow.Process to
close each IO pipe (in/out/err), and call those from the Cmd
implementation once the IO relay completes.
This should be a good first-pass fix here, until we can apply some more
focused cleanup to the IO relay code in the future.
Some minor renaming/cleanup as well.
Signed-off-by: Kevin Parsons …
=> internal/cmd: Close individual IO pipes when the relay finishes

test/cri-containerd/clone_test.go
Late clone needs some registry settings when running on builds older than 20H2.  We do not
add these registry settings on such builds by default so the late clone tests might fail
on machines with builds older than 20H2. Skip running these tests on such machines.
=> Run late clone tests on 20H2+ builds only.

internal/hcsoci/hcsdoc_wcow.go, internal/hcsoci/resources_wcow.go
When mounting a VHD at host path `C:\data\test.vhdx` into the container over SCSI and also sharing the same VHD inside the container over VSMB the current code just shares the VHD inside the container for both mounts instead of actually SCSI mounting the VHD for one of the mounts. This change fixes that.
=> Fix bug with VSMB & SCSI mounts on the same host path

internal/hcsoci/hcsdoc_wcow.go, internal/hcsoci/resources_wcow.go
This commit adds support in hcsshim to mount a virtual disk backed by storage spaces as a
data disk into a container. In container config the `host_path` in the mount entry
should use the format `space://{storage_space_pool_guid}{storage_space_disk_guid}` to
specify a storage space virtual disk.
=> Support for storage space data disks

internal/oci/uvm.go, internal/uvm/create.go, internal/uvm/create_wcow.go, internal/uvm/types.go, internal/uvm/vsmb.go, test/cri-containerd/runpodsandbox_test.go
This PR adds the option for a user to set `NoDirectMap` as a default option for VSMB mounts without needing to set the UVM to be fully physically backed. 
=> Add option to set no direct map by default on wcow VSMB devices

cmd/containerd-shim-runhcs-v1/delete.go
Panic.log file can get very large if there are other log statements writing to
stderr. Avoid reading the entire file
=> Read max 1MB data from panic.log

test/cri-containerd/container_downlevel_test.go, test/cri-containerd/container_network_test.go, test/cri-containerd/container_test.go, test/cri-containerd/container_virtual_device_test.go, test/cri-containerd/createcontainer_test.go, test/cri-containerd/execcontainer_test.go, test/cri-containerd/logging_binary_test.go, test/cri-containerd/main.go, test/cri-containerd/pullimage_test.go, test/cri-containerd/removepodsandbox_test.go, test/cri-containerd/runpodsandbox_test.go, test/cri-containerd/sandbox.go, test/cri-containerd/scale_cpu_limits_to_sandbox_test.go, test/cri-containerd/stats_test.go, test/cri-containerd/stopcontainer_test.go
Add some new flags to the integration test suite that enables choosing what virtstack
to use for hypervisor isolated containers. This makes it so we can re-use our existing tests
and just pass in new flags to run them with a new stack.
To have this play nice with the test suite I changed `getRunPodSandboxRequest` to take in whatever
annotations we'd want to set on the pod config directly instead of us having to set them on the
returned object itself.
=> Add new flags to integration tests to specify virtstack

test/cri-containerd/runpodsandbox_test.go
In this PR (https://github.com/microsoft/hcsshim/pull/1019) I changed how we pass annotations to
the cri-containerd suite, but this PR (https://github.com/microsoft/hcsshim/pull/1030) got in before
which added a new test. This caused the CI to fail on checkin of the first PR. Always rebase kids
=> Change VSMBNoDirectMap_WCOW_Hypervisor test to fix CI break

test/cri-containerd/runpodsandbox_test.go
=> fix break in cpu groups test on machines with build < 20124

test/cri-containerd/container_test.go
First test validates that after launching a pod and one container there is only a single
scsi disk available in the guest.
Second test launches two workload containers both sharing the pod sandbox containers scratch space. A
file is written in the first workload container and the available size left on the rootfs is then checked in
both workload containers. The success case is if both containers show the same available size left.
=> Add tests for LCOW shared scratch space work

cmd/containerd-shim-runhcs-v1/delete.go
This changes the behavior when the shim is invoked with the "delete"
command line argument.
Previously, the delete path did two things it should not:
- Attempted to locate the sandbox container for the pod and delete it as
well. This meant if "shim delete" was invoked for a workload
container, it could bring down the whole pod. The only reason we did
not see this in the past is that prior to containerd 1.5 "shim delete"
was not called for successful container stop operations.
- Deleted the bundle directory. We shouldn't do this in the shim, as
containerd does it itself.
For reference on what the Linux shim does, see here: https://github.com/containerd/containerd/blob/master/runtime/v2/runc/v2/service.go#L291
=> shim: Clean up delete invocation behavior

internal/oci/uvm.go, internal/tools/uvmboot/main.go, internal/uvm/create.go, internal/uvm/create_lcow.go, internal/uvm/create_wcow.go, test/cri-containerd/runpodsandbox_test.go, test/vendor/github.com/Microsoft/hcsshim/internal/cpugroup/cpugroup.go, test/vendor/github.com/Microsoft/hcsshim/internal/hcs/schema2/cpu_group_config.go, test/vendor/github.com/Microsoft/hcsshim/internal/oci/uvm.go, test/vendor/github.com/Microsoft/hcsshim/internal/uvm/create.go, test/vendor/github.com/Microsoft/hcsshim/internal/uvm/create_lcow.go, test/vendor/github.com/Microsoft/hcsshim/internal/uvm/create_wcow.go
HCS maintains an internal guest connection to the GCS normally if you request it.
However, there are certain features that require us to maintain an external connection
(external in this sense meaning not in HCS) instead like late cloning.
We had swapped to always managing the connection to the GCS ourselves some time ago and
afaik there's been no fallout from it, so I propose let's get rid of the internal branches
altogether. This greatly simplifies the work for going through a different virtstack for
hypervisor isolated containers as well.
Ran go mod vendor in /test to bring in the changes as well.
=> Remove internal GCS connection functionality

cmd/containerd-shim-runhcs-v1/delete.go
Backport of 450cdb150a74aa594d7fe63bb0b3a2a37f5dd782 for `release/0.8`.
This changes the behavior when the shim is invoked with the "delete"
command line argument.
Previously, the delete path did two things it should not:
- Attempted to locate the sandbox container for the pod and delete it as
well. This meant if "shim delete" was invoked for a workload
container, it could bring down the whole pod. The only reason we did
not see this in the past is that prior to containerd 1.5 "shim delete"
was not called for successful container stop operations.
- Deleted the bundle directory. We shouldn't do this in the shim, as
containerd does it itself.
For reference on what the Linux shim does, see here: https://github.com/containerd/containerd/blob/master/runtime/v2/runc/v2/service.go#L291 …
=> [release/0.8] shim: Clean up delete invocation behavior

internal/cmd/diag.go
This PR addresses broken tests for process isolated container update by making use of the requested stdio pipes specified in the call to `ExecInShimHost`
=> use requested stdio in call  to exec in shim host

internal/hns/hnsendpoint.go
It was missing from our go definition. For instance if the hcn definitions were used to set the
dns information/make the endpoint and then we requery for the endpoint with the v1 hns schema/calls,
this information won't be present.
This controls the `Connection-specific DNS Suffix` you'd see on ipconfig for example.
=> Add DNSDomain to hns endpoint object

ext4/dmverity/dmverity.go, internal/guestrequest/types.go, internal/uvm/vpmem.go
this builds on top of the dm-verity footer feature that
has been previously added. changes to opengcs have already been
made where the verity info (root hash, merkle tree etc) is expected
to be appended to the ext4 data and this change enables passing
in the actual verity information.
If dm-verity footer read fails, fallback to the original behavior as
if the footer wasn't present at all.
NOTE: Integration tests will be added in a separate PR, since there's a dependency on CRI/containerd
=> Read vhd verity footer

hcn/hcnsupport.go
Kubeproxy logs are filled with redudnant version check spam from an unexported call that's invoked
as part of checking if a feature is supported. The logs don't detail what feature(s) are even being checked
so it just seems like spam. With the way things are implemented all of the hcn features are checked for support in
any of the `hcn.XSupported()` calls not just the one being checked, so these logs come up quite a bit if there's
many features that aren't supported on the machine.
Add two new logs in a sync.Once that logs the HNS version and supported features. This should be enough
to investigate version issues.
Should remedy #1043
=> Get rid of redundant logs in HCN version range checks

cmd/containerd-shim-runhcs-v1/pod.go, cmd/containerd-shim-runhcs-v1/task_hcs.go, cmd/containerd-shim-runhcs-v1/task_wcow_podsandbox.go, internal/hcsoci/resources_lcow.go, internal/hcsoci/resources_wcow.go, internal/jobcontainers/jobcontainer.go, internal/jobcontainers/storage.go, internal/layers/layers.go, internal/oci/util.go
* Add the necessary plumbing in containerd shim to be able to create a job container
if asked for via the annotation.
=> Add containerd-shim plumbing for job containers

errors.go, internal/hcs/errors.go
Previously, certain error check functions like IsAlreadyStopped returned
true if the error was ERROR_PROC_NOT_FOUND. Based on the comment in the
file, this was intended to be used to indicate a case where the process
could not be found. However, it seems this may have been added
erroneously. ERROR_PROC_NOT_FOUND is actually typically used to mean
that a _procedure_ lookup failed, and has nothing to do with processes.
The original change[1] to check against ERROR_PROC_NOT_FOUND was made
five years ago, and did not contain much information on why this error
would be returned. We are removing this now based on several factors:
- We are not aware of any condition where HCS would intentionally return
ERROR_PROC_NOT_FOUND to indicate a condition "process does not exist".
- There is an issue …
=> Remove ERROR_PROC_NOT_FOUND from error checks

internal/oci/annotations.go, internal/oci/uvm.go, internal/oci/uvm_test.go, test/cri-containerd/clone_test.go, test/cri-containerd/container_layers_packing_test.go, test/cri-containerd/container_test.go, test/cri-containerd/container_update_test.go, test/cri-containerd/container_virtual_device_test.go, test/cri-containerd/createcontainer_test.go, test/cri-containerd/jobcontainer_test.go, test/cri-containerd/pod_update_test.go, test/cri-containerd/runpodsandbox_test.go, test/cri-containerd/scale_cpu_limits_to_sandbox_test.go, test/cri-containerd/stats_test.go, test/vendor/github.com/Microsoft/hcsshim/internal/oci/annotations.go, test/vendor/github.com/Microsoft/hcsshim/internal/oci/uvm.go
The goal of this PR is to reduce the chances of outdated/wrong tests if an annotation is changed or removed 
=> export annotations for use in test suite

errors.go, internal/hcs/errors.go
Backport to `release/0.8` of #1064.
Previously, certain error check functions like IsAlreadyStopped returned
true if the error was ERROR_PROC_NOT_FOUND. Based on the comment in the
file, this was intended to be used to indicate a case where the process
could not be found. However, it seems this may have been added
erroneously. ERROR_PROC_NOT_FOUND is actually typically used to mean
that a _procedure_ lookup failed, and has nothing to do with processes.
The original change[1] to check against ERROR_PROC_NOT_FOUND was made
five years ago, and did not contain much information on why this error
would be returned. We are removing this now based on several factors:
- We are not aware of any condition where HCS would intentionally return
ERROR_PROC_NOT_FOUND to indicate a condition "process does …
=> [release/0.8] Remove ERROR_PROC_NOT_FOUND from error checks

errors.go, internal/hcs/errors.go
Same as https://github.com/microsoft/hcsshim/pull/1065; backport of https://github.com/microsoft/hcsshim/pull/1064 for the "moby" branch, which is currently used for the Docker 20.10 releases.
Relates to https://github.com/moby/moby/pull/42611
Previously, certain error check functions like IsAlreadyStopped returned
true if the error was ERROR_PROC_NOT_FOUND. Based on the comment in the
file, this was intended to be used to indicate a case where the process
could not be found. However, it seems this may have been added
erroneously. ERROR_PROC_NOT_FOUND is actually typically used to mean
that a _procedure_ lookup failed, and has nothing to do with processes.
The original change[1] to check against ERROR_PROC_NOT_FOUND was made
five years ago, and did not contain much information on why this …
=> [moby backport] Remove ERROR_PROC_NOT_FOUND from error checks

go.mod, go.sum, vendor/github.com/containerd/containerd/version/version.go, vendor/modules.txt
Upgrade containerd to 1.5.2
Signed-off-by: Manuel Alejandro de Brito Fontes aledbf@gmail.com
=> Bump containerd to 1.5.2

test/cri-containerd/scale_cpu_limits_to_sandbox_test.go
Without this tag, gopls under VSCode notes that this file calls undefined functions when no build tags are defined (the default).
=> Add missing 'functional' tag to test source

internal/wclayer/nametoguid.go, test/vendor/github.com/Microsoft/hcsshim/internal/wclayer/nametoguid.go
"name" is also used for the span title, so this attribute is lost, at least in the textual output.
I noticed the missing log attribute while trying to diagnose possible causes for "file in use" issues on https://github.com/containerd/containerd/pull/4419.
=> Fix lost span attribute for NameToGuid

internal/jobcontainers/jobcontainer.go, internal/jobcontainers/mounts.go, internal/jobcontainers/mounts_test.go, test/cri-containerd/jobcontainer_test.go
This adds basic directory mount support for job containers. As any path on the host
is already accessible from the container, the concept of volume mounts is a bit funny
for job containers. However, it still makes sense to treat the volume mount point where
the container image is mounted as where most things should be found regarding the container.
The manner in which this is done is by appending the container mount path for the volume to
where the rootfs volume is mounted on the host and then symlinking it.
So:
Container rootfs volume path = "C:\C\123456789abcdefgh\"
Example #1
--------------
{
"host_path": "C:\mydir"
"container_path": "\dir\in\container"
}
"C:\mydir" would be symlinked to "C:\C\123456789abcdefgh\dir\in\container"
Example #2
---------------
Drive letters will be stripped …
=> Add volume mount support for job containers

test/cri-containerd/container_update_test.go, test/cri-containerd/main.go
Upstream containerd/cri doesn't have support for updating container resources,
so running these tests currently fails.
=> Gate CRI update container tests behind feature flag

hcn/hcnpolicy.go, internal/hns/hnspolicy.go
Signed-off-by: elweb9858 <elweb@microsoft.com>
Several fields in the NatPolicy and AclPolicy v1 schema structs do not reflect the omitEmpty json field. This can be problematic in cases of integer fields because if the user does not specify a value for this field, it will be assigned a 0 during marshalling. In cases like protocol, a value of 0 is not something HNS recognizes so policy application will fail. This PR reflects all the omitEmpty fields properly in the hcsshim v1 policy schema structs (all v2 structs are currently up to date).
=> Updating HNS v1 policy schemas with correct omitEmpty fields

internal/jobcontainers/jobcontainer.go, internal/jobcontainers/path.go, internal/jobcontainers/path_test.go
Relative paths supplying a dot don't make it through our commandline
parsing for job containers, this change fixes that.
In addition to this, this change adds logic to actually honor the working
directory specified for the container.
=> Fix relative paths (with dot) not working for job containers

Makefile
currently opengcs unit tests are not verbose enough and it's hard
to tell which tests are actually run. Increase verbosisty by
adding -v flag
=> tests: increase opengcs tests verbosity

internal/guest/runtime/hcsv2/spec.go, internal/guest/runtime/hcsv2/workload_container.go, test/cri-containerd/container_test.go
This PR adds annotation `"io.microsoft.container.storage.shm.size-kb"` to
set container's `/dev/shm` tmpfs size, which overrides any existing `/dev/shm`
mount in the spec
=> make container's shared memory configurable via annotation

internal/hcs/schema2/attachment.go, internal/hcsoci/hcsdoc_wcow.go, internal/hcsoci/resources_wcow.go, internal/uvm/create_wcow.go, internal/uvm/scsi.go
This commit adds support in hcsshim to mount an extensible virtual disk data disk into a
container. In container config the host_path in the mount entry should
use the format `evd://<evdType>/<evdPath>` to specify an extensible virtual disk.
=> Support for extensible virtual disks as data disks

internal/guest/runtime/hcsv2/uvm.go, internal/guest/storage/crypt/crypt.go, internal/guest/storage/crypt/crypt_test.go, internal/guest/storage/crypt/utilities.go, internal/guest/storage/scsi/scsi.go, internal/guest/storage/scsi/scsi_test.go
This protects the files generated by the guest from the host OS, as they
are encrypted by a key that the host doesn't know.
This commit adds a new argument to the scsi.Mount() function, `encrypted`,
that makes the SCSI drive be mounted using dm-crypt. It also uses
dm-integrity for integrity checking. This makes the boot process a couple
of seconds slower.
Also, it adds scsi.Unmount(), which also has the `encrypted` argument,
and it does the necessary cleanup for a drive that has been mounted as
an encrypted drive.
All the pre-existing SCSI tests have been fixed to work with the new
scsi.Mount() function prototype. New tests have been added for the new
code.
This is all disabled for now, it has to be enabled in a future patch.
Important note: This depends on cryptsetup and mkfs.ext4. Also, …
=> Add support to encrypt SCSI scratch disks with dm-crypt

internal/layers/layers.go
This change adds a simple retry loop to handle some behavior on RS5. Loopback VHDs
used to be mounted in a different manor on RS5 (ws2019) which led to some
very odd cases where things would succeed when they shouldn't have, or we'd simply
timeout if an operation took too long. Many parallel invocations of this code path
and stressing the machine seem to bring out the issues, but all of the possible failure
paths that bring about the errors we have observed aren't known.
On 19h1+ this retry loop shouldn't be needed, but the logic is to leave the loop if everything succeeded so this is harmless
and shouldn't need a version check.
=> Add retry around wclayer operations for process isolated containers

internal/guest/runtime/hcsv2/uvm.go
I have a habit of capitalizing the first letter of error messages. We missed this one as part of the review for my PR that added the security policy functionality.
=> Fix incorrect casing in error message

internal/guest/storage/devicemapper/devicemapper.go, internal/guest/storage/devicemapper/targets.go, internal/guest/storage/pmem/pmem.go
Move device mapper code from pmem to devicemapper package.
=> chore: Cleanup guest pmem package

internal/guest/runtime/hcsv2/uvm.go, internal/uvm/security_policy.go
Due to an error ignored when calling to json.Unmarshal the call
to SetSecurityPolicy with an empty or invalid string policy results
in a policy with no Containers and AllowAll set to false. No
container can be run as a result.
Fix the behavior by not sending modification request for SetSecurityPolicy
when policy string is empty (which is the default) and checking the
error result from json.Unmarshal call
=> Skip setting security policy when it's empty

pkg/securitypolicy/securitypolicyenforcer.go
I tend to use snake case rather than camel case. These snuck through previous reviews.
=> Fix variable naming

test/cri-containerd/container_layers_packing_test.go
Previously ubuntu:18.04 container had 3 image layers, which is not
true anymore. Pin image digest to make sure that this issue doesn't
resurface.
=> tests: fix VPMem layer packing tests

internal/oci/annotations.go, internal/oci/uvm.go, internal/uvm/create_lcow.go, test/cri-containerd/runpodsandbox_test.go, test/vendor/github.com/Microsoft/hcsshim/internal/oci/annotations.go, test/vendor/github.com/Microsoft/hcsshim/internal/oci/uvm.go, test/vendor/github.com/Microsoft/hcsshim/internal/uvm/create_lcow.go, test/vendor/github.com/Microsoft/hcsshim/internal/uvm/security_policy.go
Description:
=======
A new annotation "io.microsoft.virtualmachine.lcow.kernelbootoptions" support has been added, which lets one pass kernel boot options.
This will be used for an upcoming change to provide support for hugepages.
A sample usage:
==========
"io.microsoft.virtualmachine.lcow.kernelbootoptions" : "hugepagesz=2M hugepages=1024"
Behavior:
=====
Invalid options are ignored.
Verification:
=======
Pod comes up successfully with ""io.microsoft.virtualmachine.lcow.kernelbootoptions" : "hugepagesz=2M hugepages=1024"" setting.
Signed-off-by: vivekagg@microsoft.com
=> Support for Kernel Boot Options - LCOW

hcn/hnsv1_test.go, hnsendpoint.go, internal/hns/hnsendpoint.go
The metrics endpoint with containerd running doesn't return stats (https://github.com/kubernetes/kubernetes/issues/104286) and the dockershim component calls metrics twice  (https://github.com/kubernetes/kubernetes/issues/104285)
This PR enables the gathering the stats to enable the two scenarios.
=> Add network stats to the enable getting stats directly 

internal/layers/layers.go
This change adds a small sleep before a re-attempt on layer operation
failures. These failures should only happen on RS5 and the probable cause is because
of a different way in which container loopback vhds were mounted on this OS version.
A theory of why things might go awry on RS5 is due to some events from pnp getting reported
too late/early. If the prognosis is correct, a small sleep might help to try and get
things back into a "good" state before a reattempt.
=> Add sleep before layer operation retries

hcn/hcn.go, hcn/hcnsupport.go
To avoid a breaking change on `GetSupportedFeatures` introduce a new
`GetCachedSupportedFeatures` method. This method does the feature check
and version parsing once and then assigns a global with the information.
This can be used to optimize for situations where many uses of the
hcn.IsXSupported methods are going to be used (kube-proxy for example).
Previously they would call `GetSupportedFeatures` and end up re-querying and 
revalidating the feature ranges every time.
=> Add GetCachedSupportedFeatures method to hcn package

internal/jobcontainers/process.go
This change does two things:
1. Checks if the stdio pipes are nil before closing them via the CloseStdout,
CloseStderr, CloseStdin methods. This just brings it inline with the other
`cow.Process` implementations that check for nilness.
2. Fix an oversight where windows.Close was being used instead of windows.FreeLibrary
after loading kernel32.dll
=> Check if stdio pipes are nil for job containers/fix windows.Close usage

internal/winapi/utils.go, internal/winapi/winapi_test.go
The existing UnicodeString constructor creates a unicode string object by taking the
length of a given GO string. This works fine for ASCII strings but fails when the input
string contains non ASCII characters. This change fixes it.
Description: 
In the earlier version of NewUnicodeString the length would be set to the number of bytes in the string than the number of runes in the string. If the input string of 3 runes had one non-ascii character (i.e a character that would take 2 bytes to encode in UTF=8) the value of length would be 4 and the UnicodeString.Length & UnicodeString.MaximumLength would be set to 8. However, the buffer returned by UTF16FromString would include only 3 uint16s which is 6 valid bytes. So the generated UnicodeString would end up with garbage bytes at the end. …
=> Bugfix for UnicodeString constructor

hcn/hcnglobals.go, internal/wclayer/activatelayer.go, internal/wclayer/createlayer.go, internal/wclayer/createscratchlayer.go, internal/wclayer/destroylayer.go, internal/wclayer/expandscratchsize.go, internal/wclayer/exportlayer.go, internal/wclayer/getlayermountpath.go, internal/wclayer/getsharedbaseimages.go, internal/wclayer/grantvmaccess.go, internal/wclayer/importlayer.go, internal/wclayer/layerexists.go, internal/wclayer/nametoguid.go, internal/wclayer/preparelayer.go, internal/wclayer/unpreparelayer.go
noticed this in https://github.com/moby/moby/issues/42743#issuecomment-907507159
HcsError.Error() already appends "failed" to the error message, which resulted in some uses to contain a duplicate "failed", for example:
re-exec error: exit status 1: output: hcsshim::ImportLayer - failed failed in Win32: The system cannot find the path specified. (0x3)
=> Fix duplicate "failed" in HCS errors

README.md
We recently added the DCO github app and it will get run on every PR. This change
adds a small blurb to our README to give more information on DCO for contributors.
=> Add extra info about DCO check to README

internal/guest/runtime/hcsv2/sandbox_container.go, internal/guest/runtime/hcsv2/standalone_container.go, internal/guest/runtime/hcsv2/uvm.go
This PR fixes up some logic when creating sandboxes and container where we might overwrite the error from a previous call. 
=> Fixup logic for sandbox and container cleanup on failure

internal/uvm/vpmem.go, internal/uvm/vpmem_mapped.go, test/vendor/github.com/Microsoft/hcsshim/internal/uvm/vpmem.go, test/vendor/github.com/Microsoft/hcsshim/internal/uvm/vpmem_mapped.go
Previously dm-verity was enabled only for dedicated VPMems. This
change adds dm-verity footer parsing logic to multi-mapped LCOW
layers
=> Enable dm-verity for multi-mapped LCOW layers

cmd/dmverity-vhd/main.go, ext4/dmverity/dmverity.go, internal/tools/securitypolicy/main.go
Add Max disk size constant to eliminate hard code size. 
The size is synced with [max disk size in containrd](https://github.com/containerd/containerd/blob/main/diff/lcow/lcow.go#L47). In the future, this need to be upstreamed in containerd.
=> add RecommendedVHDSizeGB constant

internal/guest/runtime/hcsv2/uvm.go, internal/guest/runtime/runc/runc.go, internal/guest/storage/scsi/scsi.go
Additionally cleanup dead code during scsi mount, bump scsi mount
timeout to 5 seconds.
=> Add more messages when guest relays and init process finish

internal/jobcontainers/jobcontainer.go, internal/jobcontainers/path.go, internal/jobcontainers/path_test.go
This change does a couple of things for the path resolution logic and tests. 
1. I was using `filepath.Clean` to remove any initial '.' paths in the command line. However it changes all forward slashes to backslashes, which hinders command lines like the following:
`"cmd /c ping 127.0.0.1"`
as the /c argument will be altered. Windows Server containers don't handle relative paths with a dot, so it doesn't seem necessary to support them for job containers either, so just get rid of the call entirely.
2. Remove empty spaces off the end of the cmdline if it's quoted. There was an empty space in this case as I was using strings.Join to join the arguments after the quoted element. This had no effects on actual usage/functionality, but to compare command lines for tests, this made things easier. …
=> Job container path touchups + rework tests

internal/guest/runtime/hcsv2/container.go, internal/guest/runtime/hcsv2/sandbox_container.go, internal/guest/runtime/hcsv2/uvm.go, internal/guest/runtime/hcsv2/workload_container.go, internal/hcsoci/resources_lcow.go, test/cri-containerd/container_test.go, test/vendor/github.com/Microsoft/hcsshim/internal/hcsoci/resources_lcow.go
This adds hugepages support for LCOW. 
A hugetlbfs drive can be mounted inside a LCOW. This is backed by a location in UVM. Currently, linux kernel shipped with containerd only supports hugepage size of 2M.
In order to specify a container path is a hugepage mount, hostpath needs to be specified as hugepages://2M. 
In order for container to use hugepage successfully, it is expected UVM will be created appropriate KernelOptions annotation.
_"io.microsoft.virtualmachine.lcow.kernelbootoptions" : "hugepagesz=2M hugepages=10"_
UVM also has to be created with sufficient memory to host desired number of hugepages.
Ex: 
_"io.microsoft.virtualmachine.computetopology.memory.sizeinmb": "2048",
"io.microsoft.virtualmachine.lcow.kernelbootoptions" : "hugepagesz=2M hugepages=10"_
In order to realize …
=> Hugepage support for LCOW

internal/guest/runtime/hcsv2/uvm.go, internal/guest/storage/test/policy/mountmonitoringsecuritypolicyenforcer.go, internal/tools/securitypolicy/README.md, internal/tools/securitypolicy/main.go, pkg/securitypolicy/securitypolicy.go, pkg/securitypolicy/securitypolicy_test.go, pkg/securitypolicy/securitypolicyenforcer.go, test/go.sum, test/vendor/github.com/Microsoft/hcsshim/pkg/securitypolicy/securitypolicy.go, test/vendor/github.com/Microsoft/hcsshim/pkg/securitypolicy/securitypolicyenforcer.go
Supports two different matching schemes:
- string
This is a direct string match. All characters must be equal.
- re2
The rule is an re2 regular expression that will be matched against the environment variable.
Environment variables are in the form "KEY=VALUE" as a single string.
The securitypolicy tool has been updated to automatically include any environment variables defined
in the image spec for an image to the allowed environment variables in the generated policy.
=> Add security policy enforcement of environment variables

README.md, test/go.sum, test/vendor/github.com/Microsoft/hcsshim/README.md
This change adds a quick blurb about the test directory situation for contributors.
As the test directory is a bit odd and our CI will fail if the condition isn't met, this seems like a good thing to call out.
=> Add note about test directory go mod vendor steps to README

go.sum, scripts/Verify-GoModules.ps1, test/go.sum, test/vendor/github.com/Microsoft/hcsshim/go.sum
This PR addresses an issue found in the CI pipeline in https://github.com/microsoft/hcsshim/pull/1146. In that instance, the CI initially failed indicating that the test vendor modules were not up to date, which also led to test failures in the CI.
This was because the `Verify-GoModules.ps1` script only validated that the code in the vendor directory of the package was unchanged. It did not, however, validate if the target `go.sum` file matched the expected one for the code. `go mod tidy` cleans up unnecessary references by removing their entries in the `go.sum` file, thereby changing its contents. This could cause the main modules and the test modules to become out of sync.
This PR addresses this issue by validating that all files in the target directory are as expected. This will …
=> Update script to verify go modules to match hashes of all files

internal/guest/runtime/hcsv2/uvm.go, internal/tools/securitypolicy/README.md, internal/tools/securitypolicy/main.go, pkg/securitypolicy/securitypolicy.go, pkg/securitypolicy/securitypolicy_test.go, pkg/securitypolicy/securitypolicyenforcer.go, test/vendor/github.com/Microsoft/hcsshim/pkg/securitypolicy/securitypolicy.go, test/vendor/github.com/Microsoft/hcsshim/pkg/securitypolicy/securitypolicyenforcer.go
The existing array based policy  doesn't work with managed HSMs query language, so, we have switched
it up to using maps instead of arrays. Map keys correspond to the array index that an entry would have.
This allows us to keep ordering.
=> Switch JSON policy schema from using arrays to maps

cmd/containerd-shim-runhcs-v1/task_hcs.go, cmd/containerd-shim-runhcs-v1/task_wcow_podsandbox.go, go.sum, internal/cmd/cmd.go, internal/cmd/diag.go, internal/devices/assigned_devices.go, internal/devices/pnp.go, test/vendor/github.com/Microsoft/hcsshim/go.sum, test/vendor/github.com/Microsoft/hcsshim/internal/cmd/cmd.go, test/vendor/github.com/Microsoft/hcsshim/internal/cmd/diag.go, test/vendor/github.com/Microsoft/hcsshim/internal/devices/assigned_devices.go, test/vendor/github.com/Microsoft/hcsshim/internal/devices/pnp.go
Something weird happened with this PR https://github.com/microsoft/hcsshim/pull/1149, so moving here. 
=> Add new internal cmd package request struct to remove shimdiag package import

.github/workflows/ci.yml
=> Add additional information to the error message when validating modules

internal/tools/securitypolicy/README.md, internal/tools/securitypolicy/main.go
Before this change, the securitypolicy tool could authorize with a registry
by providing a username and password as command-line options.
This approach worked fine as long as all images were being pulled from the
same registry. It doesn't work if you need to access multiple registries.
After this change, authorization is provided in the policy.toml on a per-image
basis. This allows for mixing and matching different registries together as
part of a pod.
=> Update securitypolicy tool to support multiple registries

internal/guest/prot/protocol.go, internal/guest/runtime/hcsv2/uvm.go, internal/guest/storage/overlay/overlay_test.go, internal/guest/storage/pmem/pmem.go, internal/guest/storage/pmem/pmem_test.go, internal/guest/storage/scsi/scsi.go, internal/guest/storage/scsi/scsi_test.go, internal/guest/storage/test/policy/mountmonitoringsecuritypolicyenforcer.go, internal/guestrequest/types.go, internal/uvm/scsi.go, pkg/securitypolicy/securitypolicy_test.go, pkg/securitypolicy/securitypolicyenforcer.go, test/vendor/github.com/Microsoft/hcsshim/internal/guestrequest/types.go, test/vendor/github.com/Microsoft/hcsshim/internal/uvm/scsi.go, test/vendor/github.com/Microsoft/hcsshim/pkg/securitypolicy/securitypolicyenforcer.go
Previously, we only had support for VPMem devices, however, under some scenarios, container
layer devices will be mounted as SCSI; for those scenarios, we will to enforce policy.
Currently, we only enforce policy for read-only devices in a guest as those are the only ones that
are container layers. The scratch space for containers is mounted as read-write and we do
not want enforce policy for them.
Actually dm-verity setup isn't included in this commit and will be added in a future change.
=> Add security policy enforcement for SCSI devices

internal/guest/prot/protocol.go, internal/guest/runtime/hcsv2/uvm.go, internal/guestrequest/types.go, internal/hcsoci/resources_lcow.go, internal/hcsoci/resources_wcow.go, internal/layers/layers.go, internal/lcow/scratch.go, internal/oci/annotations.go, internal/oci/uvm.go, internal/uvm/create_lcow.go, internal/uvm/create_wcow.go, internal/uvm/scsi.go, internal/uvm/types.go, test/functional/lcow_test.go, test/functional/uvm_scratch_test.go, test/functional/uvm_scsi_test.go, test/vendor/github.com/Microsoft/hcsshim/internal/guestrequest/types.go, test/vendor/github.com/Microsoft/hcsshim/internal/hcsoci/resources_lcow.go, test/vendor/github.com/Microsoft/hcsshim/internal/hcsoci/resources_wcow.go, test/vendor/github.com/Microsoft/hcsshim/internal/layers/layers.go, test/vendor/github.com/Microsoft/hcsshim/internal/lcow/scratch.go, test/vendor/github.com/Microsoft/hcsshim/internal/oci/annotations.go, test/vendor/github.com/Microsoft/hcsshim/internal/oci/uvm.go, test/vendor/github.com/Microsoft/hcsshim/internal/uvm/create_lcow.go, test/vendor/github.com/Microsoft/hcsshim/internal/uvm/create_wcow.go, test/vendor/github.com/Microsoft/hcsshim/internal/uvm/scsi.go, test/vendor/github.com/Microsoft/hcsshim/internal/uvm/types.go
Add bool annotation "io.microsoft.virtualmachine.storage.scratch.encrypted"
that enables scratch space encryption.
Update guest request protocols to allow encryption for SCSI
devices.
=> Enable scratch space encryption via annotation

internal/guest/runtime/hcsv2/uvm.go, internal/guest/storage/pmem/pmem.go, internal/guest/storage/pmem/pmem_test.go, internal/guest/storage/scsi/scsi.go, internal/guest/storage/scsi/scsi_test.go, internal/guest/storage/test/policy/mountmonitoringsecuritypolicyenforcer.go, pkg/securitypolicy/securitypolicy_test.go, pkg/securitypolicy/securitypolicyenforcer.go, test/vendor/github.com/Microsoft/hcsshim/pkg/securitypolicy/securitypolicyenforcer.go
This is the first iteration of policy enforcement at unmount. There is an additional set
of functionality that will come as part of a larger change in the near future.
With this commit, we record that a device has been unmounted such that it isn't eligible to
be used in any overlay after unmounting.
In a future commit, I will be adding disallowing unmounting a device that is being used by a
running container.
=> Enforce security policy at unmount

internal/tools/securitypolicy/main.go, pkg/securitypolicy/securitypolicy.go, pkg/securitypolicy/securitypolicy_test.go, test/vendor/github.com/Microsoft/hcsshim/pkg/securitypolicy/securitypolicy.go
This was a small change that came up in the initial code review that we put
off "for a later date".
The valid strategy strings are now shared between the policy tool and gcs
so they can't end up with a mismatch.
=> Make policy environment variable rules consts

internal/uvm/security_policy.go, test/vendor/github.com/Microsoft/hcsshim/internal/uvm/security_policy.go
=> Remove unused variable

internal/tools/securitypolicy/README.md, internal/tools/securitypolicy/main.go
Maksim pointed out that when we added information beyond the image of an image
that the "image" entries in a TOML policy generation file weren't describing
images; the describe containers.
The addition of command line, environment variables, and what not to allow
is a description of a container that should be allowed to be created. The
only image specific bit is the name.
=> Update naming in internal security policy tool

pkg/securitypolicy/securitypolicyenforcer.go, test/vendor/github.com/Microsoft/hcsshim/pkg/securitypolicy/securitypolicyenforcer.go
Once upon a time, naming the variable that represented the type as
"policyState" made sense, it no longer does.
At Maksim's suggestion, this commit renames from "policyState" to "pe" which is short
for "policy enforcer".
=> Rename variable in SecurityPolicyEnforcer

internal/uvm/scsi.go, test/vendor/github.com/Microsoft/hcsshim/ext4/dmverity/dmverity.go, test/vendor/github.com/Microsoft/hcsshim/internal/uvm/scsi.go, test/vendor/github.com/Microsoft/hcsshim/internal/uvm/vpmem_mapped.go
AddSCSI wasn't using vmAccess parameter when making addSCSIRequest
=> fix vmAccess param usage in AddSCSI

pkg/securitypolicy/securitypolicy_test.go, pkg/securitypolicy/securitypolicyenforcer.go, test/vendor/github.com/Microsoft/hcsshim/pkg/securitypolicy/securitypolicyenforcer.go
This commit changes the data structure that we use to track possible
GCS container ids for a given security policy container from an array
to a set.
Set is the correct data structure to represent our constraint of "id
should only appear once".
Additionally, it makes this tricky bit of code slightly easier to understand.
=> Change internal data structure in SecurityPolicyEnforcer

internal/hcsoci/devices.go, internal/hcsoci/resources_wcow.go, internal/oci/annotations.go, test/cri-containerd/container_virtual_device_test.go, test/vendor/github.com/Microsoft/hcsshim/internal/hcsoci/devices.go, test/vendor/github.com/Microsoft/hcsshim/internal/hcsoci/resources_wcow.go, test/vendor/github.com/Microsoft/hcsshim/internal/oci/annotations.go
This annotation is not being used in prod currently, so updating it to be more accurate since adding drivers don't need to be tied to assigning a device from the spec.  
=> Update kernel driver annotation for accuracy

internal/jobcontainers/jobcontainer.go, test/cri-containerd/jobcontainer_test.go, test/cri-containerd/main.go, test/cri-containerd/test-images/jobcontainer_createvhd/Dockerfile, test/cri-containerd/test-images/jobcontainer_etw/Dockerfile, test/cri-containerd/test-images/jobcontainer_workdir/Dockerfile, test/cri-containerd/test-images/jobcontainer_workdir/main.go
Instead of taking the working directory as is, change to joining the working directory
requested with where the sandbox volume is located. It's expected that the default behavior
would be to treat all paths as relative to the volume as this would be equivalent to a
normal Windows Server Containers behavior.
For example:
A working directory of C:\ would become C:\C\12345678\
A working directory of C:\work\dir would become C:\C\12345678\work\dir
=> Rework how working directories function for job containers

internal/hcsoci/hcsdoc_wcow.go, internal/hcsoci/resources_wcow.go, test/cri-containerd/runpodsandbox_test.go, test/vendor/github.com/Microsoft/hcsshim/internal/hcsoci/hcsdoc_wcow.go, test/vendor/github.com/Microsoft/hcsshim/internal/hcsoci/resources_wcow.go
This change adds sandbox mount like support for WCOW. Sandboxmounts were our LCOW
solution similar to a k8s empty dir mount. We create a directory that will house
various other subdirectories that a user can specify by supplying a sandbox:// prefix
for the host path of a mount. In the usual case the hostpath of a mount is in the context of the
physical host (e.g. I want C:\path on my machine mapped to C:\containerpath in my container),
however for sandbox mounts the host path is treated as relative to this directory we have
made in the VM. The root directory for these sandbox mounts I defined as C:\SandboxMounts
Example:
```json
"mounts": [
{
"container_path": "C:\\test",
"host_path": "sandbox:///test"
}
]
```
The above will make a directory at C:\SandboxMounts\test in the Utility VM that …
=> Add WCOW sandbox mount support

internal/devices/assigned_devices.go, internal/hcsoci/devices.go, internal/hcsoci/resources_lcow.go, internal/uvm/create_lcow.go, internal/uvm/create_wcow.go, internal/uvm/types.go, internal/uvm/virtual_device.go, test/functional/uvm_virtualdevice_test.go, test/vendor/github.com/Microsoft/hcsshim/internal/devices/assigned_devices.go, test/vendor/github.com/Microsoft/hcsshim/internal/hcsoci/devices.go, test/vendor/github.com/Microsoft/hcsshim/internal/hcsoci/resources_lcow.go, test/vendor/github.com/Microsoft/hcsshim/internal/uvm/create_lcow.go, test/vendor/github.com/Microsoft/hcsshim/internal/uvm/create_wcow.go, test/vendor/github.com/Microsoft/hcsshim/internal/uvm/types.go, test/vendor/github.com/Microsoft/hcsshim/internal/uvm/virtual_device.go
This PR plumbs through support for passing in a virtual function index when assigning PCI devices. 
To specify a device with a virtual function index, add the index to the end of the device instance ID path like so to the CRI spec for the container:
> "devices": [
> 		{"host_path":"vpci-location-path://PCIP\\VEN_10DE&DEV_15F8&SUBSYS_118F10DE&REV_A1\\6&17F903&0&00400010\\2"}
> ],
Where `2` is the virtual function index. 
=> Add support for passing in a virtual function index to assign pci device

internal/jobcontainers/jobcontainer.go
This change sets the PATHEXT environment variable which Go checks during
exec.Cmd startup to do some path resolution. PATHEXT contains a semicolon
separated list of extensions to check against if a path ended without one
(e.g. /path/to/my/binary). This simply adds an empty string entry to the end
so that binaries with no extension can be launched correctly. Although this isn't
a common occurrence it's still a good thing to support. Windows Server containers
are able to handle this fine, and CreateProcess is perfectly happy launching
a valid executable without an extension.
This is mainly to support the agnhost image which is a common k8s testing image whose
entrypoint is a binary named agnhost with no extension.
https://github.com/kubernetes/kubernetes/blob/d64e91878517b1208a0bce7e2b794464 …
=> Set PATHEXT for job containers to handle binaries with no extension

cmd/gcs/main.go, internal/guest/runtime/hcsv2/container.go, internal/guest/runtime/hcsv2/sandbox_container.go, internal/guest/runtime/hcsv2/spec.go, internal/guest/runtime/hcsv2/workload_container.go, internal/hcsoci/hcsdoc_wcow.go, internal/oci/annotations.go, internal/oci/uvm.go, internal/uvm/create.go, internal/uvm/create_lcow.go, internal/uvm/create_wcow.go, internal/uvm/types.go, test/cri-containerd/main.go, test/cri-containerd/runpodsandbox_test.go, test/cri-containerd/test-images/stackoverflow-lcow/Dockerfile, test/cri-containerd/test-images/stackoverflow-lcow/main.c, test/vendor/github.com/Microsoft/hcsshim/internal/hcsoci/hcsdoc_wcow.go, test/vendor/github.com/Microsoft/hcsshim/internal/oci/annotations.go, test/vendor/github.com/Microsoft/hcsshim/internal/oci/uvm.go, test/vendor/github.com/Microsoft/hcsshim/internal/uvm/create.go, test/vendor/github.com/Microsoft/hcsshim/internal/uvm/create_lcow.go, test/vendor/github.com/Microsoft/hcsshim/internal/uvm/create_wcow.go, test/vendor/github.com/Microsoft/hcsshim/internal/uvm/types.go
This commit adds support for generating process dumps for hypervisor isolated containers. This includes
a new annotation to specify where process dumps should get placed on creation, which is global
to all containers.
This was verified the following way through crictl:
```json
Linux Pod spec
--------------
{
"metadata": {
"name": "sandbox-coredump",
"namespace": "default",
"attempt": 1
},
"annotations": {
"io.microsoft.container.processdumplocation": "/coredumps/core.%s.%e.%P.%t" 
}
}
```
```json
Linux container spec 
-----------------
{
"metadata": {
"name": "coredump-test"
},
"image": {
"image": "docker.io/library/ubuntu:latest"
},
"command": [
"sh",
"-c",
"while true; do echo 'Hello, World!'; sleep 1; done"
],
"mounts": [
{
"container_path": "/coredumps",
"host_path": "sandbox:///core" …
```
=> Add process dump functionality for WCOW/LCOW

internal/tools/securitypolicy/README.md, internal/tools/securitypolicy/main.go, pkg/securitypolicy/securitypolicy.go, pkg/securitypolicy/securitypolicy_test.go, pkg/securitypolicy/securitypolicyenforcer.go, test/vendor/github.com/Microsoft/hcsshim/pkg/securitypolicy/securitypolicy.go, test/vendor/github.com/Microsoft/hcsshim/pkg/securitypolicy/securitypolicyenforcer.go
These changes come by way of a suggestion from Maksim who noted that this
new format keeps the same information as the previous format, but organizes
it in a way that makes it easier to maintain the creation code and can
allow for the usage of a custom JSON marshaller to remove a source
of possible bugs in keeping the number of elements and the field that
is the length of said elements in sync,
=> Update json format for security policy

internal/guest/runtime/hcsv2/container.go, internal/guest/runtime/hcsv2/sandbox_container.go, internal/guest/runtime/hcsv2/spec.go, internal/guest/runtime/hcsv2/workload_container.go, test/cri-containerd/container_test.go, test/cri-containerd/main.go, test/cri-containerd/test-images/lcow_custom_user/Dockerfile
This change swaps to checking the OCI specs username field instead of
our custom annotation to match upstream. The real change is in how what
user an exec runs as is handled. In most places in Containerd an execed process
gets assigned the process spec of the container it’s getting launched in
(so it will inherit anything set on the container spec), but due to the nature
of LCOW there’s some OCI spec fields we set in the UVM instead as they’re not
able to be handled on the host (in a clean manner at least). One of these is
the user for the container.
On a Linux host, Containerd will check if the user exists in the filesystem for
the container before setting the user on the spec. On LCOW we just have vhd’s with
the contents of the layers when making the spec which makes this a bit …
=> Rework LCOW username setup/exec behavior

test/cri-containerd/container_downlevel_test.go, test/cri-containerd/container_layers_packing_test.go, test/cri-containerd/container_network_test.go, test/cri-containerd/container_test.go, test/cri-containerd/container_update_test.go, test/cri-containerd/container_virtual_device_test.go, test/cri-containerd/createcontainer_test.go, test/cri-containerd/execcontainer_test.go, test/cri-containerd/jobcontainer_test.go, test/cri-containerd/logging_binary_test.go, test/cri-containerd/main.go, test/cri-containerd/pod_update_test.go, test/cri-containerd/pullimage_test.go, test/cri-containerd/removepodsandbox_test.go, test/cri-containerd/runpodsandbox_test.go, test/cri-containerd/sandbox.go, test/cri-containerd/scale_cpu_limits_to_sandbox_test.go, test/cri-containerd/stats_test.go, test/cri-containerd/stopcontainer_test.go
Add SandboxConfigOpt func type, which enables pluggable configuration
of PodSandboxConfig.
=> Refactor pod config generation in tests

test/cri-containerd/container_test.go
Lack of rebase when merging
https://github.com/microsoft/hcsshim/pull/1180 resulted in some
test files being out of date and containing old helper function
name
=> tests: Fix tests that used old pullRequiredLCOWImages func name

internal/winapi/memory.go, internal/winapi/zsyscall_windows.go, test/vendor/github.com/Microsoft/hcsshim/internal/winapi/memory.go, test/vendor/github.com/Microsoft/hcsshim/internal/winapi/zsyscall_windows.go
This change removes some unused memory related definitions in internal/winapi.
They were originally going to be used for stats for host process contaienrs
but NtQuerySystemInformation was used instead.
=> Remove unused definitions in winapi

.github/workflows/ci.yml
Low-hanging fruit, but nice to have in place while things like #1160 are in-flight.
Outstanding thoughts:
=> Also run tests on Windows Server 2022 GitHub Runner

test/cri-containerd/container_test.go
=> tests: Fix ExecUser LCOW tests using old function signature

cmd/ncproxy/ncproxy.go, internal/uvm/computeagent.go, internal/uvm/computeagent_test.go, test/vendor/github.com/Microsoft/hcsshim/internal/uvm/computeagent.go
This PR adds unit tests for the compute agent portion of the ncproxy flow. 
=> Add unit tests for computeagent

osversion/windowsbuilds.go, test/vendor/github.com/Microsoft/hcsshim/osversion/windowsbuilds.go
This reverts commit 7b6e3dac2b3b0c2e06ab5d0bf2a0665fb80ae511 that added 
a windows server 2022 build number. The reason
for this is because the tag 21h2 actually refers to a couple different
Windows builds now unfortunately. It's the tag for the latest Windows 10
update, for Windows 11, and Windows Server 2022. We're looking into how
best to actually name these going forward if we're going to account for an
event like this again.
=> Revert V21H2 osversion definition

internal/guest/storage/pmem/pmem.go, internal/guest/storage/pmem/pmem_test.go, internal/guest/storage/scsi/scsi.go, internal/guest/storage/scsi/scsi_test.go, internal/uvm/scsi.go, test/vendor/github.com/Microsoft/hcsshim/internal/uvm/scsi.go
LCOW layers can be added both as VPMem and as SCSI devices.
Previous work focused on enabling integrity protection for read
only VPMem layers, this change enables it for read-only SCSI
devices as well.
Just like in a VPMem scenario, create dm-verity target when
verity information is presented to the guest during SCSI device
mounting step.
Additionally remove unnecessary unit test, since the guest logic
has changed.
=> Extend integrity protection of LCOW layers to SCSI devices

ext4/internal/compactext4/compact.go, ext4/tar2ext4/tar2ext4_test.go, test/vendor/github.com/Microsoft/hcsshim/ext4/internal/compactext4/compact.go
Addresses https://github.com/microsoft/hcsshim/issues/1120. This PR removes the previous block preventing hardlinks from being made to symlinks. Since symlinks are evaluated dynamically in the container based on the current root and tar2ext4 bounds hard link targets within the root of the inode structure, we don't need additional checking of any symlink targets in this scenario. 
Additionally adds test to verify behavior. 
=> Remove block preventing us from making hardlinks to symlinks

internal/guest/network/network.go, internal/guest/network/network_test.go, internal/guest/prot/protocol.go, internal/guest/runtime/hcsv2/network.go, internal/guest/runtime/hcsv2/network_test.go, internal/guest/storage/pci/pci.go, internal/guestrequest/types.go, test/vendor/github.com/Microsoft/hcsshim/internal/guestrequest/types.go
This PR adds support in the linux GCS for using network adapters that have been assigned into the guest via vpci. 
=> Add support for finding net adapters that were assigned with vpci

internal/guest/storage/devicemapper/devicemapper.go, internal/guest/storage/devicemapper/devicemapper_test.go, internal/guest/storage/pmem/pmem.go
Additionally ignore the error from device mapper if target removal
still fails. The corresponding layer path is already unmounted
at that point and this avoids having an inconsistent state.
=> Add retries when removing device mapper target

ext4/internal/compactext4/compact.go, ext4/tar2ext4/tar2ext4.go, ext4/tar2ext4/tar2ext4_test.go, test/vendor/github.com/Microsoft/hcsshim/ext4/internal/compactext4/compact.go, test/vendor/github.com/Microsoft/hcsshim/ext4/tar2ext4/tar2ext4.go
When extracting a container image layer tar, some files can show in an out of order
fashion (i.e the file shows up first before its parent directory shows up). We already
handle this by creating these parent directories if they don't already exist. However,
that handling didn't apply to whiteout files. This commit fixes that.
=> Handling of out-of-order whiteout files during tar expansion

internal/guest/runtime/hcsv2/workload_container.go
An issue was reported where when a user went to write files as a non-privileged user in a sandboxMount mounted with r/w in a container, they'd get a permission denied error. This was because the underlying directories in the UVM were created with 0755 permissions so only a privileged user in the container could write to a r/w sandboxMount mounted in. This PR changes that behavior by creating the underlying directories with 0777 permissions. 
=> Fix permissions issues with sandbox mounts

README.md, test/vendor/github.com/Microsoft/hcsshim/README.md
Our README stated that you'd need go 1.9 or newer to build. Our go.mod
currently lists 1.13 however.
=> Update readme to list accurate go version

computestorage/format.go, test/vendor/github.com/Microsoft/hcsshim/computestorage/format.go
On RS5 the HcsFormatWritableLayerVhd call expects to receive a disk handle.
On 19h1+ you can pass a vhd handle and internally they will do the same
work we're doing in this change to grab a disk handle to perform the format.
=> Pass disk handle for computestorage.FormatWritableLayerVhd on RS5

internal/jobcontainers/jobcontainer.go, test/cri-containerd/jobcontainer_test.go, test/cri-containerd/main.go, test/cri-containerd/test-images/jobcontainer_cmdline/dockerfile, test/cri-containerd/test-images/jobcontainer_cmdline/main.go
We already escape the arguments passed to us by Containerd to form a
Windows style commandline, however the commandline was being split back
into arguments and then passed to exec.Cmd from the go stdlib. exec.Cmd
internally also does escaping, which ended up applying some extra quotes
in some cases where the commandline had double/single quotes present. This change
just passes the commandline as is to the Cmdline field on the Windows
syscall.SysProcAttr. Go takes this field as is and doesn't do any further
processing on it which is the behavior we desire.
(cherry picked from commit 7cb95b6)
=> [release/0.9] Fix commandline double quoting for job containers

hcn/hcnpolicy.go, test/vendor/github.com/Microsoft/hcsshim/hcn/hcnpolicy.go
The "Type" fieldname was interfering with a internal "Type" field. Changing it to "PolicyType"
Signed-off-by: netal <netalgupta17@gmail.com>
=> Update the Type field name to PolicyType for SetPolicy
