internal/guest/runtime/hcsv2/uvm.go

Attestation sidecar containers need to have access to the security policy so they can extract the init-time claims of the utility VM as presented in the security policy.

security policy appended to container's environment variables 

---

osversion/windowsbuilds.go
test/vendor/github.com/Microsoft/hcsshim/osversion/windowsbuilds.go

This change adds three new definitions to the osversion package. All
three definitions are all of the 21H2 builds across Windows 10, Windows Server
and Windows 11, which all have different build numbers.
The approach taken was to prefix the definitions with Win10, WinServer and
Win11 respectively.

Add 21H2 definitions to osversion package

---

cmd/dmverity-vhd/main.go
ext4/dmverity/dmverity.go
ext4/tar2ext4/tar2ext4.go
internal/tools/securitypolicy/main.go
test/vendor/github.com/Microsoft/hcsshim/ext4/dmverity/dmverity.go
test/vendor/github.com/Microsoft/hcsshim/ext4/tar2ext4/tar2ext4.go

MerkleTree implementation requires the entire content of ext4 file
system to be read into a byte array when computing cryptographic digest.
This PR reworks the existing implementation to work with io.Reader
interface instead.
Additionally update the existing usages of MerkleTree with the new
MerkleTreeWithReader implementation.

Rework merkle tree implementation to use io.Reader instead of byte array

---

cmd/gcs/main.go
internal/guest/commonutils/utilities.go
internal/oci/uvm.go
internal/uvm/create_lcow.go
pkg/annotations/annotations.go
test/cri-containerd/runpodsandbox_test.go
test/vendor/github.com/Microsoft/hcsshim/internal/oci/uvm.go
test/vendor/github.com/Microsoft/hcsshim/internal/uvm/create_lcow.go
test/vendor/github.com/Microsoft/hcsshim/pkg/annotations/annotations.go

Currently LCOW UVM doesn't run any time synchronization service which causes a small amount of time lag after running the UVM for a long time (~10 days).
This change updates OpenGCS to start `chronyd` daemon as soon as gcs is started. It also adds a new annotation which can be used to disable this service inside the UVM.

Time synchronization inside LCOW UVM

---

ext4/tar2ext4/tar2ext4.go
test/vendor/github.com/Microsoft/hcsshim/ext4/tar2ext4/tar2ext4.go

Previously the function would read bytes from a given file
and convert them into internal ext4 super block object,
without checking that the read bytes are actually ext4
super block.
Fix the behavior by checking ext4 super block magic.

Fix ReadExt4SuperBlock function

---

test/cri-containerd/main_test.go

This change adds a new case to the getWindowsServerCoreImage and
getWindowsNanoserverImage functions to return ws2022 on a ws2022 or higher
build. The higher case is because of some recent efforts to improve down-level
compatability for Windows container images. For reference, the ltsc2022 image
works on a win11 host without hypervisor isolation.

Add ws2022 image/build to cri-containerd tests

---

cmd/ncproxy/computeagent_cache.go
cmd/ncproxy/hcn.go
cmd/ncproxy/ncproxy.go
cmd/ncproxy/server_test.go
internal/computeagent/computeagent.pb.go
internal/computeagent/computeagent.proto
internal/computeagent/mock/computeagent_mock.pb.go
internal/tools/networkagent/main.go
internal/uvm/computeagent.go
internal/uvm/computeagent_test.go
internal/uvm/virtual_device.go
pkg/ncproxy/ncproxygrpc/v1/networkconfigproxy.pb.go
pkg/ncproxy/ncproxygrpc/v1/networkconfigproxy.proto
test/vendor/github.com/Microsoft/hcsshim/internal/computeagent/computeagent.pb.go
test/vendor/github.com/Microsoft/hcsshim/internal/computeagent/computeagent.proto
test/vendor/github.com/Microsoft/hcsshim/internal/uvm/computeagent.go
test/vendor/github.com/Microsoft/hcsshim/internal/uvm/virtual_device.go

The primary change in this PR is the update of the ncproxy API with additional messages for a new "ncproxy network" and "ncproxy endpoint". The PR refactors and updates the existing code flow for hcn networks and leaves the implementation of the ncproxy network and ncproxy endpoint for later PRs. 

Update ncproxy API and adjust hcn support

---

cmd/dmverity-vhd/main.go
ext4/dmverity/dmverity.go
ext4/tar2ext4/tar2ext4.go
test/vendor/github.com/Microsoft/hcsshim/ext4/dmverity/dmverity.go
test/vendor/github.com/Microsoft/hcsshim/ext4/tar2ext4/tar2ext4.go

Split hash-device computation and writing into a separate function.
This allows to store hash device in a separate file, which (e.g.) can
be converted to VHDs and exposed inside VMs as separate block devices.

Add function to write hash device

---

internal/conpty/conpty.go
internal/winapi/console.go
internal/winapi/process.go
internal/winapi/winapi.go
internal/winapi/zsyscall_windows.go
test/vendor/github.com/Microsoft/hcsshim/internal/winapi/console.go
test/vendor/github.com/Microsoft/hcsshim/internal/winapi/process.go
test/vendor/github.com/Microsoft/hcsshim/internal/winapi/winapi.go
test/vendor/github.com/Microsoft/hcsshim/internal/winapi/zsyscall_windows.go

This change adds a conpty package (and necessary bindings) that houses go friendly wrappers around
the Pseudo Console API in Windows. This will be used to support tty scenarios for Host Process containers.
There's not many tests I can add here as you need to hook this up to a running
process, where that work is coming soon. I've included a video of this working below using the 
new process execution package I've been working on. 
https://user-images.githubusercontent.com/36526702/141923467-0dda59db-1480-4144-bf16-527f80c20838.mp4
Code for the demo for a sneak peak at the API:
```go
package main
import (
"context"
"fmt"
"io"
"log"
"os"
"syscall"
"github.com/Microsoft/hcsshim/internal/conpty"
"github.com/Microsoft/hcsshim/internal/exec"
"github.com/Microsoft/hcsshim/internal/jobobject" …
```

Add conpty (pseudo console) package

---

ext4/tar2ext4/tar2ext4.go
test/vendor/github.com/Microsoft/hcsshim/ext4/tar2ext4/tar2ext4.go
test/vendor/github.com/Microsoft/hcsshim/internal/winapi/process.go

Somehow after the last two check-in's the CI (specifically our linter)
started whining about ext4BlockSize being dead code. The last PR
to master our verify-test-vendor step also somehow didn't catch that
/internal/winapi/process.go was updated and needed to be pulled in, but it 
did after check-in This change fixes both of those issues.

Revendor in /test and remove dead code

---

internal/exec/exec.go
internal/jobcontainers/jobcontainer.go
internal/jobcontainers/process.go

This change swaps to using the new internal/exec package for host process containers to make use of the pseudo console functionality and ability to launch a process in a job object at creation time instead of assigning shortly after. This PR additionally adds in the bits needed to get tty support for host process up and running.  See below for it in action:
https://user-images.githubusercontent.com/36526702/146683421-ae678d98-97d2-45ae-8450-ed4e076dfc03.mp4

Swap to the internal/exec pkg for host process containers

---

internal/hcs/schema2/isolation_settings.go
internal/uvm/create_lcow.go
test/vendor/github.com/Microsoft/hcsshim/internal/hcs/schema2/isolation_settings.go
test/vendor/github.com/Microsoft/hcsshim/internal/uvm/create_lcow.go

These are both required due to evolution of the hcs/vmms layers.
This PR replaces https://github.com/microsoft/hcsshim/pull/1232 (GuestStateFileType=BlockStorage) which had trouble with signing and so passing the CI. In addition it sets the HclEnabled flag which is required or the vmgs file is corrupted by the vmms leading to the UVM only starting exactly once.
Signed-off-by: Ken Gordon <Ken.Gordon@microsoft.com>

HCS fixes for HclEnabled and guest state file type.

---

internal/conpty/conpty.go
internal/exec/exec_test.go
internal/jobcontainers/jobcontainer.go

This change renames conpty.New, the method used to create a new ConPTY object, to Create instead. Mostly preference and to stay in line with what we'd named the method for creating a job object. The windows API used to create the pty is 'CreatePseudoConsole' so to me it makes more sense and would be more familiar to folks if this was ever moved out of /internal for outside use.

Rename conpty.New to conpty.Create

---

internal/hcs/process.go
test/vendor/github.com/Microsoft/hcsshim/internal/hcs/process.go

When calling HcsTerminateProcess on a process that has exited, but we still have open handles to, an ERROR_ACCESS_DENIED may be returned.
https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-terminateprocess#remarks
Fixes: https://github.com/microsoft/hcsshim/issues/1251

Ignore access denied on HcsTerminateProcess

---

internal/conpty/conpty.go
internal/exec/options.go
internal/jobcontainers/jobcontainer.go
internal/jobcontainers/process.go

This change renames the ConPTY struct in the conpty package to just Pty

Change redundant conpty.ConPTY struct name

---

internal/guest/runtime/hcsv2/workload_container.go

Fix deferred os.Umask usage in loops

---

.golangci.yml
internal/exec/exec_test.go
test/vendor/github.com/Microsoft/hcsshim/.golangci.yml

Before, this test used to write something to the pty and then see if we
could read the same thing shortly afterwards. Really all we wanna test here
is just that we can write things in general, so the same thing that
TestExecStdinPowershell is currently doing should suffice.
If the process exits then the 'exit' write went through so that should be
plenty for this test. This change additionally adds a timeout for waiting
for the process to exit for TestPseudoConsolePowershell as well as
TestExecStdinPowershell so we have an indicator for if the 'exit' write
didn't work.

Rework TestPseudoConsolePowershell

---

internal/hcs/process.go
test/vendor/github.com/Microsoft/hcsshim/internal/hcs/process.go

When calling HcsTerminateProcess on a process that has exited, but we
still have open handles to, an ERROR_ACCESS_DENIED may be returned.
https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-terminateprocess#remarks
Signed-off-by: Gabriel Adrian Samfira <gsamfira@cloudbasesolutions.com>
(cherry picked from commit 58caeedaebd9cd721a74fafd2bdcbc274d8d21b9)

[release/0.9] Ignore ERROR_ACCESS_DENIED on Kill (#1252)

---

cmd/containerd-shim-runhcs-v1/pod.go
cmd/containerd-shim-runhcs-v1/task_hcs.go
cmd/containerd-shim-runhcs-v1/task_hcs_test.go

This change gives waitInitExit() a chance to cleanup resource when DeleteExec() is called, before returning.
TL;DR
This should fix situations where the shim exits before releasing container resources.
TS;NM
I am not sure if this is a proper fix, or if it is just a band-aid over something that should be fixed elsewhere, but it did fix the ```TestRestartMonitor``` test in ```containerd```. This issue also seems to cause flakiness in the ```TestContainerdRestart```` test due to the fact that lingering sandboxes are picked up by the test and fails.
The restart monitor in ```containerd``` watches for situations where tasks end, and attempts to restart them. The ```TestRestartMonitor``` test will spawn a task, then send a ```Kill()``` signal to that task and wait for the restart monitor to …

Wait for waitInitExit() to return

---

cmd/containerd-shim-runhcs-v1/pod.go
cmd/containerd-shim-runhcs-v1/task_hcs.go
cmd/containerd-shim-runhcs-v1/task_hcs_test.go

This change gives waitInitExit() a chance to cleanup resource when DeleteExec() is called, before returning.
TL;DR
This should fix situations where the shim exits before releasing container resources.
(cherry picked from commit 6241c53e02a8fb9cbfb67d86ad583c31bf090caa)

[release/0.9] Wait for waitInitExit() to return #1249

---

test/cri-containerd/runpodsandbox_test.go

This change aims to de-flake the Windows process dump test by continuously checking for a .dmp instead of waiting some arbitrary amount of time and then checking once. While we haven't seen any flakes with the Linux version of this test for generating core dumps, the same logic is employed for the LCOW test as well to keep it consistent.

Rework process dump cri-containerd tests

---

osversion/windowsbuilds.go
test/cri-containerd/main.go
test/vendor/github.com/Microsoft/hcsshim/osversion/windowsbuilds.go

This change backports the following changes to get ws2022 support for the cri-containerd suite. 
1. osversion package definitions for 21h2: https://github.com/microsoft/hcsshim/pull/1205
2. Add ws2022 image/build to cri-containerd tests: https://github.com/microsoft/hcsshim/pull/1160

[release/0.9] Add ws2022 image/build to cri-containerd tests (#1160)

---

cmd/containerd-shim-runhcs-v1/task.go
cmd/containerd-shim-runhcs-v1/task_hcs.go
internal/hcs/errors.go
test/vendor/github.com/Microsoft/hcsshim/internal/hcs/errors.go

When querying the stats of a container that is in the process of beingstopped, an ERROR_INVALID_HANDLE (0x6) may be returned. This change ignores that error as part of ```isStatsNotFound()```.
This change also fixes the return values of Stats() when encountering one of the expected errors. Returning nil stats when error is nil will break caller assumptions of finding a valid value when error is nil. Instead, we now return an ```ErrNotFound```.
Signed-off-by: Gabriel Adrian Samfira <gsamfira@cloudbasesolutions.com>

Add ErrInvalidHandle and fix list stats

---

ext4/dmverity/dmverity.go
ext4/dmverity/dmverity_test.go
internal/guest/storage/devicemapper/targets.go
test/vendor/github.com/Microsoft/hcsshim/ext4/dmverity/dmverity.go

Make sure to assert the value of dmveritySuperblock.Signature before
trying to read the root hash, without the check, any valid footer would
be treated as a dm-verity superblock.
Add unit tests to cover other edge cases.

Fix ReadDMVeritySuperBlock function

---

cmd/containerd-shim-runhcs-v1/task.go
cmd/containerd-shim-runhcs-v1/task_hcs.go
internal/hcs/errors.go
test/vendor/github.com/Microsoft/hcsshim/internal/hcs/errors.go

When querying the stats of a container that is in the process of being
stopped, an ERROR_INVALID_HANDLE (0x6) may be returned. This change
ignores that error and returns an empty stats object.
This change also fixes the return values of Stats() when encountering
one of the expected errors. Returning nil stats when error is nil will
break caller assumptions of finding a valid value when error is nil.
Instead, an ErrNotFound is returned.
Signed-off-by: Gabriel Adrian Samfira <gsamfira@cloudbasesolutions.com>
(cherry picked from commit 790bcae4c9e9734f4ca50d0e17b03ed749f2b4d9)

[release/0.9] Add ErrInvalidHandle and fix list stats

---

test/cri-containerd/extended_task_test.go

Test_ExtendedTask_ProcessorInfo had a minor bug, when the
processor info request would return an error and the error was
expected. The test would still proceed to check the processor
count from the response in whicn case the response is nil and
the check results in nil point dereference.

Fix Test_ExtendedTask_ProcessorInfo CRI test

---

.github/workflows/ci.yml
internal/layers/layers.go
test/vendor/github.com/Microsoft/hcsshim/internal/layers/layers.go

This change adds a small log to the code path that handles retrying layer setup if we encountered a set of known error codes that we'd observed on ws2019. This is mostly just so we can tell how often we're actually hitting this and see which error is most prevalent.
This additionally contains a commit to remove the --timeout flag passed for our golangci runs. The command line flags have higher priority than the config file so our timeout defined there wasn't being honored.

Add logging to layer retry code path

---

internal/exec/exec_test.go

This test is fairly flaky on the Github CI but seems to run fine locally (maybe pure
luck). Skip this for now to let contributions continue without a hitch and until we
can replace this with a better suited test shortly.

Skip flaky TestPseudoConsolePowershell 

---

internal/exec/exec_test.go
internal/jobobject/jobobject.go
internal/jobobject/jobobject_test.go
internal/winapi/jobobject.go
test/vendor/github.com/Microsoft/hcsshim/internal/winapi/jobobject.go

The `AllPids` method on JOBOBJECT_BASIC_PROCESS_ID_LIST would allocate a very large array to store any pids in the job object, cast the memory to this array, and then slice down to what elements it actually took up in the array based off the value of what was in the NumberOfProcessIdsInList field. The checkptr compile option doesn't like when slices don't have an explicit length and capacity so this change updates the slicing to use a three-index slice to set the capacity to the same as the length.
Before for fmt.Println(len(arr), cap(arr)) -> 2, 134217727
After: -> 2, 2
This change additionally adds a test in internal/jobobject and modifies the TestExecWithJob test in internal/exec to verify that checkptr doesn't get angry when we hit a code path that performs the cast (calling …

Fix checkptr error with > 1 process in job object

---

internal/tools/securitypolicy/main.go
pkg/securitypolicy/securitypolicy.go
pkg/securitypolicy/securitypolicy_test.go
pkg/securitypolicy/securitypolicyenforcer.go
test/vendor/github.com/Microsoft/hcsshim/pkg/securitypolicy/securitypolicy.go
test/vendor/github.com/Microsoft/hcsshim/pkg/securitypolicy/securitypolicyenforcer.go

The current implementation exposes some internal structure,
which is unnecessary as well as some structs are duplicated
across security policy package and security policy tool.
This PR refactors code to de-duplicate exported structures
and hides internal implementation behind new factory methods.

Refactor code for security policy

---

cmd/containerd-shim-runhcs-v1/pod.go

Correctly uses a named return value on createPod. Previously if err was
redeclared in a nested scope and then returned, defers would not see the
returned error value. In particular this prevented the UVM cleanup defer
from working properly.

shim: Don't shadow err return in createPod

---

internal/guest/gcserr/errors.go
internal/guest/runtime/hcsv2/container.go
internal/guest/runtime/hcsv2/uvm.go
internal/guest/runtime/runc/runc.go
internal/guest/runtime/runc/utils.go
internal/guest/runtime/runtime.go

Fixed bug where container is cast as a process, which then causes the
container to be deleted prematurely before when the container finishes
executing. 
Currently, whenever an LCOW container is stopped, the logs show multiple
errors being raised that runc cannot find the container, which cause the 
`Kill` command issued by containerd to exit unsuccessfully. 
Added conversion of runc log file error strings into `error` types that
wrap HResult error types.
Wrapped runc errors from log file, which is more informative that error
returned from cmd execution.
Added traces to guest container operations, to trace low level container
operations.

Bug fix with runc container lifetime management

---

cmd/containerd-shim-runhcs-v1/main.go
cmd/containerd-shim-runhcs-v1/serve.go
cmd/containerd-shim-runhcs-v1/service.go
cmd/containerd-shim-runhcs-v1/service_internal.go
cmd/containerd-shim-runhcs-v1/service_internal_podshim_test.go
cmd/containerd-shim-runhcs-v1/service_internal_taskshim_test.go
cmd/containerd-shim-runhcs-v1/service_internal_test.go

Currently, when a `Shutdown` request is received, `service` calls `os.Exit` to forcefully exits the binary without cleaning up resources and IO channels, ending spans, or flushing logs. Primarily this prevents logging of shim-wide or long running spans but can also leak un-closed system resources.
For reference, the runc shim within containerd [does not respect](https://github.com/containerd/containerd/blob/77d53d2d230c3bcd3f02e6f493019a72905c875b/runtime/v2/runc/task/service.go#L470) the `ShutdownRequest.Now` parameter, and calls several cleanup callbacks instead of exiting immediately via `os.Exit`
Added `.Done()` and `.IsShutdown()` methods to `service` to signal that a service shutdown request from containerd for the init task was received, and updated the `serve` action to wait on a …

Shutdown hcsshim properly

---

internal/jobcontainers/jobcontainer.go
test/cri-containerd/jobcontainer_test.go

When installing tools into container it is sometimes desirable to have
those tools on the path for the current process.  Since the Windows
doesn't support variable expansion on the PATH variable and the
job mount path as something that isn't know at runtime we need to expand
it for the passer.  This could go away if the mount path is no longer
used in the future.
A sample docker file where this would work:
```
FROM mcr.microsoft.com/windows/servercore:${OS} AS runtime
WORKDIR /apps
ENV PATH="%CONTAINER_SANDBOX_MOUNT_POINT%\apps\vim\;C:\Windows\system32;C:\Windows"
```
cc: @dcantah

Expand env variables for job containers to job mount path

---

internal/hcsoci/network.go
test/vendor/github.com/Microsoft/hcsshim/internal/hcsoci/network.go

If you try and run a hypervisor isolated container through ctr (`.\ctr.exe run --runtime io.containerd.runhcs.v1 --rm --isolated
mcr.microsoft.com/windows/nanoserver:1809 hyp-test cmd /c "echo Hello World!"`) currently you'll get "ctr: failure while creating namespace for container: network namespace not found: unknown". The normal path through ctr is no network namespace is passed, so our shim will try and make one. The namespace was being created via `hns.CreateNamespace` which stores the ID of the namespace in all caps, however later on in the process when we go to add the namespace to the uvm we re-grab a namespace object via `hcn.GetNamespaceByID` which populates the Id field in all lowercase.
When we originally store the namespace in our map of known namespaces we use the hns …

Fix Network Namespace Bug For Ctr

---

internal/layers/layers.go
test/vendor/github.com/Microsoft/hcsshim/internal/layers/layers.go

The comment had an empty line between it and the declaration so it didn't
show up for go doc.

Fix comment placement for layers.MountContainerLayers

---

internal/jobcontainers/jobcontainer.go
internal/jobcontainers/oci.go

This function used to just return a bool of whether the annotation was "true"
or not which is a bit diffferent than what the name implied. Change to inheritUserTokenIsSet
to be more clear. It also used to check if the annotation was set internally which
shouldn't be needed as we only cared about whether it was "true" or not. If the
value isn't in the map we should just get back the default value of a string which
is fine for what it was being used for.
Additionally moves a comment that was mistakingly directly above the function body
to the top of the file.

Cleanup 'getUserTokenInheritAnnotation'

---

internal/uvm/network.go
test/vendor/github.com/Microsoft/hcsshim/internal/uvm/network.go

When consolidating guest protocol into its own package
in https://github.com/microsoft/hcsshim/pull/1240 wrong constant
definition was used for adding a network namespace. Fix this by
using the correct constants.

Fix bugs in network setup introduced by a refactor PR

---

internal/guest/transport/vsock.go

Most of the code in /internal/guest has build tags as it's all Linux specific
so apply one for vsock.go as well as vsock.Dial is unimplemented on Windows.
This also fixes a linter issue we've been seeing on the push trigger for
golangci-lint. It complains that the error check we're performing can
never be true (err == nil) because on linting this file with GOOS=windows
it will check the Windows implementation for vsock.Dial which is hard coded
to return an unimplemented error.

Put Linux build tag on /internal/guest/transport/vsock.go

---

test/cri-containerd/pod_update_test.go

Skipping for now to prevent failures during package creation. 

Skip test for updating VM cpugroup membership for now

---

internal/guest/storage/overlay/overlay.go

We've had quite a few times where creating the upper or work directories in
the guest fails with ENOSPC but we don't have any view into what the mount
looks like at the time we get this. This change just catches any ENOSPC errors
when creating an overlayfs mount, calls statfs and logs the disk space and inode
info for the mount the failed directory is on. This should make investigating
these types of issues much easier.
This may be followed up with a change to delete the upper and work directories
for a container, as this becomes troublesome with the model for sharing a scratch volume.

Linux GCS: Log disk info on ENOSPC errors

---

internal/winapi/utils.go
internal/winapi/winapi_test.go

This cherry-picks two changes that fixed bugs when unpacking images that contained non-ascii characters.
https://github.com/microsoft/hcsshim/pull/1138/commits/0afb0c9f89a5e7e3a0c64e0572460f44923ac888
https://github.com/microsoft/hcsshim/pull/1138/commits/587be85a4cc3ae962665adcf20be1bfe511ab741
----
The existing UnicodeString constructor creates a unicode string object by taking the
length of a given GO string. This works fine for ASCII strings but fails when the input
string contains non ASCII characters. This change fixes it.
Description:
In the earlier version of NewUnicodeString the length would be set to the number of bytes in the string than the number of runes in the string. If the input string of 3 runes had one non-ascii character (i.e a character that would take 2 bytes to …

[release/0.8] Backport 'Bugfix for UnicodeString constructor'

---

cmd/containerd-shim-runhcs-v1/delete.go
internal/jobcontainers/jobcontainer.go
internal/jobcontainers/logon.go
internal/winapi/jobobject.go
internal/winapi/path.go
internal/winapi/system.go
internal/winapi/thread.go
internal/winapi/user.go
internal/winapi/winapi.go
internal/winapi/zsyscall_windows.go
test/cri-containerd/jobcontainer_test.go
test/vendor/github.com/Microsoft/hcsshim/internal/winapi/jobobject.go
test/vendor/github.com/Microsoft/hcsshim/internal/winapi/path.go
test/vendor/github.com/Microsoft/hcsshim/internal/winapi/system.go
test/vendor/github.com/Microsoft/hcsshim/internal/winapi/thread.go
test/vendor/github.com/Microsoft/hcsshim/internal/winapi/user.go
test/vendor/github.com/Microsoft/hcsshim/internal/winapi/winapi.go
test/vendor/github.com/Microsoft/hcsshim/internal/winapi/zsyscall_windows.go

This allows a user the ability to pass a Windows group name as the username for the container. What happens in this
case is:
1. Client provides a Windows group name as the username for the container
2. We validate that it's a group, and if so then make a temporary local
account.
3. Add local account to the group passed in and run the container under the
account.
4. On container exit delete the account.
This allows a client to setup a group with whatever permissions/restrictions
needed on it and have any host process containers run as a user in the group.
The blocker for not just creating a user itself with the right permissions is
there's no cri field to pass a user password, and passwordless logon seems to be
blocked on Windows by default.

Add local user account creation for host process containers

---

cmd/ncproxy/server_test.go
internal/exec/exec_test.go
internal/guest/storage/utilities_test.go
internal/jobcontainers/path_test.go
internal/ncproxy/store/store_test.go
internal/safefile/safeopen_admin_test.go
internal/safefile/safeopen_test.go
test/containerd-shim-runhcs-v1/delete_test.go
test/containerd-shim-runhcs-v1/start_test.go
test/cri-containerd/container_network_test.go
test/cri-containerd/container_test.go
test/cri-containerd/createcontainer_test.go
test/cri-containerd/jobcontainer_test.go
test/cri-containerd/runpodsandbox_test.go
test/functional/uvm_scsi_test.go
test/runhcs/create-scratch_test.go

A small testing enhancement.
We can use the `T.TempDir` function from the `testing` package to create temporary directory. The directory created by `T.TempDir` is automatically removed when the test and all its subtests complete.
Reference: https://pkg.go.dev/testing#T.TempDir

test: use `T.TempDir` to create temporary test directory

---

internal/jobobject/iocp.go
internal/winapi/iocp.go
internal/winapi/winapi.go
internal/winapi/zsyscall_windows.go
test/vendor/github.com/Microsoft/hcsshim/internal/winapi/iocp.go
test/vendor/github.com/Microsoft/hcsshim/internal/winapi/winapi.go
test/vendor/github.com/Microsoft/hcsshim/internal/winapi/zsyscall_windows.go

Previously we had our own definition for GetQueuedCompletionStatus as x/sys/windows had an incorrect definition for it. This was remedied a bit ago in this change https://github.com/golang/sys/commit/683adc9d29d7bd1f0f778e1f7f2eeb61b415f4d5 so we're alright to remove our own at this point.

Replace winapi GetQueuedCompletionStatus bind with x/sys/windows

---

internal/jobcontainers/logon.go

fix lint issue

---

internal/guest/runtime/hcsv2/uvm.go
internal/guest/storage/test/policy/mountmonitoringsecuritypolicyenforcer.go
internal/jobcontainers/logon.go
internal/tools/securitypolicy/main.go
pkg/securitypolicy/securitypolicy.go
pkg/securitypolicy/securitypolicy_test.go
pkg/securitypolicy/securitypolicyenforcer.go
test/vendor/github.com/Microsoft/hcsshim/pkg/securitypolicy/securitypolicy.go
test/vendor/github.com/Microsoft/hcsshim/pkg/securitypolicy/securitypolicyenforcer.go

The working directory can be set as part of container image
by WORKINGDIR Dockerfile directive or could be explicitly
set inside CRI container config. Changing the CWD of container
can change the expected behavior of a container.
If the working_dir config is not present or empty inside the
policy config, this information will be gathered from container
image spec.
Add logic to enforce CWD enforcement inside GCS and extend
policy dev tool and policy structure to support this scenario.
The enforcement is an exact string match between what's in the
policy and what's in the generated container spec. If the paths
don't match, the container will fail to start.
Add a utility funcion that picks a random container from an array
and generates a valid/invalid overlay for that container. Refactor …

Working directory enforcement

---

pkg/securitypolicy/securitypolicyenforcer.go
test/vendor/github.com/Microsoft/hcsshim/pkg/securitypolicy/securitypolicyenforcer.go

Fix typo in error message

---

internal/uvm/create_lcow.go
test/vendor/github.com/Microsoft/hcsshim/internal/uvm/create_lcow.go

Our dev OS branch and the target deployment OS are quite different in capabilities. This reverts to the earlier interface.
Signed-off-by: Ken Gordon <ken.gordon@microsoft.com>

Revert to v2.5 schema GuestStateFileType to support release target OS

---

internal/tools/securitypolicy/README.md
pkg/securitypolicy/securitypolicyenforcer.go
test/vendor/github.com/Microsoft/hcsshim/pkg/securitypolicy/securitypolicyenforcer.go

When creating internal representation of security policy for a container
WorkingDir field wasn't properly initialized, which broke the policy
enforcement.

Fix WorkingDir missing in securityPolicyContainer

---

cmd/gcs/main.go
internal/guest/bridge/bridge.go
internal/log/scrub.go
internal/uvm/create_lcow.go
test/vendor/github.com/Microsoft/hcsshim/internal/log/scrub.go
test/vendor/github.com/Microsoft/hcsshim/internal/uvm/create_lcow.go

Updated scrubbing to include logging from guest Linux GCS
Added scrubbing for annotations.

Scrubbing annotations from logs

---

internal/jobcontainers/jobcontainer.go

Previously the values in the spec weren't being used.
This change additionally changes the defaults to an 80 width and 25 height
to match what cexecsvc/hcs sets.

Respect console size for host process containers

---

internal/guest/runtime/hcsv2/uvm.go
internal/tools/securitypolicy/README.md
internal/uvm/security_policy.go
pkg/securitypolicy/securitypolicy.go
test/vendor/github.com/Microsoft/hcsshim/internal/uvm/security_policy.go
test/vendor/github.com/Microsoft/hcsshim/pkg/securitypolicy/securitypolicy.go

When bringing up the UVM default to closed door security policy
to reject any modification requests prior to security policy is set
inside GCS.
When security policy is empty, default to open door policy.

Default to deny all security policy.

---

internal/log/scrub.go
test/vendor/github.com/Microsoft/hcsshim/internal/log/scrub.go

Bug where un-scrubbed parameter was returned instead of scrubbed result

Scrubbing bugfix: incorrect return variable

---

internal/uvm/create_lcow.go
test/vendor/github.com/Microsoft/hcsshim/internal/uvm/create_lcow.go

GCS init fails to parse the entropy socket when enabling ConsolePipe.
Fix by separating entropy parameters from the rest init args and
wrapping only init args with `sh -c`.

Fix gcs init args wrapping when ConsolePipe is enabled

---

internal/exec/exec_test.go
internal/jobobject/jobobject_test.go

Most of the `jobobject` package tests we have ask for options that aren't actually needed/used. This change makes it so that any test that doesn't need a named job object doesn't ask for one and any test that doesn't plan on using the iocp messages doesn't flip the notifications field either. This wasn't causing any issues, but it's probably best to filter down what's being tested to only what's needed.

Fix up job object options for unit tests

---

internal/guest/storage/scsi/scsi.go

When adding layer integrity checking feature for SCSI devices,
the dm-verity device format naming was inconsistent with the
already existing pmem based verity target.
Make the naming consistent by changing `verity-scsi-...` to
`dm-verity-scsi-...`.

Fix dm-verity target naming format in linux guest

---

internal/exec/exec_test.go
internal/jobobject/jobobject.go
internal/jobobject/jobobject_test.go
internal/winapi/bindflt.go
internal/winapi/jobobject.go
internal/winapi/winapi.go
internal/winapi/zsyscall_windows.go
test/vendor/github.com/Microsoft/hcsshim/internal/winapi/bindflt.go
test/vendor/github.com/Microsoft/hcsshim/internal/winapi/jobobject.go
test/vendor/github.com/Microsoft/hcsshim/internal/winapi/winapi.go
test/vendor/github.com/Microsoft/hcsshim/internal/winapi/zsyscall_windows.go

This change adds a couple Go bindings for calls and constants from bindfltapi.dll as well as some silo flags for job objects. Together these allow file bindings (think bind mounts on Linux) to be performed for a specific job object. The bindings
are only viewable from processes within that specific job.
This change additionally adds a couple unit tests for this behavior.

Add Go bindflt/silo definitions

---

.github/workflows/ci.yml

Some of the tooling golangci-lint uses doesn't fully support 1.18 yet resulting in a bunch of hard to decode errors. We were using ^1.17.0 as our version listed so we ended up resolving to 1.18 a couple of days ago and finally ran into this. v1.45.0 of golangci-lint has a workaround for this which is disabling some of the problematic linters, but these are some of our most used. This seems like a sane fix for now until the kinks are ironed out and things are working on 1.18.

Pin go version for linter to 1.17.x

---

pkg/securitypolicy/opts.go
test/cri-containerd/layer_integrity_test.go
test/cri-containerd/policy_test.go
test/vendor/github.com/Microsoft/hcsshim/pkg/securitypolicy/opts.go

Add basic positive and negative tests for security policy enforcement.

Add tests for security policy enforcement

---

test/cri-containerd/policy_test.go

Fix working_dir negative test error expectation

---

internal/jobobject/jobobject.go
internal/jobobject/jobobject_test.go
internal/jobobject/limits.go

This change swaps to fmt.Errorf for wrapped errors in the jobobject package from errors.Wrap. We'd had talks of moving this code to winio where we've removed our pkg/errors dependency so this would make the port easier.
We should probably do this for most things to see if we can get rid of our pkg/errors use, the only thing I'm not sure on is we use the stack embedding errors.Wrap provides for the gcs https://github.com/microsoft/hcsshim/blob/master/internal/guest/gcserr/errors.go#L57-L88

Swap to fmt.Errorf in jobobject package

---

cmd/containerd-shim-runhcs-v1/events.go
cmd/containerd-shim-runhcs-v1/events_test.go
cmd/containerd-shim-runhcs-v1/serve.go

Shim `eventPublisher` now uses an internal setting for the namespace instead of relying on a global flag.

Removed shim publisher dependence on global flag/setting 

---

Makefile
test/vendor/github.com/Microsoft/hcsshim/Makefile

Reorganized makefile to read from top to bottom, and added additional
files to LCOW rootfs that include the time stamp of of the vhd creation,
the image build date, and its full name (pulled from a *.testdata.json
file in the yocto release).

Reorganizing makefile and adding info to rootfs

---

cmd/containerd-shim-runhcs-v1/delete.go
cmd/containerd-shim-runhcs-v1/task_hcs.go
computestorage/helpers.go
ext4/dmverity/dmverity.go
ext4/internal/compactext4/compact.go
ext4/internal/compactext4/compact_test.go
internal/guest/storage/crypt/crypt_test.go
internal/guest/storage/overlay/overlay.go
internal/jobcontainers/oci.go
internal/memory/pool.go
internal/memory/pool_test.go
internal/memory/types.go
internal/tools/uvmboot/lcow.go
internal/uvm/constants.go
internal/uvm/memory_update.go
internal/uvm/vpmem_mapped_test.go
test/cri-containerd/container_update_test.go
test/cri-containerd/createcontainer_test.go
test/cri-containerd/pod_update_test.go
test/cri-containerd/stats_test.go
test/functional/test.go
test/functional/uvm_memory_test.go
test/vendor/github.com/Microsoft/hcsshim/computestorage/helpers.go
test/vendor/github.com/Microsoft/hcsshim/ext4/dmverity/dmverity.go
test/vendor/github.com/Microsoft/hcsshim/ext4/internal/compactext4/compact.go
test/vendor/github.com/Microsoft/hcsshim/internal/memory/pool.go
test/vendor/github.com/Microsoft/hcsshim/internal/memory/types.go
test/vendor/github.com/Microsoft/hcsshim/internal/uvm/constants.go
test/vendor/github.com/Microsoft/hcsshim/internal/uvm/memory_update.go

We have a bunch of 1024 * 1024 or 1024 * 1024 * 1024 numerical constants (or just other named megabyte constants) lying around. This changes to using the constants we have defined in the /internal/memory package instead.
This change additionally renames the memory.MegaByte and memory.GigaByte constants to Mib and GiB respectively, and leaves them as untyped consts.

Use /internal/memory constants

---

.github/workflows/ci.yml

Testing GCS code before building rootfs, and making it easier to parse test and make failures by separating the two.

Split out GCS test and build

---

test/cri-containerd/policy_test.go

This reverts commit 2028de8b8d5e0516e0e65664f9085dab02a6a5e2.

Revert "Fix working_dir negative test error expectation (#1348)"

---

internal/guest/bridge/bridge_v2.go
internal/guest/gcserr/errors.go
internal/guest/runtime/hcsv2/container.go
internal/guest/runtime/hcsv2/uvm.go
test/cri-containerd/policy_test.go

Prior to this change, GCS allowed only one CreateContainer operation
at a time. This isn't an issue in general case, however this doesn't
work properly with synchronization via OCI runtime hook.
Synchronization via runtime hook was introduced in:
https://github.com/microsoft/hcsshim/pull/1258
It injects a CreateRuntime OCI hook, if security policy provides
wait paths.
This allows container-A to run after container-B, where container-B
writes to an empty directory volume shared between the two containers
to signal that it's done some setup container-A depends on.
In general case, container-A can be started before container-B which
results in a deadlock, because CreateContainer request holds a lock
to a map, which keeps track of running containers.
To resolve the issue, the code has been …

Allow multiple CreateContainer operations at the same time.

---

internal/hns/hnspolicy.go
test/vendor/github.com/Microsoft/hcsshim/internal/hns/hnspolicy.go

The libnetwork logic uses a dummy proxy to bind the ports for communication between container and host. WS 2019 Aug 2020 patch onwards, Windows started doing an early port reservation which conflicts with the aforementioned logic for overlay and host publish mode for the ports.
Adding ExternalPortReserved flag to NatPolicy for HNS API V1. This is a flag exposed for docker to avoid port reservation conflict with external port
HNS API V2 will use NatFlags to check and see if ExternalPortReserved is set
(cherry picked from commit b85f3fdc17dad534a2cebbc67e0c18f77fb0fca8)
Signed-off-by: Ameya Gawde <agawde@mirantis.com>
Verified the fix with private HostNetSvc.dll from Windows networking team and corresponding change on libnetwork to send down the flag `ExternalPortReserved`

Fix for port conflict with docker daemon. 

---

pkg/securitypolicy/securitypolicyenforcer.go
test/vendor/github.com/Microsoft/hcsshim/pkg/securitypolicy/securitypolicyenforcer.go

Hold lock when updating DefaultMounts

---

internal/hcs/system.go
test/vendor/github.com/Microsoft/hcsshim/internal/hcs/system.go

Hey team,
It can be horribly annoying without verbose logs for a user to figure out what exactly was being executed when running a command in a container. How do we feel about including the `CommandLine` in the main error?
Without:
```
ctr run --rm mcr.microsoft.com/windows/nanoserver:ltsc2022 test powershell -Command { Write-Host Here }
ctr: hcs::System::CreateProcess test: The system cannot find the file specified.: unknown
```
With:
```
ctr run --rm mcr.microsoft.com/windows/nanoserver:ltsc2022 test powershell -Command { Write-Host Here }
ctr: hcs::System::CreateProcess: powershell -Command { Write-Host Here } test: The system cannot find the file specified.: unknown
```
The second example more clearly illustrates to the caller that "powershell" was the file that was not found. …

Include CommandLine in CreateProcess errors

---

internal/tools/uvmboot/lcow.go
internal/tools/uvmboot/main.go
internal/tools/uvmboot/mounts.go
internal/winapi/elevation.go
test/vendor/github.com/Microsoft/hcsshim/internal/winapi/elevation.go

Added functionality to internal\tools\uvmboot for LCOW:
* specifying boot file path;
* picking kernel or vmlinux file;
* mounting SCSI VHDS and sharing files into the uVM;
* disabling the time sync;
* setting the uVM security policy.
Added `IsElevated() bool` function to `internal/winapi` to quit early
if the command is not run with admin privileges rather than returning a
cryptic error.
This is to support testing and benchmarking the Linux GCS.

uvmboot functionality

---

test/cri-containerd/argsescaped_test.go
test/cri-containerd/main_test.go
test/cri-containerd/test-images/argsescaped/dockerfile

This adds a test to validate execs work with ArgsEscaped images. ArgsEscaped refers to a non-standard OCI image spec field
that indicates that the command line for Windows Containers should be used from args[0] without escaping. This behavior
comes into play with images that use a shell-form ENTRYPOINT or CMD in their Dockerfile. The behavior that the test is testing
is that execs work properly with these images. Hcsshim prefers the commandline field on the OCI runtime spec and will ignore
Args if this is filled in, which ArgsEscaped does. In Containerd/cri plugin the containers runtime spec is used as a base for the execs spec as well, so if commandline isn't cleared out then we'll end up launching the init process again instead of what the user requested.

Add ArgsEscaped exec test

---

.github/workflows/ci.yml
internal/safefile/safeopen.go
internal/safefile/safeopen_admin_test.go
internal/wclayer/exportlayer.go
internal/wclayer/legacy.go
test/vendor/github.com/Microsoft/hcsshim/internal/safefile/safeopen.go
test/vendor/github.com/Microsoft/hcsshim/internal/wclayer/exportlayer.go
test/vendor/github.com/Microsoft/hcsshim/internal/wclayer/legacy.go

A small batch of fixes that I've broken out of #901 to reduce the scope of that PR to only those parts that introduce not-yet-acceptible features.
This reduces the depth of the branches I have to manage and rebase.
Mostly documentation and CI, but also introduces a new SafeOpen API used by #901.

Random fixes broken out of base layer work

---

internal/layers/layers.go
test/vendor/github.com/Microsoft/hcsshim/internal/layers/layers.go

Manor -> manner, even though it was pretty comical to imagine the scenario of the current spelling :)

Fix wrong word use

---

internal/guest/spec/doc.go
internal/guest/spec/spec.go
internal/guest/storage/test/policy/doc.go
internal/guest/storage/vmbus/doc.go
test/cri-containerd/disable_vpmem_test.go
test/vendor/github.com/Microsoft/hcsshim/internal/guest/spec/doc.go
test/vendor/github.com/Microsoft/hcsshim/internal/guest/spec/spec.go

Missing build constraint, doc.go

---

internal/hns/hnspolicy.go
test/vendor/github.com/Microsoft/hcsshim/internal/hns/hnspolicy.go

Since moby master is vendoring 0.9.x hcsshim, backporting #1370 to release/0.9 branch

[release/0.9] Fix for port conflict with docker daemon

---

cmd/hooks/wait-paths/main.go
cmd/hooks/wait-paths/wait_paths_test.go

Follow up PR to add tests for wait-paths after initial PR https://github.com/microsoft/hcsshim/pull/1258
was merged.

tests: add tests for wait-paths

---

test/cri-containerd/containerdrestart_test.go

Prevent pulling LCOW images if it is not enabled for testing, and vice versa

Only pull appropriate images for testing

---

test/cri-containerd/containerdrestart_test.go

Change file path for restart tests to avoid permission issue

---

cmd/containerd-shim-runhcs-v1/service_internal.go

As part of the work to get WCOW-Hypervisor working for the upstream Containerd CRI plugin, parse our shims SandboxIsolation field here and set the HyperV runtime spec field if it's set to the HYPERVISOR option. This avoids us needing to parse our shim specific options in upstream Containerd which is always a plus.

Fill in HyperV runtime spec field if shim options asks for it

---

internal/gcs/protocol.go
test/vendor/github.com/Microsoft/hcsshim/internal/gcs/protocol.go

Factored `internal/gcs.(rpcProc).String()` method out from `internal/gcs.(msgType).String()`
This is needed for PR #1379

Bridge `rpcProc` string conversion

---

.gitattributes
test/vendor/github.com/Microsoft/hcsshim/.gitattributes

This PR fixes the issues in the `verify-test-vendor` ci job seen in https://github.com/microsoft/hcsshim/pull/1351 where a file was vendored with a crlf line ending but due to our git attributes settings, the file was pushed with lf line endings. This causes a file difference when checking if the modules are out of date in the ci job. 

Unset text attribute for vendored files in gitattributes

---

internal/guest/transport/vsock.go

They're defined in the vsock package we use, and we never used the CidAny const anywhere.

Remove vsock consts

---

internal/hcsoci/create.go
test/vendor/github.com/Microsoft/hcsshim/internal/hcsoci/create.go

In the function that handles checking if the cloned containers spec retrieved from the registry matches the current spec, it was comparing the hyperv field on the runtime spec using the != operator. This won't work as the hyperv field is a pointer so it would just be comparing the address and not the contents. 
This became an 'issue' as we set the hyperv field now if in our shim options the SandboxIsolation field is set to the HYPERVISOR option. This doesn't have much of an effect being set for containers that are going to be launched IN the UVM, so this is mostly just a bug that was surfaced from a field that didn't use to be set. This was causing the late clone spec comparisons to fail at the hyperv field, and thus the late clone tests.
This additionally changes to errors.New instead of …

Fix Hyper-V check in late clone spec comparisons

---

ext4/dmverity/dmverity.go
ext4/dmverity/dmverity_test.go
test/vendor/github.com/Microsoft/hcsshim/ext4/dmverity/dmverity.go

`unsafe.Sizeof` depends on ABI details, but we're not actually using the raw memory layout of `dmveritySuperblock`. We're just writing it out with `encoding/binary.Write`, so `encoding/binary.Size` gives the relevant size.

Don't use unsafe.Sizeof where encoding/binary.Size suffices

---

cmd/containerd-shim-runhcs-v1/service_internal.go

This fixes a nil deref possible if no shim options for the runtime
specified were supplied. For example:
[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runhcs-wcow-process.options]
vs.
[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runhcs-wcow-process.options]
SandboxIsolation = 0

Fix nil deref if no shim options were specified

---

internal/exec/exec_test.go
internal/hcs/system.go
internal/jobcontainers/jobcontainer.go
internal/jobobject/iocp.go
internal/jobobject/jobobject.go
internal/jobobject/jobobject_test.go
internal/jobobject/limits.go
internal/winapi/iocp.go
internal/winapi/jobobject.go
internal/winapi/process.go
internal/winapi/winapi.go
internal/winapi/zsyscall_windows.go
test/vendor/github.com/Microsoft/hcsshim/internal/hcs/system.go
test/vendor/github.com/Microsoft/hcsshim/internal/jobobject/doc.go
test/vendor/github.com/Microsoft/hcsshim/internal/jobobject/iocp.go
test/vendor/github.com/Microsoft/hcsshim/internal/jobobject/jobobject.go
test/vendor/github.com/Microsoft/hcsshim/internal/jobobject/limits.go
test/vendor/github.com/Microsoft/hcsshim/internal/queue/mq.go
test/vendor/github.com/Microsoft/hcsshim/internal/winapi/iocp.go
test/vendor/github.com/Microsoft/hcsshim/internal/winapi/jobobject.go
test/vendor/github.com/Microsoft/hcsshim/internal/winapi/process.go
test/vendor/github.com/Microsoft/hcsshim/internal/winapi/winapi.go
test/vendor/github.com/Microsoft/hcsshim/internal/winapi/zsyscall_windows.go
test/vendor/modules.txt

This cherry-picks in the work to query for statistics for Windows containers in-process as well as some additional 
commits that fixed some issues for our job object code/was easier to include than work around the merge conflicts. 
1. 51a80ffb1663ba636722932bf699b243889c789b
2. dab144a28c3d2f9de28b6240a5751cff2be2b1f3
3. 5a70918ec55c1282d68d0dedcb660907821027d7
4. 063ce4693d9a3ea82a18aecbdaa3d72017cf01f5
Original PR description for the query work:
This change adds in functionality to query statistics directly in the shim instead of reaching out to HCS. One of the main motivators behind this was poor performance for tallying up the private working set total for the container in HCS.
HCS calls NtQuerySystemInformation with the class SystemProcessInformation which returns an array containing …

[release/0.9] Query stats directly in-shim

---

pkg/ociwclayer/export.go
pkg/ociwclayer/import.go
test/vendor/github.com/Microsoft/hcsshim/pkg/ociwclayer/export.go
test/vendor/github.com/Microsoft/hcsshim/pkg/ociwclayer/import.go

Bypass function in base package (`.\layers.go`) and use layer functions
defined in `.\internal\wclayer`, since those allow propagating (span)
context.

Pass span context in ociwclayer

---

internal/tools/securitypolicy/helpers/helpers.go
test/vendor/github.com/Microsoft/hcsshim/internal/tools/securitypolicy/helpers/helpers.go

Container images may contain ENTRYPOINT and CMD directives and in
the case when "command" is missing in policy config, that information
needs to be inferred from the image itself.

Add handling of ENTRYPOINT and CMD when "command" is not in policy

---

internal/guest/policy/default.go
internal/guest/runtime/hcsv2/uvm.go
internal/tools/securitypolicy/helpers/helpers.go
pkg/securitypolicy/opts.go
pkg/securitypolicy/securitypolicy.go
pkg/securitypolicy/securitypolicy_test.go
pkg/securitypolicy/securitypolicyenforcer.go
test/cri-containerd/policy_test.go
test/vendor/github.com/Microsoft/hcsshim/internal/tools/securitypolicy/helpers/helpers.go
test/vendor/github.com/Microsoft/hcsshim/pkg/securitypolicy/opts.go
test/vendor/github.com/Microsoft/hcsshim/pkg/securitypolicy/securitypolicy.go
test/vendor/github.com/Microsoft/hcsshim/pkg/securitypolicy/securitypolicyenforcer.go

Add new container security policy config "AllowElevated", which when set
allows running container in privileged mode. As an initial implementation
this adds sysfs and cgroup mount constraints with "rw" mount option to
the container's mount policy. Later, more thorough container spec validation
for privileged containers should be added (e.g. validating capabilities in
container spec).
Introduce `standardEnforcerOpt` type which allows updating internal
security policy representation and add an opt to append mount constraints for
privileged container mounts,`NewSecurityPolicy` now accepts enforcer options.
securitypolicy.Containers.toInternal now returns a slice of pointers rather
than objects. This makes sure that modification through enforcer options are
presereved.
Add CRI tests to cover …

Add security policy config to allow containers to run in privileged mode

---

cmd/containerd-shim-runhcs-v1/task_hcs.go
internal/guest/prot/protocol.go
internal/guest/runtime/hcsv2/container.go
internal/guest/runtime/hcsv2/uvm.go
internal/hcsoci/create.go
internal/hcsoci/hcsdoc_lcow.go
internal/hcsoci/resources_lcow.go
internal/hcsoci/resources_wcow.go
internal/jobcontainers/storage.go
internal/layers/layers.go
internal/resources/resources.go
test/functional/wcow_test.go
test/vendor/github.com/Microsoft/hcsshim/internal/hcsoci/create.go
test/vendor/github.com/Microsoft/hcsshim/internal/hcsoci/hcsdoc_lcow.go
test/vendor/github.com/Microsoft/hcsshim/internal/hcsoci/resources_lcow.go
test/vendor/github.com/Microsoft/hcsshim/internal/hcsoci/resources_wcow.go
test/vendor/github.com/Microsoft/hcsshim/internal/layers/layers.go
test/vendor/github.com/Microsoft/hcsshim/internal/resources/resources.go
test/vendor/modules.txt

Normally, container scratch is a separate VHD that is mounted at `/run/gcs/c/<CID>` The
mount vhd call to gcs creates this directory and mounts the disk at that path.  The modify
combined layers call creates the `upper` & `work` directories at `/run/gcs/c/<CID>/upper`
& `/run/gcs/c/<CID>/work` and also creates the rootfs directory at
`/run/gcs/c/<CID>/rootfs`. Finally, overlayfs is mounted at `/run/gcs/c/<CID>/rootfs` for
the container to run. The remove combined layers call will remove the
`/run/gcs/c/<CID>/rootfs` directory.  The unmount VHD will remove the `/run/gcs/c/<CID>`
directory. The `upper` & `work` directories continue to live on the container sandbox VHD
until that snapshot is removed.
However, when the container scratch VHD is shared with the UVM (the UVM scratch is mounted …

Cleanup for shared container scratch

---

internal/jobcontainers/jobcontainer.go
internal/jobcontainers/mounts.go
internal/jobcontainers/mounts_test.go
internal/jobcontainers/oci.go
internal/jobcontainers/storage.go
internal/jobobject/jobobject.go
internal/layers/layers.go
pkg/annotations/annotations.go
test/cri-containerd/jobcontainer_test.go
test/vendor/github.com/Microsoft/hcsshim/internal/jobobject/jobobject.go
test/vendor/github.com/Microsoft/hcsshim/internal/layers/layers.go
test/vendor/github.com/Microsoft/hcsshim/pkg/annotations/annotations.go

This change adds in file binding support for host process containers if the host has the functionality available (bindfltapi.dll exists). This makes it so mounts in the runtime spec actually show up in the container at `mount.Destination` instead of simply being symlinks to a relative path, as well as are completely unique per container. This is achieved by upgrading the job object to a silo and making use of silo local file bindings that the Bind Filter supports.
This additionally opens up the opportunity for the rootfs for the container to be container local and unique. So instead of the rootfs showing up to any process on the host and being located at C:\C\\{containerid}, it now (by default at least) will be present at C:\hpc and be unique in each container as well. In a similar …

Implement file binding support for host process containers

---

internal/layers/layers.go
test/vendor/github.com/Microsoft/hcsshim/internal/layers/layers.go

The OS of the UVM was being checked by a pointer method at the start of the function when passing in a UVM object is optional. For process isolated and host process containers nil would be passed where this would be hit.

Fix nil deref in Windows layer setup

---

internal/guest/runtime/hcsv2/uvm.go
internal/guest/storage/test/policy/mountmonitoringsecuritypolicyenforcer.go
internal/tools/securitypolicy/README.md
internal/tools/securitypolicy/helpers/helpers.go
pkg/securitypolicy/opts.go
pkg/securitypolicy/securitypolicy.go
pkg/securitypolicy/securitypolicyenforcer.go
test/cri-containerd/policy_test.go
test/vendor/github.com/Microsoft/hcsshim/internal/tools/securitypolicy/helpers/helpers.go
test/vendor/github.com/Microsoft/hcsshim/pkg/securitypolicy/opts.go
test/vendor/github.com/Microsoft/hcsshim/pkg/securitypolicy/securitypolicy.go
test/vendor/github.com/Microsoft/hcsshim/pkg/securitypolicy/securitypolicyenforcer.go

`ExpectedMounts` was a poor name choice and was confusing in the
context of mount policy enforcement.

Rename ExpectedMounts to WaitMountPoints

---

internal/jobobject/jobobject.go
internal/winapi/bindflt.go
internal/winapi/zsyscall_windows.go

Change to using BfSetupFilter instead of BfSetupFilterEx. The Ex variant is
only useful if you want to pass a SID to perform the bind as a specific
user. We don't use this functionality, and it didn't exist on some
versions of Windows as well.

Change bind filter API used

---

internal/tools/securitypolicy/README.md

After adding "allow_elevated" config to contianer policy the
docs hasn't been updated.

update docs for security policy tool

---

internal/layers/layers.go

When mounting container layers we override containerScratchPathInUVM
with scsiMount.UVMPath after calling into vm.AddSCSI(...), which is
fine in scenarios when scratch disk isn't shared. In case when scratch
sharing is enabled, the scsiMount returned has sandbox container's
scratch path and we end up mounting all of the workload containers'
overlay at `/run/gcs/c/<podid>/container_<podid>` instead of
`/run/gcs/c/<podid>/container_<cid1>` and `/run/gcs/c/<podid>/container_<cid2>`.
Fix by removing the unnecessary assignment.

fix shared scratch scenario

---

.github/workflows/ci.yml

This PR adds an integration tests job to the CI workflow. Both the containerd cri-integration tests and the hcsshim cri-containerd tests are run as part of it. The tests run against the main branch of containerd.
Signed-off-by: Gabriel Adrian Samfira <gsamfira@cloudbasesolutions.com>

Adds cri-integration job

---

internal/guest/bridge/bridge_v2.go
internal/guest/runtime/runc/container.go
internal/guest/runtime/runc/runc.go
internal/guest/runtime/runc/utils.go

Certain runc commands (eg, Delete, State) do not need to use a log file
since runc does not consume the stdio and pass it to the container.
This PR switches the commands to consume the error directly from stderr,
without needing to parse from a file.
This fixes a bug where the directory containing the runc log file for a
container is deleted before the container itself can be deleted via the
runc command.
Runc errors that the directory containing the logfile does not exist, but since the returned error is `errors.Wrapf(runcErr,...)`, where `runcErr` is parsed from the logfile, it ends up being nil.
The fix is to read directly from stderr, skipping the log file.
Additionally, even if the runc delete command errors, the container is still deleted from the `gcs`, since if runc was able to …

Remove log file from runc commands

---

internal/jobcontainers/jobcontainer.go
internal/jobobject/jobobject.go
internal/jobobject/limits.go
internal/winapi/jobobject.go
internal/winapi/process.go
internal/winapi/system.go
internal/winapi/zsyscall_windows.go

Per rule 4 of unsafe.Pointer usage, conversion of a unsafe.Pointer
to a uinptr to pass to the syscall.Syscall family should only be done in
the argument list. We had a couple spots where we were passing it in as
an argument to a small wrapper function until it reached the underlying
syscall.Syscall*.
https://pkg.go.dev/unsafe#Pointer

Fix unsafe uses of unsafe.Pointer

---

.github/workflows/ci.yml

downgrade mingw

---

internal/guest/runtime/hcsv2/uvm.go
internal/guest/storage/test/policy/mountmonitoringsecuritypolicyenforcer.go
internal/oci/annotations.go
internal/oci/uvm.go
pkg/annotations/annotations.go
pkg/securitypolicy/opts.go
pkg/securitypolicy/securitypolicy.go
pkg/securitypolicy/securitypolicyenforcer.go
test/cri-containerd/policy_test.go

Previously SECURITY_POLICY env var was set for container init process
only when StandardSecurityPolicyEnforcer was in use, however the
environment variable is useful even with OpenDoor enforcer.
Address this gap by updating enforcers and adding an accessor
method.
The `SECURITY_POLICY` environment variable will be set only when
the appropriate annotation says so:
`"io.microsoft.virtualmachine.lcow.securitypolicy.env"`

Always set SECURITY_POLICY env var, even for open door policy.

---

internal/jobobject/jobobject.go
internal/jobobject/jobobject_test.go
internal/winapi/jobobject.go

We don't set the silo field on Open of an existing job object today.
This is useful if once opening a job we want to bind a file that only
that silo can see as it relies on atomically checking the `silo` u32
field to determine if we can carry out the operation.
The manner in which we check if the job is a silo is by using a new
jobobject information class with QueryInformationJobObject that fails
unless the job is a silo.

Correctly set silo field when opening job object

---

internal/jobobject/iocp.go
internal/jobobject/jobobject.go
internal/queue/mq.go
internal/queue/queue_test.go

Given our use cases for this package, we don't need methods that don't block
on reads if there's no value to be read. Due to this, I've removed the
ReadOrWait function and did a small redesign of the methods to be more
in line with standard queue method naming.
* Change Read/Write/IsEmpty to Dequeue/Enqueue/Size and remove ReadOrWait.
Now there is no version of Read/Dequeue that doesn't block if the queue
is empty.
* Fix up tests to be in line with this removal of the non-blocking read
and simplified most of the tests.

Rework /internal/queue package

---

internal/jobcontainers/jobcontainer.go
internal/jobcontainers/mounts.go
internal/jobcontainers/storage.go
internal/layers/layers.go

In beta, mounts couldn't be unique per silo so they were mounted
to a relative path under the rootfs for the container. There's a
bunch of pod specs/apps floating around that were written with that
in mind so as to make a smooth transition, additionally keep mounting
them under the rootfs for now via the same approach (symlink the dir/file).

Backwards compat for hostprocess cntrs mounts

---

cmd/containerd-shim-runhcs-v1/pod.go
internal/oci/sandbox.go

This changes adds in a way for annotations specified for a sandbox
container to be passed through to every container in the pod.
K8s only passes annotations to the RunPodSandbox call and not to individual
containers unfortunately. To accomplish this I cache the pod sandboxes OCI
spec on the pod object as well as expose a method that passes through
specific annotations from the pod spec through to an individual containers.
This is useful for a couple of host process containers annotations, like
microsoft.com/hostprocess-rootfs-location which specifies a non-default
path for the rootfs of the container to show up at.

Add annotations passthrough for host process containers

---

internal/jobcontainers/jobcontainer.go
internal/jobobject/jobobject.go
internal/jobobject/jobobject_test.go

HCS enables this to get more in depth IO stats for the silo of the
container, and is what is returned when asking for stats for the container. 
I'd swapped hostprocess containers to querying for these stats, but without 
the prerequisite of actually enabling them :)
This change adds a new option on jobobject.Options{} to enable this
functionality and adds a new test to ensure we can actually call
StorageStats now (It would return Element Not Found previously).

Add IO tracking option for job objects

---

internal/jobobject/jobobject_test.go

Two tests added recently by yours truly don't need to be running as
silos so remove the silo field set to true. Was running into this when
trying to backport a fix to a branch that doesn't have the silo work.

Remove uneccessary use of silos in jobobject tests

---

internal/uvm/vpmem_mapped.go

When using VPMem multi-mapping feature, we can end up in a
situation when a VHD at offset 0 is not the last VHD that
is being removed:
1. Add the very first VHD (vhd1) and essentially VPMem
(vpmem1) device itself will add the vhd1 at offset `0`.
Mapped VHD count: `1`
2. Add second VHD (vhd2), which be mapped at offset `N`.
Mapped VHD count: `2`
3. Remove vhd1 at offset `0`. Mapped VHD count: `1`
4. Try removing vhd2 will result in removing the VPMem
device itself, however, HCS API doesn't allow that.
Which is most likely a bug. Removing VPMem with 0
mapped VHDs also doesn't work.
As a work-around, keep the VPMem "intact" and just remove the
last mapped VHD. The VPMem can still be used later to map new
VHDs.

VPMem device unmap VHD, don't remove VPMem itself.

---

internal/jobcontainers/jobcontainer.go
internal/jobobject/iocp.go
internal/jobobject/jobobject.go
internal/jobobject/jobobject_test.go
internal/jobobject/limits.go
internal/queue/mq.go
internal/queue/queue_test.go
internal/winapi/jobobject.go
internal/winapi/process.go
internal/winapi/system.go
internal/winapi/zsyscall_windows.go
test/cri-containerd/jobcontainer_test.go
test/vendor/github.com/Microsoft/hcsshim/internal/jobobject/iocp.go
test/vendor/github.com/Microsoft/hcsshim/internal/jobobject/jobobject.go
test/vendor/github.com/Microsoft/hcsshim/internal/jobobject/limits.go
test/vendor/github.com/Microsoft/hcsshim/internal/queue/mq.go
test/vendor/github.com/Microsoft/hcsshim/internal/winapi/jobobject.go
test/vendor/github.com/Microsoft/hcsshim/internal/winapi/process.go
test/vendor/github.com/Microsoft/hcsshim/internal/winapi/system.go
test/vendor/github.com/Microsoft/hcsshim/internal/winapi/zsyscall_windows.go

This change brings a fix to make storage stats work for hostprocess containers, as well as some additional fixes to jobobjects/hpc along the way in the commit history. 
Commits cped:
1. 1154e47f9766102d3ffca283acf01bf28f8331ad
2. 52a4ea99865dd097d1c963e94bd7cfb14b5b8c96
3. 7fbb79f823aa5a039d6329501accc0b2c92a91d3
4. 566e3b0f89b2c769fc874ea3cc2a33ac5423ab08
5. f29964fb18afcd85c561494c04a8e797a1fdf2fd
6. 014849a4b0dcf88831921f34ba751b0400716203
7. 9d05b5b66d4cc3e678b4cd87b50a54977820101c
And one additional commit to vendor everything in test as release/0.9 still has the test vendor directory.

[release/0.9] Backport hostprocess fixes 

---

internal/jobcontainers/jobcontainer.go

A large use case for these containers is to get a shell onto a node or
to carry out administrative tasks via powershell commands, but a lot
of images have a PATH defined in the docker file that only includes system32.
Before any sort of slim image is available for these that doesn't have a
PATH set (so it will just use the hosts) add in powershell and the system32/wbem
dir for wmic to alleviate some "what is going on" moments. Additionally
rearrange some code closer together that was a bit too spread for no reason.

Add powershell to hostprocess container paths

---

pkg/securitypolicy/securitypolicy_test.go
pkg/securitypolicy/securitypolicyenforcer.go

Fix an issue when the same mount target could have different hashes
during device mount policy enforcement.
Although it's possible to mount different devices at the same mount
location, this doesn't make sense for read-only container layers.
The device mount enforcement logic has been updated to cover this
case.
This was discovered by randomized security policy unit tests.
The tests have been updated, to minimize the chance of it happening
by adding a minimal length for a random string and appropriate unit
test has been added to cover the change.

enforcement: fix use case when the same target has different hashes

---

computestorage/format.go
computestorage/setup.go

This change reverts commit https://github.com/microsoft/hcsshim/commit/aaf5db90ef6961e767a4d5ca4bcf7f1f6465bcca.
We'd added a change to FormatWritableLayerVhd to help the caller work around
a breaking change in the OS, but this would actually cause a breaking change
in our wrapper of it if the caller was already working around the issue
themselves. To avoid this scenario, revert the commit that added the
"friendly" behavior.
This additionally adds a comment on our wrapper of HcsFormatWritableLayerVhd to describe that
it expects a different handle on anything above ws2019 and adds a comment above SetupBaseOSVolume 
stating what build it's supported on.

Remove osversion usage in computestorage APIs

---

internal/hcs/system.go

I didn't reassign the logEntry that contained the error reason if
querying for stats in the shim failed

Properly assign logrus entry for fallback queries

---

internal/uvm/scsi.go

addSCSI currently uses a mutex only to check if a disk is already attached to the UVM. However, no mutex is
held when actually attaching the disk to the UVM. Because of this if two goroutines try to add the same SCSI
disk to a UVM at the same time, one of them will see that the disk is not already attached, will add an entry
into the controller/LUN map and continue with the attach process. The other goroutine will just see the entry
in the map and returns thinking that the SCSI disk is already attached to the UVM. At this point the disk
attach operation from the first goroutine is still in progress so if the second goroutine tries to use that
disk inside the UVM it fails with cryptic errors from overlayfs (or whatever other component in the guest that
tries to use this disk).
To get …

Fix a race condition in add SCSI workflow

---

internal/hcs/system.go

The only two methods on a compute system that didn't short circuit if the system was already closed were Properties and PropertiesV2.

Short circuit Properties calls if NULL handle

---

Makefile
cmd/containerd-shim-runhcs-v1/pod.go
internal/guest/runtime/hcsv2/uvm.go
internal/oci/uvm.go
internal/protocol/guestresource/resources.go
internal/tools/uvmboot/lcow.go
internal/uvm/create_lcow.go
internal/uvm/security_policy.go
pkg/annotations/annotations.go
pkg/securitypolicy/securitypolicy.go
pkg/securitypolicy/securitypolicyenforcer.go
pkg/securitypolicy/securitypolicyenforcer_rego.go
test/go.sum

Add enforcer registration logic and support for default enforcer.
The host can request which security policy enforcer to use with
supplied policy, if none supplied, GCS code tries to make a "guess"
as to which enforcer should be used: "allow all" or "default".
Default enforcer is set to `StandardSecurityPolicyEnforcer` unless
GCS is built with "rego" tag present. In that case, the default
enforcer will be set to `RegoEnforcer`.
New annotation has been added that allows callers to pick which
enforcer to use, e.g.
```pod.json
{
...
"annotations": {
"io.microsoft.virtualmachine.lcow.enforcer": "rego"
},
...
}
```

securitypolicy: add security policy enforcer registration and defaults

---

internal/guest/runtime/hcsv2/uvm.go
internal/guest/storage/test/policy/mountmonitoringsecuritypolicyenforcer.go
internal/tools/securitypolicy/README.md
internal/tools/securitypolicy/helpers/helpers.go
pkg/securitypolicy/opts.go
pkg/securitypolicy/securitypolicy.go
pkg/securitypolicy/securitypolicyenforcer.go
test/cri-containerd/policy_test.go

Wait mounts was originally added as a synchronization mechanic that
allows to build dependencies between containers via security policy.
Some issues:
- Only available via policy so, you can't use in a non-confidential scenario
- Mixes configuration into policy enforcement
- Completely bespoke
With our moving to a rego based policy engine, we've decided to stop doing
anything that is "include configuration in policy" and instead switch to
"policy controls if a bit of configuration is allowed to be changed". This
approach eliminates wait mounts as a possibility to move over even if we
decided that the issues listed above weren't problematic.
We expect that any customer using wait mounts functionality via policy
will switch to handling dependencies amongst containers as they usually
would. …

Remove wait mounts functionality

---

internal/guest/prot/protocol.go
internal/guest/runtime/hcsv2/uvm.go

When adding multiple enforcer support in https://github.com/microsoft/hcsshim/pull/1476
I forgot to update the unmarshal code accordingly.

fix unmarshaling of LCOWSecurityPolicyEnforcer

---

cmd/containerd-shim-runhcs-v1/task_hcs.go

We were logging if HcsShutdownComputeSystem failed, but we weren't
trying to force kill the container via Terminate after if we timed
out waiting for it to complete. Shutdown is async and we wait for
a notification for success, so most of the time the call itself will
return nil, but it doesn't indicate indicate success until we can
see that the system exited. So now we will fallback to Terminate for:
1. Shutdown returning an error that doesn't indicate the result is
to be waited on.
2. The async result of shutdown was non-nil
3. Waiting for the result passed the timeout we set.

Call container.Terminate() on shutdown timeouts

---

cmd/containerd-shim-runhcs-v1/pod.go
cmd/containerd-shim-runhcs-v1/pod_test.go
cmd/containerd-shim-runhcs-v1/service.go
cmd/containerd-shim-runhcs-v1/service_internal.go
cmd/containerd-shim-runhcs-v1/task.go
cmd/containerd-shim-runhcs-v1/task_hcs.go
cmd/containerd-shim-runhcs-v1/task_test.go
cmd/containerd-shim-runhcs-v1/task_wcow_podsandbox.go
cmd/shimdiag/shimdiag.go
cmd/shimdiag/tasks.go
internal/shimdiag/shimdiag.pb.go
internal/shimdiag/shimdiag.proto

This command prints the tasks that are currently being managed
by a given shim instance, and optionally the execs in each task.
There've been a couple times where our shim and containerd have
seemingly disagreed on what tasks are still running.. This should
make it easy to see the state of the world from our shims point
of view.
Example output:
```
PS C:\cplat> .\shimdiag.exe tasks -execs k8s
07f437749e5cd32534b8eef2eeb8eb3bf9fdfaacb9085b5b8ff4a281c48b87ab
|
|---->  running: 07f437749e5cd32534b8eef2eeb8eb3bf9fdfaacb9085b5b8ff4a281c48b87ab
3307379237a87b9a1243f83ea3ba933d1f48dffc4186dd697f5ab73589f7cda4
|
|---->  running: 9bbb5a3bd36ef4e8db0531f5bdbef9def01b782f5ac916f5d5737632834e32af
running: 7492e558a89d4f5ff10442112d93e92f26593671497878f7d431fdf0988144a0
```

Add Tasks command to shimdiag

---

internal/jobcontainers/mounts.go
internal/jobobject/jobobject.go

Add in ability to parse read only mount options for hostprocess mounts.
Change the API of ApplyFileBinding to take in a readOnly bool instead of
it signifying a merged binding. We don't have any use for merged bindings
as the default for containers is to shadow the directory we're binding
to. We could alternatively pass in a set of options/flags as this argument,
but readonly seems to be the only thing needed as of now.

Readonly option for hostprocess mounts

---

internal/guest/runtime/hcsv2/uvm.go
internal/tools/securitypolicy/main.go
pkg/securitypolicy/framework.rego
pkg/securitypolicy/open_door.rego
pkg/securitypolicy/policy.rego
pkg/securitypolicy/regopolicy_test.go
pkg/securitypolicy/securitypolicy.go
pkg/securitypolicy/securitypolicy_internal.go
pkg/securitypolicy/securitypolicy_marshal.go
pkg/securitypolicy/securitypolicyenforcer.go
pkg/securitypolicy/securitypolicyenforcer_rego.go
test/cri-containerd/policy_test.go

Refactors (due to build tags):
- Internal classes (needed for Rego marshaling) moved to `securitypolicy_internal.go`
- Marshal code (needed for Rego marshaling) moved to `securitypolicy_marshal.go`. Once the JSON input/output is removed, this code can safely be moved to the `securitypolicy` tool
- Rego error logic has been moved to `framework.rego`
- `open_door.rego` added as Rego alternative to OpenDoor, and the `allow_all` logic has been removed from `policy.rego`
New Features:
- `MarshalPolicy` method which supports turning a policy into either JSON or Rego
- `securitypolicy` now takes a `t` parameter that can be equal to either `rego` or `json` and a `r` parameter which indicates whether it should output the raw output in addition to the base64 encoded policy
- `createRegoEnforcer` …

Add support for accepting Rego policy code.

---

internal/uvm/scsi.go

The new change that we added to fix a race condition in addSCSI introduced a bug where the code ends up accessing a
nil pointer in certain situations. For example, the deferred function to unblock any waiters of the attach
SCSI operation accesses the scsi mount object to propagate any errors. However, this pointer is a named return
value of the function and is set to `nil` when returning an error. In those cases the deferred function panics
with the nil pointer dereference error. To fix this we don't use the named return value for the scsi mount
object anymore.
This change also removes the check for zero SCSI controllers since that check is done by the
`allocateSCSIMount` function.

Fix nil pointer dereference in addSCSI

---

.github/workflows/ci.yml
.golangci.yml
pkg/securitypolicy/securitypolicy_test.go

Pipeline does not check that `./test/go.mod` is up to date, which can cause issues with linting and other stages.
Combined verifying `test/go.mod` and `./go.mod` into one stage. Simplified the job ordering to increase the number of possible parallel runs.
Removed `build_gcs` dependence on vendoring stage, since that is subsumed by `test-linux`.
Removed `build_gcs` and `build` dependence on `integration-tests`, since those fail frequently and ideally integration testing requires successfully building executables.

Add step to check test/go.mod, updated test/go.mod

---

pkg/securitypolicy/api.rego
pkg/securitypolicy/policy.rego
pkg/securitypolicy/regopolicy_test.go
pkg/securitypolicy/securitypolicy_test.go
pkg/securitypolicy/securitypolicyenforcer_rego.go

Adds versioning to the framework (and policies) to enable backwards compatibility and fine-tuned behavioral logic based upon version comparisons. Every enforcement point will now be explicitly linked to a minimum version and given a default behavior (allow/not allow) which should be applied automatically below that version. The logic looks like this:
```go
func (policy *regoEnforcer) allowed(enforcementPoint string, input map[string]interface{}) (bool, error) {
results, err := policy.Query(enforcementPoint, input)
if err != nil {
// Rego execution error
return false, err
}
if len(results) == 0 {
// rule was undefined
available, err := policy.enforcementPoints.isAvailableByVersion(enforcementPoint, policy.versionInfo)
if err != nil {
// unknown rule
return false, err
}
if available {
// …
```

Add enforcement versioning to rego enforcer 

---

pkg/securitypolicy/api.rego
pkg/securitypolicy/api_test.rego
pkg/securitypolicy/framework.rego
pkg/securitypolicy/regopolicy_test.go
pkg/securitypolicy/securitypolicyenforcer_rego.go

This PR moves the API test fixtures to a separate `api_test.rego` file. In order to avoid code duplication, the logic to check enforcement point information was moved to the framework. This PR also addresses some whitespace issues that crept into the Rego files.

Moving rego api test fixtures to a separate file

---

pkg/securitypolicy/securitypolicyenforcer_rego.go

Returning OpenDoorSecurityPolicyEnforcer (when appropriate) for Rego policies. This change reverts an unintended behaviour change when calling `CreateSecurityPolicyEnforcer` with:
1. `enforcer = ""` indicating to use the default (which, with the `rego` build tag, will be `rego`)
2. `base64EncodedPolicy` = a JSON policy with `AllowAll=True` and no containers
3. Empty default and privileged mounts
In the past this would have produced an `OpenDoorSecurityPolicyEnforcer` but after the change to accept authored Rego policies, it would produce a `RegoEnforcer` with an allow all policy (which allows all enforcement points). There are changes in the pipe which will make a `RegoEnforcer` created in this way have the same properties as `OpenDoorSecurityPolicyEnforcer`, but for the time being this …

Open Door fix for Rego policies

---

cmd/containerd-shim-runhcs-v1/pod.go
internal/guest/prot/protocol.go
internal/guest/runtime/hcsv2/uvm.go
internal/oci/uvm.go
internal/protocol/guestresource/resources.go
internal/tools/uvmboot/lcow.go
internal/uvm/create_lcow.go
internal/uvm/security_policy.go
pkg/annotations/annotations.go
test/cri-containerd/policy_test.go
test/internal/uvm/lcow.go

Workload containers need to be aware of the reference UVM measurement
they are currently running on. The expectation is that the signed UVM
measurement file will be a part of the package and located in the
same directory as the rest of the boot files (e.g. kernel, initrd
or VMGS). The file itself is a COSE_Sign1 document containing the
measurement and related information.
The content of the file will be plumbed to the UVM as
part of setting the security policy request and can later be
presented to the containers via an environment variable.

Set HCSSHIM_UVM_REFERENCE_INFO env for workload containers

---

cmd/containerd-shim-runhcs-v1/task.go
cmd/containerd-shim-runhcs-v1/task_hcs.go
cmd/containerd-shim-runhcs-v1/task_wcow_podsandbox.go
internal/guest/prot/protocol.go
internal/guest/runtime/hcsv2/uvm.go
internal/protocol/guestresource/resources.go
internal/uvm/security_policy.go
internal/uvm/update_uvm.go
pkg/ctrdtaskapi/update.go
test/functional/uvm_update_test.go

Add new typeurl registered data structure to represent
additional security policy constraint fragments, which
can be passed as part of shim's task Update request.
Change behavior of UpdateContainerConstraints to return
an error when an invalid resource is passed.
Make sure hcsshim can consume the new resource as part
of task Update request handling and new GCS protocol
message can be properly accepted by the guest.

Add new `ctrdtaskapi` package for shim task API support.

---

pkg/securitypolicy/securitypolicyenforcer.go

I did an automated refactoring a while ago and it left to unused methods hanging around when enforce mount logic was moved into create container enforcement logic.

Remove unused open/closed door enforcement methods

---

pkg/securitypolicy/api.rego
pkg/securitypolicy/framework.rego
pkg/securitypolicy/regopolicy_test.go
pkg/securitypolicy/securitypolicy.go
pkg/securitypolicy/securitypolicy_marshal.go
pkg/securitypolicy/securitypolicy_test.go

If an environment variable rule is marked as "required", then it must be defined in the container. This is enforced in the Rego in the following way:
``` rego
env_ok(pattern, "string", value) {
pattern == value
}
env_ok(pattern, "re2", value) {
regex.match(pattern, value)
}
rule_ok(rule, env) {
not rule.required
}
rule_ok(rule, env) {
rule.required
env_ok(rule.pattern, rule.strategy, env)
}
envList_ok(container) {
every env in input.envList {
some rule in container.env_rules
env_ok(rule.pattern, rule.strategy, env)
}
every rule in container.env_rules {
some env in input.envList
rule_ok(rule, env)
}
}
```
Signed-off-by: Matthew A Johnson <matjoh@microsoft.com>

Adding required environment variable rules logic.

---

pkg/securitypolicy/regopolicy_test.go
pkg/securitypolicy/securitypolicy_test.go

We are seeding the `testRand` module level variable. However, testing/quick was not set to use that seeded random number generator. The testing/quick configuration has a field `Rand` which is not set, will result in a random number generator being created and used. This created generator hasn't been seeded so our seeding had no impact on any of our `Generate` functions.
This commit updates all testing/quick tests to initialize `Rand` in the configuration to be set to our seeded `testRand`.

Fix seeding for generative policy tests

---

internal/guest/bridge/bridge_v2.go
internal/guest/runtime/hcsv2/uvm.go
internal/guest/storage/test/policy/mountmonitoringsecuritypolicyenforcer.go
internal/tools/securitypolicy/helpers/helpers.go
pkg/securitypolicy/api.rego
pkg/securitypolicy/framework.rego
pkg/securitypolicy/open_door.rego
pkg/securitypolicy/policy.rego
pkg/securitypolicy/regopolicy_test.go
pkg/securitypolicy/securitypolicy.go
pkg/securitypolicy/securitypolicy_internal.go
pkg/securitypolicy/securitypolicy_marshal.go
pkg/securitypolicy/securitypolicy_test.go
pkg/securitypolicy/securitypolicyenforcer.go
pkg/securitypolicy/securitypolicyenforcer_rego.go

This commit adds the `exec_in_container` enforcement point, but as part of this change we must also perform a refactoring of the framework to enable supporting this and other additional enforcement points which come _after_ creating a container. Due to the number of possible matches and the way in which each subsequent enforcement point narrows the list of matches, we need to maintain for each container ID a list of potentially matching containers.
As part of making this change to the framework, we took the opportunity to build a more flexible system for a policy to store data for use in evaluating later rules. This has the beneficial side effect of removing more policy logic from the Go code while also creating a far more powerful and flexible system for policy authoring.
Before, a …

Adding the `exec_in_container` enforcement point

---

cmd/containerd-shim-runhcs-v1/task.go
hcsshim.go
internal/gcs/bridge.go
internal/hcs/errors.go
internal/hcs/errors_test.go
internal/hcserror/hcserror.go
internal/uvm/start.go

Add `.Is(` and `.Unwrap(` to `internal\hcs\errors.go` and `internal\gcs\bridge.go` to using them with `errors.Is(` and `errors.As(`

Update hcs errors to gov1.13 style

---

test/cri-containerd/container_test.go
test/cri-containerd/main_test.go
test/cri-containerd/policy_test.go

Occasionally we've started seeing issues with docker rate limiting image pulls when running cri-containerd tests locally. Switch to MSFT mirrors.

Use alpine and pause images from MSFT mirrors in tests

---

internal/guest/runtime/hcsv2/uvm.go
pkg/annotations/annotations.go
test/cri-containerd/policy_test.go

Make sure the naming of security policy and uvm reference env vars are consistent. Drop `HCSSHIM_` prefix and use `UVM_` instead. The env vars now become `UVM_SECURITY_POLICY` and `UVM_REFERENCE_INFO`.

update security policy and uvm reference env var names

---

internal/guest/bridge/bridge_v2.go
internal/guest/runtime/hcsv2/uvm.go
internal/guest/storage/test/policy/mountmonitoringsecuritypolicyenforcer.go
pkg/securitypolicy/api.rego
pkg/securitypolicy/framework.rego
pkg/securitypolicy/open_door.rego
pkg/securitypolicy/policy.rego
pkg/securitypolicy/regopolicy_test.go
pkg/securitypolicy/securitypolicyenforcer.go
pkg/securitypolicy/securitypolicyenforcer_rego.go

Adds policy enforcement around shutting down a container. In the supplied framework, shutting down a container is always allowed. We update metadata based on the change in state that will be used by other framework rules. This enforcement point is important for custom policies for metadata tracking and also for allowing the creation of rules like "this container isn't allowed to shutdown if some other container is running".
This commit rewrites `signalContainerV2` and gives it a new name. `signalContainerV2` was only called from the kill and shutdown container functions. Despite only having 2 possible signals it could receive, it accepted any signal. There's a replacement method called `signalContainerShutdownV2` that has "the same functionality" as `signalContainerV2`. …

Add policy enforcement for shutting down a container

---

pkg/securitypolicy/securitypolicyenforcer.go

For the "layerPaths... " message, adding the root cause of the error to be displayed to the user in addition to the symptom of the failure.

Update policy enforcer overlay error message to be more descriptive

---

internal/guest/runtime/hcsv2/uvm.go

Fixes GCS panic, because OCIProcess for exec external is nil.
For exec external process we don't use OCIProcess field of ProcessParameters, but instead use the top level CommandArgs, Environment and WorkingDirectory.

fix wrong parameters passed to EnforceExecExternalProcessPolicy

---

cmd/containerd-shim-runhcs-v1/pod.go
internal/guest/runtime/hcsv2/uvm.go
internal/oci/uvm.go
internal/protocol/guestresource/resources.go
internal/uvm/create_lcow.go
internal/uvm/security_policy.go
pkg/annotations/annotations.go
test/gcs/main_test.go

In general case the fragment injection will happen via sandbox task update request. However, we may need to inject fragments before the pod is created and ready to accept the update request. One of the examples is the pause container, which holds the pod network namespace.
This PR addresses this issue by adding functionality to read an arbitrary security policy fragment from UVM's file system. The assumption is that the fragment will be embedded into the UVM and the path will be supplied as part of confidential UVM options together with security policy and UVM reference.
The actual calling into fragment validation and injection could be changed in the future.

Add pod startup security policy fragment injection

---

cmd/runhcs/create-scratch.go
cmd/runhcs/prepare-disk.go
cmd/runhcs/vm.go
internal/guest/runtime/hcsv2/uvm.go
pkg/securitypolicy/securitypolicyenforcer.go
test/cri-containerd/runpodsandbox_test.go
test/internal/uvm/lcow.go

`runhcs` subcommands were missing a call to `SetConfidentialUVMOptions` after the uVM has been booted. This results in closed door policy to be set for all UVM operations, including (now) execs into UVM. Previously the exec would succeed, UVM exited and we had our scratch.
Additionally GCS has been updated to set the policy to "open door" when both enforcer and security policy options are empty.

fix create-scratch and other `runhcs` subucommands

---

pkg/securitypolicy/securitypolicy.go

The `ExecProcesses` and `Signals` fields on `Container`, which are needed for newly added enforcement points, were not being ignored during JSON marshalling. These values should not be included in the marshalled object because the new enforcement points that require them are not implemented for the `StandardSecurityPolicyEnforcer` which uses the JSON representation for policies.

Ignoring unneeded fields in JSON policy marshalling.

---

cmd/containerd-shim-runhcs-v1/pod.go
cmd/runhcs/create-scratch.go
cmd/runhcs/prepare-disk.go
cmd/runhcs/vm.go
internal/tools/uvmboot/lcow.go
internal/uvm/create_lcow.go
internal/uvm/start.go
internal/uvm/types.go
test/cri-containerd/runpodsandbox_test.go
test/functional/lcow_container_bench_test.go
test/functional/lcow_container_test.go
test/functional/uvm_plannine_test.go
test/internal/uvm/lcow.go

To make the interface cleaner for cases when security policy isn't required, call to `SetConfidentialUVMOptions` within `Start`. When no enforcer or policy are supplied GCS will initialize an open door enforcer.
UtilityVM object now holds the confidential options to use them during `Start`.
By default the UVM reference is expected to be located at the directory as the shim executable rather than under linux boot files. This has been done to avoid holding this information on the UVM object.
`uvmboot` has been updated to take a `security-policy-enforcer` parameter.

set confidential UVM options during UVM start

---

internal/guest/runtime/hcsv2/uvm.go
internal/guest/storage/overlay/overlay.go
internal/guest/storage/overlay/overlay_test.go
pkg/securitypolicy/api.rego
pkg/securitypolicy/framework.rego
pkg/securitypolicy/open_door.rego
pkg/securitypolicy/policy.rego
pkg/securitypolicy/regopolicy_test.go
pkg/securitypolicy/securitypolicy_test.go
pkg/securitypolicy/securitypolicyenforcer.go
pkg/securitypolicy/securitypolicyenforcer_rego.go
test/gcs/helper_container_test.go

We previously weren't doing any enforcement around whether an overlay should be allowed to be unmounted. The initial logic is very simple and matches our device unmounting logic:
only allow an unmount if we've seen a mount.
When we get to the hardening PRs, we'll want to revisit this basic rule and decide if we want to make it more vigorous in policy or if we want to put all hardening in GCS or some mixture in-between. That's a design discussion we'll need to have.

Add policy enforcement for overlay unmounting

---

internal/guest/bridge/bridge_v2.go
internal/guest/runtime/hcsv2/uvm.go
internal/tools/securitypolicy/main.go
pkg/securitypolicy/api.rego
pkg/securitypolicy/framework.rego
pkg/securitypolicy/open_door.rego
pkg/securitypolicy/policy.rego
pkg/securitypolicy/regopolicy_test.go
pkg/securitypolicy/securitypolicy.go
pkg/securitypolicy/securitypolicy_internal.go
pkg/securitypolicy/securitypolicy_marshal.go
pkg/securitypolicy/securitypolicy_test.go
pkg/securitypolicy/securitypolicyenforcer.go
pkg/securitypolicy/securitypolicyenforcer_rego.go
test/cri-containerd/policy_test.go

GetProperties allows getting information about what is running. This is related to debugging etc. This gates it with a simple yes/no for policy. This might be used for getting stats.

Adding GetProperties policy enforcement point.

---

internal/guest/bridge/bridge_v2.go
internal/guest/runtime/hcsv2/uvm.go
internal/tools/securitypolicy/main.go
pkg/securitypolicy/api.rego
pkg/securitypolicy/framework.rego
pkg/securitypolicy/open_door.rego
pkg/securitypolicy/policy.rego
pkg/securitypolicy/regopolicy_test.go
pkg/securitypolicy/securitypolicy.go
pkg/securitypolicy/securitypolicy_internal.go
pkg/securitypolicy/securitypolicy_marshal.go
pkg/securitypolicy/securitypolicy_test.go
pkg/securitypolicy/securitypolicyenforcer.go
pkg/securitypolicy/securitypolicyenforcer_rego.go
test/cri-containerd/policy_test.go

DumpStacks allows access to guest stacks. Can be used for debugging etc. This gates it with a simple yes/no for policy.

Adding DumpStacks policy enforcement point.

---

cmd/gcs/main.go
internal/guest/runtime/hcsv2/uvm.go
internal/tools/securitypolicy/main.go
pkg/securitypolicy/api.rego
pkg/securitypolicy/framework.rego
pkg/securitypolicy/open_door.rego
pkg/securitypolicy/policy.rego
pkg/securitypolicy/regopolicy_test.go
pkg/securitypolicy/securitypolicy.go
pkg/securitypolicy/securitypolicy_internal.go
pkg/securitypolicy/securitypolicy_marshal.go
pkg/securitypolicy/securitypolicy_test.go
pkg/securitypolicy/securitypolicyenforcer.go
pkg/securitypolicy/securitypolicyenforcer_rego.go
test/cri-containerd/policy_test.go
test/gcs/main_test.go

In order to provide a confidential environment for confidential containers, we need to provide a means for customers to control information that will leave the UVM running their code. A key means for information to leave the UVM is via logging.
There's no guarantee that logging will leak information that the customer considers confidential. There's no guarantee that it won't. To address this issue, we are adding 2 additional enforcement points for policy related to logging.
The first, which is this commit, is to allow control over logging coming from GCS itself. The second which will come in another commit is to allow control over logging from containers.
For GCS logging, we have exposed it in policy as the name "runtime logging" as we don't feel that "GCS" will be particularly meaningful …

Add enforcement of logging from the GCS runtime

---

.github/workflows/ci.yml
go.mod
go.sum
internal/tools/securitypolicy/README.md
internal/tools/securitypolicy/main.go
pkg/securitypolicy/api.rego
pkg/securitypolicy/framework.rego
pkg/securitypolicy/open_door.rego
pkg/securitypolicy/policy.rego
pkg/securitypolicy/regopolicy_test.go
pkg/securitypolicy/securitypolicy.go
pkg/securitypolicy/securitypolicy_internal.go
pkg/securitypolicy/securitypolicy_marshal.go
pkg/securitypolicy/securitypolicy_test.go
pkg/securitypolicy/securitypolicyenforcer.go
pkg/securitypolicy/securitypolicyenforcer_rego.go
test/cri-containerd/policy_test.go
test/go.sum
vendor/github.com/blang/semver/v4/LICENSE
vendor/github.com/blang/semver/v4/json.go
vendor/github.com/blang/semver/v4/range.go
vendor/github.com/blang/semver/v4/semver.go
vendor/github.com/blang/semver/v4/sort.go
vendor/github.com/blang/semver/v4/sql.go
vendor/modules.txt

This PR adds the ability for an authored security policy to be expanded at runtime with policy fragments. It focuses purely on the policy enforcement aspect, which assumes that the fragments which the guest is asking to load have been verified to have been obtained from the issuer and feed specified.
The `load_fragment` enforcement point takes an input with the following members:
``` json
{
"issuer": "<identifier for the issuer>",
"feed": "<feed endpoint>"
}
```
Also, for the purpose of this call, the fragment is loaded as a module. The result is of the form:
``` json
{
"allowed": true
"add_module": true
}
```
If the value of `add_module` is `true`, then the fragment will continue to be loaded as a module for all future executions.
In the case that the authored security policy uses the …

Adding policy fragments.

---

internal/guest/network/netns.go
internal/guest/prot/protocol.go
internal/guest/runtime/hcsv2/network.go
internal/protocol/guestresource/resources.go
internal/uvm/network.go
test/functional/lcow_networking_test.go

Currently, HCN endpoint IPv6 settings are not passed into the Linux guest, so containers will not be assigned the v6 addresses that the host endpoint has.
This PR updates the shim to forward IPv6 information to the guest, updates the guest to assign both v4 and v6 addresses, if they are present, and adds tests for ipv6 functionality.

Pass ipv6 address information to Linux GCS

---

cmd/gcs/main.go

logrus uses `os.Stderr` by default, so setting output to `os.Stdout` resulted in no GCS logs being relayed.

Change the default policy stance to "allow" and fix logging

---

.github/workflows/ci.yml
internal/hcs/errors.go
test/vendor/github.com/Microsoft/hcsshim/internal/hcs/errors.go

Addresses CI build break in https://github.com/microsoft/hcsshim/pull/1554 that was caused by the pipeline automatically choosing golang 1.19. Instead, use golang 1.18.x.

Fix all go installations in the CI to the same version

---

cmd/containerd-shim-runhcs-v1/task_hcs.go

Call container.Terminate() on shutdown timeouts
(cherry picked from commit cae120b42536adea72101e6a358183c74a0bdac5)

[release/0.9] Call container.Terminate() on shutdown timeouts

---

internal/guest/runtime/hcsv2/uvm.go
internal/guest/runtime/hcsv2/uvm_state.go
internal/guest/runtime/hcsv2/uvm_state_test.go
internal/guest/storage/crypt/crypt.go
internal/guest/storage/crypt/crypt_test.go
internal/guest/storage/crypt/utilities.go
internal/guest/storage/overlay/overlay.go
internal/guest/storage/overlay/overlay_test.go
internal/guest/storage/scsi/scsi.go
internal/guest/storage/scsi/scsi_test.go
internal/tools/securitypolicy/main.go
pkg/securitypolicy/api.rego
pkg/securitypolicy/framework.rego
pkg/securitypolicy/policy.rego
pkg/securitypolicy/regopolicy_test.go
pkg/securitypolicy/securitypolicy.go
pkg/securitypolicy/securitypolicy_internal.go
pkg/securitypolicy/securitypolicy_marshal.go
pkg/securitypolicy/securitypolicy_test.go
pkg/securitypolicy/securitypolicyenforcer.go
pkg/securitypolicy/securitypolicyenforcer_rego.go
test/cri-containerd/main_test.go
test/cri-containerd/policy_test.go
test/gcs/helper_container_test.go

rego and hardening: add enforcement and hardening for encrypted scratch
The request to encrypt scratch comes from the host, but in confidential
scenario, the host cannot be trusted and it may attempt to mount the
read-write overlay of a container under an unencrypted path or omit the
encryption request altogether.
To address the issue, add `scratch_mount`, `scratch_unmount` enforcement
points and `allow_unencrypted_scratch` policy config, which can be used
to (you guessed it) allow containers to run with unencrypted scratch.
Since the request to add encrypted read-write scratch disk and mounting
container overlayfs come at different times, we also introduced minimal
(for now) hardening around adding read-write devices to the UVM. We
record the mounted read-write devices when they arrive …

rego and hardening: add enforcement and hardening for encrypted scratch

---

internal/hcs/system.go
internal/hcs/waithelper.go
internal/hcsoci/resources.go
internal/uvm/create_lcow.go
internal/uvm/start.go
internal/vmcompute/vmcompute.go

`(*UtilityVM).Start` was using a potentially timed-out context for its terminate, which can cause the terminate to immediately error and not log the correct status of the operation.
Additionally `(*UtilityVM).Start` sets a 2 minute timeout on the context it ultimately passes to `"vmcompute".execute`, which silently overrides the timeout `execute` uses.
Improved logs to report correct timeout.
Spelling fix.
Shortened long lines.

uVM timeout handling and logging improvement

---

internal/uvm/start.go

`(*UtilityVM).acceptAndClose()` waits on `(*UtilityVM).exitCh`, but `exitCh` is not created until after the goroutines with the `acceptAndClose` calls are launched, causing a potential race condition.

race condition with exitCh in `(*UtilityVM).Start()`

---

test/functional/lcow_container_bench_test.go
test/functional/lcow_container_test.go
test/functional/lcow_networking_test.go
test/functional/lcow_test.go
test/functional/main_test.go
test/functional/uvm_vpmem_test.go
test/functional/wcow_test.go
test/go.mod
test/internal/containerd/containerd.go
test/internal/flag/flag.go
test/internal/layers/layerfolders.go
test/internal/layers/lazy.go
test/internal/oci/oci.go
test/internal/util/util.go
test/internal/uvm/lcow.go
test/internal/uvm/wcow.go
test/runhcs/e2e_matrix_test.go

Add lcow/wcow layer paths flag to allow providing image layer paths.
Remove dependence on containerd, and instead use github.com/google/go-containerregistry/ (which the dmverity exe uses) to download the images if none are provided.
The goal is to allow functional tests to be run without requiring containerd to be installed.

test/functional: Add flag for container layer paths, remove containerd dependence 

---

.github/workflows/ci.yml

Update `actions/checkout` and `actions/setup-go` to version 3, since the version 2 of the actions uses a deprecated version of node.js, and raises the following warning in the CI:
```
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
```

[CI] update actions version

---

test/functional/main_test.go
test/functional/uvm_update_test.go
test/gcs/main_test.go
test/go.mod
test/internal/flag/flag.go

Add flag to control logging level in functional and gcs tests (since they do not get forwarded to ETW automatically), and enable collecting spans.
Output logs to std out, so it is combined with logs and output from `testing` framework, and also consumed by `test2json` in CI pipeline. Otherwise, the output would be split in two, if the stdout and stderr of the process are not sent to the same destination (eg, if the stdout is written to a file or captured by a variable).
Additionally, redirecting stderr in powershell throws an error since powershell pipes and redirections are byte-oriented.
That is, from within powershell:
```powershell
> cmd /c "cmd /c `"echo hi >&2`" 2>&1"
hi
```
However, whenever powershell encounters data on stderr, it always raises an error:
```powershell
> powershell …
```

[test]logging and tracing to stdout

---

test/cri-containerd/containerdrestart_test.go
test/cri-containerd/main_test.go

[test]Add feature for CRI extensions

---

pkg/securitypolicy/api.rego
pkg/securitypolicy/open_door.rego
pkg/securitypolicy/policy.rego
pkg/securitypolicy/regopolicy_test.go

When encrypted scratch was added the policy and open door templates were not updated properly, i.e. the SVN was not incremented and `scratch_mount` and `scratch_unmount` were not added to the open door template. I've added a test which will keep this from happening in the future.

Adding some missing policy elements from the templates.

---

.github/dependabot.yml

Change dependebot to only check for updates on Sundays, and to ignore patch version updates (ie, `a.b.c` -> `a.b.d` will not trigger a PR).

Reduce dependabot update schedule

---

test/go.mod
test/go.sum

Keeping test module at 1.17 causes issues when running `go mod tidy`, due to incompatibilities with how go 1.17 and 1.18 resolve dependencies.
Upgrading to 1.18 resolves this.

Upgrade test module to go1.18

---

internal/guest/runtime/hcsv2/uvm.go
internal/oci/annotations.go
internal/uvm/security_policy.go
internal/uvm/start.go
pkg/annotations/annotations.go
test/cri-containerd/policy_test.go

Add logic to plumb AMD certificates to workload containers. The
assumption is that the certificates will be "fresh enough" for
necessary attestation and key release by the workflow and third
party services.

plumb AMD certs to workload containers

---

internal/hcs/process.go
internal/hcs/system.go

Add checks to `hcs.System` to prevent attempting to shutdown or terminate a compute system that has already been stopped.
The same checks could be added to other operations (eg, pause, start, resume) but it is unclear what error should be returned in those situations, so those operations are left untouched.
Add checks to `hcs.Process` to prevent attempting to kill a stopped process. 
Although `hcs.Process` differs from `hcs.System` in that the latter returns an error if the system is already stopped or closed, but the former does not.
Therefore, `(*Process).Kill` returns `ErrProcessAlreadyStopped`, which is the expected error in `(*hcsExec).Kill`.
Finally, an additional check is added to `(*Process).CloseStdin` to skip sending a modify request to the process to close stdin if the process …

Prevent operations on exited HCS objects.

---

cmd/containerd-shim-runhcs-v1/exec_hcs.go
internal/cow/cow.go
internal/gcs/container.go
internal/hcs/system.go
internal/jobcontainers/jobcontainer.go

Fixes the memory leak seen in the shim. Removes the creation of channel that waits on container exit for every new exec created.
Instead, a new function 'WaitChannel()' is added to the Container interface to expose the wait channel of a container. The caller of WaitChannel() can use the container's wait channel to decide if the container has exited or not rather than creating a new channel for every exec and blocking on container.Wait() call.

Remove blocking on container exit for every new exec created

---

cmd/containerd-shim-runhcs-v1/exec_hcs.go
internal/cow/cow.go
internal/gcs/container.go
internal/hcs/system.go
internal/jobcontainers/jobcontainer.go
test/vendor/github.com/Microsoft/hcsshim/internal/cow/cow.go
test/vendor/github.com/Microsoft/hcsshim/internal/gcs/container.go
test/vendor/github.com/Microsoft/hcsshim/internal/hcs/system.go

This PR is porting fix with commit hash 5fc00c5eeb3a6e909be65bfdb7df6e26575dd182 from hcsshim/main to hcsshim release/0.9 branch
Commit fixes the memory leak seen in the shim.
It removes creation of channel that waits on container exit for every new exec. Instead, the container wait channel is exposed through WaitChannel() function which callers can use to decide if container has exited or not.

[release/0.9] Remove blocking wait on container exit for every exec created

---

.github/workflows/ci.yml
cmd/containerd-shim-runhcs-v1/exec_hcs.go
internal/cow/cow.go
internal/gcs/container.go
internal/hcs/system.go
internal/jobcontainers/jobcontainer.go
test/vendor/github.com/Microsoft/hcsshim/internal/cow/cow.go
test/vendor/github.com/Microsoft/hcsshim/internal/gcs/container.go
test/vendor/github.com/Microsoft/hcsshim/internal/hcs/system.go

This PR ports commit 5fc00c5eeb3a6e909be65bfdb7df6e26575dd182 to release/0.8 branch
It also fixes CI to use the same version of golang and updated golangci-lint version to v1.48
Commit fixes the memory leak seen in the shim.
It removes creation of channel that waits on container exit for every new exec. Instead, the container wait channel is exposed through WaitChannel() function which callers can use to decide if container has exited or not.
(cherry picked from commit 5fc00c5eeb3a6e909be65bfdb7df6e26575dd182)

[release/0.8] Remove blocking wait on container exit for every exec created

---

internal/uvm/security_policy.go

Currently hcsshim is setting an allow all open door policy if no security policy has been provided.
On the host side, the security policy is hashed and used as HostData when starting an SNP-uVM. However, guest receives the aforementioned "open_door" policy and computes hash over it. As a result, this has doesn't match the LaunchData which is returned by the attestation report and rightfully so, GCS rejects the security policy.
Fix this by not special handling empty security policy on the host side and let the guest decide what to do with it, thus ensuring that both host and guest compute the hash over the same thing.

policy: do not set policy to open door if none is provided

---

internal/hcsoci/devices.go
internal/schemaversion/schemaversion.go
osversion/windowsbuilds.go
test/internal/constants/images.go

Add 20H2 container to testing constants for completeness, since mcr has corresponding nanoserver and servercore images.
Add test constants with codenames (RS5, 20H1, etc.) and server LTSC builds to make selection easier.
Update `"osversion"` constants with 22H2 for Windows 10 & 11.
Add aliases in `"osversion"` for version numbers and LTSC server builds to ease confusion between build code names and versions.

Add 20H2 container image to test constants

---

cmd/dmverity-vhd/README.md
cmd/dmverity-vhd/main.go

This will be used in a "clean-room" scenario for use to security policy generation. Clean-room in this instance is for generating a security policy on computers without internet access or the docker daemon (or similar) running.
The `&tag` passed in defaults to "latest" if only the image name is passed in. If the value of the tag is `nil`, the tarball must only have one image in it. Otherwise, many images can be stored in the tarball and be searched by their image name and tag.

adding tarball support for generating root layer hashes

---

internal/guest/runtime/hcsv2/container.go
internal/guest/runtime/hcsv2/uvm.go
internal/guest/runtime/hcsv2/workload_container.go

This PR fixes a shared scratch scenario where the scratch directory is cleaned up on container delete, but since the container's root directory is in a different location, the root directory is never cleaned up. Be sure to clean up both the scratch and root directories regardless of whether shared scratch is set. 

Add logic to cleanup the oci bundle root dir on container delete

---

cmd/containerd-shim-runhcs-v1/pod.go

Currently, the entrypoint for all pause containers is being overriden to ping.exe immaterial of the pause image used. This is causing perf issues even when the default pause image is used.
This PR retains /pause.exe as entrypoint for the default pause image and overrides to ping.exe only if the default arg/commandline of the non-default pause image being used is "c:\\windows\\system32\\cmd.exe" . We intend to completely get rid of the ping override by containerd/1.7 and hence throw a warning log message to switch to the default pause image asap.

Retain pause.exe as entrypoint for default pause images

---

internal/guest/runtime/hcsv2/uvm.go
pkg/securitypolicy/framework.rego
pkg/securitypolicy/regopolicy_test.go
pkg/securitypolicy/securitypolicy_test.go
pkg/securitypolicy/securitypolicyenforcer.go
pkg/securitypolicy/securitypolicyenforcer_rego.go
test/cri-containerd/policy_test.go

When we added AllowElevated and checked it was working correctly, we got it slightly wrong. When a container is started, we were adding in expected mounts that only happen for privileged containers and using those are mounts that are allowed.
During testing, if AllowElevated was left off, a privileged container would fail to start seemingly indicating that all was good. However, all was not good.
A malicious orchestrator with control of the API could create a container privileged that didn't contain any extra "privileged mounts" and the container would start as privileged with everything else that being privileged entails except for the mounts.
This commit adds an explicit check as part of crete container to verify that is the container is attempting to be started as privileged that it …

Add missing AllowElevated policy check when creating a container

---

internal/guest/runtime/hcsv2/spec.go
internal/guest/runtime/hcsv2/uvm.go

A change to one of these two checks was requested by Hamza as part of https://github.com/microsoft/hcsshim/pull/1624. It was decided to get both instances in their own PR as the change was unrelated to the work in 1624.

Make LCOWPrivileged annotation more resilient to change

---

internal/tools/snp-report/main.go

Previously `fake-report` flag of `snp-report` binary was incorrectly handled when report was requested in `binary` format. This PR fixes the logic.

fix snp-report: fake-report flag is now correctly parsed

---

internal/tools/securitypolicy/README.md
pkg/securitypolicy/securitypolicy_test.go
pkg/securitypolicy/securitypolicyenforcer_rego.go
test/cri-containerd/policy_test.go

Sandbox and hugepage mounts come via CRI config in the form: `sandbox://<absolute-path>`, however the existing enforcement and tests expect it to be `sandbox://<relative-path>` which causes a problem during mount enforcement, when the sandbox prefix is replaced with an additional path separator in the end.
Additionally update policy tests.

rego: fix slightly incorrect sandbox and hugepage mounts enforcement

---

.github/workflows/ci.yml

Integration test often fails because of mingw installation failure, which in turn appears to be a web-request issues.
Adding rety and backoff/sleep to resolve issue.

Add retry to install mingw

---

cmd/containerd-shim-runhcs-v1/pod.go

This PR ports [6cd5572](https://github.com/microsoft/hcsshim/commit/6cd5572970cf7c82813e9c29bf41d9b0bd435977) from hcsshim/main to release/0.9 branch
Currently, the entrypoint for all pause containers is being overriden to ping.exe immaterial of the pause image used. This is causing perf issues even when the default pause image is used.
This PR retains /pause.exe as entrypoint for the default pause image and overrides to ping.exe only if the default arg/commandline of the non-default pause image being used is "c:\windows\system32\cmd.exe" . We intend to completely get rid of the ping override by containerd/1.7 and hence throw a warning log message to switch to the default pause image asap.
Signed-off-by: Kirtana Ashok …

[release/0.9] Retain pause.exe as entrypoint for default pause images

---

internal/guest/storage/scsi/scsi.go
test/cri-containerd/execcontainer_test.go

SCSI mount operation used to check for ENOENT ("no such file or directory") error and used to retry the mount operation because the SCSI device sometimes takes a bit of a time to show up. However, in the recent version of the Linux kernel the error it returns seems to have changed from ENOENT to ENXIO ("no such device or address"). This commit updates the retry logic to retry no matter the error code so that even if the error code changes in the future this won't break.
This also updates a test that used to specifically look for 2000 bits of entropy inside the guest. However, Linux kernel 5.15 has changed the entropy behavior and now it only has 256 bits of entropy (with increased security and performance).

Fix SCSI mount error handling

---

cmd/containerd-shim-runhcs-v1/pod.go
internal/uvm/create.go
internal/uvm/create_lcow.go

This PR fixes an issue when multiple UVMs are started in a
concurrent fashion, which results in an access denied error from
HCS when trying to load VMGS while another UVM start is using it.
The fix is to treat the VMGS file as template and create a temporary
copy in pod's OCI bundle directory for the lifetime of the UVM.
The copy is deleted when UVM is terminated.

fix: treat VMGS file as template when launching multiple UVMs

---

pkg/securitypolicy/framework.rego
pkg/securitypolicy/regopolicy_test.go
pkg/securitypolicy/securitypolicyenforcer_rego.go

Environment variable values might contain sensitive information. This commit scrubs those values from appearing in policy error messages.
In any error messages "Input" section, the value of the environment variables is replaced with "<<redacted>>".
In the errors list, only the key of the environment variable is listed as not matching rather than the full "KEY=VALUE" string.

Redact environment variable values in policy error output

---

pkg/securitypolicy/securitypolicyenforcer_rego.go

If the policy does not return an error, this means that an unexpected error has occurred. We want to signal this to the user by throwing a generic error which will indicate to them the general nature of what has gone wrong, i.e. that their Rego is invalid.

Adding a default error message.

---

pkg/securitypolicy/securitypolicyenforcer_rego.go

When I did the change to redact environment variable values in policy engine error messages, I create a "false positive error message" bug.
If any policy check were to be denied that involved environment variables in the check, then environment variables would be listed as a cause even if they weren't. This was because the previous redacting code was changing the data object used to determine the errors.
The updated data object had the redacted environment variables which would never match so all error messages would include that the envs were invalid.
This commit fixes that issue but creating a new object when redacting, the original object is still used to data checking and if redaction has been done, the new data object is used for generating the error message.
The current test system …

Fix unintended data modification when redacted environment variables

---

pkg/securitypolicy/framework.rego

Due to errors in the logic for detecting errors when exec_external was denied, if it was denied, env list and working directory errors would always appear because the error checks were incorrect.
This commit fixes those errors.
At the moment, checking to make sure we don't have false positives in tests is difficult. Work to add those tests is planned but will take a bit. In the meantime, this change will fix the issue that is live in production.

Fix false positive error messages on exec_external policy denial

---

ext4/dmverity/dmverity.go

Due to a missing check for whether padding is needed or not, for certain images we may end up with an extra 4096 zero-byte padding in the merkle tree. Fix this by checking if padding is needed.

dmverity: fix padding

---

ext4/tar2ext4/tar2ext4.go

Fix a temp file leak when computing dmverity root hash. This mainly 
affects `dmverity-vhd` tool and users may see their temp storage filling up.

fix: temp file leak during hash computation

---

pkg/securitypolicy/framework.rego
pkg/securitypolicy/regopolicy_test.go

If two containers are indistinguishable at create_container or exec_external time except for their `allow_stdio_access` value, then we are unable to proceed as we don't know if access should be allowed or not.
Prior to this commit, no error message at all was displayed when this was hit making it almost impossible for someone not "in the know" to diagnose.
This first version gives a very simple error message that will be improved with more information in later commits.

Provide error message when allow_stdio_access creates and undecideable error

---

pkg/securitypolicy/regopolicy_test.go

A couple of tests had a _ between Enforce and CreateContainer that isn't part of the naming scheme we came up with for the rego policy tests. This commit fixes those variances.

Make a couple tests match the naming convention around them

---

pkg/securitypolicy/regopolicy_test.go
pkg/securitypolicy/securitypolicy_test.go

A small point of improvement that we saved away was to take a list of containers rather than constraints when selecting a container. This will make the function more usable elsewhere in tests.
This change doesn't do anything but the refactoring. Future usage of the more generally useful function can be done as needed.

Update selectContainerFromConstraints to work on a container list

---

pkg/securitypolicy/framework.rego
pkg/securitypolicy/regopolicy_test.go
pkg/securitypolicy/securitypolicy_test.go

This commit handles the simplest case of error reporting and doesn't inform as to the particular variables or the group them into sets based on container/process.
Signed-off-by: Matthew A Johnson <matjoh@microsoft.com>

Provide error message when the lack of required environment variable causes policy denial

---

pkg/securitypolicy/opts.go
pkg/securitypolicy/securitypolicy.go
test/cri-containerd/main_test.go
test/cri-containerd/policy_test.go

Add CRI integration tests to validate rego policy enforcement around container execs.
Additionally introduce new `PolicyConfigOpt` type for easier policy config generation, update policy tests to use the opts.

tests: rego policy exec in container tests

---

pkg/securitypolicy/regopolicy_test.go

Two recent PRs of mine had an unfortunate interaction. Both passed they should have. Bunt one was refactoring that removed a method that the second PR relied and when they were both merged to main, compilation error!
Refactor commit:
https://github.com/microsoft/hcsshim/commit/2c33d3d83a1e447e129b7487bf04c3144d14f4a9
Commit that didn't take the above changes into account:
https://github.com/microsoft/hcsshim/commit/c97246d11f19a4f178f1a82fe8b2caa0b404b472

Fix compilation error caused by "PRs crossing in the night"

---

internal/guest/storage/crypt/crypt.go
internal/guest/storage/crypt/crypt_test.go
internal/guest/storage/crypt/utilities.go
internal/guest/storage/scsi/scsi.go

To avoid the  ioerror detected by the integrity layer.

Format encrypted scratch disk as xfs rather than ext4fs

---

.github/workflows/ci.yml

I've been watching the mingw failures I get and I've been checking "successes" to see if I can see the current 2 second back off being successful. I regularly see the short retry period not working and I've seen only once or twice that it it worked.
This commit ups the time to retry to a longer 60 seconds which should give a better chance at success.

Wait longer before trying to install mingw after failing to install

---

osversion/osversion_windows.go
osversion/osversion_windows_test.go

This allows the type to be used with fm.Sprintf() and similar uses.
To preview the GoDoc (pkg.go.dev);
```bash
GOOS=windows pkgsite -http=:6060 .
```

osversion: implement stringer interface, deprecate ToString()

---

.github/workflows/ci.yml

`gotestsum` displays a test summary at the end, allowing us to view the test results without needing to scroll through to search for the failing test:

Use gotestsum to get test summary

---

test/cri-containerd/stopcontainer_test.go

This PR ports graceful termination test fix from main.
- Loosen the time interval check that measures the time taken to
stop the container with -t command to account for cloud test delays
- Add to check that OS version is V21H2Server since the graceful
termination test images are based on servercore and nanoserver 2022.
(cherry picked from commit 5e3a6dfa5fdcb695748e19f03d5ffb5127a7588a)

[release/0.9] Fix graceful termination test errors (#1687)

---

.github/workflows/ci.yml
internal/guest/prot/protocol.go
internal/guest/storage/devicemapper/devicemapper.go
internal/security/grantvmgroupaccess.go
pkg/amdsevsnp/report.go
test/cri-containerd/container_update_test.go
test/cri-containerd/container_virtual_device_test.go
test/cri-containerd/main_test.go
test/cri-containerd/pod_update_test.go
test/cri-containerd/policy_test.go
test/functional/lcow_test.go
test/functional/main_test.go
test/functional/uvm_mem_backingtype_test.go
test/functional/uvm_scsi_test.go
test/functional/uvm_virtualdevice_test.go
test/functional/wcow_test.go

The goal of this PR is to fix a problem seen in https://github.com/microsoft/hcsshim/pull/1704. In that PR, it appears that the linter continuously fails with 
```
level=error msg="Running error: 1 error occurred:\n\t* can't run linter goanalysis_metalinter: buildir: failed to load package : could not load export data: no export data for \"github.com/Microsoft/hcsshim/test/internal/require\"\n\n"
```
However, in that PR that package has been removed and all references to it in the repo have been updated. 
We believe this is an issue with the linter's mod cache being out of date. This PR aims to address that by updating the linter version and adding an additional step beforehand to clean the mod cache.

Update golangci linter and clean go mod cache

---

go.mod
go.sum
test/go.mod
test/go.sum
vendor/modules.txt

Upgrade runc to version 1.1.5, closing PRs #1712 and #1713, and resolving CVE alert https://github.com/microsoft/hcsshim/security/dependabot/51
Note: our code does not seem to be affected at all, but just to resolve the alerts ...

upgrade runc dependency

---

internal/guest/runtime/hcsv2/spec.go
internal/guest/runtime/hcsv2/uvm.go

This change adds SEV device to linux container spec whenever security policy isn't empty.

sev-snp: add SEV device when security policy is present

---

internal/guest/runtime/hcsv2/uvm.go
pkg/annotations/annotations.go
pkg/securitypolicy/securitypolicy.go
test/cri-containerd/policy_test.go

Due to `execve` limitation on the size of environment variable, write the base64 encoded security policy, UVM reference info and host AMD certificate to container's rootfs.
Update existing test accordingly.

con-con: write policy, reference info and cert to container's rootfs

---

internal/guest/bridge/bridge_v2.go
internal/guest/runtime/hcsv2/uvm.go
internal/regopolicyinterpreter/regopolicyinterpreter.go
pkg/securitypolicy/framework.rego
pkg/securitypolicy/regopolicy_test.go
pkg/securitypolicy/securitypolicy.go
pkg/securitypolicy/securitypolicy_test.go
pkg/securitypolicy/securitypolicyenforcer.go
pkg/securitypolicy/securitypolicyenforcer_rego.go
test/cri-containerd/policy_test.go

This PR makes two major changes:
1. All policy enforcement points now receive a context objects and use it to log policy errors and denial decisions.
2. Policy denials are now conveyed as structured JSON objects.
Whereas previously policy denial was surfaced as a text error message, the policy now generates a bracketed base64 encoded string:
`policydecision< (base64) >policydecision`
When decoded, this will be a JSON object with the following structure:
```javascript
{
"input": {/*redacted input object*/},
"decision": "deny",
"reason": {/*reason object explaining decision*/},
"policyError": "optional error field"
}
```
NB: the `"policyError"` field above is only present if the denial was triggered by an actual error in the Rego policy.

Moving to structured JSON policy decisions.

---

internal/guest/storage/devicemapper/targets.go
internal/guest/storage/scsi/scsi.go

After moving to 5.10+ we started seeing occasional failures when creating verity/crypt device-mapper targets.
Longer term fix should be adding retries on particular errors at lower level e.g. in devicemapper/crypt packages.
The other PR is currently in draft: https://github.com/microsoft/hcsshim/pull/1721

hack: add blanket retries on device-mapper failures with SCSI

---

test/cri-containerd/policy_test.go

Enable a few negative tests for rego enforcer. Since JSON policies will be dropped soon, replace existing negative JSON policy tests with negative rego policy tests.

negative rego cri-integration tests

---

test/cri-containerd/policy-v0.1.0.rego
test/cri-containerd/policy_test.go

Rego error messages are now returned base64 encoded, so direct error message assertions don't work and we need to decode the policy decision string first. One of the tests was missing this.
Additionally alpine container has been updated and the layer digest has changed, so the policy used to check backward compat is now broken. Update it to have a valid digest.

tests: fix error assertion and container layer sha256

---

internal/guest/runtime/hcsv2/uvm.go

The recent changes to store the UVM security context in files rather than envvars prevents other processes running in the container from reading these as the parent `/security-context-*` directory doesn't allow for these files to be read. 
```
$ sudo ls -la /security-context-2100795932/
total 32
drwxr--r-- 2 root root    93 Apr 13 10:23 .    << Missing x for others
drwxr-xr-x 1 root root   148 Apr 13 14:30 ..
-rwxr--r-- 1 root root  8924 Apr 13 10:23 host-amd-cert-base64
-rwxr--r-- 1 root root 14524 Apr 13 10:23 reference-info-base64
-rwxr--r-- 1 root root   988 Apr 13 10:23 security-policy-base64
$ cat /security-context-2100795932/host-amd-cert-base64
cat: /security-context-2100795932/host-amd-cert-base64: Permission denied
$ sudo chmod 745 /security-context-2100795932/
$ cat …
```

Make sure that security context files are readable by all

---

internal/guest/runtime/hcsv2/uvm.go
internal/regopolicyinterpreter/regopolicyinterpreter.go
pkg/securitypolicy/framework.rego
pkg/securitypolicy/policy.rego
pkg/securitypolicy/regopolicy_test.go
pkg/securitypolicy/securitypolicyenforcer.go
pkg/securitypolicy/securitypolicyenforcer_rego.go
test/cri-containerd/policy-v0.1.0.rego

In some circumstances, the policy decision object returned from a policy denial causes the resulting error message to exceed the maximum error length imposed by Service Fabric. This PR adds some truncation logic to reduce the size of the decision object so it first into the limit. Firstly, all standard capability sets (privileged and unprivileged) are replaced with a placeholder. Then, if the message is above the length limit the following things are truncated until the message is below the threshold:
1. `reason.error_objects`
2. `input`
3. `reason` (the rest of the reason object returned from the policy)

Policy decision truncation.

---

internal/regopolicyinterpreter/regopolicyinterpreter.go
pkg/securitypolicy/regopolicy_test.go
pkg/securitypolicy/securitypolicyenforcer_rego.go

Due to a change made during the switch to structured JSON policy decisions, the path that was previously
followed to produce the errors for missing enforcement points was broken. This commit fixes that change and adds a test to protect against regression on these error messages in the future.

Fixing the errors for missing enforcement points

---

internal/guest/storage/ext4/format.go

This PR adds a new call to format a disk as ext4 in the guest.
This PR does NOT hook up the code flow, that will come in later PRs.

Add code to format disk as ext4 in guest

---

pkg/securitypolicy/securitypolicy.go
pkg/securitypolicy/securitypolicyenforcer_rego.go

This commit switches from raw encoding (no padding) to standard encoding (padding with `=`) for base64-encoded policy decisions.

Adding padding to base64 encoded policy decisions

---

internal/guest/prot/protocol.go
internal/guest/runtime/hcsv2/uvm.go
internal/protocol/guestresource/resources.go

This is commit 2/6 in a chain. Recommended to review in order. If reviewing a later PR in the chain, you can view individual commits to see just what that PR changes.
- #1740
- #1741
- #1742
- #1743
- #1744
- #1745
SCSI devices must be unplugged by the guest before removal on the host
side, to ensure smooth operation. Previously a SCSI device was unplugged
when a LCOWMappedVirtualDisk entry was removed. However, we want to
support multiple mounts per disk, which means we need to decouple unplug
from unmount.
This change introduces a new SCSIDevice resource type that has a remove
operation that can be used by the host to trigger an explicit unplug via
SCSI.
This is a breaking change to the bridge protocol:
- With new host/old guest, the host will attempt a SCSIDevice remove
which will fail …

gcs: Add SCSIDevice type with remove operation

---

cmd/gcstools/installdrivers.go
internal/devices/drivers.go
internal/hcsoci/create.go
internal/hcsoci/hcsdoc_wcow.go
internal/hcsoci/resources_wcow.go
internal/uvm/scsi.go

This is commit 3/6 in a chain. Recommended to review in order. If reviewing a later PR in the chain, you can view individual commits to see just what that PR changes.
- #1740
- #1741
- #1742
- #1743
- #1744
- #1745
`GetScsiUvmPath` encodes the unfortunate assumption that there is a single guest mount path for each SCSI device host path. This may be correct today, but there is no good reason for it to be treated as an invariant (mounting a SCSI device gives you back an object that tells you where it was mounted) and needs to not be true in the future (so we can do things like mounting multiple partitions from a device).
These commits remove the usage of `GetScsiUvmPath`, and replace it with just getting the guest path directly from the returned `SCSIMount` object.
Please see individual …

Remove dependence on GetScsiUvmPath function

---

internal/hcsoci/resources_lcow.go
internal/hcsoci/resources_wcow.go
internal/jobcontainers/jobcontainer.go
internal/jobcontainers/storage.go
internal/layers/layers.go
internal/resources/resources.go
internal/uvm/vpmem.go
test/functional/uvm_vpmem_test.go
test/functional/wcow_test.go

This is commit 4/6 in a chain. Recommended to review in order. If reviewing a later PR in the chain, you can view individual commits to see just what that PR changes.
- #1740
- #1741
- #1742
- #1743
- #1744
- #1745
Currently, the layers package relies on the caller of Mount*COWLayers to
subsequently call NewImageLayers, which constructs a special ImageLayers
object that can be used to later clean up the layer mounts. However,
this requires the caller to know too much about the internals of the
layer mounting process.
A cleaner approach, which I take here, is to instead return a standard
ResourceCloser from Mount*COWLayers which then knows how to clean up
whatever mounts were done. I have also changed the layers code to use
ResourceCloser in more places internally.
There is a new check in …

Rework layer handling to return a ResourceCloser 

---

.github/dependabot.yml

Patch updates can be disabled for most dependencies, but ignoring all patch-fixes has caused errors (notably containerd).
Individual dependecies can have their patch updates ignored if they are too noisy

Allow patch dependabot updates

---

.github/workflows/ci.yml
go.mod
go.sum
test/cri-containerd/main_test.go
test/go.mod
test/go.sum
test/internal/containerd/containerd.go
vendor/github.com/containerd/containerd/filters/filter.go
vendor/github.com/containerd/containerd/filters/parser.go
vendor/github.com/containerd/containerd/filters/quote.go
vendor/github.com/containerd/containerd/mount/mount.go
vendor/github.com/containerd/containerd/mount/temp.go
vendor/github.com/containerd/containerd/namespaces/store.go
vendor/github.com/containerd/containerd/runtime/v2/shim/shim.go
vendor/github.com/containerd/containerd/runtime/v2/shim/shim_darwin.go
vendor/github.com/containerd/containerd/runtime/v2/shim/shim_freebsd.go
vendor/github.com/containerd/containerd/runtime/v2/shim/shim_linux.go
vendor/github.com/containerd/containerd/runtime/v2/shim/shim_windows.go
vendor/github.com/containerd/containerd/runtime/v2/shim/util.go
vendor/github.com/containerd/containerd/version/version.go
vendor/github.com/containerd/ttrpc/server.go
vendor/modules.txt

Use the upstream version of containerd that matches what hcsshim imports.
This resolves most of the containerd integration test failures, except for `TestContainerSymlinkVolumes`

Checkout appropriate containerd ref

---

internal/guest/runtime/runc/container.go
internal/guest/runtime/runc/runc.go

The PR aims to add support for redirecting container stdout and stderr statements to a another container(logging container) via named pipes. 
This is controlled by set of annotations being passed in the spec. 
When the annotation is set, the named pipe is created in the UVM. The workload container will start to redirect stdout and stderr statements to this named pipe and logging container will use the pipe file descriptor passed to it to read data coming through pipe.

gcs: Support routing container stdio to sidecar

---

.github/workflows/ci.yml

This PR enables the guest agent unit tests as part of the CI's linux testing. This includes unit tests for everything under internal/guest, such as scsi mounting, pmem mounting, etc.

Enable guest agent unit tests in the CI

---

cmd/containerd-shim-runhcs-v1/rootfs.go
cmd/containerd-shim-runhcs-v1/service_internal.go
cmd/containerd-shim-runhcs-v1/task_hcs.go
internal/hcsoci/create.go
internal/hcsoci/resources_lcow.go
internal/layers/layers.go
internal/protocol/guestresource/resources.go
internal/uvm/scsi/backend.go
internal/uvm/scsi/manager.go
internal/uvm/scsi/mount.go

This is commit 6/6 in a chain. Recommended to review in order. If reviewing a later PR in the chain, you can view individual commits to see just what that PR changes.
- #1740
- #1741
- #1742
- #1743
- #1744
- #1745
This PR increases the flexibility of how we handle LCOW layers. This gives us greater ability to represent layers differently. For example, this PR also adds a new `lcow-partitioned-layer` type which consists of a VHD path and a partition index on that VHD for each read-only layer.
Please see individual commits for details.

Support flexible LCOW layer parsing and partitioned layers

---

internal/guest/runtime/hcsv2/uvm.go
internal/guest/storage/scsi/scsi.go
internal/guest/storage/scsi/scsi_test.go

This PR is based on Kevin's recent PRs to clean up our package, refactor our SCSI package, and refactor how we handle layers. You can find those PRs here:
* https://github.com/microsoft/hcsshim/pull/1740
* https://github.com/microsoft/hcsshim/pull/1741
* https://github.com/microsoft/hcsshim/pull/1742
* https://github.com/microsoft/hcsshim/pull/1743
* https://github.com/microsoft/hcsshim/pull/1744
* https://github.com/microsoft/hcsshim/pull/1745
This PR does the following:
* Update `ControllerLunToName` to `GetDevicePath` and take in partition as an additional param
* Wait for partition subdirectory to appear for the devices
* Update device encryption and verity device names with partition index
* Update device encryption and verity device tests
* Add new unit tests for `GetDevicePath` …

Guest agent support for partitions on SCSI devices

---

ext4/tar2ext4/tar2ext4.go
internal/guest/runtime/hcsv2/uvm.go
internal/guest/storage/crypt/crypt.go
internal/guest/storage/crypt/crypt_test.go
internal/guest/storage/ext4/format.go
internal/guest/storage/scsi/scsi.go
internal/guest/storage/scsi/scsi_test.go
internal/guest/storage/xfs/format.go
internal/layers/layers.go
internal/protocol/guestresource/resources.go
internal/uvm/scsi/backend.go
internal/uvm/scsi/manager.go
internal/uvm/scsi/mount.go

This PR is based on https://github.com/microsoft/hcsshim/pull/1747, which is in turn based on the below PRs:
* https://github.com/microsoft/hcsshim/pull/1740
* https://github.com/microsoft/hcsshim/pull/1741
* https://github.com/microsoft/hcsshim/pull/1742
* https://github.com/microsoft/hcsshim/pull/1743
* https://github.com/microsoft/hcsshim/pull/1744
* https://github.com/microsoft/hcsshim/pull/1745
This PR additionally has one temporary commit that was used for testing. When the PRs that this PR is based on are updated, this PR will also need to be updated and will likely have some rebase conflicts. You can find the target code changes in the last commit on this PR.
The main work in this PR is the creation of two new options on an LCOW scsi mount `EnsureFilesystem` and `Filesystem`. …

SCSI ensure filesystem

---

.github/workflows/ci.yml
test/containerd-shim-runhcs-v1/delete_test.go
test/containerd-shim-runhcs-v1/global_command_test.go
test/containerd-shim-runhcs-v1/start_test.go

Update shim tests to match current shim behavior.
Run shim tests in GitHub CI.

Update containerd-shim-runhcs-v1 tests

---

ext4/dmverity/dmverity.go
ext4/dmverity/dmverity_test.go
ext4/tar2ext4/tar2ext4.go
internal/verity/verity.go

Add another `ReadExt4SuperBlock` implementatino to work with `io.ReadSeeker` in addition to working with files directly. This way we'll be able to work with e.g. ext4 GPT partitions.
Additionally write verity superblock directly without `io.SeekEnd`, assumming that the writer is already set at correct offset.

update tar2ext4 package

---

.github/workflows/ci.yml
.gitignore
Protobuild.toml

Use official github cli tool to download releases, instead of manually creating URLs.
Update runners to windows 2022 from 2019

Use `gh` cli to download releases

---

test/cri-containerd/container_test.go
test/cri-containerd/main_test.go

LCOW kernel needs to be built with certain config options(`CONFIG_NFS_FS=y`, `CONFIG_NFS_V4=y` & `CONFIG_NFS_V4_1=y`)_in order to be able to successfully run a NFS client and mount a NFS inside a container. This test attempts to mount a (fake) NFS server to ensure that the kernel has the capabilities of running a NFS client.
We don't mount a real NFS server because creating a real NFS server that will work in all kinds of test environments is not simple. Instead, we look at the error returned by the NFS mount operation and decide if the failure is because the server wasn't available (i.e a `Connection refused` error) or because the kernel doesn't support NFS clients (`No Device` error).
Limitations on different approaches of starting a real NFS server:
1. Starting another LCOW container …

Add test for support of NFS mount

---

scripts/Test-LCOW-UVM.ps1
test/gcs/container_bench_test.go
test/gcs/helper_container_test.go

Can no longer specify guest path for SCSI mounts, so update gcs test script.
Additionally, now need to unmount scratch space before deleting the container, so update gcs tests.

[gcs.test] update scratch space cleanup order

---

test/functional/uvm_update_test.go

inject fragment logic has been added and the uvm resource update tests are failing for a completely different reason. Update the tests to check for specific "invalid resource" message.

tests: fix uvm resources update tests

---

ext4/tar2ext4/tar2ext4.go
internal/guest/storage/scsi/scsi.go
test/cri-containerd/container_test.go
test/cri-containerd/main_test.go

During a recent refactor SCSI mount operation code removed a retry logic that is needed when examining the filesystem type on a SCSI device. Retry is needed because sometimes attempting to open a SCSI devices immediately after attaching it results in ENXIO/ENOENT errors. This adds the retry logic back.
Names of some images used in the tests had changed, this commit updates those names too.

Minor fixes to SCSI mount operation

---

.github/workflows/ci.yml

Caching is enabled by default in `actions/setup-go@v4` (https://github.com/actions/setup-go#caching-dependency-files-and-build-outputs) so update the `go.sum` path when checking out hcsshim to a non-default path.
Additionally, disable for linting, since that often causes errors.
Without caching, wont need to explicitly delete the module cache.

[ci] Enable caching for proto and integration jobs

---

.github/workflows/ci.yml

containerd integration tests have been failing to build since mingw `10.2` appears to no install `mingw32-make.exe` anymore.
upgrading to `10.3` appears to fix this. 
add dedicated check for `mingw32-make.exe` instead of relying on build stage to fail
also, move `choco upgrade` command to dedicated step to allow environment variables to be reloaded.

[ci] Fix integration test failure

---

test/cri-containerd/main_test.go

In a previous commit, the image used in the ArgsEscaped test was changed incorrectly. This fixes that.

Revert image name change in the ArgsEscaped test

---

cmd/containerd-shim-runhcs-v1/task_hcs.go

This uses the same logic for pods that are in invalid states when the properties are queried.  Found this while testing https://github.com/kubernetes/kubernetes/pull/116968 and the "not found error" will allow to handle gracefully in https://github.com/containerd/containerd/pull/8671.

When fetching the pid counts for the container the state can be invalid sometimes

---

.github/workflows/ci.yml

Windows image layers are no longer `ocispec.MediaTypeImageLayerNonDistributable`.
Skip `containerd` integration test `TestConvert`, until it is updated in the `release/1.6 branch`.
See: https://github.com/containerd/containerd/pull/8691

skip failing test, use gotestsum

---

cmd/dmverity-vhd/main.go

Currently we're not closing output VHD files and read closers when creating layer VHDs with dmverity-vhd tool.
Refactor error wrapping.

make sure to close files in dmverity-vhd tool

---

internal/log/format.go
internal/log/scrub.go

use `google.golang.org/protobuf/encoding/protojson` when encoding protobuf structs in logs.
the biggest difference will be enums being encoded by their string name instead of numerical value

use protojson when formatting for logs

---

osversion/platform_compat_windows.go
osversion/platform_compat_windows_test.go
osversion/windowsbuilds.go
test/vendor/github.com/Microsoft/hcsshim/osversion/platform_compat_windows.go
test/vendor/github.com/Microsoft/hcsshim/osversion/windowsbuilds.go

Cherry pick commit [640a560 ](https://github.com/microsoft/hcsshim/commit/640a5606a855a275cda5b8862221ae32b09b6a35) from hcsshim/main + add windows versions to osversion/windowsbuilds.go

[release/0.9] Add support for platform compatibility check for windows + add windows builds

---

test/cri-containerd/policy_test.go
test/functional/lcow_policy_test.go
test/functional/main_test.go
test/internal/layers/lazy.go
test/internal/layers/scratch.go
test/pkg/securitypolicy/policy.go

Update test images package to support image extract decorators as an easy way to extend the logic if we need to chain a few steps, in this case appending verity hashes to an ext4 fs.
Add default mount extension logic to standalone container path as well to enable functional tests.
Add new `securitypolicy` package under `test/pkg` to share some logic between cri-containerd and functional tests.
Add lower level `get_properties` test with rego policies.

tests: rego `get_properties` functional test

---

computestorage/helpers.go
internal/wclayer/baselayerreader.go
internal/wclayer/converttobaselayer.go
internal/wclayer/legacy.go
internal/winapi/offlinereg.go
internal/winapi/ofreg.go
internal/winapi/zsyscall_windows.go
pkg/cimfs/cimfs.go
pkg/ociwclayer/export.go
pkg/ociwclayer/import.go

offline registry API is required during CimFS layer import. This commit adds Go wrappers around it.  It also exports some constants from the wclayer package so that those constants can be used by the cim layer package

cimfs: Add Offline registry API wrappers and export constants

---

.golangci.yml
internal/tools/networkagent/README.md
internal/tools/networkagent/defs.go
internal/tools/networkagent/main.go
internal/tools/networkagent/v0_service_wrapper.go

This PR updates our test network agent for use with ncproxy nodenetsvc v0 api. This tool is intended only for dev use. A new README is additionally added with information on how to use the test tool.

Add support for nodenetsvc v0 and readme to test network agent

---

.github/workflows/ci.yml

Prevent cancelling tests if one fails, since its helpful to see all test results

disable fail fast on windows tests

---

osversion/osversion_windows.go

GetVersion API returns correct OS version values only if the calling binary is manifested.  Hcsshim is manifested. However, other binaries using the osversion package from hcsshim (like containerd) are not manifested and so they are not able to get the accurate OS version information. RtlGetVersion doesn't need the binary to be manifested so this commit replaces the use of GetVersion with RtlGetVersion.
Note that hcsshim is still manifested even if we aren't using GetVersion anymore. This is because there are some other advantages of using a manifest as described here: https://learn.microsoft.com/en-us/windows/win32/w8cookbook/application--executable--manifest. The use of a default thread pool for RPC and the fix for a race condition in GetOverlappedResult are relevant to hcsshim. So in …

Use RtlGetVersion instead of GetVersion

---

test/functional/lcow_container_bench_test.go
test/functional/lcow_container_test.go
test/functional/lcow_policy_test.go
test/internal/cmd/cmd.go

Add benchmarks to measure (LCOW) exec performance to functional test suite.
Additionally, remove helper testing functions from benchmark section (between `b.StartTimer()` and `b.StopTimer()`), since helper functions will call `"testing".(TB).Helper()`, which involves mutex (un)lock operations as well as parsing stack frames.

Add exec benchmarks

---

.github/workflows/ci.yml

Don't need `-mod=mod` flag when running tests in root repo, removing uses vendored dependencies and avoids downloading packages per test run.
Running tests in `internal/regopolicyinterpreter/` on Windows is redundant, since tests are already run with `./...`.
Switch from running tests in `test/internal` to `test/...` on Windows, since, without `-tag functional` flag, it will not run `test/functional`, `test/cri-containerd`, and related tests, but will encompass other tests defined.

[ci] Update testing jobs

---

internal/guest/storage/crypt/crypt.go
internal/guest/storage/crypt/crypt_test.go
internal/guest/storage/devicemapper/devicemapper.go
internal/guest/storage/devicemapper/targets.go
internal/guest/storage/scsi/scsi.go
internal/guest/storage/scsi/scsi_test.go

Occasionally /dev/sd* devices arrive late and not available at the time when verity or dm-crypt targets are created. This commit introduces a `CreateDevice` wrapper which can retry the operation on specific errors and always retries cryptsetup once, but with a large retry timeout.

retry device mapper and cryptsetup errors

---

computestorage/storage.go
computestorage/zsyscall_windows.go

HcsDestoryLayer -> HcsDestroyLayer

computestorage: Fix incorrect syscall in DestroyLayer

---

.golangci.yml
internal/vhdx/info.go

CimFS layer import requires that we do the base scratch VHD processing without calling the HCS APIs (since those APIs do not understand the CimFS format). This processing involves fetching the partitioning information of the scratch VHD. This commit adds a package that adds new Go wrappers around the IOCTLs that fetch partitions information of a device.

cimfs: Add helpers for retrieving partition information from a vhdx

---

.golangci.yml
cmd/containerd-shim-runhcs-v1/service.go
cmd/ncproxy/service.go
internal/exec/exec.go
internal/jobobject/jobobject.go
internal/layers/layers.go
internal/log/scrub.go
internal/regopolicyinterpreter/regopolicyinterpreter.go
internal/safefile/safeopen.go
internal/tools/networkagent/main.go
internal/uvm/create_test.go
internal/uvm/update_uvm.go
internal/vm/remotevm/builder.go
pkg/cimfs/cim_test.go
pkg/cimfs/cim_writer_windows.go

Turn on all [go vet](https://pkg.go.dev/cmd/vet) checks (except for `fieldalignment` and ignore shadowing `err` variables.
Caught a couple minor bugs:
- ncproxy did not set the panic file for the service
- `nil`-field access in logs
- not updating `processorLimits` in `(*UtilityVM).Update`
Simplified a couple `if` statements clauses where [conditional evaluation](https://go.dev/ref/spec#Logical_operators) made `!= nil` checks redundant.

Add more go vet checks

---

internal/hcs/schema2/isolation_settings.go
internal/oci/annotations.go
internal/oci/uvm.go
internal/uvm/create_lcow.go
pkg/annotations/annotations.go

This PR:
- changes the `HclEnabled` field's type from a boolean to pointer to a boolean.  
- plumbs in a new annotation `io.microsoft.virtualmachine.lcow.hcl-enabled` which can be used to set the value of `HclEnabled`.
- If the annotation is not set then the `HclEnabled` field in omitted (as it is currently)
First, currently the JSON Marshaller is set to `omitempty` on the `HclEnabled` field. This means that the field is omitted if it is regarded as empty, and `false` is regarded as empty. See https://pkg.go.dev/encoding/json#Marshal. (This prevents deployment in scenarios where we need to set `HclEnabled` to `false`.) However a pointer to boolean with value `false` is not regarded as empty, while an empty pointer is. 
Second, there is no way to choose the value of `HclEnabled` prior to …

Allow setting HclEnabled to false

---

internal/tools/securitypolicy/README.md

SVNs are integers, not semantic version numbers.

Fix SVN reference in policy readme

---

internal/devices/drivers.go
internal/guest/runtime/hcsv2/nvidia_utils.go
internal/guest/runtime/hcsv2/workload_container.go
internal/guestpath/paths.go
internal/hcsoci/devices.go
internal/oci/uvm.go
pkg/annotations/annotations.go
test/cri-containerd/container_virtual_device_test.go
test/cri-containerd/main_test.go
test/functional/uvm_virtualdevice_test.go

This PR cleans up the support for NVIDIA GPUs. Instead of relying on a separate VHD that contains the NVIDIA drivers to be mounted into the UVM at runtime, we assume the UVM image has the drivers and necessary tools (such as libnvidia-container's cli binary) already present. `annotations.GPUVHDPath` is no longer used and will be removed in the future. Functional tests and cri-containerd tests have been cleaned up for this new logic.

Clean up NVIDIA hook

---

internal/oci/uvm_test.go
internal/tools/uvmboot/lcow.go
internal/uvm/create_lcow.go
internal/uvm/start.go
internal/uvm/types.go

Currently, `NewDefaultOptionsLCOW` creates a logrus output handler using the provided UVM ID, but if the `ID` field is changed, the `parseLogrus` `OutputHandler` still uses the old ID.
Change `OptionsLCOW` to take `OutputHandlerCreator`, which is a `func(*Options) OutputHandler`, so creating the output handler is delayed until LCOW creation, when all `Option` parameters are finalized.

Add `OutputHandlerCreator` type for UVMs

---

osversion/platform_compat_windows.go
osversion/platform_compat_windows_test.go

This change is backporting the following commit to release/0.11 
640a5606a855a275cda5b8862221ae32b09b6a35
(cherry picked from commit 640a5606a855a275cda5b8862221ae32b09b6a35)
Note: there could be some CI test failures but they are failures that exist on v0.10.0-rc.8 tag that release/0.11 is based off of. We need the stable ABI changes in upstream to unblock stable ABI work for annual channel Zn release. Fix all the test failures need up to update the containerd version used in go.mod file and this in turn is causing grpc changes while vendoring into containerd/1.7 and upstream seems to have a problem with it.
Since the tests are already present in rc8 tag and aren't new, we should be ok to check in this fix with CI failures (mainly to unblock annual channel work). Once that is done, we …

[release/0.11] Add support for platform compatibility check for windows + fix integration test failures

---

.github/workflows/ci.yml
pkg/go-runhcs/runhcs.go
test/vendor/github.com/Microsoft/hcsshim/pkg/go-runhcs/runhcs.go

rerun protobuild
fix: check for `exec.ErrDot`
(cherry picked from commit 66fe5f7f91d753070ed352ce1edc1f437fe468e9)

github-ci: use go1.19.x (#1689)

---

test/containerd-shim-runhcs-v1/delete_test.go
test/containerd-shim-runhcs-v1/global_command_test.go
test/containerd-shim-runhcs-v1/start_test.go

Update shim tests to match current shim behavior.
Run shim tests in GitHub CI.
(cherry picked from commit 55f8c428a2d9b6f0aeced9d5dc497095160817d6)
CI changes postponed to #1891, since they `.github/workflows/ci.yml` has diverged significantly.

[release/0.9] Update containerd-shim-runhcs-v1 tests (#1783)

---

test/containerd-shim-runhcs-v1/global_command_test.go
test/containerd-shim-runhcs-v1/start_test.go
test/pkg/require/requires.go

Rather than failing tests when attempting to exec the shim executable, look up its path first and skip if it is not found.
Most testing binaries require that other binaries be located in the same directory as them (see `require.Binary`), but since the CI runs the shim tests directly, add `require.BinaryInPath`, which looks for the binary in the path or current working directory first.

Skip shim tests if shim binary is not found

---

cmd/containerd-shim-runhcs-v1/rootfs.go
cmd/containerd-shim-runhcs-v1/task_hcs.go
internal/guest/runtime/hcsv2/uvm.go
internal/guest/storage/pmem/pmem.go
internal/guest/storage/scsi/scsi.go
internal/guest/storage/scsi/scsi_test.go
internal/layers/layers.go
internal/protocol/guestresource/resources.go
internal/uvm/scsi/backend.go
internal/uvm/scsi/manager.go
internal/uvm/scsi/mount.go
internal/uvm/vpmem.go
internal/uvm/vpmem_mapped.go
pkg/annotations/annotations.go

Add an option to mount partitioned disks with dmverity.
Additionally add support for reading verity information from within the guest.
The expectation is that verity hash device is appended to the read-only file system.
The functionality is enabled by default.
Host no longer reads verity superblock and as a result
the `DeviceVerityInfo` protocol message is being
deprecated. The guest will always attempt to read verity
super-block when non-empty security policy is passed.
Security policy is expected to be empty only in regular
LCOW scenarios.

add support for verity checking partitioned disks

---

cmd/dmverity-vhd/main.go

In the `confcom` CLI tooling that uses the dmverity-vhd executable, we were seeing an issue where large OCI images would cause the dmverity hashing process to get killed because the machine ran out of memory: [example](https://github.com/Azure/azure-cli/issues/27275).
This unbuffered option makes go-containerregistry stream in the image as needed instead of loading it all at once, saving memory with the tradeoff of being slower for large images. The typical use case we've seen is to use the `confcom` tooling on a local machine or VM with ~16GB of memory so memory efficiency is more important than time efficiency.
Discussed with Maksim that making this the default should be fine. thanks!

defaulting to unbuffered reader for dmverity hashing

---

internal/hcs/process.go

moby tried updating hcsshim to 0.11.0 and we had some failures in our tests ([see this PR](https://github.com/moby/moby/pull/45966)).
We tracked the issue to [this change](https://github.com/microsoft/hcsshim/commit/3e090b05a82c0e226e26c0d1e2ae89d336d7ff69), the close request wasn't forwarded any more if stdin is nil. This change moves the nil check to after the modify request, letting the process handle it.

Fix closing stdin

---

cmd/dmverity-vhd/main.go
internal/hcs/process.go

Backport the following commits into `release/0.11`:
https://github.com/microsoft/hcsshim/pull/1887
https://github.com/microsoft/hcsshim/pull/1887

Update release 0.11

---

cmd/containerd-shim-runhcs-v1/serve.go
internal/log/format.go
internal/log/hook.go
test/cri-containerd/runpodsandbox_test.go
test/go.mod
test/go.sum

Moving the log package to a separate repository is part of our containerd 2.0 effort to break circular dependencies where we can. Importing the `log` package in the internal log seems unnecessary since it only uses a const. If copying that const is still not ideal, it can be updated to use new package as well (removed based on "A little copying is better than a little dependency.")
Uses the new log package for the shim and tests.

Update containerd log dependency

---

cmd/containerd-shim-runhcs-v1/service_internal_taskshim_test.go
cmd/containerd-shim-runhcs-v1/task.go
cmd/containerd-shim-runhcs-v1/task_hcs.go
cmd/containerd-shim-runhcs-v1/task_test.go
internal/guestpath/paths.go
internal/uvm/share.go
pkg/ctrdtaskapi/update.go

This PR adds hcsshim support to mount host volumes/directories to running windows containers.
HCS supports mounting host volumes/directories to running windows containers by modifying the hcs compute system with ResourcePath of Containers/MappedDirectories. These changes leverage this by extending the hcsTask.Update() function to process and add mounts for running process isolated and hyperV windows containers.

Support adding mount to running containers

---

cmd/containerd-shim-runhcs-v1/service_internal_taskshim_test.go
cmd/containerd-shim-runhcs-v1/task.go
cmd/containerd-shim-runhcs-v1/task_hcs.go
cmd/containerd-shim-runhcs-v1/task_test.go
internal/guestpath/paths.go
internal/uvm/share.go
pkg/ctrdtaskapi/update.go

- Extend hcsTask.Update() to process and add mount for running process isolated and hyperV
wcow containers
(cherry picked from commit aad7467e620da7c4958945bb68e2f10bb0ea26b2)
P.S : This is a direct cherry-pick with no additional changes

[release/0.11] Support adding mount to running containers

---

internal/hcs/process.go
internal/hcs/schema2/close_handle.go
internal/hcs/schema2/console_size.go
internal/hcs/schema2/process_modify_request.go
internal/hcs/schema2/process_status.go
internal/protocol/guestrequest/types.go

Use `hcsschema.ProcessModifyRequest` (and associated structs) in `internal/hcs/process` when making modify requests and getting process properties.
Update `hcschema` structs to match documentation (swagger seems to default to `int32` for generated fields regardless of the type specified in the documentation).

Use `"hcsschema"` in `internal/hcs`

---

.github/workflows/ci.yml

Update CI to look at both `go.sum` and `test/go.sum` when caching go modules.
Update initial CI josb (`protos`, `verify-vendor`, and `go-gen`) to download all module dependencies (that are not already vendored) to pre-fill the cache and speed up future runs.
This way, on cache miss, the cache is updated with all potential (hcsshim) dependencies.
Also, add `$LASTEXITCODE` check when running `go mod tidy` (and `go mod test`) to catch errors early on.

Also use `test/go.sum` for caching go dependencies

---

cmd/dmverity-vhd/main.go

Update release branch to include some fixes for `dmverity-vhd` tool:
* https://github.com/microsoft/hcsshim/pull/1770
* https://github.com/microsoft/hcsshim/pull/1948

[release/0.11] make sure to close files in dmverity-vhd tool (#1770)

---

internal/oci/uvm.go
internal/tools/uvmboot/lcow.go
internal/uvm/create_lcow.go
internal/uvm/create_test.go
test/functional/main_test.go
test/pkg/uvm/lcow.go

`NewDefaultOptionsLCOW` sets `RootFSFile` and `KernelFile` depending on the contents of the (default) `BootFilesPath` directory and `KerenelDirect` field.
However, if `BootFilesPath` is subsequently updated, those fields are not updated.
This can result in inconsistent behavior, where (depending on if the default `BootFilesPath` contains `vmlinux` and `rootfs.vhd` files), a uVM created with an overridden `BootFilesPath` may either use `initrd` (`kernel`) or `vmlinux` (`rootfs.vhd`), respectively.
Add a `UpdateBootFilesPath` function to consistently change the `BootFilesPath` and associated options.
Update annotation handling to use `UpdateBootFilesPath`. Security policy is still performed after the update, so settings will be re-overridden for the confidential case, or by other …

Standardize LCOW uVM bootfiles update

---

internal/wclayer/cim/LayerWriter.go
internal/wclayer/cim/bcd.go
internal/wclayer/cim/common.go
internal/wclayer/cim/file_writer.go
internal/wclayer/cim/pending.go
internal/wclayer/cim/process.go
internal/wclayer/cim/registry.go
internal/wclayer/layerutils.go
layer.go
pkg/cimfs/cim_test.go
pkg/cimfs/cimfs.go
pkg/ociwclayer/cim/import.go

Adds a new CimLayerWriter that implements the same LayerWriter interface that the legacy layer writer implements. This CimLayerWriter can be used in containerd to pull images into the cimfs format.

cimfs: Add a LayerWriter for writing cim layers

---

internal/hcsoci/hcsdoc_wcow.go
pkg/annotations/annotations.go

Create new subdirectory at the specified dumpPath with name of the subdirectory as the containerId if dumpPath has a suffix of {container_id}.
Add new annotation to specify the dumpCount for LocalDumps reg key. These annotations can be specified at the pod or container level.
Following configuration was tested for process isolated and hyperV wcow containers:
- The container_annotation field in containerd.toml should be set to "io.microsoft.container.*"
- pod.json:
{
"metadata": {
"name": "sandbox-coredump",
"namespace": "default",
"attempt": 1
}
}
- container.json:
{
"metadata": {
"name": "wcow-test"
},
"image": {
"image": "mcr.microsoft.com/windows/servercore:ltsc2022"
},
"command": [
"ping",
"-t",
"127.0.0.1"
],
"annotations": {
"io.microsoft.container.processdumplocation": …

Create container subdirectories for process dump

---

hcn/hcn.go
hcn/hcnglobals.go
hcn/hcnnetwork.go
hcn/hcnnetwork_test.go
hcn/hcnsupport.go
hcn/hcnsupport_test.go

When this flag is set, a host-port will not be created for the network.

Adding a new "DisableHostPort" network flag

---

internal/tools/uvmboot/lcow.go
internal/tools/uvmboot/main.go
internal/tools/uvmboot/mounts.go
internal/tools/uvmboot/wcow.go
test/gcs/main_test.go

Fix bugs:
- Using `boot-files-path` flag name instead of value
- Explicitly passing open door policy instead of empty string
Functional gcs tests also passed in encoded open door policy string, which is no longer necessary.
Remove unnecessary else blocks.
Pass context through calls.
Use `log.G(ctx)` instead of `logrus`.
Rename variables `cmd` and `scsi` to avoid overshadowing package names.

uvmboot and gcs.test bug fix

---

internal/guest/linux/ioctl.go
pkg/amdsevsnp/report.go

Add support for Linux kernel 6.x to fetch attestation report.
Because I can't add tests which require SNP VM under amdsevsnp package, I tested the change in the following way.
```bash
git apply --ignore-space-change <<EOF
diff --git a/pkg/amdsevsnp/report_test.go b/pkg/amdsevsnp/report_test.go
index e42af6de..65acbc91 100644
--- a/pkg/amdsevsnp/report_test.go
+++ b/pkg/amdsevsnp/report_test.go
@@ -4,6 +4,7 @@
package amdsevsnp
import (
+       "encoding/hex"
"testing"
)
@@ -51,3 +52,24 @@ func Test_Mirror_Nil_Slice(t *testing.T) {
t.Fatalf("expected nil slice, got: %+v", result)
}
}
+
+func Test_Fetch_Report(t *testing.T) {
+       const REPORT_DATA_SIZE = 64
+       const REPORT_DATA_OFFSET = 80
+       // Report data for test
+       reportData := [REPORT_DATA_SIZE]byte{}
+       for i …
```

Add support for Linux kernel 6.x to fetch attestation report

---

internal/wclayer/cim/mount.go
pkg/cimfs/cim_test.go
pkg/cimfs/mount_cim.go

Adds helper functions for mounting CimFS layers.

cimfs: Add cim layer mount/unmount functionality.

---

internal/guest/runtime/hcsv2/hostdata.go
pkg/amdsevsnp/report.go

[PR1886](https://github.com/microsoft/hcsshim/pull/1886/files) changed the error type returned by the fetch SNP report code.
It transpires that when validating host data, we would always try to fetch the SNP report, even in non SNP mode, where we expect to get back an os.IsNotExist error and ignore it. 
After PR1886 the SNP report fetch no longer returns an os.IsNotExist and so the new error is not ignored. This PR removes the reliance on the os.IsNotExist error.

Check for SNP before fetching SNP report

---

.github/workflows/codeql.yml

Need to build binaries for CodeQL to work:
> For the compiled languages C/C++, C#, Go, Java, and Swift, the process of populating
> this database involves building the code and extracting data.
https://docs.github.com/en/code-security/code-scanning/creating-an-advanced-setup-for-code-scanning/codeql-code-scanning-for-compiled-languages#about-the-codeql-analysis-workflow-and-compiled-languages
Without explicit build commands between CodeQL `init` and `analyze` steps, CodeQL will attempt to automatically build go code using the following logic:
https://docs.github.com/en/code-security/code-scanning/creating-an-advanced-setup-for-code-scanning/codeql-code-scanning-for-compiled-languages#autobuild-for-go
This can be see in the `CodeQL Analyze` step in out pipelines:
```
Attempting to …
```

Build components in CodeQL pipeline

---

internal/guest/bridge/bridge.go
internal/guest/runtime/hcsv2/spec.go
internal/hcsoci/hcsdoc_wcow.go
internal/jobobject/limits.go
internal/logfields/fields.go
internal/oci/annotations.go
internal/oci/uvm.go

Fix CodeQL alerts for unchecked downcasts from `int`s are to `(u)int32` (or `uintptr`) without checking for overflow. This can (potentially) cause incorrect behavior due to the value wrapping around to an unexpected value.
Alerts:
https://github.com/microsoft/hcsshim/security/code-scanning?query=branch%3Amain+rule%3Ago%2Fincorrect-integer-conversion
Issue description:
https://cwe.mitre.org/data/definitions/190.html
https://cwe.mitre.org/data/definitions/681.html

Fix CodeQL code scanning alerts

---

internal/uvm/vsmb.go

When attaching a file, `foo/bar`, `uvm.AddVSMB` adds the `VSMBShare`to `uvm.vsmbFileShares` as `foo/`, and then also sets `VSMBShare.HostPath` to `foo/`.
So, when `(*VSMBShare).Release` calls `uvm.RemoveVSMB`, it uses `foo/` as the `hostPath`, which, it then assumes is a directory share (stored in `uvm.vsmbDirShares`) instead of a file share (stored in `uvm.vsmbFileShares`) since `foo/` is a directory. This then fails since it cannot find the VSMBShare in `uvm.vsmbDirShares`.
Fix this by adding a `VSMBShare.isDirShare` field to indicate which `uvm.vsmb*Shares` map it is stored under.

RemoveVSMB uses the wrong hostPath for file shares

---

internal/wclayer/cim/file_writer.go
internal/wclayer/expandscratchsize.go
internal/winapi/cimfs.go
internal/winapi/zsyscall_windows.go
pkg/cimfs/cim_writer_windows.go
pkg/cimfs/cimfs.go
pkg/ociwclayer/cim/import.go

This PR adds minor bug fixes to CimFS writer and also correctly updates the windows OS build that adds support for CimFS.

Minor CimFS bug fixes

---

pkg/ociwclayer/import.go

CodeQL is generating a warning for tar extraction code suggesting that the tar file entries are used in an unsanitized way and that could lead to file system traversal attacks. However, during tar extraction all the files are written to the disk using the `internal/safefile` package which ensures all the filesystem operations during layer extraction happen under the layer root directory. So this warning can be safely suppressed.

Add CodeQL suppression for tar extraction code

---

internal/guest/runtime/hcsv2/nvidia_utils.go
internal/guest/runtime/hcsv2/uvm.go
internal/guest/runtime/hcsv2/workload_container.go

This fixes an issue where running with the rootfs.vhd fails to write log files since the root directory in the UVM is RO. Instead, write log files to the container bundle directory which is RW. This also allows us to separate nvidia logs by container.

Update nvidia hook log file paths to use container bundle path as base dir

---

cmd/dmverity-vhd/main.go

related PR: https://github.com/microsoft/hcsshim/pull/1887
We previously set the default to an unbuffered reader for the sake of memory efficiency. This PR adds the option back in to use a buffered reader for users with ample available memory. This allows for faster dmverity hashing if needed.
Testing in a VM with a 1.5GB image, an unbuffered reader uses 1/4 the RAM but takes 3x longer for dmverity hashing (from 20s up to 1m). With a swing that large either way, it would be nice to give users the option to choose which they want for use in the [confcom](https://github.com/Azure/azure-cli-extensions/tree/main/src/confcom/azext_confcom) plugin. Thanks!

adding option of using buffered image reader for faster dmverity hashing

---

internal/exec/exec.go

CreateProcess gives us back a handle to the newly created process. Previously, we ignored this handle, which meant it was leaking every time we created a new job container (or anything else that uses internal/exec in the future).
Process handle leaks can be bad as an exited process is left as a "zombie" until all handles to it have closed, continuing to use memory.
Fix this by closing the handle from CreateProcess.

Fix process handle leak when launching a job container

---

internal/guest/runtime/runc/container.go
internal/guest/runtime/runc/runc.go

This reverts commit b1b07686425bd7e4594f46a153aa84bf224acf66.
This work was done as an experiment, and is no longer being used.

Revert "gcs: Support routing container stdio to sidecar"

---

internal/exec/exec.go

exec today has two problems with how it handles stdio pipes:
- When Wait completes, closeStdio() is called. This closes the parent-side stdio pipes for receiving IO from the process. This is a problem because once the process has completed, we still need to be able to receive any final output. Today data from the process could be lost because of this.
- The parent's handles to the child-side stdio pipes are not closed after starting the process. Leaving duplicates of these handles in the parent process means that the other ends of the pipes are never closed when the process exits.
This commit makes the following changes:
- The parent's handles to the child-side stdio pipes are now closed after the child is started. This is necessary so that once the child exits, the parent-side pipes will …

internal/exec: Fix stdio pipe problems

---

internal/guest/runtime/hcsv2/spec_devices.go

This PR updates support assigned devices to allow for finding multiple dev nodes (under /dev) that correspond to an assigned device. 
Example scenario, nvidia gpu kernel modules create the following dev nodes that need to be present in a container to interact with the GPU: 
- /dev/nvidiaX (where X is the index of the GPU)
- /dev/nvidia-uvm
- /dev/nvidiactl
- /dev/nvidia-uvm-tools

Allow mounting multiple dev nodes per assigned device

---

test/cri-containerd/test-images/argsescaped/dockerfile
test/cri-containerd/test-images/imagepull_timestamp/Dockerfile
test/cri-containerd/test-images/nanoserver-gracefultermination-repro/latest/Dockerfile
test/cri-containerd/test-images/servercore-gracefultermination-repro/latest/Dockerfile

tests: update docker images
Update docker image hashes to satisfy compliance requirements.
The images have been rebuilt.

tests: update docker images

---

internal/wclayer/cim/process.go

For WCIFS based layers, a container scratch base VHD (and a differencing VHD) both are created per unique base layer. This is because we add reparse points for the base layer files inside the VHD. However, with UnionFS we don't add any reparse points and the VHD is empty, so we don't need to create a VHD per unique base layer. Now the CimFS snapshotter will handle container scratch VHD creation and the LayerWriter will only created a VHD for the UtilityVM. (The UtilityVM VHD still needs to be created per unique base layer since the BCD of that layer is configured to boot from the UtilityVM VHD and the BCD is unique per image)

Don't create container scratch per base layer

---

.github/workflows/codeql.yml

CodeQL Analyze job fails with:`Resource not accessible by integration`, and logs show the following help:
This run of the CodeQL Action does not have permission to access Code Scanning API endpoints.
As a result, it will not be opted into any experimental features. This could be because the Action is running on a pull request from a fork. If not, please ensure the Action has the 'security-events: write' permission. Details: Resource not accessible by integration
Add `security-events: write`, along with default `contents` and `packages` read permissions.

Fix CodeQL pipeline failure

---

internal/cmd/cmd.go
internal/cmd/cmd_test.go
internal/cmd/io.go

Have `internal\cmd.Cmd` ignore relay and close errors from the underlying IO channel being closed, since not all
`io.Reader`/`io.Writer`s return an `io.EOF` if the are closed during an IO operation.
This standardizes behavior between an `hcs`/`gcs` `Process` (which use a `go-winio.win32File` for their IO channels, and return `io.EOF` for read and write operations on a closed handle) and `JobProcess` (which uses an `os.Pipe` that instead return an `os.ErrClosed`).
Additionally, ignore errors from closing an already-closed std IO channel.
Update `Cmd.Wait` to return a known error value if it times out waiting on IO copy after the command exits (and update `TestCmdStuckIo` to check for that error).
Prior, the test checked for an `io.ErrClosedPipe`, which:
1. is not the best indicator that IO …

Update Cmd IO handling

---

internal/cmd/io_binary.go
internal/cmd/io_binary_test.go

Windows UNC paths weren't properly handled by `filepath.Clean` and this behavior was fixed in
https://github.com/golang/go/commit/be9d78c9c5905fbc10d8cd6a4714dd4ad1c91674
For a binary URL `binary:///\executable`, the `URL.Path` will be `/\executable` and `filepath.Clean`
will now return `\\executable`, which previously would return `\executable`.
In the case of binary logger, it'd be safer to not accept UNC paths, so this PR adds a
short circuit when the clean path starts with `\\`.

update `newBinaryCmd` URL path handling

---

.github/workflows/ci.yml
.github/workflows/codeql.yml
.github/workflows/release.yml
ext4/dmverity/dmverity_test.go
go.mod
go.sum
internal/cmd/io_binary.go
internal/cmd/io_binary_test.go
internal/cmd/io_npipe.go
internal/tools/networkagent/main.go
internal/winapi/utils.go
test/go.mod

Upgrade hcsshim/main to golang 1.21

Upgrade to go1.21

---

internal/jobobject/jobobject.go
internal/winapi/jobobject.go

`isJobSilo` is currently at the mercy of the Go compiler, as it is using a `SILOOBJECT_BASIC_INFORMATION` with a wrong alignment. Win32 expects it to be 4-bytes aligned, while `struct { _ [16]byte}` is 1-byte aligned.
This hasn't produced any failure yet because previous to Go 1.22, the Go compiler always laid memory aligned to 16-bytes, but that's no longer the case since Go 1.22. Extract from [1.22 release notes](https://go.dev/doc/go1.22):
> ... this change adjusts the size class boundaries of the memory allocator ...
> A consequence of this change is that some objects' addresses that were previously always aligned to a 16 byte (or higher) boundary will now only be aligned to an 8 byte boundary. Some programs that use assembly instructions that require memory addresses to be more than …

fix SILOOBJECT_BASIC_INFORMATION alignment

---

cmd/containerd-shim-runhcs-v1/exec_hcs.go
internal/gcs/bridge.go
internal/guest/bridge/bridge.go

This PR adds spans and drops debug logs to trace logs for large size high volume debug logs (bridge send, bridge receive, request read request and request write response traces). These logs carry the payload and incoming/outgoing message fields which cause the message column to be between 1000-4500 bytes. But since these logs are helpful for connectivity issues, it would be helpful to add spans and drop to trace level.

Add spans and drop large size high volume logs to trace level

---

internal/guest/runtime/hcsv2/spec_devices.go

There are two main issues to solve when hot adding devices in the UVM:
- We have no generic way to know when a device is actually ready to use and the relevant /dev nodes have been created.
- We have no way to know how many /dev nodes to look for unless we had device and vendor specific handling in our code. 
Given that our existing support for assigned devices attempts to handle devices in a very device- and vendor- generic way, there is a race condition between when we hot add devices to the UVM for the first time during container creation and when the /dev nodes have been created. We attempt to minimize this by adding retry logic for when we try to find related /dev nodes. 
This does not entirely solve our problems, since there could be a case where we find only a subset of the desired …

Add the ability to retry when looking for hot added device nodes

---

internal/annotations/annotations.go
internal/oci/annotations.go
internal/oci/annotations_test.go
internal/oci/uvm.go
internal/uvm/create.go
internal/uvm/create_lcow.go
internal/uvm/create_wcow.go
internal/uvm/start.go

Allow specifying the hyper-v configuration for specific service GUIDs via an annotation to allow dedicated hvsocket communication from the host to the guest

Add hvsock service config annotation

---

.github/workflows/ci.yml
.github/workflows/codeql.yml
Makefile
README.md
init/init.c

This PR allows for loading kernel modules in the init binary that is run during UVM boot. This is necessary for running certain distros of linux since many builtin modules have been moved out into their own .ko files. We use the same library, libkmod, that is used by programs like systemd and dracut to accomplish this. 
We could alternatively manually call the __NR_finit_module syscall with each .ko file that we find to load the modules. However, some modules have dependencies on other modules being loaded first, which would require us to manually track the dependency graph of modules. When you run `depmod` in a system, a series of files such as [modules.dep](https://www.man7.org/linux/man-pages/man5/modules.dep.5.html) are created under /lib/modules/<uname -r>. These files contain …

Use kmod library to load modules in init script

---

init/init.c

`libkmod` relies of `libc`, which means we no longer can build with `musl`.
Remove reference to it.

Remove musl references

---

.github/workflows/release.yml

Updating job permissions to be "write" instead of the default "read" so that the pipeline is able to succeed. Updating the GitHub release action version to 2.0.4 to remove node.js warning.

Updating Release CI Yaml

---

.github/workflows/release.yml

The permissions block should be under `create_release` job, rather than `build`.

fix: move permissions to the correct job

---

.github/workflows/release.yml

The permissions block should be under `create_release` job, rather than `build`.
(cherry picked from commit 3eeba905b4e0a408b372e3de326f00c70bdb442a)

fix: move permissions to the correct job (#2080)

---

internal/guest/storage/devicemapper/devicemapper.go
internal/guest/storage/devicemapper/devicemapper_test.go
internal/guest/storage/devicemapper/targets.go

Testing revealed that creating device mapper targets sometimes yields `device or resource busy` error (`EBUSY`). Add it to the list of retriable errors and consolidate them into a single slice.
Add unit tests for `CreateDeviceWithRetryError`.

devicemapper: add `EBUSY` to the retriable errors

---

.github/workflows/release.yml

The release Github action will automatically publish a release for each non-rc tag
in a form `v*`, which is not desired. This may lead to accidents described in https://github.com/microsoft/hcsshim/issues/2084
Change the release action to instead create draft releases, regardless of the tag being
final or RC.
It will be up to the maintainers to decide when to publish an official release.

gh-actions: prevent publishing release automatically

---

internal/jobobject/jobobject.go
internal/winapi/jobobject.go
internal/winapi/zsyscall_windows.go

Update `JOB_OBJECT_ALL_ACCESS` value to the most recent one.
Update `winapi.OpenJobObject` to accept `inheritHandle` as `bool`
as the documentation suggests.

Update `JOB_OBJECT_ALL_ACCESS` and `OpenJobObject`

---

internal/guest/runtime/hcsv2/nvidia_utils.go

Removing an out-of-date configuration option on libnvidia-container that prevented devices from being added to container device cgroups. This caused the need to run containers as privileged to access devices.

Remove no-cgroups option in gpu code path

---

internal/oci/uvm.go

Since we added support to use the rootfs VHD as a `VirtualDisk` instead of a vpmem device when the vpmem count is 0 (code [here](https://github.com/microsoft/hcsshim/blob/c248e516653406d3be399a48dd8bc012f0ac3f09/internal/uvm/create_lcow.go#L730)), we can use the rootfs VHD in scenarios where we want the UVM to be backed entirely with physical memory.

Remove requirement on initrd for fully physically backed UVM

---

Makefile
Makefile.bootfiles

The existing Makefile grew pretty large and now has a few additional dependencies like python and crypto for SNP targets.
The idea behind the split is that the new Makefile.bootfiles can be used to create Linux boot files and it depends only on `delta*.tar.gz`. This is useful in e.g. multi staged build process, where `delta*.tar.gz` artifacts can be produced separately from the final boot files. Since the delta can be applied to any base image, the build job that does it, wouldn't need go runtime or C compiler.

split existing Makefile

---

internal/uvm/scsi/backend.go

When unmounting LCOW read-only container layers with layer integrity enabled, the guest checks whether the unmount request is coming for a read-only SCSI device. If that's the case, GCS also attempts to clear out the corresponding verity targets. Current implementation omits the `ReadOnly` setting in the guest request, which results in verity targets to linger even though the target has been unmounted. The security policy is also unaware that the layer has been unmounted, since it's enforced only when `ReadOnly` is set to `true`.
This PR fixes this on the host side, by ensuring that the `ReadOnly` is set in the guest request. It seems, though, we may need to revisit the enforcement logic to potentially deny unmounting a read-only layer when the host is not explicitly specifies it as …

fix: set `ReadOnly` when unmounting LCOW mapped virtual disk

---

internal/uvm/create_lcow.go

When a SCSI device is added to an LCOW UVM the controllers inside
the guest can be reliably mapped via their corresponding GUIDs.
Make sure that we are adding the rootfs and corresponding rootfs
hash device to the correct controller 0.

fix scsi attachment for verity boot

---

internal/uvm/create_lcow.go

Make sure that there's no potential race in accessing
rootfs.vhd and rootfs.hash.vhd when multiple SNP pods
are created concurrently with verity boot.

copy rootfs and hash VHD to bundle directory for SNP

---

internal/guest/bridge/bridge.go

In addition to scrubbing create container requests, add
scrubbing of execute process requests inside the guest.

scrubbing: scrub execute process message inside the guest

---

Makefile.bootfiles
internal/annotations/annotations.go
internal/oci/uvm.go
internal/uvm/create_lcow.go
pkg/annotations/annotations.go

Turned out that dev nodes for SCSI devices may not be
determenistic, where the hash device and rootfs may end
up appearing under /dev/sda and /dev/sdb respectively.
Instead of mounting a separate hash device, append the
verity Merkle tree to rootfs ext4 filesystem, similarly
to how it's done for layer VHDs and mount single VHD.
Remove redundant hash device code.
The default `GuestStateFile` filename was changed to `kernel.vmgs`.
Update the IVGM kernel init to reflect the changes.
The kernel command looks something like this:
```
8250_core.nr_uarts=0 panic=-1 debug loglevel=7 root=/dev/dm-0 \
dm-mod.create="dmverity,,,ro,0 173768 verity \
1 /dev/sda /dev/sda 4096 4096 21721 21721 sha256 \
42896a788a58da77b6acb8ddf53aa744bd269c19146cfdf48eb8fc5529a52e62 \ …
```

verity-boot: append hash device to rootfs

---

cmd/runhcs/create-scratch.go
pkg/go-runhcs/runhcs_create-scratch.go

The create-scratch command creates a UVM that is used to mount a vhdx file and format as ext4. This is necessary since windows does not have any existing tooling that can format a disk as ext4. This PR changes the create-scratch code such that the UVM uses physical backed memory instead of virtual backed memory by default. Additionally, the PR adds the option to specify that you want a virtual backed UVM instead. 
The create-scratch command is called by containerd [here](https://github.com/containerd/containerd/blob/ccc41e6705c9f8fd8d1ec9ea2a4b9db2a03e809e/plugins/snapshots/lcow/lcow.go#L469) to create scratch vhdxs for containers. This should only happen once per deployment of containerd on the hosting machine since the first time we attempt to pull an image with the lcow snapshotter, …

Change runhcs create-scratch to use physical backed memory by default

---

hcn/hcn.go
hcn/hcnerrors.go
hcn/hcnglobals.go
hcn/hcnsupport.go

This to check the if the current version of hns supports modify loadbalancer. These functions will be used by Kube proxy to decide whether to go with modify loadbalancer api or not.

Changes for checking the global version for modify policy version support.

---

hcn/hcn.go
hcn/hcnerrors.go
hcn/hcnglobals.go
hcn/hcnloadbalancer.go
hcn/hcnloadbalancer_test.go
hcn/hcnpolicy.go
hcn/hcnsupport.go
hcn/hcnutils_test.go
internal/hns/hnspolicy.go

c79a6310e6f15a893430063ca76f44dcb7711426 : https://github.com/microsoft/hcsshim/pull/2106 
8beabacfc2d21767a07c20f8dd5f9f3932dbf305 : https://github.com/microsoft/hcsshim/pull/2139
0f7d8de9948c3ebfd45911dc55b451d8902d48b2 : https://github.com/microsoft/hcsshim/pull/2085

[release/0.12] Backport networking commits

---

internal/devices/assigned_devices.go
internal/hcsoci/devices.go
internal/oci/uvm.go
internal/uvm/create.go
internal/uvm/create_lcow.go
internal/uvm/create_wcow.go
internal/uvm/types.go
internal/uvm/virtual_device.go

This PR adds the ability pass devices on the OCI spec for the pod as devices on the UVM's compute system document sent to HCS. This will add devices at the UVM's boot time, instead of hot adding them afterwards.

Support passing oci devices on pod boot

---

hcn/hcn.go
hcn/hcnerrors.go
hcn/hcnglobals.go
hcn/hcnloadbalancer.go
hcn/hcnloadbalancer_test.go
hcn/hcnpolicy.go
hcn/hcnsupport.go
hcn/hcnutils_test.go
internal/hns/hnspolicy.go

https://github.com/microsoft/hcsshim/commit/c79a6310e6f15a893430063ca76f44dcb7711426 : https://github.com/microsoft/hcsshim/pull/2106 ---> direct cherry-pick
https://github.com/microsoft/hcsshim/commit/8beabacfc2d21767a07c20f8dd5f9f3932dbf305 : https://github.com/microsoft/hcsshim/pull/2139 ---> This commit had merge conflicts that were fixed.
https://github.com/microsoft/hcsshim/commit/0f7d8de9948c3ebfd45911dc55b451d8902d48b2 : https://github.com/microsoft/hcsshim/pull/2085 ---> This commit had merge conflicts that were fixed.

[release/0.11] Backport networking commits

---

hcn/hcn.go
hcn/hcnerrors.go
hcn/hcnglobals.go
hcn/hcnloadbalancer.go
hcn/hcnloadbalancer_test.go
hcn/hcnpolicy.go
hcn/hcnsupport.go
hcn/hcnutils_test.go
internal/hns/hnspolicy.go

https://github.com/microsoft/hcsshim/commit/c79a6310e6f15a893430063ca76f44dcb7711426 : https://github.com/microsoft/hcsshim/pull/2106 ---> direct cherry-pick
https://github.com/microsoft/hcsshim/commit/8beabacfc2d21767a07c20f8dd5f9f3932dbf305 : https://github.com/microsoft/hcsshim/pull/2139 ---> This commit had merge conflicts that were fixed.
https://github.com/microsoft/hcsshim/commit/0f7d8de9948c3ebfd45911dc55b451d8902d48b2 : https://github.com/microsoft/hcsshim/pull/2085 ---> This commit had merge conflicts that were fixed.

[release/0.9] Backport networking commits

---

.github/workflows/ci.yml
hcn/hcn.go
hcn/hcnerrors.go
hcn/hcnglobals.go
hcn/hcnloadbalancer.go
hcn/hcnloadbalancer_test.go
hcn/hcnpolicy.go
hcn/hcnsupport.go
hcn/hcnutils_test.go
internal/hns/hnspolicy.go

https://github.com/microsoft/hcsshim/commit/c79a6310e6f15a893430063ca76f44dcb7711426 : https://github.com/microsoft/hcsshim/pull/2106 ---> direct cherry-pick
https://github.com/microsoft/hcsshim/commit/8beabacfc2d21767a07c20f8dd5f9f3932dbf305 : https://github.com/microsoft/hcsshim/pull/2139 ---> This commit had merge conflicts that were fixed.
https://github.com/microsoft/hcsshim/commit/0f7d8de9948c3ebfd45911dc55b451d8902d48b2 : https://github.com/microsoft/hcsshim/pull/2085 ---> This commit had merge conflicts that were fixed.

[release/0.8] Backport networking commits

---

internal/guest/runtime/hcsv2/nvidia_utils.go

Previously the `load-kmods` option was set for libnvidia-container because we were not loading the kernel modules at pod boot time. However, recent changes https://github.com/microsoft/hcsshim/pull/2167 would allow for loading kernel modules at boot time. We need to remove `load-kmods` so we don't attempt to load the modules twice. 
Note: this also requires that persistence mode has been set in the pod so that the GPUs stay initialized between pod boot and container start.

Remove load-kmods option to libnvidia-container

---

internal/oci/annotations.go
internal/oci/annotations_test.go
pkg/annotations/annotations.go

Host process containers are not safe for multi-tenant scenarios since they run directly on the host and use the host's network. Don't allow host process containers to be used when `DisableUnsafeOperations` is set.

Disable host process containers when disable unsafe operations is enabled

---

Makefile
init/init.c

This PR adds back the support for loading kernel modules in the init script and adds a definition block around the code. This was necessary because some images we use do not have all the dependencies that kmod needs installed, causing the pods to fail to boot. To compile with this variable, you can run:  
```
make KMOD=1 bin/init
```
This PR is essentially this PR https://github.com/microsoft/hcsshim/pull/2034 with the additional Makefile work and C macro.

Add support for loading modules in init script when makefile variable is set

---

internal/hns/hnsendpoint.go

The struct HNSEndpoint is used by CNIs like calico to validate the state of an endpoint. In order to support Hyperv containers on k8s we need to expose the State attribute. This attribute can be used by CNIs to determine the state of the endpoint.
HNS API versions: 
Hcsshim supports both APIS v1 and v2 via the HCN folder (documented way) or via hns files in the root which expose internal/hns apis 
CodeFlow:   
Calico::endpoint_mgr.go::RefreshHnsEndpointCache  --> hns.HNSListEndpointRequest() which lands at hcsshim/hnsendpoint.go which calls into the internal HNS package at /hcsshim/internal/hns which runs a get call into HNS OS code.

Adding state attribute to the HNSEndpoint struct to support hyperv 

---

hcn/hcn.go
hcn/hcnglobals.go
hcn/hcnsupport.go
hcn/hnsv1_test.go
hnsaccelnet.go
internal/hns/hnsaccelnet.go

Hcsshim wrapper over HNS API needed for exclusion of management mac addresses for VF reassignment

Hcsshim wrapper over HNS API needed for exclusion of management mac addresses for VF reassignment 

---

internal/exec/exec.go

Cherry-picking this PR into release/0.11
https://github.com/microsoft/hcsshim/pull/2020
commit: 976716ed6294e3a641d80196dcb08ac5eefd4091
CreateProcess gives us back a handle to the newly created process. Previously, we ignored this handle, which meant it was leaking every time we created a new job container (or anything else that uses internal/exec in the future).
Process handle leaks can be bad as an exited process is left as a "zombie" until all handles to it have closed, continuing to use memory.
Fix this by closing the handle from CreateProcess.

[release/0.11]: Fix process handle leak when launching a job container

---

internal/exec/exec.go

Cherry-picking this PR into release/0.9
https://github.com/microsoft/hcsshim/pull/2020
commit: https://github.com/microsoft/hcsshim/commit/976716ed6294e3a641d80196dcb08ac5eefd4091
CreateProcess gives us back a handle to the newly created process. Previously, we ignored this handle, which meant it was leaking every time we created a new job container (or anything else that uses internal/exec in the future).
Process handle leaks can be bad as an exited process is left as a "zombie" until all handles to it have closed, continuing to use memory.
Fix this by closing the handle from CreateProcess.

[release/0.9] Fix process handle leak when launching a job container

---

internal/tools/uvmboot/lcow.go

Rely on default `sh` to be in `PATH` rather than hardcoding to `/bin/sh`
when using uvmboot with GCS and exec.

fix: uvmboot gcs exec

---

internal/uvm/create.go
test/functional/hvsock_test.go
test/functional/main_test.go
test/internal/util/reexec.go
test/pkg/uvm/uvm.go

Add tests for binding to and listening on hyper-v sockets from within a uVM (as well as a hyper-v isolated containers).
Tests verify default SDDL and wildcard bind settings, as well updating the settings for a particular service ID.
In order to test HVSocket communication, an agent is needed to run from within the uVM (or container within that).
To accomplish that, the ability to re-exec the (functional) testing binary is added, so that it can be shared into the uVM (or container) and then run a separate code path that is defined within the same test case that is running on the host.
For example, while running the test case `TestHVSock_Container_GuestBind/default`, the functional testing binary
that is being run (i.e. `functional.test.exe`) is shared within the running container and then …

[test] Add Hyper-V socket functional tests

---

hcn/hcn.go
hcn/hcnglobals.go
hcn/hcnnetwork.go
hcn/hcnsupport.go
hcn/hnsv1_test.go
hnsaccelnet.go
internal/hns/hnsaccelnet.go

c8451ee02b701ab1b7efbad6e21e3fbaea6cb038 -> 0ec29e7298d54fd10a7703e36af3ee6ac04a49e1
ab958a7a2e2e4ad63089183a8a6bc0df1c1167b7 -> e4f58faee160ca1849956b97c34c8b6b6b56934e

[release/0.12] Backport networking commits for L1VH feature

---

internal/guest/runtime/hcsv2/uvm.go

When filesystem mount fails, we attempt to cleanup read-write mount tracking. 
However, the return error is being shadowed and `RemoveRWDevice` is never called.

fix: error shadowing removing read-write mount tracking

---

cmd/runhcs/create-scratch.go

This PR increases the memory size of the UVM that is created to create the initial scratch VHD. Since creation of the scratch VHD should only happen once per installation/reboot, this should not negatively impact any scenarios. 
This change was needed after testing running with an Azure Linux based UVM. Azure Linux needs more memory to boot than the previous UVM which was leading to a kernel panic during creation of the scratch.

Add higher memory size for create scratch UVM 

---

internal/uvm/create.go

This code previously attempted to gracefully remove DDA'd devices from a pod on close. However, the platform does not require that we gracefully remove DDA devices and attempting to do so may increase the time it takes to stop the pod. 
For example, the attempted graceful removal of NVIDIA GPUs when nvidia-persistenced is running increases the pod stop time by more than 3x.

Remove graceful removal of DDA devices added on pod boot

---

init/init.c

This PR adds the ability to run nvidia-persistenced and nv-fabricmanager in the init script. Does not fail the init script if the binaries for these daemons are not on the system. This PR additionally adds helper functions for writing to dmesg. 
This is the first iteration of this support. This work is incomplete without the ability to get insights into the statuses of the daemons and collect their logs. Most daemons write logs using syslog, however, since we do not use systemd, we need an alternative to this  in the future.

Start nvidia-persistenced and nv-fabricmanager daemons in init script

---

internal/lcow/scratch.go

By default, create LCOW will set the number of SCSI controllers to 4,
when VPMem isn't used, which is the case when formatting scratch.
This makes the device path lookup non-determenistic, since the
SCSI controllers in the guest may have different indices.
To workaround that, use a block device mount and
use the mount-path to format the scratch VHDX
without needing to lookup the actual dev node path.

fix: use block device mount to format scratch

---

README.md

The file changed locations in the containerd repo. I believe this new path is the correct file

updating a link in the readme to its new location

---

internal/uvm/network.go
internal/uvm/network_test.go

This addresses an issue where when adding multiple interfaces, the eth0 interface in the guest does not correspond correctly to the primary NIC that the CNI intended. This happens because hcsshim queries HNS to get the list of endpoints for the network namespace and adds the endpoints sequentially based on what is returned from HNS. HNS guarantees no specific ordering of endpoints returned from this query. 
CNI names the interfaces such that they have the suffix `-ethX` where X is the index for the interface. We could leverage this information in the future to sort all the endpoints according to index. However, I didn't think that was necessary here since we are only working with two endpoints added to the UVM and the CNI team confirmed they do not care about the ordering of the non-eth0 …

Sort the endpoints such that eth0 is first

---

init/init.c

This PR removes the check that will cause the kernel to panic when an error is returned from ftw. See the comment for explanation why we ignore errors. This PR just treats all errors from ftw the same.

Remove kernel panic when kmod load fails

---

.github/codeql/codeql-config.yml
.github/workflows/codeql.yml

It appears GH doesn't recognize our CodeQL pipeline and attempts to run its own default version.
Rename the workflow to conform to what GH expects of the standard "advanced setup" for CodeQL, with some minor updates:
- run on `release/*` branches
- use the recommended job permissions
- explicit `manual` build mode
- use `c-cpp` instead of `cpp`
- add a `codeql-config` file to ignore the test and vendor directories
Based on recommendations here, which simple create the appropriate workflow:
https://docs.github.com/en/enterprise-cloud@latest/code-security/code-scanning/creating-an-advanced-setup-for-code-scanning/configuring-advanced-setup-for-code-scanning-with-codeql-at-scale

Configure advanced codeql.yml scanning

---

internal/guest/bridge/bridge.go
internal/guest/runtime/hcsv2/container.go
internal/guest/runtime/hcsv2/uvm.go
internal/jobobject/jobobject.go
internal/jobobject/jobobject_test.go
internal/log/scrub.go
internal/uvm/counter.go
internal/uvm/types.go
test/gcs/helper_conn_test.go

Per Go documentation recommendation (e.g. [link](https://pkg.go.dev/sync/atomic#AddUint64)), use the `atomic` types and their associated methods instead of the `atomic.Add*`/`.Store*` functions.
This makes the intent for atomic access clearer, prevents (accidental) non-atomic access, and (for boolean variables) simplifies code.

Use `atomic` types instead of raw values

---

.github/actions/setup-go/action.yml
.github/workflows/ci.yml
.github/workflows/codeql.yml
.github/workflows/release.yml

Create composite action to call `actions/setup-go` with common values and logic across different jobs and workflows to reduce duplication and make sure workflows all use the same Go version.
Specifically, the action defaults to `oldstable` for the Go version, uses both `go.sum` and `test/go.sum` for the cache dependency, and allows pre-filling the Go module cache after installing Go.
It exposes the same outputs as `actions/setup-go` as well.

Consolidate Go installation step

---

.clang-format
init/init.c
vsockexec/vsock.c
vsockexec/vsockexec.c

Add `.clang-format` file that can be used directly by the clang formatter or by the Microsoft C/C++ VSCode extension. Style based on Microsoft default style guide, but update brace and case indentation settings to match current files better (as well as Go code).
Run formatter on `init\init.c` and `vsockexec\*`. Changes mostly with brace position, spacing, indentation, and pointer alignment.

Add `.clang-format` and format C files

---

cmd/dmverity-vhd/main.go

Update dmverity tool to fix bug where hdv creation fails to move all VHDs from the temp dir.
To recreate the error, run:
go run cmd\dmverity-vhd\main.go create -i python:latest -o python_layers -hdv
You will notice the following output:
hash device created at python_layers\8f4ceb8cc1a2056b98f0424fad4715dd334aecc9769186b3ea0394f131524e27.hash-dev.vhd
hash device created at python_layers\916d866d5b0dc17158c78e5a09717fcf619b04450125caafa9c1b8f7aa6a2c45.hash-dev.vhd
hash device created at python_layers\0d80db6a0977d5ade37d5d248772c0e9aaa1b6c898ddb31b26c803ee1a9f57a2.hash-dev.vhd
hash device created at python_layers\28e03088bc157bfe42d66970cf7f47de35821aabaece5f767804902a8fa1d779.hash-dev.vhd
hash device created at python_layers\2c3d7750fa05a52d63169a54cb95f1c7415cff5abe04d8e8f083b1a66a7a90fc.h …

Update dmverity tool to fix bug where hdv creation fails

---

.github/workflows/ci.yml
cmd/containerd-shim-runhcs-v1/pod_test.go
cmd/containerd-shim-runhcs-v1/service_internal_podshim_test.go
cmd/containerd-shim-runhcs-v1/service_internal_taskshim_test.go
cmd/containerd-shim-runhcs-v1/task_hcs_test.go
ext4/dmverity/dmverity_test.go
internal/tools/networkagent/main.go

Update ci.yml to use golang 1.20 + fix lint errors with math.Rand
This change fixes the long standing mingw errors PRs were running into in release/0.11

[release/0.11] Update golang version in ci.yml

---

init/init.c

This PR adds support for passing in a configuration file when running fabric manager in the init program. If this configuration file is not present on the machine, fabric manager will fall back to running with all default settings. 
The config file can be customized to determine where the fabric manager's logs will be output, when to rotate the log files, fabric operation mode, and more. See [fabric manager doc](https://docs.nvidia.com/datacenter/tesla/pdf/fabric-manager-user-guide.pdf) for more details on how fabric manager works and how it can be configured.

Support passing in fabric manager config

---

internal/gcs/guestcaps.go
internal/gcs/guestconnection.go
internal/gcs/protocol.go
internal/uvm/capabilities.go
internal/uvm/dumpstacks.go
internal/uvm/network.go
internal/uvm/start.go
internal/uvm/types.go
test/functional/uvm_properties_test.go

This PR refactors the guest defined capabilities work so that we can more easily distinguish between capabilities defined by WCOW runtimes and LCOW runtimes.

Refactor guest defined capabilities

---

ext4/internal/compactext4/compact.go
ext4/tar2ext4/tar2ext4_test.go

`./dmverity-vhd roothash` is  not deterministic for some file docker images.
```bash
IMAGE=gcr.io/distroless/cc-debian11@sha256:d5a2169bc2282598f0cf886a3d301269d0ee5bf7f7392184198dd41d36b70548
docker pull $IMAGE > /dev/null
./dmverity-vhd -v -d roothash -i $IMAGE > bad-debian-1.txt
./dmverity-vhd -v -d roothash -i $IMAGE > bad-debian-2.txt
diff  bad-debian-1.txt bad-debian-2.txt
```
The above command shows a diff which suggest it's not deterministic.
This is causing a problem for `az confcom` tool that the generated security policy is not consistent for each run (`./dmverity-vhd roothash`  is called [here](https://github.com/Azure/azure-cli-extensions/blob/316fd959d9904c1d91a66ce0242eddaa87c4202d/src/confcom/azext_confcom/rootfs_proxy.py#L120)).
Container deployment is blocked as well for …

Make tar2ext4 deterministic with files without parent dir in tar

---

internal/uvm/create_lcow.go

When creating HCS doc for SNP UVM with verity boot, the SCSI
controllers are overriden to always have only a single SCSI
controller. This limits the max number of container layers to 64.

fix: verity boot overrides SCSI config

---

internal/devices/drivers.go
internal/hcsoci/resources_lcow.go
internal/hcsoci/resources_wcow.go
internal/layers/lcow.go
internal/layers/wcow_mount.go
internal/lcow/disk.go
internal/lcow/scratch.go
internal/tools/uvmboot/mounts.go
internal/uvm/scsi/manager.go
internal/uvm/scsi/manager_test.go
internal/uvm/scsi/mount.go
test/functional/uvm_scratch_test.go
test/functional/uvm_scsi_test.go

Adds support for callers to `internal/uvm/scsi.Manager` to specify a path where the disk will be mounted in the guest.
Adds unit tests for SCSI manager behavior.
Fixes a refcount bug found through the tests.
Details in the individual commits.

scsi: Support optional guest path for mount, add tests, refcount fix

---

internal/uvm/scsi/manager_test.go
internal/uvm/scsi/mount.go

This is to fix a case with shared scratch enabled where the pause container scratch and workload container scratch should be the same mountpoint. This effectively changes the SCSI mount logic to have the same semantics as before the SCSI refactor, which mainly affected:
* where the `runc` config.json for a container is written
* scratch encryption
The old semantics ensured that the scratch (in a shared scratch case) is encrypted only once and also ensured that runc config.json for a given container is written to a unique location: either container's scratch (when scratch isn't shared) or tmpfs (when scratch is shared).
As before, the eventual hope is to remove guestPath support, and always generate a path, but that requires more extensive work to pass this path to the GCS.

scsi: relax mount re-use constraint

---

internal/hns/hnsendpoint.go

We missed setting "Created" as an Endpoint state option, fixing that.
(cherry picked from commit 166e62a783e2ca9a19ab0402821178b15479b77f)

Fixing typo

---

internal/oci/uvm.go

This PR fixes a bug with the device parsing for adding devices on pod boot. This ensures invalid devices have been removed from the list of devices to add.

Fix parse pod devices to not include invalid devices

---

.github/workflows/ci.yml
.github/workflows/release.yml
cmd/containerd-shim-runhcs-v1/pod_test.go
cmd/containerd-shim-runhcs-v1/task_hcs_test.go
ext4/tar2ext4/tar2ext4.go
go.mod
go.sum
internal/cmd/io_binary.go
internal/cmd/io_binary_test.go
internal/cmd/io_npipe.go
internal/winapi/utils.go
test/go.mod
test/go.sum
vendor/github.com/containerd/containerd/mount/temp.go
vendor/github.com/containerd/containerd/version/version.go
vendor/modules.txt

Update golang versions used in github actions to 1.21.x, update containerd versiont o v1.6.26 and fix lint errors.

[release/0.11] Update golang CI version + containerd version to v1.6.36

---

internal/guest/network/netns.go

In more recent golang versions, net library's implementation of ParseIP was changed to always return a byte array of length 16 whether or not the parsed IP is IPv4 or IPv6 (see [here](https://pkg.go.dev/net#ParseIP)). However, the GCS was relying on the length of ParseIP to match the IP type when calculating a mask length before adding the gateway address. 
Without this change, a mask length of 128 is always created in cases where we add a gateway address that is outside the interface's subnet. If the gateway IP is IPv4 and the mask length is 128, then the call to `netlink.AddrAdd` will return `invalid argument` and we will fail to create a pod.

Fix issue with mask length of gateway addresses

---

internal/hns/hnsendpoint.go

We missed setting "Created" as an Endpoint state option, fixing that.
(cherry picked from commit 166e62a783e2ca9a19ab0402821178b15479b77f)

[release/0.11] Fixing typo

---

internal/uvm/cpulimits_update.go
test/cri-containerd/pod_update_test.go

Prevent test break by adding in a build version requirement when updating pod CPU limits. This feature was not added in HCS until 20H2.

Add build version block for pod CPU limits updating

---

go.mod
test/go.mod

As of recent Go versions, specifying the go directive without a patch (e.g. 1.22) is no longer supported. Because go tries to download a matching toolchain if you're not already using one, it will try to download go toolchain version 1.22, which doesn't exist (1.22.0 does).
Fix the go.mod version to specify the full version with patch, 1.22.0.

Fix go.mod to have the correct Go version

---

pkg/octtrpc/interceptor.go
pkg/octtrpc/interceptor_test.go

It turns out for years that the autogenerated TTRPC spans have not been marked correctly if the call failed. This is because defers evaluate their arguments immediately, rather than at the deferred execution time. Fix this by changing err from an argument to the defer, to a variable evaluated inside the defer.
Also adds tests for octtrpc client and server interceptors.

octtrpc: Fix span status defer, add tests

---

internal/hcs/schema2/cimfs.go
internal/layers/helpers.go
internal/layers/wcow_mount.go
internal/layers/wcow_parse.go
internal/resources/resources.go
internal/wclayer/cim/block_cim_writer.go
internal/wclayer/cim/cim_writer_test.go
internal/wclayer/cim/common.go
internal/wclayer/cim/file_writer.go
internal/wclayer/cim/forked_cim_writer.go
internal/wclayer/cim/mount.go
internal/wclayer/cim/pending.go
internal/wclayer/cim/process.go
internal/winapi/cimfs.go
internal/winapi/zsyscall_windows.go
pkg/cimfs/cim_test.go
pkg/cimfs/cim_writer_windows.go
pkg/cimfs/cimfs.go
pkg/cimfs/doc.go
pkg/cimfs/mount_cim.go
pkg/ociwclayer/cim/import.go

This PR adds support for creating, mounting and using block CIMs for running windows process isolated containers.
Individual commits provide additional details on what changes they bring in.

Support for Block CIMs

---

go.mod
osversion/platform_compat_windows.go
osversion/platform_compat_windows_test.go
osversion/windowsbuilds.go
test/go.mod

- Add V23H2 (annual channel) and LTSC2025 to the version list
- Use the LTSC build naming in the compat checks and tests, to make
intent clearer
- Fix a bug in the compat check. A given LTSC release should be able to
run everything from the previous LTSC up to itself
- Add new test cases, including for the fixed compat check bug
- Change the tests to use t.Run for each test case

osversion: Add new versions, fix compat bug, improve tests

---

test/functional/hvsock_test.go
test/internal/util/reexec_windows.go
test/internal/util/util_windows.go

Use the full path to the `functional.test.exe` binary when sharing into the uVM for the `TestHVSock_*` test cases in
`test\functional\hvsock_test.go` to prevent vSMB share issues.
Otherwise, `os.Args[0]` will return the path that the tests were run with (e.g., `.\functional.test.exe`), which can cause vSMB to fail with `The parameter is incorrect.` (likely because it cannot find the current file).

Use abs path to testing binary

---

.github/workflows/ci.yml

This PR enables the Windows UVM tests in the hcsshim functional test suite. It is done so by removing `uvm` from the exclusion flag of the test execution. In addition, the default gitHub runner was replaced with the 1ES gitHub runners which support nested virtualization.
Before the PR change, in the `test-windows` CI job, the step `build and run functional testing binary` shows result: **DONE 70 tests, 38 skipped in 37.046s**
After the PR change, in the `test-windows` CI job, the step `build and run functional testing binary` shows result: 
: **DONE 167 tests, 28 skipped in 476.079s**
Note: Linux UVM tests will be enabled in a follow-up PR as it requires additional changes.

Enable Windows UVM functional tests

---

internal/annotations/annotations.go
internal/guest/network/netns.go
internal/guest/network/netns_test.go
internal/guest/runtime/hcsv2/network.go
internal/oci/uvm.go
internal/protocol/guestresource/resources.go
internal/uvm/computeagent.go
internal/uvm/create_lcow.go
internal/uvm/network.go
internal/uvm/network_test.go
internal/uvm/types.go
pkg/annotations/annotations.go

- switch to HCN v2 endpoint API by default 
- Support parsing routes in GCS when we setup the network interfaces
- [breaking] update gcs bridge LCOW network adapter type with new fields that better align with v2 endpoint
- Add unit tests for new GCS side changes
- Add support for the legacy policy based routing with the new endpoint type 
The motivation for this change was to support adding custom routes on interfaces. However, the v1 endpoint implementation does not have this support. Therefore, we needed to move to the V2 implementation.

Add support for HCN v2 endpoint and add unit tests

---

.github/workflows/ci.yml

This PR fixes a bug that broke the `test-windows` step in the CI. The `matrix.os` was previously removed and not replaced. 
* [`.github/workflows/ci.yml`](diffhunk://#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fL393-R393): Updated the `name` field for the uploaded artifact to use `matrix.name` instead of `matrix.os`.

Fix duplicate artifact name in github CI

---

test/functional/lcow_networking_test.go

Previously we were just using the IPAM routes configured earlier in the test, but this causes an error since the IPAM route will append the scope identifier at the end of IPv6 routes' NextHop.

Fix TestLCOW_IPv6_Assignment functional test

---

.github/workflows/ci.yml
test/functional/uvm_plannine_test.go

This reverts commit e5c83a121b980b1b85f4df0813cfba2d83572bac.
The OIDC authentication is failing for PRs from external contributors because the `id-token` write permission is not granted to forked repos. Disabling the Linux UVM tests for now to unblock the CI for PRs from forked repos. Note that OIDC authentication will work fine if the PR is coming from the hcsshim repo itself. 
Detailed root cause:
According to [the github documentation](https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#workflows-in-forked-repositories-2), the `GITHUB_TOKEN` which includes the `id-token` has read-only permissions in pull requests from forked repositories. You can read more about this in [this Security Lab …

Revert "Enabled Linux UVM tests to run on 1ES github runner pool"

---

.github/workflows/ci.yml
.golangci.yml
hcn/hcnerrors.go
internal/exec/exec.go
internal/guest/gcserr/errors.go
internal/guest/network/netns_test.go
internal/hcs/process.go
internal/hcs/system.go
internal/hns/hnsaccelnet.go
internal/regopolicyinterpreter/regopolicyinterpreter.go
internal/vmcompute/vmcompute.go

seems like something broke with newer golang versions.
Update golangci-lint version and set `only-new-issues` to `true`.

github-actions: update lint action

---

.golangci.yml

golangci-lint config is now case sensitive and complains about
`Text` entries. Update to `text` to fix this.

fix golangci-lint config

---

internal/hcs/schema2/chipset.go
internal/hcs/schema2/firmware.go
internal/hcs/schema2/windows_crash_reporting.go
internal/layers/wcow_parse.go
internal/tools/uvmboot/conf_wcow.go
internal/tools/uvmboot/main.go
internal/uvm/create.go
internal/uvm/create_lcow.go
internal/uvm/create_wcow.go
internal/uvm/types.go
internal/wclayer/legacy.go

This PR brings in changes via 2 different commits:
First commit updates the WCOW boot files struct to allow different kinds of boot configurations for WCOW UtilityVMs.
Second commit builds on top of the first commit to add support for running confidential WCOW UtilityVMs. This involves using Block CIMs to boot the VM and setting other confidential VM specific configurations in the HCS doc of the UtilityVM.

Initial support for creating confidential windows UtilityVMs

---

internal/oci/annotations.go
internal/oci/annotations_test.go

Return all errors from `"internal/oci".ProcessAnnotations`. 
Update associated tests to check for expected errors.

Use multi-error for annotation processing

---

internal/winapi/devices.go
internal/winapi/zsyscall_windows.go
internal/windevice/devicequery.go
internal/windevice/devicequery_test.go

Adds the Go wrappers on windows device query APIs to allow finding a disk device by the provided LUN. This is mostly required inside the GCS where shim includes the LUN at which a disk is attaches in the request and then the GCS needs to be able to find that disk to use it further.

Support for querying disks based on LUN

---

cmd/mkuvmcim/main.go
pkg/extractuvm/bcim.go
pkg/extractuvm/bcim_test.go
pkg/extractuvm/utils.go
pkg/extractuvm/uvm_cim_writer.go
test/functional/make_uvm_cim_test.go

This commit adds a new tool that can take a valid Windows container image tarball and extracts all the UtilityVM files from that tarball into a block CIM. The end result should be a block CIM that has all the files necessary to successfully boot & run a UtilityVM.

Tool for extracting UtilityVM files from a container layer into a CIM

---

internal/guest/runtime/hcsv2/workload_container.go
internal/hcsoci/resources_lcow.go

Allow privileged LCOW containers to mount the uVM's filesystem. This supports cadvisor and related tools to monitor the pod and associated containers without needing to run directly within the uVM.
See: https://github.com/google/cadvisor

Add `uvm://` mount support for LCOW

---

test/pkg/uvm/lcow.go

Empty path was being added to lookup paths for `LinuxBootFiles`. Worked since the path was often just `C:\ContainerPlat`, but fix it regardless.
Also add check to make sure the `LinuxBootFiles` path found is also a directory.

Bug: when searching for `LinuxBootFiles`

---

internal/annotations/annotations.go
internal/oci/annotations.go
internal/oci/annotations_test.go
pkg/annotations/annotations.go

Break out `pkg\annotations\annotations.go` constants into sections (by container or uVM; LCOW, WCOW, or both) for easier searching and readability.
Deprecate `AnnotationExpansions` and instead provide `AnnotationExpansionMap()`, which returns the same value, but provides a
new copy every call, so the `map` cannot be modified.
Cannot delete it or change its type, since it is technically public.
Requires #2440.
A quick and dirty way to validate that no annotations have been deleted:
```pwsh
git checkout helsaawy/annotations-org
$r = '(?-i)^\s([A-Z]\w+)\s=\s"[\w\.\-/]+"'
$new = ((Select-String -Path .\pkg\annotations\annotations.go -Pattern $r).Matches.Groups | Where-Object Name -eq 1).Value
git checkout main
((Select-String -Path .\pkg\annotations\annotations.go -Pattern $r).Matches.Groups …
```

Organize annotations; change annotation expansions

---

internal/lcow/scratch.go

Log the stderr output when `mkfs.ext4` fails during scratch formatting. This should help troubleshooting easier, e.g. when the binary is missing or not properly symlinked etc.

log `mkfs.ext4` stderr output

---

.github/workflows/ci.yml

There are known regressions in Ws2025 networking
which is causing several sig-windows nightlies to fail as well.
Remove Ws2025 from CIs like we did in containerd for the interim

Remove WS2025 from CIs

---

ext4/tar2ext4/tar2ext4.go
internal/wclayer/cim/block_cim_writer.go
internal/wclayer/cim/common.go
pkg/extractuvm/bcim.go
pkg/extractuvm/bcim_test.go
pkg/extractuvm/uvm_cim_writer.go
pkg/ociwclayer/cim/import.go

This PR uses the new verified block CIM APIs to add the support for importing image layers in the verified block CIM format.
It also updates the UVM CIM makers tool to create verified CIMs.

Support for importing verified block CIM layers 

---

cmd/runhcs/container.go
internal/gcs/bridge.go
internal/guest/bridge/bridge.go
internal/guest/network/netns.go
internal/oci/uvm.go
internal/uvm/create.go
internal/uvm/create_lcow.go
internal/uvm/create_wcow.go
internal/uvm/vnuma.go
pkg/annotations/annotations.go

Warn if vNUMA is not completely specified in uVM creation options, as this is likely a user error.
Rename `"uvm".Opts.MaxSizePerNode` to `MaxMemorySizePerNumaNode` and clarify that it is measured in MiB. Similarly, rename `"annotations".NumaMaximumSizePerNode` to `NumaMaximumMemorySizePerNode`.
Format `prepareVNumaTopology` doc comment to display appropriately.
Related: switch to using `"logrus".IsLevelEnabled` rather than explicit logging level comparison, and fix bug where `--debug` flag was not added to runc if logging level is greater than `Debug` (i.e., `Trace`)

Warn on incomplete vNUMA setting, clarify field names

---

internal/guest/runtime/hcsv2/nvidia_utils.go
internal/guest/runtime/hcsv2/workload_container.go
internal/guest/spec/spec_devices.go
internal/hcsoci/devices.go

CUDA initialization for GPUs fails for non-privileged containers. Experimenting shows that adding `rw` for all character devices fixes the error, so expand the [default `c *:* m` permissions](https://github.com/opencontainers/runc/blob/6bae6cad4759a5b3537d550f43ea37d51c6b518a/libcontainer/specconv/spec_linux.go#L205-L222) to `c *:* rwm`.
Add `"gpu"` string constant and streamline device assignment logic.

Fix CUDA for non-privileged containers

---

internal/gcs/guestconnection_test.go
test/functional/hostprocess_test.go

Unit test `TestGcsWaitProcessBridgeTerminated` and the functional test `TestHostProcess_whoami` keeps failing intermittently on our github CI test runs. That blocks us from merging our PRs.
This commit fixes the race condition in the `TestGcsWaitProcessBridgeTerminated` test by adding a small sleep. The other test failure is probably more related to the test environment than the test itself. That will require additional investigations to fix the test, so the test is currently disabled.

Fix/Disable failing CI tests

---

internal/timeout/timeout.go
internal/uvm/start.go

Currently the uvm.Start() method hardcodes 2 minute timeout value in the context that gets used when making hvsocket connections to the UVM (for entropy, output handling & GCS) . This timeout is good enough for general scenario but is very restrictive when debugging uvm boot issues. This change allows overriding the default timeout via environment variables.
Another option that was considered, was to use the deadline/timeout passed in the context instead of hardcoding it. However, there is code in the Start method that explicitly assumes that the parent context won't have a timeout(we could probably get around that problem by creating a new context without a deadline). Another problem is that there are lot of existing callers of the Start method who may or may not include a proper …

Allow overriding UVM start timeout.

---

cmd/containerd-shim-runhcs-v1/pod.go
internal/fsformatter/formatter_driver.go
internal/gcs-sidecar/handlers.go
internal/gcs-sidecar/uvm.go
internal/guest/runtime/hcsv2/uvm.go
internal/layers/wcow_mount.go
internal/layers/wcow_parse.go
internal/oci/uvm.go
internal/oci/uvm_test.go
internal/protocol/guestresource/resources.go
internal/uvm/cimfs.go
internal/uvm/combine_layers.go
internal/uvm/create_wcow.go
internal/uvm/security_policy.go
internal/uvm/types.go
pkg/annotations/annotations.go
pkg/cimfs/mount_cim.go

This PR adds the support for running confidential UVMs/Pods and then running containers inside such pods. It also brings in some additional fixes related to confidential pods.
1. Support for starting confidential pods
This commit allows running confidential pods/UtilityVMs by including a non-empty security
policy in the pod config annotations. The files (VHDs & guest statef file) required for
starting such a confidential UVM MUST be available in a directory named
`WindowsBootFiles/confidential` that is located next to the shim binary.
2. Support for starting confidential containers
Adds support for mounting block CIM based container image layers inside the UVM.
(ResourceTypeWCOWBlockCims is only supported by sidecar GCS at the moment. Inbox GCS will
add this support soon.)
3. Include …

Support for starting confidential containers

---

internal/oci/annotations.go
internal/oci/uvm.go
internal/tools/uvmboot/main.go
internal/uvm/create.go
internal/uvm/create_lcow.go
internal/uvm/create_wcow.go
pkg/annotations/annotations.go

Adds annotation for resource partition id, when present, set the
corresponding field on HCS doc (no-op for now), the rest
will be handled by HCS.

add support for resource partitions

---

internal/hvsocket/hvsocket.go
internal/tools/hvsocketaddr/main.go

Update hvsocketaddr utility to exit on error.

fix: close handle when DeviceIoControl fails
