guid.go
layerutils.go

Make guid external

---

exportlayer.go
importlayer.go

Fix import/export proc calls

---

createcomputesystem.go
createprocess.go

This fixes a couple of %s rather that %v log statements.

Fix logging

---

getlayermountpath.go
getsharedbaseimages.go
hcsshim.go

@swernli. Modifications to hcsshim for support of the central store.

Support for central store

---

hcsshim.go
nametoguid.go

Signed-off-by: Stefan J. Wernli <swernli@microsoft.com>

Adding methods for calling into hcsshim to do string to guid hashing.

---

guid.go

Signed-off-by: Stefan J. Wernli <swernli@microsoft.com>

Fix for GUID ToString.

---

createprocess.go

Gofmt on all files

---

activatelayer.go
copylayer.go
createcomputesystem.go
createlayer.go
createprocess.go
createsandboxlayer.go
deactivatelayer.go
destroylayer.go
exportlayer.go
getlayermountpath.go
getsharedbaseimages.go
importlayer.go
layerexists.go
nametoguid.go
preparelayer.go
resizeconsole.go
shutdowncomputesystem.go
startcomputesystem.go
terminatecomputesystem.go
terminateprocess.go
unpreparelayer.go

Signed-off-by: Stefan J. Wernli <swernli@microsoft.com>
@jhowardmsft @jstarks

Adding comments for remaining HCSSHIM public functions.

---

hnsfuncs.go

Updating HNS structures to their latest implementation

---

importlayer.go
legacy.go

This only affects the legacy import/export code path.

Fix import and export of layers containing long paths

---

baselayer.go

For TP5, the utility VM is shipped with the base image. Process it if its contents are present in "UtilityVM\Files"
@swernli

Support utility VM paired with base image

---

getcomputesystemproperties.go
hcsshim.go
zhcsshim.go

@jstarks @jhowardmsft 
Signed-off-by: Stefan J. Wernli <swernli@microsoft.com>

Adding GetComputeSystemProperties for use in servicing scenario.

---

container.go

This adds logging of the configs for CreateContainer and CreateProcess.

Added logging of JSON config in success case

---

legacy.go

@darrenstahlmsft Please include this in the next revendor

legacyLayerReader: handle tombstones correctly

---

expandsandboxsize.go
hcsshim.go
zhcsshim.go

@swernli PTAL
This adds ExpandSandboxSize. Version checking will be done in Docker.

Added ExpandSandboxSize

---

hnsfuncs.go

Added support for VLAN and VSID policies required for Azure and data center scenarios.

Vlan and VSID policy

---

container.go

Fixed PendingUpdates call with correct query

---

README.md

Add reference to code of conduct

---

cgo.go

Added import C to force hcsshim to compile as CGO

---

errors.go

Added proc not found error

---

baselayer.go

Skip reparse points when adding to the list of directories to fix the file info on. This fixes the failure to load base images on CI servers.
This also adds some error wrapping to aid debugging future errors.
/cc @jstarks 

Only update directory modified times if not a reparse point

---

container.go
interface.go

Add support for ProcessList

---

interface.go

@darrenstahlmsft Noticed while working on the OCI stuff that we are passing information through to HCS which isn't required. Added some `omitempty`'s and some comments.

Add omitempty and annotations

---

container.go
hcsshim.go
process.go
utils.go
waithelper.go
zhcsshim.go

This removes TP5 functions, dealing with lack of async handling, and the now unused code.
/cc @jstarks @jhowardmsft 

Remove TP5 support

---

hnsfuncs.go

Structure changes required to support overlay networking 

Overlay networking support

---

preparelayer.go

This is a fix for timeouts in PrepareLayer. It is a temporary workaround until a platform fix is available. It is still possible to hit this on low spec or heavily loaded systems
/cc @jhowardmsft @jstarks 

Serialize calls to PrepareLayer due to Windows bug

---

interface.go

`User` was missing..... @darrenstahlmsft @jstarks

Add user to ProcessConfig interface

---

waithelper.go

I realized that this could be done with a single switch rather than two, so fixed it.
Signed-off-by: Darren Stahl darst@microsoft.com

Combine timeout switches

---

hnsfuncs.go

Adding control path support to disable inter container communication for an endpoint

Control path support to disable ICC

---

hnsfuncs.go

Fixing the field name to DisableICC

---

container.go

Added comment for exported type ContainerProperties
@jhowardmsft 

Add comment for exported ContainerProperties

---

interface.go

cc @jhowardmsft Can you please merge and tag.

Adding omitempty tag to DnsSearchList

---

container.go

Signed-off-by: John Howard (VM) <jhoward@microsoft.com>
@jstarks 
Manual verification with updated docker passing in null, but environment variable set
Daemon:
`$env:HCSSHIM_CREATECONTAINER_ADDITIONALJSON='{"Additional":"foo", "HvRuntime":{"NestedAddition":"bar"}}'`
Client:
`PS C:\> docker run --rm microsoft/nanoserver cmd /s /c echo hello
Hello
`
Daemon log:
`
time="2017-03-22T14:24:51.010036400-07:00" level=debug msg="HCSShim::CreateContainer id=a8a13338141df10fbb4396e42bd1024d36622ebba60e947e8d9a8f82c9c59977 merged config={\"Additional\":\"foo\",\"AllowUnqualifiedDNSQuery\":true,\"EndpointList\":[\"99814e52-dcd2-4b35-acb6-a27ca50560f2\"],\"HostName\":\"a8a13338141d\",\"HvPartition\":true,\"HvRuntime\":{\"ImagePath\":\"C:\\\\control\\\\windowsfilter\\\\7240ed0171af8e623c11c1c4556f2085681 …

Allow additional JSON for create container

---

container.go
errors.go
hnsfuncs.go
interface.go

This is required for Hot Add/Remove of Network Endpoints
Signed-off-by: MadhanRaj.Mookkandy@microsoft.com

    Expose ModifySettings Support in HcsShim. 

---

interface.go
waithelper.go

Adds fields for LCOW. ping @gupta-ak Please review!

LCOW: Add fields

---

interface.go

Add MappedVirtualDisks to ContainerConfig

---

interface.go

Add initrd/kernel path to HvRuntime

---

container.go

Change Data to interface in ResourceModificationRequestResponse

---

interface.go

The HCS schema has had some fields renamed.

HCS schema updates for 6/21 on builds

---

interface.go

Slight docs update to fix range on ProcessorMaximum and updated comment on ProcessorWeight.

Update ProcessorMaximum and ProcessorWeight comments

---

hnsendpoint.go
hnsnetwork.go
hnspolicylist.go

Add files missed with the merge

Fix casing on logrus

---

hnsendpoint.go
hnspolicylist.go
test/hns_test.go

(1) Expose Attach/Detach 
(2) Add hns unit testing

(1) Expose Attach/Detach (2) Add hns unit testing

---

container.go

This fixes a container leak when the container create background thread hangs and never returns, or if hcsshim fails to register for container notifications.
@jhowardmsft @jstarks 

Cleanup on failed container create due to timeout

---

README.md

More README updates including formatting and more links.

Update README to include HCS link, and formatting/spelling fixes

---

legacy.go

On NTFS, on spinning hard disks, reducing the number of writes reduces
the number of disk seeks, which greatly improves image extraction
performance.

Use bufio when extracting layer files

---

internal/hcs/system.go
internal/mergemaps/merge.go

Move mergemaps to its own internal package

---

container.go
internal/hcs/system.go

Renames container to compute system in the internal package to mirror HCS APIs.

Container to ComputeSystem

---

container.go
internal/hcs/system.go
internal/schema1/schema1.go

This change also adds some type safety to hcs.System.Properties.

Add State property and remove HasPendingUpdates

---

uvm/create_test.go
uvm/sample.go
uvm/scsi.go

Remove v1 from UVM

---

uvm/constants.go
uvm/create.go
uvm/types.go
uvm/vpmem.go
uvm/vsmb.go

Tidying to uvm package

---

internal/hcs/process.go
internal/hcs/system.go
internal/hns/hnsendpoint.go
internal/hns/hnsnetwork.go
internal/hns/hnspolicylist.go
uvm/globals_test.go
uvm/scsi_test.go

Adds partial testing for SCSI for utility VMs.

Partial SCSI UVM tests

---

uvm/create_test.go
uvm/functional_tests.ps1

Fix functional tests for UVM. Adds a script for running them locally

Functional tests UVM

---

uvm/functional_tests.ps1
uvm/init_test.go

Functional tests. VPMEM still failing

---

uvm/scsi_test.go
uvm/vpmem_test.go
uvm/vsmb_test.go

Fix UVM tests after lock changes

---

uvm/vpmem.go
uvm/vpmem_test.go

Ref counting removal on vpmem

---

internal/schema2/schema2.go
internal/wclayer/nametoguid.go
uvm/functional_tests.ps1
uvm/lcowhostedsettings/types.go
uvm/plan9.go
uvm/plan9_test.go
uvm/scsi.go
uvm/types.go
uvm/vpmem.go
uvm/vsmb.go
uvm/vsmb_test.go

Add Plan9 shares for LCOW

---

internal/hcsoci/containerex.go
internal/hcsoci/mount.go
uvm/types.go
uvm/vsmb.go
uvm/vsmb_test.go

- map to containing pointers so easier to update
- remove GUID and use counter
- case sensitive

VSMB Updates to match Plan9 PR feedback

---

internal/hcsoci/mount.go

@jstarks - err was being masked and not caught.

Mount: Catch AddVPMEM failure correctly

---

internal/guestrequest/types.go
internal/requesttype/types.go
internal/uvm/network.go

@beweedon As per podscenariotests.ps1, but I'm not sure that the remove looks correct in terms of the guestrequest type. Could you take a look, and I'll update accordingly.
@jterry75 Is opengcs geared up to expect this?

Network pre-add and network add/rm updates

---

internal/uvm/scsi.go

Remove old SCSI comment

---

internal/schema1/schema1.go

Add device passthrough support

---

interface.go

Adds linux metadata support for MappedDir for v1

---

interface.go

Signed-off-by: Sandeep Bansal <sabansal@microsoft.com>
Replaces closed #259 @jterry75

Changes to support registry modification in containers

---

internal/osversion/windowsbuilds.go

To last nights RS5_RELEASE build. @jterry75

Bump RS5 build number

---

cmd/go-runhcs/LICENSE
cmd/go-runhcs/NOTICE
cmd/go-runhcs/runhcs.go
cmd/go-runhcs/runhcs_create.go
cmd/go-runhcs/runhcs_delete.go
cmd/go-runhcs/runhcs_exec.go
cmd/go-runhcs/runhcs_kill.go
cmd/go-runhcs/runhcs_start.go
cmd/go-runhcs/runhcs_test.go

Introduce go-runhcs client bindings

---

internal/schema1/schema1.go

Put LinuxMetadata in the right place (oops)

---

cmd/go-runhcs/runhcs_exec.go

Adding detach support to go-runhcs exec

---

internal/hcs/system.go
internal/lcow/scratch.go
internal/timeout/timeout.go

@jterry75 Thinking of future supportability at 3AM... Making each of the timeouts configuration separately.

Add individual timeouts rather than global

---

internal/hcsoci/resources.go
internal/uvm/network.go

Fixing issues found by go 1.11

---

cmd/runhcs/tar2vhd.go

Adding VHD Access for tart2vhd

---

cmd/runhcs/exec.go
cmd/runhcs/kill.go

Unify runhcs container stopped error

---

cmd/runhcs/exec.go

Fix issue with exec on linux oci spec

---

hcn/hcn.go
hcn/hcnendpoint.go
hcn/hcnerrors.go
hcn/hcnerrors_test.go
hcn/hcnloadbalancer.go
hcn/hcnnamespace.go
hcn/hcnnetwork.go

* Creating a NetworkType with proper const values for the various types.
* Improving the errors for V2 based of feedback from a pervious PR.

Better errors, NetworkType added.

---

cmd/runhcs/container.go
cmd/runhcs/shim.go
cmd/runhcs/tty.go

Adding map between host pid and guest pid

---

cmd/go-runhcs/runhcs.go
cmd/go-runhcs/runhcs_create.go
cmd/go-runhcs/runhcs_exec.go
cmd/runhcs/container.go
cmd/runhcs/create.go
cmd/runhcs/exec.go
cmd/runhcs/main.go
cmd/runhcs/shim.go
cmd/runhcs/utils.go
cmd/runhcs/utils_test.go
cmd/runhcs/vm.go

Adds named pipe logging for debug/shim/vmshim logs

---

cmd/runhcs/container.go

Reorder shim cmd args

---

cmd/runhcs/shim.go

V2 support process User

---

internal/uvm/network.go

A few network fixes

---

cmd/runhcs/container.go

Only store namespace in registry for sandbox/uvm

---

appveyor.yml

Add tar2ext4 to artifacts

---

cmd/runhcs/delete.go
cmd/runhcs/kill.go
cmd/runhcs/kill_test.go
cmd/runhcs/list.go
cmd/runhcs/pause.go
cmd/runhcs/ps.go
cmd/runhcs/shim.go
cmd/runhcs/signalmap.go
cmd/runhcs/start.go
cmd/runhcs/state.go
cmd/runhcs/vm.go
functional/uvm_properties_test.go
internal/guestrequest/types.go
internal/hcs/hcs.go
internal/hcs/process.go
internal/hcs/zsyscall_windows.go

Implement signal support

---

internal/uvm/create.go

Enable HotHint for Windows

---

cmd/runhcs/container.go
cmd/runhcs/kill.go
cmd/runhcs/state.go

Adding Signal support for RS5 Argon

---

cmd/runhcs/container.go
functional/uvm_mem_backingtype_test.go
internal/schema2/memory_2.go
internal/uvm/create.go

Adding MemoryBackingType support via OCI annotations

---

interface.go

Export AssignedDevice in V1

---

internal/uvm/create.go

Assign uvm.vpmemMaxSizeBytes on create to avoid SCSI fallback

---

cmd/runhcs/container.go
cmd/runhcs/create.go

Forward --owner from runhcs command to UVM/container creation

---

cmd/runhcs/container.go

Add JSON tagging and comments to persistedState fields

---

cmd/runhcs/container.go

- Simplify annotations parsing and assignment for custom opts
- Fix issue not forwarding UVM resources for LCOW activations

Simplify annotations for easier use across types

---

functional/lcow_test.go
functional/test.go
functional/uvm_mem_backingtype_test.go
functional/uvm_plannine_test.go
functional/uvm_properties_test.go
functional/uvm_scratch_test.go
functional/uvm_scsi_test.go
functional/uvm_vpmem_test.go
functional/uvm_vsmb_test.go
functional/wcow_test.go
functional/wcow_xenon_v2_test.go

Use uvm.Close() rather than uvm.Terminate()

---

appveyor.yml
pkg/go-runhcs/runhcs_e2e_matrix_test.go
pkg/go-runhcs/runhcs_test.go

Change runhcs_test build tag to 'integration' to match other tests.

---

ext4/internal/compactext4/compact_test.go

Fix ext4 compact_test leak testfs.img

---

internal/schemaversion/schemaversion_test.go

Fix schemaversion tests on RS5+

---

cmd/runhcs/create-scratch.go

Forward Owner to runhcs create-scratch

---

pkg/go-runhcs/runhcs.go
pkg/go-runhcs/runhcs_integration_test.go
pkg/go-runhcs/runhcs_test.go

Store the runhcs.exe path for faster invocation

---

internal/uvm/create.go

Turn pci devices off for LCOW

---

internal/uvm/create.go

Set LCOW kernel boot quiet for production

---

internal/uvm/create.go

Moving uart kernel config to ComPort creation

---

cmd/runhcs/container.go

Adding CPU and Memory override OCI annotations

---

internal/wclayer/exportlayer.go
internal/wclayer/importlayer.go
internal/wclayer/wclayer.go
internal/wclayer/zsyscall_windows.go
layer.go

Remove FilterLayerReader/Writer as it is unused

---

internal/hcserror/hcserror.go
internal/wclayer/activatelayer.go
internal/wclayer/createlayer.go
internal/wclayer/createscratchlayer.go
internal/wclayer/deactivatelayer.go
internal/wclayer/destroylayer.go
internal/wclayer/expandscratchsize.go
internal/wclayer/exportlayer.go
internal/wclayer/getlayermountpath.go
internal/wclayer/getsharedbaseimages.go
internal/wclayer/grantvmaccess.go
internal/wclayer/importlayer.go
internal/wclayer/layerexists.go
internal/wclayer/layerutils.go
internal/wclayer/nametoguid.go
internal/wclayer/preparelayer.go
internal/wclayer/unpreparelayer.go

Convert wclayer to use logrus.Fields

---

internal/uvm/counter.go
internal/uvm/types.go

Stop using a global container counter for all UVM's

---

internal/uvm/create_lcow.go
internal/uvm/create_wcow.go

Use TerminateOnLastHandleClosed for UVM

---

cmd/runhcs/container.go
cmd/runhcs/create-scratch.go
functional/lcow_test.go
functional/utilities/createuvm.go
functional/uvm_mem_backingtype_test.go
functional/wcow_test.go
internal/uvm/create.go
internal/uvm/create_lcow.go
internal/uvm/create_test.go
internal/uvm/create_wcow.go
tools/uvmboot/main.go

Simplify WCOW/LCOW opts passing

---

cmd/runhcs/container.go
cmd/runhcs/create-scratch.go
internal/uvm/create_lcow.go
test/functional/lcow_test.go
tools/uvmboot/main.go

Enable KernelDirect and VHD boot by default

---

internal/uvm/create_lcow.go
internal/uvm/start.go

Fix regression in OutputHandler serialization

---

cmd/runhcs/main.go

Remove duplicate error message write on runhcs failure

---

internal/guestrequest/types.go
internal/hcsoci/hcsdoc_lcow.go
internal/hns/hnsendpoint.go
internal/uvm/network.go

Implement LCOW V2 NetworkNamespace support

---

internal/hcs/system.go

Stop logging operation errors when they are expected

---

hcn/hcnloadbalancer.go
hcn/hcnloadbalancer_test.go

Add ability to set additional DSR flags

Update DSR flags

---

cmd/runhcs/kill.go
cmd/runhcs/kill_test.go
cmd/runhcs/signalmap.go

Fix support for Docker signal by value

---

internal/uvm/create_lcow.go

Add decompressed kernel support for LCOW start

---

cmd/runhcs/create-scratch.go

Shrink the size of the create-scratch uvm

---

internal/hcs/system.go

Stop logging failure for pending shutdown

---

cmd/containerd-shim-runhcs-v1/exec_hcs.go
cmd/containerd-shim-runhcs-v1/exec_wcow_podsandbox.go
cmd/containerd-shim-runhcs-v1/exec_wcow_podsandbox_test.go

Stop resetting Pid to 0 on exec exit

---

cmd/containerd-shim-runhcs-v1/task_hcs.go
internal/uvm/create.go

Add better hcsTask exit logging and handling

---

cmd/containerd-shim-runhcs-v1/pod.go
cmd/containerd-shim-runhcs-v1/task_hcs.go

Only use shim binary name for ComputeSystem owner

---

cmd/containerd-shim-runhcs-v1/exec_hcs.go
cmd/containerd-shim-runhcs-v1/task_hcs.go
cmd/runhcs/kill.go
internal/signals/signal.go
internal/signals/signal_test.go
internal/signals/signalmap.go
internal/uvm/capabilities.go

Add SignalSupport check and Signal validation to v2 shim

---

cmd/containerd-shim-runhcs-v1/pod.go

When should only be creating the guest network for WCOW when the container is
hypervisor isolated.

Fix panic trying to provision guest network on process container

---

hcn/hcnglobals.go

@pradipd
@erfrimod
@madhanrm
@dineshgovindasamy
@daschott

Update minor version for HNS V2 support

---

cmd/containerd-shim-runhcs-v1/exec_hcs.go
cmd/containerd-shim-runhcs-v1/io.go
cmd/containerd-shim-runhcs-v1/io_npipe.go
cmd/containerd-shim-runhcs-v1/task_hcs.go

Simplify v2 shim upstream IO handling

---

cmd/containerd-shim-runhcs-v1/delete.go

Fix delete hang when the platfrom does not return

---

tools/zapdir/main.go

This is basically docker-ci-zap. Adding to hcsshim so it can be included in the package we build.

Add zapdir utility to delete data directories

---

tools/zapdir/main.go

Improve zapdir error reporting

---

internal/hcs/process.go

Fix logging typo

---

hcn/hcnendpoint.go
hcn/hcnnetwork.go
internal/hns/hnsnetwork.go

This combination should not be allowed.

We throw if address prefix given but no gateway

---

internal/hcs/process.go
internal/hcs/system.go

To avoid a panic in waithelper. @jterry75

Delete rather than nil

---

test/cri-containerd/createcontainer_test.go
test/cri-containerd/main.go
test/cri-containerd/runpodsandbox_test.go

Add initial CreateContainer tests

---

internal/hcsoci/hcsdoc_lcow.go
test/cri-containerd/createcontainer_test.go

Add OCI privileged container support

---

appveyor.yml

CI build uvmboot.exe

---

cmd/runhcs/create-scratch.go

Throw an error if create-scratch attempted pre-RS5

---

test/cri-containerd/main.go
test/cri-containerd/runpodsandbox_test.go

Fix bug in pulling LCOW pause image

---

internal/hcsoci/network.go

@jterry75 As mentioned yesterday. Just debug logging so we can track timing

Logging in createNetworkNamespace

---

cmd/containerd-shim-runhcs-v1/pod.go
internal/uvm/create.go

Fix bug that fails to return error when out of memory

---

internal/uvm/create.go
internal/uvm/create_lcow.go
internal/uvm/create_wcow.go
internal/uvm/modify.go
internal/uvm/network.go
internal/uvm/plan9.go
internal/uvm/scsi.go
internal/uvm/start.go
internal/uvm/terminate.go
internal/uvm/vpmem.go
internal/uvm/vsmb.go
internal/uvm/wait.go

Update UVM package logging to include context

---

internal/oci/uvm.go

When using the sandbox override annotation:
"io.microsoft.virtualmachine.computetopology.memory.sizeinmb" in CRI the
setting is expected in MB. When using OCI Windows.Resources.Memory.Limit the
setting is expeced in Bytes. The platform expects the setting in MB. So the
resolver now ALWAYS returns MB regardless if using the annotation override or
OCI spec.

Fix bug in UVM activation when using OCI Windows.Resources.Memory.Limit

---

internal/hcsoci/hcsdoc_wcow.go
internal/uvm/create.go
internal/uvm/create_lcow.go
internal/uvm/create_wcow.go
internal/uvm/types.go

Automatically verify and downgrade user CPUCount to runtime.NumCPU

---

internal/hcsoci/hcsdoc_lcow.go
internal/hcsoci/hcsdoc_wcow.go
internal/oci/uvm.go
internal/uvm/create.go
internal/uvm/create_lcow.go
internal/uvm/create_wcow.go
test/cri-containerd/createcontainer_test.go
test/cri-containerd/runpodsandbox_test.go

Add support for UVM CPU/Memory/Storage QoS
Add support for WCOW Container CPU/Memory/Storage QoS
Add support for LCOW CPU/Memory QoS
Add CRI Pod/Container tests for QoS settings

Add support for WCOW/LCOW QoS

---

internal/uvm/create_lcow.go
internal/uvm/scsi.go
internal/uvm/vpmem.go

Stop setting grantvmaccess per layer.vhd

---

appveyor.yml

Because @jterry75 is having a bad week..... alphabeticalising things

G comes before U and Zed

---

cmd/containerd-shim-runhcs-v1/service_internal.go
cmd/containerd-shim-runhcs-v1/task_hcs.go
cmd/containerd-shim-runhcs-v1/task_hcs_test.go
cmd/containerd-shim-runhcs-v1/task_wcow_podsandbox.go

Change the state model allow Delete from Created

---

internal/hcs/system.go

Fix system.Properties log message

---

appveyor.yml
test/runhcs/create-scratch_test.go
test/runhcs/e2e_matrix_test.go
test/runhcs/list_test.go
test/runhcs/runhcs_test.go

Move 'integration' to 'functional' tag for runhcs tests

---

internal/hcs/callback.go
internal/hcs/process.go
internal/hcs/system.go

Fix real deadlock in notification delivery

---

cmd/containerd-shim-runhcs-v1/serve.go
cmd/containerd-shim-runhcs-v1/start.go

Hook up a panic.log on shim serve

---

cmd/containerd-shim-runhcs-v1/start.go

@jterry75 As discussed offline.

Move panic log to bundle dir

---

internal/uvm/scsi.go
test/functional/uvm_scsi_test.go

It turns out that the Linux kernel can get very confused if a HotRemove
on the SCSI happens without a guest initiated eject. This change will always
initiate a guest request to eject the SCSI controller/lun before removing the
virtual disk from the host UVM.

Always send guest eject for SCSI LCOW HotRemove

---

cmd/containerd-shim-runhcs-v1/exec_hcs.go

Handles ERROR_NOT_FOUND for HcsSignalProcess and properly coverts this to the
containerd errdefs.ErrNotFound so upstream callers handle the exit
appropriately.

Handle ERROR_NOT_FOUND for HcsSignalProcess

---

internal/uvm/create_lcow.go
internal/uvm/start.go

This also cleans up the opengcs log output a bit.

uvm: Include VM ID in opengcs logs

---

internal/hcs/callback.go

Force log NotificationType to string

---

cmd/containerd-shim-runhcs-v1/diag.go
cmd/containerd-shim-runhcs-v1/pod.go
cmd/containerd-shim-runhcs-v1/service_internal.go
cmd/containerd-shim-runhcs-v1/task.go
cmd/containerd-shim-runhcs-v1/task_hcs.go
cmd/containerd-shim-runhcs-v1/task_test.go
cmd/containerd-shim-runhcs-v1/task_wcow_podsandbox.go

Fix shimdiag

---

appveyor.yml

Move to golang 1.12.4

---

internal/oci/uvm.go

Fix bug in documentation for UVM processor.limit

---

cmd/containerd-shim-runhcs-v1/delete.go
cmd/containerd-shim-runhcs-v1/exec_hcs.go
cmd/containerd-shim-runhcs-v1/task_hcs.go
cmd/containerd-shim-runhcs-v1/task_wcow_podsandbox.go
cmd/runhcs/container.go
cmd/runhcs/kill.go
cmd/runhcs/shim.go
container.go
internal/hcs/errors.go
internal/hcs/process.go
internal/hcs/system.go
internal/lcow/scratch.go
internal/tools/uvmboot/main.go
internal/uvm/create.go
internal/uvm/wait.go
process.go
test/functional/wcow_test.go

This updates Terminate, Shutdown, Kill, and Signal to avoid returning
errors in expected cases, and removes WaitTimeout.

hcs: Improve Process and System wait-related interfaces

---

cmd/containerd-shim-runhcs-v1/diag.go
cmd/containerd-shim-runhcs-v1/exec_hcs.go
cmd/runhcs/shim.go
internal/lcow/scratch.go

This updates the various places that were manually using CreateProcess to use hcsoci.Cmd instead.

Use hcsoci.Cmd everywhere

---

internal/gcs/bridge.go
internal/gcs/bridge_test.go
internal/gcs/container.go
internal/gcs/guestconnection.go
internal/gcs/guestconnection_test.go
internal/gcs/iochannel.go
internal/gcs/iochannel_test.go
internal/gcs/process.go
internal/gcs/protocol.go
internal/tools/uvmboot/main.go
internal/uvm/create.go
internal/uvm/create_lcow.go
internal/uvm/create_wcow.go
internal/uvm/modify.go
internal/uvm/start.go
internal/uvm/types.go

This adds an optional external bridge implementation, as discussed in #583.

External bridge

---

internal/gcs/bridge.go
internal/gcs/protocol.go

The existing RPC protocol's error response is an HRESULT, which loses
information and does not work well for the Linux GCS. The response also
has error records, which can have richer error strings, but it is
ambiguous which of these strings are meant to be user facing and which
are for debugging.
This change adds an ErrorMessage field that Windows HCS and GCS will
ignore but Linux GCS will fill out with the underlying error string.
This makes it unambiguous which string should be returned to the user.

gcs: Add ErrorMessage field to RPC response

---

internal/uvm/create_lcow.go

Enable bridge v4 on all v2 LCOW activations

---

internal/tools/uvmboot/lcow.go
internal/tools/uvmboot/wcow.go

This option enables uvmboot to be used to create an interactive process
in the utility VM.

uvmboot: Add tty option

---

cmd/shimdiag/exec.go

os.Stdin.Read() returns EOF if the user presses Ctrl-Z. This makes sense
for non-terminal execs, where we can close stdin for the process and the
process will generally exit. But it does not make sense for terminal
execs, where Ctrl-Z will just cause the process to hang.
When using exec in terminal mode, read raw bytes from the stdin
descriptor to avoid this Ctrl-Z translation.

shimdiag: Do not hang exec -t on Ctrl-Z

---

cmd/containerd-shim-runhcs-v1/service.go

1. Improves the fields logged on exit to include important values from the
response.
2. Returns the logrus.Entry from beginActivity to avoid another alloc on
endActivity.

Improve shim entry/exit logging

---

internal/guestrequest/types.go
internal/schema1/schema1.go

Fixing malformed JSON tag

---

cmd/runhcs/create-scratch.go
internal/lcow/scratch.go
pkg/go-runhcs/runhcs_create-scratch.go
test/functional/lcow_test.go
test/functional/utilities/scratch.go
test/functional/uvm_scratch_test.go
test/functional/uvm_scsi_test.go
test/runhcs/create-scratch_test.go

Add support for custom scratch sizes

---

go.mod
go.sum
vendor/github.com/Microsoft/go-winio/pkg/etwlogrus/hook.go
vendor/modules.txt

Revendor go-winio

---

test/cri-containerd/container_network_test.go

This change adds a simple network ping test on LCOW container start and tests for any packet losses

Added a simple network ping test on container start

---

internal/uvm/wait.go

Cleanup UVM Wait

---

internal/uvm/vpmem.go

Cleanup UVM RemoveVPMEM

---

internal/uvm/scsi.go

Cleanup UVM RemoveSCSI workflow

---

internal/hcsoci/hcsdoc_lcow.go

Forward all OCI Linux.Namespaces

---

test/cri-containerd/runpodsandbox_test.go

Update minimum memory size for LCOW Memory test

---

hcn/hcnpolicy.go

Adds NatFlags to portmappings

---

cmd/containerd-shim-runhcs-v1/events.go
cmd/containerd-shim-runhcs-v1/events_test.go

Improve logging for event publishing

---

hcn/hcnendpoint_test.go
hcn/hcnloadbalancer_test.go

Making it so our tests are up to date and pass

Test fixes, removing an obsolete tests

---

internal/hcs/process.go

Capture ExitCode at process exit

---

cmd/containerd-shim-runhcs-v1/exec_hcs.go

Remove unused code

---

internal/gcs/container.go
internal/gcs/guestconnection.go
internal/gcs/guestconnection_test.go
internal/gcs/process.go
internal/gcs/protocol.go

Add external bridge OpenCensus span support

---

go.mod
go.sum
vendor/github.com/Microsoft/go-winio/file.go
vendor/github.com/Microsoft/go-winio/pkg/etw/provider.go
vendor/github.com/Microsoft/go-winio/pkg/guid/guid.go
vendor/github.com/Microsoft/go-winio/vhd/vhd.go
vendor/modules.txt

Update Microsoft/go-winio v0.4.14

---

internal/hcsoci/resources.go
internal/hcsoci/resources_lcow.go

Support LCOW /tmp backed by temporary vhdx

---

internal/hcsoci/resources_lcow.go
test/cri-containerd/createcontainer_test.go

Change parsing of hostpath string for plan9 file mounting

---

internal/hcsoci/resources.go
internal/hcsoci/resources_lcow.go
internal/hcsoci/resources_wcow.go

Add support for automanage-virtual-disk targets

---

appveyor.yml

Update AppVeyor to golang 1.12.9

---

internal/uvm/plan9.go
osversion/windowsbuilds.go
test/cri-containerd/createcontainer_test.go

Only enable single-file 9pfs test on 19H1+

---

internal/hcsoci/resources_lcow.go
test/cri-containerd/runpodsandbox_test.go

Signed-off-by: Abdul Waheed <abwah@microsoft.com>

Enable container mounts to refer to host path on the UVM

---

test/cri-containerd/stats_test.go

Accidentally didn't include this file in my previous PR. :)

Add tests for UVM stats

---

test/cri-containerd/stats_test.go

Fix test bug in defer order

---

test/cri-containerd/container_network_test.go

1. Adds a hostname test for a workload container in each of:
runhcs-wcow-process, runhcs-wcow-hypervisor, runhcs-lcow runtimes.

Add cri-containerd hostname tests

---

cmd/containerd-shim-runhcs-v1/serve.go

Today, if we create a container and restart containerd, the log will not be reconnected any more.
```
time="2019-09-25T00:57:45.577003100Z" level=error msg="copy shim log" error="failed to connect to shim log: timed out waiting for npipe \\\\.\\pipe\\containerd-shim-k8s.io-bf5569e77a8531d7aa8693fd47a08872031176349583a3cf5245aaa31bd17d32-log: context deadline exceeded"
```
@jterry75 
Signed-off-by: Lantao Liu <lantaol@google.com>

Fix live restore for shim log.

---

internal/oci/uvm.go
internal/schema2/memory_2.go
internal/uvm/create_lcow.go

Pass through cold discard hint annotation to hcs

---

hcn/hcnpolicy.go

* Adding SharedContainers to HostComptueEndpoint.
* Removing obsolete ProxyType from Policy.
##Integration Tests
```
go test -tags=integration -v
…
PASS
ok      github.com/Microsoft/hcsshim/hcn        380.754s
```

HNS Adding SharedContainers to HostComputeEndpoint

---

internal/uvm/create.go

Log runtime id GUID as string

---

cmd/containerd-shim-runhcs-v1/exec.go
cmd/containerd-shim-runhcs-v1/exec_hcs.go
cmd/containerd-shim-runhcs-v1/exec_wcow_podsandbox.go

Ignore ResizePty failure in non-running state

---

test/cri-containerd/container_downlevel_test.go
test/cri-containerd/container_network_test.go
test/cri-containerd/createcontainer_test.go
test/cri-containerd/main.go
test/cri-containerd/runpodsandbox_test.go
test/cri-containerd/stats_test.go

fixed windows images used in tests based on container host
added a downlevel hypervisor test for windows

fix 19h1 tests

---

osversion/windowsbuilds.go

Signed-off-by: John Howard <github@lowenna.com>
Now I have an almost usable office again, albeit with Internet at the speed of two cups and a piece of string...

Typo: 'Sever' --> 'Server'

---

appveyor.yml
go.mod

update to golang 1.13.4

---

internal/gcs/guestconnection.go
internal/gcs/protocol.go
internal/hcsoci/create.go
internal/hcsoci/resources.go
internal/schema1/schema1.go
internal/uvm/capabilities.go
internal/uvm/delete_container.go

related PR https://github.com/microsoft/opengcs/pull/360

add ability to call opengcs delete container state

---

internal/hcs/system.go

1. Docker already supports limiting max parallel starts at its level and we
no longer need support for limiting this at our level through an environment
variable.

Remove support for limiting max parallel starts

---

test/cri-containerd/createcontainer_test.go

See original commit: 0bc510b4c5259af4f852ff8be7421ced2c8d92a5

Fix regression in LCOW cpuset tests

---

hcn/hcnerrors.go
hcn/hcnerrors_test.go
hcn/hcnnamespace.go
hcn/hcnutils_test.go

I'm trying to accomplish two things
1. Know whether the error comes from us
2. Be able to correlate common Win32 errors without having to rely on parsing strings

Adds HcnError, and some error codes to use

---

CODEOWNERS

Set default reviewers for PR's

---

internal/hcsoci/layers.go

Log when we fallback to SCSI for vPMEM LCOW Layers

---

cmd/containerd-shim-runhcs-v1/diag.go

Fix trace context forwarding for UVM exec's

---

hcn/hcn.go
hcn/hcnerrors.go
hcn/hcnroute.go
hcn/hcnroute_test.go
hcn/hcnutils_test.go
hcn/zsyscall_windows.go

1) Add the SYS call hooks for SDN Routes
2) Add the HcnComputerRoute implementation for SDN Routes
3) Unit test

Add sdn route

---

hcn/hcnroute_test.go
hcn/hcnutils_test.go

Fix bugs in the UT file for SDN Route and the TestUtil for SDN Route creation

Fix bugs in the UT files for SDN route

---

internal/hcsoci/layers.go
internal/hcsoci/resources_lcow.go
internal/hcsoci/resources_wcow.go
internal/lcow/scratch.go
internal/uvm/scsi.go
test/cri-containerd/runpodsandbox_test.go
test/functional/lcow_test.go
test/functional/uvm_scratch_test.go
test/functional/uvm_scsi_test.go

This fixes a bug where same vhd cannot be mounted in multiple containers

Mount Same SCSI Vhd in multiple containers

---

hnspolicy.go

Expose the proxy policy types for endpoint

Expose the Proxy policy types for Endpoint

---

internal/uvm/network.go
internal/uvm/pipes.go
internal/uvm/plan9.go
internal/uvm/resourcepaths.go
internal/uvm/scsi.go
internal/uvm/vpmem.go
internal/uvm/vsmb.go

Signed-off-by: Justin Terry (SF) <juterry@microsoft.com>

Add all supported UVM resource modification paths

---

test/cri-containerd/container_test.go
test/cri-containerd/runpodsandbox_test.go
test/functional/uvm_virtualdevice_test.go

only run MMIO tests on OS builds with schema support

---

test/cri-containerd/container_test.go

This adds a new test in the cri-containerd suite. The test runs an LCOW
container with a command line that causes the init process to fork
a background process (which runs forever) then exit. The test then
ensures that the container status is reported as exited, since the init
process has terminated.
Note: This test case currently fails due to needing a fix in Microsoft/opengcs. Don't merge this until the fix is in.

Add test case where container init forks then exits

---

test/cri-containerd/main.go
test/cri-containerd/stopcontainer_test.go

Test for starting/stopping containers and reusing pod

---

internal/hcsoci/layers.go

Fixes an issue that broke mounting of SCSI layers. Due to changing the
assignment of the return values from `AddSCSILayer` from `:=` to `=`,
the error value became scoped to the inner if block, which caused the
later return statement to pick up the previous error value instead of
the new one.
This change also improves some error values and adds additional logging.

Fix LCOW SCSI layer mounting

---

test/cri-containerd/container_test.go

* Add a non gpu zero vpmem test case to test lcow scsi layer additions.

Add zero vpmem (no gpu) test case

---

README.md

Update the readme to include information on signing commits

---

hcn/hcn.go
hcn/hcnglobals.go
hcn/hcnsupport.go
hcn/hcnsupport_test.go

Added version support for HNS IPv6 dual stack.

Added Version support for IPv6 Dual stack support in HNS

---

internal/hns/hnsendpoint.go

Signed-off-by: Vinod K L Swamy <vinodko@microsoft.com>

Add the IPV6 EndPoint Address and Gateway Field to HnsEndPoint.

---

internal/hns/hnsendpoint.go

Signed-off-by: Vinod K L Swamy <vinodko@microsoft.com>

Added the IPV6PrefixLength field

---

internal/hcsoci/create.go
internal/hcsoci/hcsdoc_wcow.go
internal/hcsoci/resources_lcow.go
internal/schema2/device.go
internal/uvm/virtual_device.go
test/cri-containerd/container_virtual_device_test.go

* adds support in process isolated windows containers for assigned devices
* refactors hcswcow_doc code to use newly create helper functions

add support for assigned devices in process isolated containers

---

hcn/hcn.go
hcn/hcnglobals.go
hcn/hcnpolicy.go
hcn/hcnsupport.go
hcn/hcnsupport_test.go

Added the support for SetPolicy in HNS. This PR updates the supported HNS minor and major version for SetPolicy

Updating the supported HNS minor and major version for SetPolicy

---

hcn/hcn.go
hcn/hcnglobals.go
hcn/hcnpolicy.go
hcn/hcnsupport.go
hcn/hcnsupport_test.go

Exposing VXLAN ports configuration functionality in HCSShim

Exposing VXLAN ports configuration functionality in HCSShim

---

test/cri-containerd/createcontainer_test.go

Don't merge until the PR to add this support is merged: https://github.com/jterry75/cri/pull/70

Add test for WCOW kubernetes.io~empty-dir support

---

test/cri-containerd/container_test.go
test/cri-containerd/createcontainer_test.go
test/go.sum

Tests for changes in https://github.com/jterry75/cri/pull/71 and https://github.com/microsoft/opengcs/pull/377

Add tests for sharing devices from the sandbox into a lcow container

---

hcn/hcn.go
hcn/hcnglobals.go
hcn/hcnpolicy.go
hcn/hcnsupport.go
hcn/hcnsupport_test.go

Added support for L4Proxy policy on network level

Added support for L4Proxy policy on network level

---

internal/layers/layers.go
internal/uvm/scsi.go
internal/uvm/vpmem.go

Improve logging for LCOW layer operations

---

hcn/hcnglobals.go

Updating the Supported version ranges for Network l4proxy policy

Updating the Supported version ranges for Network L4proxy policy

---

test/cri-containerd/clone_test.go
test/cri-containerd/container.go

This is one of the many small PRs that enable the support for late cloning.
This commit adds several end to end tests for the late cloning feature.

Add tests for late cloning

---

test/cri-containerd/clone_test.go
test/cri-containerd/container.go

This is one of the many small PRs that enable the support for late
cloning. This commit adds several end to end tests for the late cloning
feature.

Add end to end tests for late cloning. (to master)

---

test/cri-containerd/container_virtual_device_test.go
test/cri-containerd/runpodsandbox_test.go
test/functional/uvm_virtualdevice_test.go

Update gpu tests with Vb build number

---

appveyor.yml

Improve CI reliability by forcing vendor use

---

errors.go
internal/hcs/errors.go
internal/hcs/system.go

Remove extra info from error logs

---

internal/uvm/vpmem.go

fix wrong error logged when dm-verity footer read fails

---

test/functional/wcow_test.go
test/vendor/github.com/Microsoft/hcsshim/go.mod
test/vendor/github.com/Microsoft/hcsshim/go.sum
test/vendor/github.com/Microsoft/hcsshim/internal/guestrequest/types.go
test/vendor/github.com/Microsoft/hcsshim/internal/hcsoci/devices.go
test/vendor/github.com/Microsoft/hcsshim/internal/hcsoci/hcsdoc_wcow.go
test/vendor/github.com/Microsoft/hcsshim/internal/hcsoci/resources_lcow.go
test/vendor/github.com/Microsoft/hcsshim/internal/hcsoci/resources_wcow.go
test/vendor/github.com/Microsoft/hcsshim/internal/layers/layers.go
test/vendor/github.com/Microsoft/hcsshim/internal/oci/annotations.go
test/vendor/github.com/Microsoft/hcsshim/internal/oci/uvm.go
test/vendor/github.com/Microsoft/hcsshim/internal/uvm/combine_layers.go
test/vendor/github.com/Microsoft/hcsshim/internal/uvm/create_lcow.go
test/vendor/github.com/Microsoft/hcsshim/internal/uvm/security_policy.go
test/vendor/github.com/Microsoft/hcsshim/pkg/securitypolicy/securitypolicy.go
test/vendor/github.com/Microsoft/hcsshim/pkg/securitypolicy/securitypolicyenforcer.go
test/vendor/modules.txt

Fix build break in functional tests

---

test/vendor/github.com/Microsoft/hcsshim/ext4/dmverity/dmverity.go
test/vendor/github.com/Microsoft/hcsshim/internal/uvm/vpmem_mapped.go

Update test modules with hcsshim changes

---

test/vendor/github.com/Microsoft/hcsshim/internal/hcsoci/resources_lcow.go

Addresses CI build break from https://github.com/microsoft/hcsshim/pull/1118

Update test modules with up to date hcsshim code

---

test/cri-containerd/pullimage_test.go
test/cri-containerd/test-images/unordered_tar/main.go
test/cri-containerd/test-images/unordered_tar/tar_generator.go
test/go.mod
test/vendor/modules.txt

Add E2E test for pulling images with unorderd tar

---

.golangci.yml
test/vendor/github.com/Microsoft/hcsshim/.golangci.yml

Will be nice to have this on to catch go fmt offenders

Enable gofmt in linter

---

internal/hns/hnspolicy.go
test/vendor/github.com/Microsoft/hcsshim/internal/hns/hnspolicy.go

Backport #1370 into hcsshim's moby branch for moby 20.10 backport

[moby backport] Fix for port conflict with docker daemon. 

---

internal/logfields/fields.go
test/vendor/github.com/Microsoft/hcsshim/internal/logfields/fields.go

Adding more field types for future tracing PRs

Adding more logfield entries

---

.github/workflows/ci.yml

Making the changes as per https://github.com/microsoft/hcsshim/pull/1373#issuecomment-1115258821

[release/0.9] Fix for linter issue on release/0.9 branch

---

internal/guest/runtime/runc/process.go

Signed-off-by: Sean T Allen <seanallen@microsoft.com>

Fix typo in comment

---

internal/tools/securitypolicy/helpers/helpers.go
test/vendor/github.com/Microsoft/hcsshim/internal/tools/securitypolicy/helpers/helpers.go

fix unused commandArgs

---

cmd/containerd-shim-runhcs-v1/options/runhcs.pb.go
cmd/containerd-shim-runhcs-v1/options/runhcs.proto
test/vendor/github.com/Microsoft/hcsshim/cmd/containerd-shim-runhcs-v1/options/runhcs.pb.go
test/vendor/github.com/Microsoft/hcsshim/cmd/containerd-shim-runhcs-v1/options/runhcs.proto

Fix spelling in runhcs options

---

internal/uvm/create_lcow.go

Add Plan9 support when booting from VMGS

---

internal/queue/queue_test.go

Additionally fix the queue tests logic.

linter: fix linting issues

---

.github/workflows/ci.yml

tests: run securitypolicy tests in github CI.

---

internal/jobobject/jobobject.go
internal/winapi/jobobject.go
internal/winapi/zsyscall_windows.go

BOOL is a typedef for int not a boolean

Fix OpenJobObject definition

---

internal/uvm/vpmem_mapped.go
test/cri-containerd/test-images/large_layer_ubuntu/Dockerfile-20.04
test/cri-containerd/test-images/large_layer_ubuntu/Dockerfile-22.04
test/cri-containerd/unmap_vpmem_test.go

test coverage for https://github.com/microsoft/hcsshim/pull/1456

---

test/cri-containerd/clone_test.go
test/cri-containerd/container_test.go
test/cri-containerd/helper_container_test.go
test/cri-containerd/policy_test.go
test/go.mod
test/go.sum

additionally refactor some of the existing tests to use the new func

add test utility func that waits for particular container state

---

pkg/securitypolicy/regopolicy_test.go
pkg/securitypolicy/securitypolicy_test.go

This will avoid linter errors.

Move rego only test fixtures into the rego tests file

---

.golangci.yml

remove spelling linter

---

pkg/securitypolicy/securitypolicyenforcer_rego.go

Adds typing for `metadataOperation` and a enumeration of `metadataAction`. No functionality changes as a result of this, but the code is easier to read and support.

Refactor of metadata operations.

---

internal/guest/runtime/hcsv2/uvm.go
pkg/annotations/annotations.go
test/cri-containerd/policy_test.go

rename SecurityPolicyEnv annotation to UVMSecurityPolicyEnv

---

internal/processorinfo/processor_count.go

GetMaximumProcessorCount -> GetActiveProcessorCount

Fix 'ProcessorCount' comment

---

.github/workflows/release.yml

fix release.yml push trigger expecting a map.

---

.github/workflows/release.yml

https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#push

fix release.yml trigger for real now

---

internal/guest/runtime/hcsv2/uvm.go
internal/oci/uvm.go
internal/protocol/guestresource/resources.go
internal/uvm/create_lcow.go
internal/uvm/security_policy.go
internal/uvm/start.go
pkg/annotations/annotations.go

This reverts changes introduced in microsoft/hcsshim#1521.

remove pod startup fragment functionality

---

internal/guest/runtime/hcsv2/uvm.go

fix: wrong assignment after enforcing a policy

---

test/cri-containerd/containerdrestart_test.go

Currently, it is possible for the test that restarted containerd as well as subsequent tests to all fail with `rpc error: code = Unknown desc = server is not initialized yet` because the CRI plugin takes a while to initialize. 
This PR adds a function to restart tests that waits for CRI plugin to be fully initialized before continuing.
`waitForCRI` waits for a specified timeout, periodically sending `Version` gRPC requests until either a successful response returns, timeout is reached, or another error besides `not initialized yet` is returned.
cri-containerd restart tests pass

test: CRI initialization

---

pkg/securitypolicy/securitypolicyenforcer_rego.go

rego enforcer: trim whitespaces from fragment namespace name

---

cmd/containerd-shim-runhcs-v1/exec_hcs.go
internal/hcs/process.go
internal/hcsoci/hcsdoc_wcow.go
test/cri-containerd/main.go
test/cri-containerd/stopcontainer_test.go
test/cri-containerd/test-images/nanoserver-gracefultermination-repro/latest/Dockerfile
test/cri-containerd/test-images/nanoserver-gracefultermination-repro/latest/delayed-shutdown.go
test/cri-containerd/test-images/servercore-gracefultermination-repro/latest/Dockerfile
test/cri-containerd/test-images/servercore-gracefultermination-repro/latest/delayed-shutdown.go
test/vendor/github.com/Microsoft/hcsshim/internal/hcs/process.go
test/vendor/github.com/Microsoft/hcsshim/internal/hcsoci/hcsdoc_wcow.go

This PR ports the commit for graceful termination from hcsshim/main to hcsshim release/0.9 branch
* This commit includes the changes to enable graceful termination of WCOW containers
Co-authored-by: Kirtana Ashok <Kirtana.Ashok@microsoft.com>
(cherry picked from commit 5cfbc2ac27e4aa4c2559a1bc7d0e4687e9279352)

[release/0.9] wcow: support graceful termination of servercore containers (#1416)

---

test/cri-containerd/stopcontainer_test.go

This PR fixes test failures seen for graceful termination tests
- Loosen the time interval check that measures the time taken to stop the container with -t command as ADO cloud tests take a few more seconds to complete
- Add to check that OS version is V21H2Server since the graceful termination test images are based on servercore and nanoserver 2022.

Fix graceful termination test errors

---

test/cri-containerd/policy_test.go

Depends on https://github.com/microsoft/hcsshim/pull/1648

tests: add tests for concurrent pod startup

---

go.mod
go.sum
test/go.mod
test/go.sum
vendor/modules.txt

Follow up to: https://github.com/microsoft/hcsshim/pull/1748 Updated wrong docker dependency.
Fixes:
https://github.com/microsoft/hcsshim/pull/1732
https://github.com/microsoft/hcsshim/pull/1733

[bug] Consolidate dependabot updates

---

.github/dependabot.yml
go.mod
go.sum
test/go.mod
test/go.sum
vendor/github.com/google/go-containerregistry/pkg/v1/remote/fetcher.go
vendor/github.com/google/go-containerregistry/pkg/v1/remote/puller.go
vendor/github.com/google/go-containerregistry/pkg/v1/remote/pusher.go
vendor/github.com/opencontainers/runc/libcontainer/user/user.go
vendor/github.com/sirupsen/logrus/README.md
vendor/modules.txt

- https://github.com/microsoft/hcsshim/pull/1780
- https://github.com/microsoft/hcsshim/pull/1781
- https://github.com/microsoft/hcsshim/pull/1787
- https://github.com/microsoft/hcsshim/pull/1788

[deps] combine and tidy `\test`

---

test/functional/lcow_container_bench_test.go
test/internal/container/container.go

LCOW layer mounting updated how it parsed the spec for partitioned layers.
Update functional tests accordingly

[func.test]update lcow layer processing

---

internal/log/format.go

If `protojson.Marshal` fails, fall back on `json.Marshal`.
Failure arose when marshalling containerd's `task.ExecProcessRequest`, since the `Spec` field is an `anypb.Any` encoded via `typeurl/v2`, which standard protobuf unmarhsalling cannot handle.
Also, downgrade logging about failures with formatting during logging to Debug level, since they do not warrant always being output.

Fall back on json encoding from protojson

---

internal/hcsoci/hcsdoc_wcow.go
internal/hcsoci/resources.go
internal/hcsoci/resources_lcow.go
internal/hcsoci/resources_wcow.go

Replace mount type strings with constants

Add constants for supported mount types

---

internal/hcsoci/hcsdoc_wcow.go
internal/hcsoci/resources.go
internal/hcsoci/resources_lcow.go
internal/hcsoci/resources_wcow.go

(cherry picked from commit 11700d2711d371b01e9f149d07a83b3f818bc343)

[release/0.11] Add constants for mount types

---

cmd/dmverity-vhd/main.go

Use `errors` package instead of the `github.com/pkg/errors`.
`createVHD` accepts layer number to avoid calling `layer.DiffID()` twice.

minor refactor in dmverity-vhd tool

---

internal/hcsoci/hcsdoc_wcow.go
pkg/annotations/annotations.go

(cherry picked from commit 0af576d29d462afc6bc7fa11b83023d2226dad51)
P.S : This is a direct cherry pick of the above commit without additional changes

[release/0.11] Create container subdirectories for process dumps

---

cmd/containerd-shim-runhcs-v1/exec_hcs.go
internal/gcs/bridge.go
internal/guest/bridge/bridge.go

(cherry picked from commit c91d82d2e8c5cad1034f17712391e0c76281e5aa)

[release/0.12] Add spans and drop large size high volume trace logs

---

internal/cmd/diag.go
internal/lcow/common.go
internal/lcow/scratch.go

Use errors.As()

---

.github/workflows/release.yml

Signed-off-by: Heather Garvison <hgarvison@microsoft.com>
(cherry picked from commit a58b41457cca7c4f08f489e15ca1768ebfd84df5)

Updating permissions and github release action versions (#2078)

---

hcn/hcnloadbalancer.go
hcn/hcnloadbalancer_test.go
hcn/hcnutils_test.go

These changes are to provide support for load balancer update in hns.

Adding support for loadbalancer policy update in hns.

---

go.mod
go.sum
test/go.mod
test/go.sum
vendor/github.com/Microsoft/go-winio/README.md
vendor/github.com/Microsoft/go-winio/backuptar/tar.go
vendor/github.com/Microsoft/go-winio/fileinfo.go
vendor/github.com/Microsoft/go-winio/pkg/etw/provider.go
vendor/github.com/Microsoft/go-winio/pkg/etw/wrapper_32.go
vendor/github.com/Microsoft/go-winio/pkg/etw/wrapper_64.go
vendor/github.com/Microsoft/go-winio/pkg/security/syscall_windows.go
vendor/github.com/Microsoft/go-winio/pkg/security/zsyscall_windows.go
vendor/github.com/Microsoft/go-winio/privilege.go
vendor/github.com/Microsoft/go-winio/vhd/vhd.go
vendor/github.com/Microsoft/go-winio/vhd/zvhd_windows.go
vendor/modules.txt

Full list of changes: https://github.com/microsoft/go-winio/compare/v0.4.17...v0.4.21

[release/0.9] Update gowinio to v0.4.21

---

hcn/hcnnetwork.go

Introducing new network flag EnableIov

Introducing new network flag EnableIov.

---

hcn/hcnnetwork.go

Changing EnableIov flag value from 9216 to 8192

Modifying network flag EnableIov.

---

init/init.c

Azure Linux provides compressed kernel module files by default for some modules. This PR adds the ability to load compressed kernel modules as part of the init script's module loading.

Add support for kernel modules files ending in .ko.xz

---

internal/guest/storage/scsi/scsi.go
internal/guest/storage/scsi/scsi_test.go

* os.Stat does not open the file. We're seeing issues where after stat'ing the device path in /dev, we get the error from _getDeviceFsType "No such device or address", aka ENXIO, when trying to open the device to read the superblock.
* Change os.Stat call to os.Open when waiting for the /dev device to show up to ensure we can successfully open the device later.

Fix no such device error when getting device filesystem

---

.github/workflows/ci.yml
go.mod
go.sum
test/go.mod
test/go.sum
vendor/github.com/opencontainers/runc/libcontainer/user/user.go
vendor/modules.txt

Update runc version to 1.1.14 + go mod tidy/vendor

[release/0.12] Update runc version to 1.1.14

---

internal/hns/hnsendpoint.go

We missed a typo in this PR: https://github.com/microsoft/hcsshim/pull/2177/files#

Fixing typo

---

.github/workflows/ci.yml
internal/safefile/safeopen.go
test/internal/layers/lazy.go

Have `test\internal\layers.LazyImageLayers` always fail if image extraction fails initially.

Store extraction error for `LazyImageLayers`
